### ISSUE TITLE
Missing x-cds-client-headers in Get Transactions For Account definition

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#102]
# Request For Clarification
The [swagger definition](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.yaml) for Get Transactions for Account and the [corresponding HTML documentation](https://consumerdatastandardsaustralia.github.io/standards/#get-transactions-for-account) have both omitted the x-cds-client-headers client header parameter. We would appreciate confirmation that this was not intentional and would suggest that this error is corrected if this is the case.

**Comment by CDR-API-Stream** [comment]
Thanks @WestpacOpenBanking. This wasn’t intentional. Please treat “x-cds-client-headers” as mandatory for Get Transactions For Account. This will be fixed in the next maintenance cycle as a documentation defect.

**Comment by commbankoss** [comment]
While Commonwealth Bank supports the inclusion of the header in Get Transactions for accounts, we recommend it be defined as Optional rather than Mandatory. This header should be mandatory when the customer is present, but not required otherwise. This would be consistent with other banking APIs.

**Comment by cdradr** [comment]
The definition of this header is unclear as to what data can be included or can not included.
1) There is a potential privacy impact (too much data included, the use of this data by Data Holders, etc). Privacy Impact Assessment needs to be done after it is defined clearly.
2) The only truly ‘customer present’ scenario is consent authorization / dashboard flow. API consumption is done by a backend server outside of user involvement even if a user still logged in to a front end.
3) What if the user interface is not a web application?

**Comment by perlboy** [comment]
@cdradr Yes, I raised the validation element of this header in #104 with my last request for clarification February 4.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

A similar article is available on the CDR Support Portal: https://cdr-support.zendesk.com/hc/en-us/articles/4404953530767-DH-requirement-for-x-cds-client-headers
