### ISSUE TITLE
Remove ProductRateTier.subTier object used in Get Product Detail

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/standards-maintenance#103]
# Description
This proposal is to remove the `ProductRateTier.subTier` object used in the `Get Product Detail` endpoint. `[Deposit|Lending]RateTier.tiers` were created as arrays in the very early days of the standards to support more than two dimensions (i.e. tier types/sets). It also implied that tier types/sets had relative precedence or importance. The `ProductRateTier.subTier` object was not removed at the time because it was seen as a structural change just prior to lock-down of version 1 of the standards (and there was no mechanism for deprecating it as far as we were aware).

Note: This proposal arose from @perlboy 's issue #94 - Clarification of rate presentation and use of subTier.

# Area Affected
Endpoint: [Get Product Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-product-detail)
Schema: [ProductRateTier](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductratetier)

# Change Proposed
Remove the `subTier` property from the `ProductRateTier` schema used in the `Get Product Detail` endpoint.

# Impact
Data providers using the `ProductRateTier.subTier` object would need to convert their `subTier` to a `ProductRateTier` object as part of the `[Deposit|Lending]RateTier.tiers` array. The `subTier` object becomes an additional object 'alongside' its 'parent' tier object. See below as an example (not representing current data provider data).

### Using `ProductRateTier.subTier` object
```
"depositRates": [
            {
                "depositRateType": "FIXED",
                "rate": "0.005",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "10000 to 20000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 10000,
                        "maximumValue": 20000,
                        "rateApplicationMethod": "WHOLE_BALANCE",
                        "subTier": {
                            "name": "1 Month",
                            "unitOfMeasure": "MONTH",
                            "minimumValue": 1,
                            "maximumValue": 2,
                            "rateApplicationMethod": "WHOLE_BALANCE"
                        }
                    }
                ],
                "additionalValue": "P2M"
            }
```

### Using `DepositRateTiers` array
```
"depositRates": [
            {
                "depositRateType": "FIXED",
                "rate": "0.005",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "10000 to 20000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 10000,
                        "maximumValue": 20000,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    },
                    {
                        "name": "1 Month",
                        "unitOfMeasure": "MONTH",
                        "minimumValue": 1,
                        "maximumValue": 2,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    }
                ],
                "additionalValue": "P2M"
            }
```

**Comment by commbankoss** [comment]
Commonwealth Bank is supportive of the change that ANZ has proposed. We will not require the use of a Sub-Tier in the foreseeable future.

**Comment by perlboy** [comment]
Biza.io is supportive of the removal of `subTier` and, in fact, chose not to support `subTier` within [babelfish-cdr](https://github.com/bizaio/babelfish-cdr/) based on prior conversations. We are also broadly supportive of ANZ's proposal to add `additionalInfo` in their proposal within #107.

We do however request clarification as to whether the proposed change(s) would represent V3 of the `BankingProduct` and `BankingProductDetail` payloads, the intended adoption timeline of such payloads especially in the context of likely more changes and the fact this area of the Standards, now being implemented by Tier 2/3's, should now be in a 3 month cadence period.

**Comment by CDR-API-Stream** [comment]
Given the broad support for removal of ``subTier`` and simplification of the product reference data the proposed position is to adopt this change request. This will remove ``subTier`` from ``BankingProductRateTier``.

This will be incorporated into v1.3.0 (based off Maintenance Iteration #2) and would have a future dated obligation of July 2020 inline with the PRD Get Products V2 dates.

**Comment by Susan-CDR** [comment]
Hi - I have just come across this proposal. Suncorp is mid stream in build and where planning to use the sub-tier. A future date of Jul 20 would require re-work for us at this point. This change needs to be deferred to a later timeline to avoid impacts to non-majors working to their first deliverable.

**Comment by CDR-API-Stream** [comment]
Hi @Susan-CDR based on the consultation during the maintenance iteration, similar feedback has been raised by other implementing data holders. We have considered this and recommended a future dated obligation of February 2021. This change will result in a versioned change of product data (v3). Other product-related change requests may be considered in Maintenance Iteration 3 to apply to the same Feb 21 future dated obligation.

**Comment by CDR-API-Stream** [comment]
This change has been incorporated into [v1.3.0 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.3.0.html#v1-3-0-release-notes).
