### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#105]
# Request For Clarification
The Standards provide an example of `x-fapi-customer-ip-address` which is an unroutable IPv6 address of `2001:0db8:85a3:0000:0000:8a2e:0370:7334` with no active AS announcement. This appears to have been sourced from the [OIDF FAPI Certification Suite](https://gitlab.com/openid/conformance-suite/blob/master/src/test/java/net/openid/conformance/condition/rs/ExtractFapiIpAddressHeader_UnitTest.java). Nonetheless it is an IPv6 rather than an IPv4 address. 

This seems to indicate that at a bare minimum ADR's may be providing IPv6 reception. Could the DSB clarify as to whether this means also means:
1) Holders are able to deliver IPv6 endpoints?
2) Holders are able to **exclusively** deliver IPv6 endpoints?

**Comment by CDR-API-Stream** [comment]
The standards are silent on this issue and the non-normative example should not be taken as implying that the standards are making a delineation either way.  If the example included an IPv4 it would also not imply anything.

The only constraints the standards would apply to data holders with regard to IP configuration would be via the normative standards relied upon for the information security profile.

**Comment by CDR-API-Stream** [comment]
If there are no more questions related to this query it will be closed on Friday.
