### ISSUE TITLE
Expected Behaviour of List Products effectiveFrom/effectiveTo Filter

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#106]
# Request For Clarification
The `effectiveFrom` and `effectiveTo` elements of a `BankingProductV2` are marked as optional.

The `GET /banking/products` call allows for filtering based on `effective` which designated `CURRENT`, `FUTURE` and `ALL` states. What appears to be absent is a `RETIRED` filter?

Nonetheless, these filtering component results in a number of scenarios we wish to seek clarity when preparing filtering clauses, as follows:

1. Where neither `effectiveFrom` and `effectiveTo` are populated is the state of the product designated as `CURRENT`?
2. Where `effectiveFrom`< `NOW()` but `effectiveTo` is `NULL` is the state of the product `CURRENT`?
3. Where `effectiveFrom`> `NOW()` but `effectiveTo` is `NULL` is the state of the product `FUTURE`?
4. Where `effectiveFrom`< `NOW()` and `effectiveTo` > `NOW()` is the state of the product `CURRENT`?
5. Where `effectiveFrom`< `NOW()` and `effectiveTo` < `NOW()` is the state of the product undefined and therefore only appears under `ALL`?
6. Where `effectiveFrom`< `NOW()` and `effectiveTo` < `NOW()` there is no filter for RETIRED state so this would only appear under `ALL`?
7. Where `effectiveFrom`>`NOW()` and `effectiveTo`>`NOW()` is the state of the product `FUTURE`?

Additionally, could the following be clarified:

1. If `effectiveFrom` > `effectiveTo` this is an invalid payload?
2. If `effectiveFrom` == `effectiveTo` is this invalid or considered a retired product only visible when filtered with `ALL`

**Comment by CDR-API-Stream** [comment]
> 1. Where neither `effectiveFrom` and `effectiveTo` are populated is the state of the product designated as `CURRENT`?

Yes

> 2. Where `effectiveFrom`< `NOW()` but `effectiveTo` is `NULL` is the state of the product `CURRENT`?

Yes

> 3. Where `effectiveFrom`> `NOW()` but `effectiveTo` is `NULL` is the state of the product `FUTURE`?

Yes

> 4. Where `effectiveFrom`< `NOW()` and `effectiveTo` > `NOW()` is the state of the product `CURRENT`?

Yes

> 5. Where `effectiveFrom`< `NOW()` and `effectiveTo` < `NOW()` is the state of the product undefined and therefore only appears under `ALL`?

Yes

> 6. Where `effectiveFrom`< `NOW()` and `effectiveTo` < `NOW()` there is no filter for RETIRED state so this would only appear under `ALL`?

Yes

> 7. Where `effectiveFrom`>`NOW()` and `effectiveTo`>`NOW()` is the state of the product `FUTURE`?

Yes


> Additionally, could the following be clarified:
> 
> 1. If `effectiveFrom` > `effectiveTo` this is an invalid payload?

No, but there is no way for this product to ever be considered effective.

> 2. If `effectiveFrom` == `effectiveTo` is this invalid or considered a retired product only visible when filtered with `ALL`

The latter.

**Comment by CDR-API-Stream** [comment]
If there are no more questions related to this query it will be closed on Friday.

**Comment by cdradr** [comment]
Will the standards be updated to reflect these business rules and clarifications? 

Will test harnesses be updated too?

**Comment by perlboy** [comment]
@cdradr I don't believe the [java-artefacts](https://github.com/consumerDataStandardsAustralia/java-artefacts) ever support/verified these directly. It's also not a particularly easy thing to do when access to the data store isn't available (ie. as a clean room setup). Nonetheless [Deep Thought](https://github.com/bizaio/deepthought) implements to these rules now, @CDR-API-Stream no further questions related to this from me although adding these use cases to the [wiki](https://github.com/consumerDataStandardsAustralia/standards/wiki) seems prudent.
