### ISSUE TITLE
Add additionalInfo and additionalUri properties to ProductRateTier

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/standards-maintenance#107]
# Description
The `additionalInfo` and `additionalInfoUri` properties are useful in many places in many schema in the data standards. They would also be useful in the `ProductRateTier` schema to describe the rate tier. This was really just an oversight in the original rate tiering proposal.

In their absence, ANZ has had to use the `additionalInfo` and `additionalInfoUri` properties in the `applicabilityConditions` sub-object to describe the tier, when its real purpose is to provide conditions additional to those codified in the generic `ProductRateTier` structure. See the example below.

# Area Affected
Endpoint: [Get Product Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-product-detail)
Schema: [ProductRateTier](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductratetier)

# Change Proposed
Add `additionalInfo` and `additionalInfoUri` as a new optional properties to the `ProductRateTier` schema. The description should be consistent with `additionalInfo` and `additionalInfoUri` properties elsewhere i.e.:
```
additionalInfo: Display text providing more information on the rate tier
additionalInfoUri: Link to a web page with more information on this rate tier
```
# Impact
As optional new properties, neither data providers or data recipients would be affected, but may include them to provide descriptive information. ANZ will move the `additionalInfo` and `additionalInfo` properties in the `applicabilityConditions` sub-object into the `ProductRateTier` object and remove the `applicabilityConditions` sub-object. See below for an example.

# Current Response (example data only)
```
	"lendingRates": [
		{
			"lendingRateType": "VARIABLE",
			"rate": "0.0400",
			"comparisonRate": "0.0440",
			"applicationFrequency": "P1M",
			"interestPaymentDue": "IN_ARREARS",
			"additionalInfo": "Loan amount of $250,000 - $499,999, borrowing 80% or less of the property value",
			"additionalInfoUri": "...",
			"tiers": [
				{
					"name": "Amount",
					"unitOfMeasure": "DOLLAR",
					"minimumValue": 150000,
					"maximumValue": 249999,
					"rateApplicationMethod": "WHOLE_BALANCE",
					"applicabilityConditions": {
						"additionalInfo": "Total mortgage lending amount between $150,000 and $249,999",
						"additionalInfoUri": "..."
					}
				},
				{
					"name": "Loan-to-Value Ratio",
					"unitOfMeasure": "PERCENT",
					"minimumValue": 0,
					"maximumValue": 80,
					"rateApplicationMethod": "WHOLE_BALANCE",
					"applicabilityConditions": {
						"additionalInfo": "Borrowing up to 80% of the property value",
						"additionalInfoUri": "..."
					}
				}
			]
                 }
            ]
```
# Proposed Response
```
	"lendingRates": [
		{
			"lendingRateType": "VARIABLE",
			"rate": "0.0400",
			"comparisonRate": "0.0440",
			"applicationFrequency": "P1M",
			"interestPaymentDue": "IN_ARREARS",
			"additionalInfo": "Loan amount of $250,000 - $499,999, borrowing 80% or less of the property value",
			"additionalInfoUri": "...",
			"tiers": [
				{
					"name": "Amount",
					"unitOfMeasure": "DOLLAR",
					"minimumValue": 150000,
					"maximumValue": 249999,
					"rateApplicationMethod": "WHOLE_BALANCE",
					"additionalInfo": "Total mortgage lending amount between $150,000 and $249,999",
					"additionalInfoUri": "..."
				},
				{
					"name": "Loan-to-Value Ratio",
					"unitOfMeasure": "PERCENT",
					"minimumValue": 0,
					"maximumValue": 80,
					"rateApplicationMethod": "WHOLE_BALANCE",
					"additionalInfo": "Borrowing up to 80% of the property value",
					"additionalInfoUri": "..."
				}
			]
                  }
            ]
```

**Comment by perlboy** [comment]
@anzbankau Probably the only concern I have with adding `additionalInfo` is what happens if the description does not match the tier attributes? Other than describing the tier components as text (which could be generated by the recipient anyway?) what purpose does `additionalInfo` serve?

The addition of `applicationInfoUri` seems reasonable although if it's a link to a PDF it would need to include anchors of some sort or it will be endlessly repeated per rate?

**Comment by CDR-API-Stream** [comment]
Thanks @anzbankau and @perlboy. Now that v1.2.0 of the standards has been issued, we are reviewing our backlog for the next iteration. We will review and consult with the community on our backlog in the next fortnight.

Equally, data holders are within their right to define non-breaking extensions to the standards where a data holder sees benefit under the extensibility model.

**Comment by CDR-API-Stream** [comment]
This change is supported to BankingProductRateTier. ``additionalInfo`` and ``additionalInfoUri`` will be included as optional attributes.

This will be incorporated into v1.3.0 (based off Maintenance Iteration #2). The change would be non-breaking and have a future dated obligation of July 2020 inline with the PRD Get Products V2 dates.

**Comment by perlboy** [comment]
Is this intended to be a V2 or V3 payload? We have a number of [active deployments](https://github.com/bizaio/deepthought) in progress and would prefer if version numbers were incremented for each `minor` release updating a payload as this allows for explicit binding of version compatibility (ie. "known nulls").

**Comment by CDR-API-Stream** [comment]
This change is applicable to V2 of the Product Reference Data.

This change has been incorporated into [v1.3.0 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.3.0.html#v1-3-0-release-notes).
