### ISSUE TITLE
URL Encoding of Links Data

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#108]
# Request For Clarification
Should Links provided in `links` object already be URL Encoded? This is particularly of note for the `updated-since` parameter which often has `+` in it:
```
{
    "links": {
        "self": "https://data.holder.com/cds-au/v1/banking/products?updated-since=2020-01-30T13:55:53%252B11:00",
        "next": "https://data.holder.com/cds-au/v1/banking/products?updated-since=2020-01-30T13:55:53%252B11:00&page=2&page-size=25",
        "last": "https://data.holder.com/cds-au/v1/banking/products?updated-since=2020-01-30T13:55:53%252B11:00&page=3&page-size=25"
    },
    "meta": {
        "totalRecords": 28,
        "totalPages": 2
    },
    "data": {
        "products": [
            {
                "productId": "6dc8c55e-702b-4ce1-9891-79c51b7cfe97",
                "lastUpdated": "2020-01-30T18:08:39.885694+11:00",
                "productCategory": "TRANS_AND_SAVINGS_ACCOUNTS",
```

**Comment by CDR-API-Stream** [comment]
The standards are not currently explicit on this which implies that this is left to the discretion of the data holder.

**Comment by perlboy** [comment]
> The standards are not currently explicit on this which implies that this is left to the discretion of the data holder.

Not providing specific guidance on this means that either:
a) Recipients will be unable to reliably use `links` uri's mainly because it is essentially impossible to reliably determine if a URL is encoded or not
b) Holders may supply `links` entries which are invalid (as per example, timestamps including + will be parsed as spaces on the query string)

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

As `links` cannot be rely on this value being url encoded or not [Electronic Thumb](https://github.com/bizaio/thumb) does not use it all, instead relying on stored parameter values and an iterator based Page conversion using `totalPages` and `totalRecords` as authorative. This puts a high reliance on Holder's providing reliable values for these fields. If Holder's do not provide correct values Electronic Thumb may continue to iterate endlessly beyond the actual page/record count. Consider this message a warning of such behaviour.
