### ISSUE TITLE
Blank Field Handling

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#109]
# Request For Clarification
Could the DSB give guidance on how blank and/or null field values are expected to be handled? When it comes to verifying validity what is acceptable?

As a simple example in `BankingProductDepositRate` there is `applicationFrequency` and `calculationFrequency`, these are both Optional fields. When the field is not present there are three options:

1. Omit the fields entirely in the payload which explicitly outlines the field is deliberately missing
2. Present the fields as `"calculationFrequency": null` which is an undefined duration but implies it should exist
3. Present the fields as `"calculationFrequency": ""` which is an invalid duration

**Comment by CDR-API-Stream** [comment]
This is explicitly address in the standards in the [Payload Conventions Section](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions) under the **Mandatory/Optional Payload** heading and the **Empty/Null Fields** heading

Specifically:
> Optional fields MAY be present but this is not guaranteed. It is also valid for these fields to be present but have a null value. Note that optional fields indicate that data may sometimes not be held by a Data Holder and this is an expected scenario.

...and...

> An empty field (ie. a field that is not present in a payload) will be considered equivalent with a field that is present with a null value.
>
> An empty string (“”) is not considered to be equivalent to null.

**Comment by perlboy** [comment]
Apologies for misreading this this has been clarified. As a followup query with reference to the above statement:
> An empty field (ie. a field that is not present in a payload) will be considered equivalent with a field that is present with a null value.

There are some parts of the specification that have an "assumed" value, like this one from `BankingBalance`:
![image](https://user-images.githubusercontent.com/4291448/73998350-7475b200-49b5-11ea-8c1f-bbeb494852a7.png)

Perhaps an additional sentence should be considered with respect to the handling for a missing/`null` value and these assumptions. At this point `babelfish-cdr` uses the Jackson `defaultValue` specifier for these fields which results in payloads which are prepopulated with the "assumed" value when they are not present/`null` in a payload.

Is this intended behaviour?

**Comment by CDR-API-Stream** [comment]
Sorry not to respond to the additional query earlier.

Where the absence (or null vlaue) of a field results in a semantic interpretation it is stated in the description.  This is not the same as a technical default value which can be included in API definitions.  It is guidance on the interpretation of the absence of the field, not guidance that the field should be replaced with a default value.

Of course, if recipients wish to add the default on receipt of a payload to simplify their implementations that is entirely in their discretion.

**Comment by perlboy** [comment]
This appears to be answered as "implementers can choose". [Electronic Thumb](https://github.com/bizaio/thumb) and [Deep Thought](https://github.com/bizaio/deepthought) both use [Babelfish](https://github.com/bizaio/babelfish) for serialisation and consequently all requests and responses are intended to include any implied assumption aligned with the Standards.
