### ISSUE TITLE
Existing OTP length greater than standard

### ISSUE THREAD

**Issue by ryderwj** [ConsumerDataStandardsAustralia/standards-maintenance#110]
The standard for authentication requires data holders to provide a mechanism for a customer to enter a one-time password through an existing channel. It also requires the OTP to be numeric and between and 4 and 6 digits:

•	Data Holders MUST provide a one-time password (OTP) to the customer through an existing channel or mechanism that the customer can then enter into the redirected page

•	The provided OTP MUST be numeric digits and be between 4 and 6 digits in length

Suncorp has existing channels for supply of one time passwords to customers.  

Customer authentication for Suncorp Web and Mobile banking channels utilises an 8 numeric digit OTP. Customers are familiar with both the mechanism and approach. Suncorp has elected to apply an 8 digit OTP as a more secure approach.

Investigation into the reuse of the existing facilities to support authentication for CDR consent purposes has shown that meeting the requirement of a reduced OTP length for CDR will dictate the same OTP length being applied to existing channels. This change would also need to combined with associated customer communications. 

While the need for consistency across data holders is appreciated, if there is an existing approach that meets the security obligations of both the data holder and the consumer data standards and that a data holder’s customers are familiar with, does the length of the OTP need to be reduced?

**Comment by CDR-API-Stream** [comment]
It is true that the standards require a numeric code of 4-6 digits so an 8 digit RSA token would not be compliant.  The intention of this was to prevent long OTPs that could cause customers problems and not to prevent an OTP mechanism as proven and reliable as a hardware token.

If this issue were raised as a change request the DSB would welcome the opportunity to consult on a specific clause for hardware tokens to extending to 8 digits depending on feedback.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
