### ISSUE TITLE
BankingTransaction transactionId to be Mandatory

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#113]
# Description
The `transactionId` is ostensibly mandatory unless _"there are specific and justifiable technical reasons why a transaction cannot be uniquely identified for a particular account type"_ but marked as "Conditional".

# Area Affected
`BankingTransaction`

# Change Proposed
1. Change this String to Mandatory but allow a blank value of `""` (based on #109 response) if _"there are specific and justifiable technical reasons why a transaction cannot be uniquely identified for a particular account type"_

**Comment by CDR-API-Stream** [comment]
Hi @perlboy

If a ``transactionId`` cannot be uniquely identified for technical reasons, then an empty string would not be the correct response.

The reason it is conditional is that it is mandatory, but only for NPP payments. ADIs who can support transaction IDs with their ledger systems for non-NPP transactions can also utilise this field.

To provide an empty string would be misleading and imply a ``transactionId`` is present but the value doesn’t exist.
 
As such, treating the conditional representation as null or omitting the attribute is the correct response.

**Comment by perlboy** [comment]
:+1: No problems, thanks for the clarification. Closing.
