### ISSUE TITLE
Merchant Category Codes

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#115]
# Request For Clarification
Further to the suggestion in #114 could clarity be provided how this field should be formatted? ISO 18245 outlines an MCC a 4 digit number but the type is a String? How does the DSB wish for this to be presented?

**Comment by CDR-API-Stream** [comment]
Apologies for the delay in response.  At the moment the requirement is that it is a string and there is no additional validation.  The #115 change request would be the path for changing this once it is prioritised for an iteration.

**Comment by perlboy** [comment]
Closure reason provided in #114.
