### ISSUE TITLE
x-<HID>-v header is not mentioned in the latest 1.2 swagger

### ISSUE THREAD

**Issue by SachiniSiriwardene** [ConsumerDataStandardsAustralia/standards-maintenance#119]
The x-<HID>-v is not mentioned in the swagger definition of version 1.2. Shouldn't this be included?

**Comment by CDR-API-Stream** [comment]
A quick check of the swagger appears to show that both `x-v` and `x-min-v` are included for each end point.

Could you clarify which swagger file you are looking at?

**Comment by CDR-API-Stream** [comment]
Apologies, the title is slightly different from the issue description.

The header that is specific the data holder is not contained in the swagger as the specific name of this header varies from holder to holder.  The `<HID>` portion is expected to be substituted with a unique identifier for the holder as the [Extensibility](https://consumerdatastandardsaustralia.github.io/standards/#extensibility) section of the standards.

**Comment by SachiniSiriwardene** [comment]
So does this mean the x-<HID>-v header will be submitted only if the data recipient is invoking an extended endpoint which is specific to the bank?
Also, is the x-v header submitted in such a request?

**Comment by SachiniSiriwardene** [comment]
Hi,
Any update on above issue?

Thanks

**Comment by CDR-API-Stream** [comment]
Hi @SachiniSiriwardene, yes the ``x-<HID>-v`` is only submitted if an extension is required.  It is expected that x-v would be still be submitted.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
