### ISSUE TITLE
Encryption algorithm for ID Tokens

### ISSUE THREAD

**Issue by versent1Jas** [ConsumerDataStandardsAustralia/standards-maintenance#12]
[This](https://consumerdatastandardsaustralia.github.io/standards/#tokens) section in Data61 spec specifies that ID tokens **must** be encrypted. However, the algorithm for encryption has not been defined. OIDC spec allows following to be used for encryption as specified [here](https://openid.net/specs/openid-connect-core-1_0.html#Encryption).
Can the algorithm be specified for assistance in implementation of encryption of ID tokens.

**Comment by commbankoss** [comment]
- Clarity is sought regarding non-normative examples of an id_token issued from the token and authorization endpoints (presumably only one will include given_name, family_name) and whether these attributes constitute “sensitive pii data” ?

- If these tokens are to be encrypted,  details of the key and algorithm to be used for encryption are required

**Comment by CDR-API-Stream** [comment]
The algorithms for signing and encryption are currently left to the data holder to specify using the `alg` claim as specified in the JWS and JWE standards referenced by OIDC.  The standards are not intending to constrain or modify the normative standards in this matter.

The `given_name` and `family_name` claims relate to an individual and are personally identifying.  These claims should only be returned in the appropriate tokens if the customer has authorised the consent request containing the request for these claims to the authorisation endpoint.

**Comment by jogu** [comment]
For completeness, FAPI-RW states that the RSA1_5 encryption algorithm must not be used. (Although the current implements draft of FAPI-RW does this in a rather confusing way; the language has been clarified in the latest draft, https://bitbucket.org/openid/fapi/src/master/Financial_API_WD_002.md#markdown-header-861-encryption-algorithm-considerations )

Also note that for signing/JWS, only PS256 and ES256 are permitted by FAPI-RW and hence by CDR.

**Comment by perlboy** [comment]
For further completeness, the current [OpenBanking UK Standard mandates exclusively PS256](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1077805207/Read+Write+Data+API+Specification+-+v3.1.2#Read/WriteDataAPISpecification-v3.1.2-MessageSigning.1):

> Specification
> The TPP must sign the HTTP body of each API request that requires message signing.
> [.......]
> **The signer must sign the message with PS256.**

The Australian standard was precipitated to be based on the UK standards. On this basis is there a reason that the signing mechanism is not constrained to only **PS256**?

**Comment by CDR-API-Stream** [comment]
The normative standards referenced by the standards apply.
