### ISSUE TITLE
Representation of multiple middle names in the GetCustomer and GetCustomerDetail API response

### ISSUE THREAD

**Issue by JamesJohnsonIBM** [ConsumerDataStandardsAustralia/standards-maintenance#120]
I have a query around how middle names are represented in the response for the GetCustomer and GetCustomerDetail API.  The specific section is listed below:

```JSON
"middleNames": [
    "string"
],
```

If a person has more than one middle name, how would this be passed back? 

One possibility is a single string with space-separation. Using my name (James William Paul Johnson), this would be represented as:

```JSON
"middleNames": [
    "William Paul"
],
```

Another possibility is to use separate array elements (our assumption, given that the value is represented by an array structure):

```JSON
"middleNames": [
    "William", "Paul"
],
```

Can you please provide clarification on the above?

Thanks,
James

**Comment by CDR-API-Stream** [comment]
The second scenario (with the multiple names as separate array elements) would be expected.

**Comment by JamesJohnsonIBM** [comment]
Excellent, many thanks for the clarification :)
