### ISSUE TITLE
Minimum compliance deadline 

### ISSUE THREAD

**Issue by SachiniSiriwardene** [ConsumerDataStandardsAustralia/standards-maintenance#121]
# Request For Clarification
When a new spec version is released, what's the bank's deadline to implement it?
This applies to all future releases as well, after 1.2.0 release.

**Comment by SachiniSiriwardene** [comment]
Hi,
Can we please get an update on this since it affects implementation deadlines for compliance.

**Comment by perlboy** [comment]
@SachiniSiriwardene In the absence of a more official response the timelines are specified in the [formally registered rules framework](https://www.legislation.gov.au/Details/F2020L00094). 
![image](https://user-images.githubusercontent.com/4291448/74664315-9828cb80-51f1-11ea-9d89-a319aa5a79b8.png)
Our interpretation of this right from an internal slide deck:
![image](https://user-images.githubusercontent.com/4291448/74664471-de7e2a80-51f1-11ea-95e4-b111fe26fd7b.png)

If there's a more official timeline posted I'll redact this info.

**Comment by SachiniSiriwardene** [comment]
Hi Stuart,
Thank you for the response.

**Comment by CDR-API-Stream** [comment]
Hi @SachiniSiriwardene for the rules-specific commencement timelines this is for the ACCC to clarify. 

That said, any changes in a new version of the standards will have a specified date by which compliance with the change is required and potentially an obsolescence date of the previous position of the standards if applicable.  These future compliance dates are now being documented in “Future Dated Obligations” section of the standards.

See https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations

**Comment by SachiniSiriwardene** [comment]
The future dated obligations section does not mention all the changes that are introduces with a new version release of the specification. For example, with the release of version 1.2, several changes were introduced for consumer experience guidelines but compliance for those are not mentioned in the future dated obligations section.
What I wanted to know specifically is whether there is a compliance period for a new version of the CDS specification from the date it is released.

**Comment by CDR-Register-Stream** [comment]
The Commencement table is subject to change in light of consultation currently underway, see https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/accc-consultation-on-proposed-timetable-for-participation-of-non-major-adis-in-the-cdr for details.

Note consultation is due to close on 21 February 2020.

**Comment by CDR-API-Stream** [comment]
This issue has been closed as per the [Data Standards Maintenance process](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance#closing-issues). No further questions or comments have been received since an answer was provided.
