### ISSUE TITLE
Does DR's Revocation Endpoint Require CDR CA?

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#122]
For CDS v1.2 and via issue #95 it was agreed that CDR CA certificate is no longer required for JWKS and Discovery endpoints.

There does not seem to be explicit mention of CDR CA certificate is also not required for DR's revocation endpoint given it is TLS only now.

Can this be clarified/confirmed to be the case?  Thanks.

**Comment by CDR-API-Stream** [comment]
The previous statement that the CDR CA is required for infosec end points that are TLS has been removed.  This means that these end points do not require a certificate from the CDR CA.

As such it is confirmed that a revocation end point hosted by an ADR requires TLS but does not require a certificate provided by the CDR CA.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
