### ISSUE TITLE
Clarification on joint account election options

### ISSUE THREAD

**Issue by xchen-ibm** [ConsumerDataStandardsAustralia/standards-maintenance#123]
The CDR rules 4.2(1)(a) refer to the ability of _both joint account holders being able to jointly elect together that **each joint account holder** will individually be able to give authorisation to make consumer data requests or to allow disclosure of CDR data to a data request made by an ADR_.

Would like to clarify whether this means the following options are available for joint account holders, Jack and Mary, to elect:
1. Either Jack or Mary can individually make consumer data requests or give authorisation to disclose CDR data;
2. Only Jack will be able to individually make consumer data requests or give authorisation to disclose CDR data. Mary cannot make consumer data requests or give authorisation to disclose;
3. Only Mary will be able to individually make consumer data requests or give authorisation to disclose CDR data. Jack cannot make consumer data requests or give authorisation to disclose.

Thanks.

**Comment by CDR-API-Stream** [comment]
It is the understanding of the DSB that all three would be possible but the ACCC should be contacted to give a final interpretation.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
