### ISSUE TITLE
AccountNumber should permit alphanumeric for non AUD accounts

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#127]
# Description
Within `BankingAccountDetail` the `accountNumber` describes that the format should be all digits:
![image](https://user-images.githubusercontent.com/4291448/74490573-0e40e000-4f1d-11ea-8034-48d30b465627.png)

While this is valid and enforceable for Australian Dollar denominated bank accounts there are instances where foreign currency accounts may contain alpha-numeric values (influenced by SWIFT allowing it).

# Area Affected
`BankingAccountDetail`

# Change Proposed
Alter wording from:
_Is expected to be formatted as digits only with leading zeros included and no punctuation or spaces_

To something along the lines of:
_For accounts denominated in Australian Dollars, it is expected to be formatted as digits only with leading zeros included and no punctuation or spaces. For non-AUD denominated accounts and where the Holder issues account numbers with alphanumeric characters alpha-numeric is permitted_

**Comment by CDR-API-Stream** [comment]
Currently only domestic accounts are in scope for the detailed account end point so international accounts would not be expected to be represented.  Also, domestic accounts can have non-AUD balances which is why the `currency` field and purse structure are included in the balance structures.

**Comment by CDR-API-Stream** [comment]
The field is only supposed to support APCA accounts and Credit Cards. If there is a valid scenario that a bank can articulate where account numbers should allow non-digits, then we can consider an alternate account identifier rather than simply overload of the account number field.

Otherwise, the preference is to keep the specification as-is.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

This has been answered as "not changing". [Babelfish](https://github.com/bizaio/babelfish) enforces PAN number compliance for this field.
