### ISSUE TITLE
Testing BSB Numbers

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#128]
# Request For Clarification
Could guidance be given on whether there is an intention to register a specific bank number that can be used for testing of BSB's that still pass validation but don't collide? The current set of APCA numbers including a number of entries by individual banks for NPP Testing (Citi in particular) but no declared _test_ namespace we can identify with.

**Comment by CDR-API-Stream** [comment]
The DSB is not intending to require Banks to create fake test accounts and is only involved in testing in a support capacity.  This is a question for the ACCC.

**Comment by perlboy** [comment]
Ticket created on `cdr-register` as there doesn't appear to be any other public place to ask.

If existing allocations are anything to go by some banks WILL designate test BSB's during testing. There are numerous APCA allocations deliberately declaring branch details for this with respect to NPP so it seems likely the same would occur for CDR data.

Additionally it is common practice since the creation of an IP Addressing scheme (RFC-1918) to designate private use allocations within a specification. This is how networks 10/8 and 172.16/12 and 192.168/16 came into existence. 

The issue here is less about what banks are doing and more about what a developer uses on their desktop environment (**Developer Experience**). Without a designation (000-000 or 999-999 would be obvious ones) a developer will be forced to either:
a) Use a BSB they have no authority over which could be interesting if such code makes it into production
b) Use a BSB which does not pass validation which _should_ make their own automated test suites fail

Not aligning this in some way will mean various validation tools will give various results.

Case in point is that the only reason faulty BSB's don't trip up the published Java Artefacts is because [BSBs are never validated](https://github.com/ConsumerDataStandardsAustralia/java-artefacts/blob/master/api-model/src/gen/java/au/org/consumerdatastandards/api/v1_1_1/banking/models/BankingDomesticPayeeAccount.java) beyond _"not null"_ and the payloads loaded never [demonstrate a functional payee](https://github.com/ConsumerDataStandardsAustralia/java-artefacts/tree/master/data-holder/payloads).

On the contrary `babelfish-cdr` does verify external types including [APCA assignments](https://github.com/bizaio/babelfish-cdr/blob/master/src/main/java/io/biza/babelfish/cdr/support/customtypes/ApcaNumberType.java) using the published BSB directory, [SWIFT BICs](https://github.com/bizaio/babelfish-cdr/blob/master/src/main/java/io/biza/babelfish/cdr/support/customtypes/SwiftBicType.java) and [Merchant Category Codes](https://github.com/bizaio/babelfish-cdr/blob/master/src/main/java/io/biza/babelfish/cdr/support/customtypes/MerchantCategoryCodeType.java). All of these attributes are error prone when mapping and yet quite important for many use cases.

Case in point here is that SWIFT **_specifically_** designates in ISO-9362 a format for test BIC's  (8th character == 0) and ISO 18245 **_specifically_** designates MCC's `0600-0699` for private use.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No further response was provided. 

Babelfish introduces a custom [APCA Number Type](https://github.com/bizaio/babelfish/blob/develop/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/support/customtypes/ApcaNumberType.java) which utilises the publicly available [APCA number database](https://github.com/bizaio/babelfish/blob/develop/babelfish-cdr/src/main/resources/bsb-directory.csv) as it's validation source. Consequently, BSBs provided **must** be valid or they will be rendered to null and, where marked as a required field, will fail validation.

Further, SWIFT numbers are validated in a similar way using a (potentially incomplete) [SWIFT number directory](https://github.com/bizaio/babelfish/blob/develop/babelfish-cdr/src/main/resources/swift-directory.csv) for correlation.
