### ISSUE TITLE
Offset Account Presentation

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#129]
# Request For Clarification
Could an example be given of a payload which demonstrates how offsets are intended to be presented? We don't see an `offset` account uType which could define similar (but not the same) fields as a `loan` account although there is a Product Category. If we did use the `loan` account uType for the offset certain mandatory fields could not be populated (for instance `minInstalmentAmount` doesn't generally apply to offsets) and the `offsetAccountIds` would be circular.

By way of example take the following somewhat complicated (!) structure:
Account A: Principal + Interest loan for $450,000
Account B: Offset account with an overdraft limit of $50,000 @ 6% interest.

Account A is not a requirement of Account B (ie. they are two separate accounts).

From what we can determine this would translate to Account A being a `loan` account type with appropriate values and Account B being an OFFSET (or OVERDRAFT perhaps?) category account (with no specific uType) with an overdraft feature of $50,000, a populated `lendingRate` of `0.06` and `offsetAccountIds` would either reference Account B (but not Account A) or be entirely blank?

As an additional example, if Account A's interest WAS calculated based on the offset Account B (such as in CBA's [Everyday Offset](https://www.commbank.com.au/content/dam/commbank/personal/home-loans/fact-sheets/005-309-everyday-offset.pdf)) would this be the scenario where Account A's `offsetAccountIds` are populated with Account B's identifier?

**Comment by perlboy** [comment]
Hmmm, rereading this I think where we've gone awry is that while it is presented as an offset account it is, in fact, an overdraft account type. Nonetheless, demonstrating offset related payloads would be useful.

**Comment by CDR-API-Stream** [comment]
The usual concept of an offset account is not an actual account type in itself.  It is usually defined as a relationship with some type of loan account.  In the standards this has been representing using the `offsetAccountEnabled` and `offsetAccountIds` fields.  These are expected to be set on the loan account and can be used to identify separate accounts that have the offset relationship with the loan account.

**Comment by perlboy** [comment]
> The usual concept of an offset account is not an actual account type in itself. It is usually defined as a relationship with some type of loan account. In the standards this has been representing using the `offsetAccountEnabled` and `offsetAccountIds` fields. These are expected to be set on the loan account and can be used to identify separate accounts that have the offset relationship with the loan account.

Hmm... So parking my initial, faulty example and taking the CBA one:

Account A: Offset Saver Account
Account B: Standard Variable Rate Home Loan

Account B would have `offsetEnabled` with an `offsetAccountIds` populated with Account A? Account A would be `productCategory` of `OFFSET` ?

**Comment by CDR-API-Stream** [comment]
Yes your treatment of Account B is correct, but Account A would have ``productCategory`` of ``TRANS_AND_SAVINGS_ACCOUNTS`` as their is no ``OFFSET`` ``productCategory`` type and the account is essentially a savings account.

**Comment by perlboy** [comment]
Answered, closing.
