### ISSUE TITLE
BankingTransaction isDetail Available Filter

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#130]
# Request For Clarification
Within `BankingTransaction` there is a `isDetailAvailable` boolean:
![image](https://user-images.githubusercontent.com/4291448/74499726-c039d580-4f38-11ea-9a7f-fb3cc8f07929.png)

Should this boolean be true or false when there is detail available but the caller does not have access to detailed transaction information?

**Comment by CDR-API-Stream** [comment]
If a call to the _detail_ endpoint would result in a successful response, the ``isDetailAvailable`` attribute should be ``true``, ``false`` otherwise.

**Comment by perlboy** [comment]
Answered. This boolean is essentially business logic injected into the payload based on the context in which it is called. This will present an interesting challenge for implementers.
