### ISSUE TITLE
Determining Interest Rate of BankingTermDepositAccount

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#132]
# Request For Clarification
If the `BankingAccountDetail` returns with one or more `BankingTermDepositAccount` is there any way of identifying what interest rate is being paid on each of them? If `BankingTermDepositAccount` is a single tuple it seems possible to use `depositRate` and/or `depositRates` but this may be inaccurate for certain scenarios? For multiple tuples it doesn't seem possible unless one assumes they are all under the same rate or reverse engineers via `lodgementDate` and `maturityDate` as well as `maturityAmount`?

Is there an easier way of determining the interest rate of an individual term deposit particularly when there exists more than 1 of them on a single account?

**Comment by CDR-API-Stream** [comment]
Hi @perlboy, the support for the ``depositRates`` array came through a change request from the banks. At that stage, no request was made for different rates applicable to the one term deposit account. The assumption is that the same rate applies to all ``termDeposit`` instances.

The DSB would welcome any worked examples from the banks on their treatment of term deposits and clarification of the assumption before considering if a change is warranted to the standards.

**Comment by BH-UDA** [comment]
The original request to provide depositRates as an array to cater for multiple deposits within a single Term Deposit Account contained the scenario where each of these deposits could have different lodgment dates, maturity dates, maturity instructions and maturity amount.
In light of the comments raised in this issue this has been reviewed and the requirement should have included the identification of interest rate within each instance of the array as highlighted by @perlboy. 
Within our product structure the interest rate to be applied to an individual deposit within the Term Deposit account may be conditional on investment amount and/or term.

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA would you be willing to submit a worked example for review to progress this issue?

**Comment by BH-UDA** [comment]
Hopefully the below simple example provides some clarity around the potential Term Deposit structures that may be generated within a single Term Deposit account.

An example Term Deposit Product is defined to allow for the following investment options:
Investment Periods: 			1 Month to 6 Months
Investment Amount Tiering:		
                                        Up to $5,000			1.5%
					Over $5,000			1.75%
					Over $20,000			2.25%
					Over $30,000			2.3%

Customer “A” opens a Term Deposit Account of the product type described above and:
1.	Deposits $6,000 on 4th March for 3 Months with interest rate = 1.75%    (Deposit 1)
2.	Deposits $50,000 on 01 APR for 1 Month with interest rate = 2.3%           (Deposit 2)

Array element			Deposit 1			        Deposit 2
Lodgement Date		4th March 2020		1st April 2020
Maturity Date			4th June 2020			1st May 2020
Maturity Amount		$6,000.00			         $50,000.00
Maturity Currency		AUD				         AUD
Maturity Instructions	Rolled Over			 Paid Out at Maturity
Interest Rate			1.75%				 2.3%

Both Deposits comply with the term and amount options available within the product.
This scenario can be extended to the account having multiple additional investments with varying amounts, terms and interest rates along with differing maturity instructions.

**Comment by BH-UDA** [comment]
Hi,

An example has been loaded into the GitHub issue #132.

Thanks,
Bob Humphries
Business Analyst / Technical Writer

Ultradata - Vision to Reality
+61 3 9291 1600
www.ultradata.com.au<http://www.ultradata.com.au/>

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No further progress on this despite example uploaded by another participant. #184 appears to be related, closing this out of my backlog.

**Comment by nils-work** [comment]
Hi @perlboy 
The DSB is proposing this issue be addressed as part of [Decision Proposal 306](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306). Any feedback would be welcome.

**Comment by nils-work** [comment]
Hi @perlboy, @BH-UDA 

The `termDeposit` structure of **Get Account Detail** has been updated in the [Candidate Standards for Banking](https://consumerdatastandardsaustralia.github.io/standards/includes/additional/candidates/dp306/banking-dp306.html) to support rate detail for each deposit as noted in comments above ([1](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/132#issue-565646529), [2](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/132#issuecomment-597938971), [3](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/132#issuecomment-606324683)).

Consultation on making the Candidate Standards binding is now open through [Decision Proposal 338](https://github.com/ConsumerDataStandardsAustralia/standards/issues/338).
