### ISSUE TITLE
Clarification on Product Eligibility types

### ISSUE THREAD

**Issue by da-banking** [ConsumerDataStandardsAustralia/standards-maintenance#135]
# Request For Clarification
Data Action seeks clarification on the intended use of eligibility types.

Most appear to be exclusive, for example:
BUSINESS: _Only_ business may apply for the account
NATURAL_PERSON: The customer _must_ be a natural person rather than another legal entity

The exception to this is
PENSION_RECIPIENT: A recipient of a government pension _may_ apply for the product

Are the descriptions intended to be taken literally? That is, should a product which is available to an individual and a business have no eligibility types or both?

Switching to an API consumer's perspective, clarity and consistency among participants will be critically important. For example, A consumer will need to know if products available to a business are all products with a BUSINESS eligibility, or all products _without_ a NATURAL_PERSON eligibility. The former is at odds with the definition, but the latter is counter-intuitive.

**Comment by CDR-API-Stream** [comment]
Hello @da-banking, the description for PENSION_RECIPIENT is intended to read:
"_Only_ a recipient of a government pension may apply for the product"

This will be treated as a bug fix for the standards documentation.

Please note that ``STAFF``, ``STUDENT,`` and ``PENSION_RECIPIENT`` are specialisations of ``NATURAL_PERSON``. 

Eligibility conditions should be considered additive so it is allowable to include an eligibility with ``eligibilityType`` of ``NATURAL_PERSON`` and an eligibility with ``eligibilityType`` of ``PENSION_RECIPIENT``.

**Comment by da-banking** [comment]
@CDR-API-Stream thanks for the response.

With respect to the our last paragraph, we take it from this that we should consider an account valid for business use provided it does _not_ have the NATURAL_PERSON eligibility. Can you please confirm?

**Comment by CDR-API-Stream** [comment]
That would be a reasonable interpretation

**Comment by nils-work** [comment]
Just adding a note to this open issue as I think the topic was raised in the Data Quality Workshop today. 

My understanding of the [Product Eligibility Types](https://consumerdatastandardsaustralia.github.io/standards/#tocSproducteligibilitytypedoc) is that they refine the list of eligible customers.
i.e. Adding more eligibility types would make the eligibility criteria more restrictive.

This is based on the replies in this issue and the Standards themselves, though the documentation change mentioned [in this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/135#issuecomment-589445371) hasn't reached the standards yet.

> "**Only** a recipient of a government pension may apply for the product"

[This reply](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/135#issuecomment-589445371) describes making the eligibility more precise/restrictive by adding more types where applicable -
> Eligibility conditions should be considered **additive** so it is allowable to include an eligibility with `eligibilityType` of `NATURAL_PERSON` and an eligibility with `eligibilityType` of `PENSION_RECIPIENT`.

[This reply](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/135#issuecomment-591225610) describes how business eligibility would be exclusive of the `NATURAL_PERSON` type, meaning they shouldn't be used together -
> consider an account **valid for business use provided it does not have the NATURAL_PERSON** eligibility

The Standards include descriptions like -
> **BUSINESS**  -  **Only business may apply** for the account

Are these derived meanings/interpretations correct @CDR-API-Stream ?

**Comment by neale-morison** [comment]
Draft support article created: https://cdr-support.zendesk.com/hc/en-us/articles/900002729503

**Comment by nils-work** [comment]
A change to clarify the intent of the `PENSION_RECIPIENT` eligibility value (as clarified in [this comment](#issuecomment-589445371)) has been staged as detailed in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/565#issuecomment-1522693636).

**Comment by nils-work** [comment]
This [change](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/135#issuecomment-1526870020) has now been incorporated into Standards version 1.24.0.
