### ISSUE TITLE
Request for Clarification: is x-fapi-interaction-id mandatory for get customer

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#137]
Commonwealth Bank seeks clarity on the use of the x-fapi-interaction-id. On the HTTP Header page, x-fapi-interaction-id it is mandatory in the response header, however the “get customer”, x-fapi-interaction-id is missing from response headers. Can you please confirm that x-fapi-interaction-id is mandatory for get customer?
 
 
![file1](https://user-images.githubusercontent.com/43626361/74688631-320d6a00-522c-11ea-861f-66d93953df96.png)
![file2](https://user-images.githubusercontent.com/43626361/74688635-35085a80-522c-11ea-8669-fd863c6593af.png)
![file3](https://user-images.githubusercontent.com/43626361/74688639-376ab480-522c-11ea-9d7c-895c324bd648.png)

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss thanks - this is a documentation defect. Please treat "x-fapi-interaction-id" as a mandatory response header for the Get Customer endpoint.

**Comment by CDR-API-Stream** [comment]
This change has been incorporated into [v1.3.0 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.3.0.html#v1-3-0-release-notes).
