### ISSUE TITLE
 Clarification of Transaction details cluster content

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#139]
# Request For Clarification
We are seeking clarification on the provision of data relating to Payer and Payee within the Transaction Detail cluster of the Consumer Data and the associated Data Language Standards.
The BankingTransaction schema describes payer content as "Label of the originating payer. Mandatory for inbound payment." and payee as "Label of the target PayID. Mandatory for an outbound transaction. "The name assigned to the BSB/Account number or PayID" (by the owner of the PayID)".
In contrast the Data Language section of the Consumer Experience Guidelines includes the following permission language "Who you have sent money to and received money from; (e.g. their name, BSB, account number)".
It would appear the Data Language Standards may be misleading as the provision of BSB and Account number of a payee or payer associated to a transaction may contravene privacy standards. Can the requirements in relation to payee and payer information be clarified (e.g. Is BSB and account number permitted/required? What is specific requirement? Is masking of information required?) and can the Data Language requirement be reviewed/amended to clarify?

**Comment by CDR-API-Stream** [comment]
This will need to be validated with the CX Stream to confirm intent.  We will respond with a clarification once confirmation is received.

**Comment by CDR-API-Stream** [comment]
The CX Stream have confirmed that this language is inaccurate and a clarification will be made to the known issues section of v1.2.0.  This will then be incorporated as fix in a later version.

**Comment by CDR-API-Stream** [comment]
It is confirmed this issue was fixed in the CX Data Language Standards. This issue has been answered and it is being closed accordingly.
