### ISSUE TITLE
Data Holder Dashboard - Re-disclosure Of Corrected Data

### ISSUE THREAD

**Issue by da-banking** [ConsumerDataStandardsAustralia/standards-maintenance#14]
# Request For Clarification
The August version of the ACCC rules have a new requirement under: Part 1, Division 1.4, Subdivision 1.4.3, Section 1.15, (3)(g). 

This new rule requires the data holder dashboard to inform consumers if a disclosure was re-disclosed because the consumer requested it to be re-disclosed due to a previous disclosure having incorrect data. The technical standards do not seem to have any mechanism to allow for this. 

Will this need to be catered for in the technical standards?

**Comment by CDR-API-Stream** [comment]
No, it is not currently intended that the standards will cover this requirement.  The standards have not sought to define any aspect of the dashboards for holders or recipients beyond CX guidance.  The mechanism by which communication made to fulfil 56EN(4) of the legislation is not defined in the standards.
