### ISSUE TITLE
Lending Products and LVR tiering clarification

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#143]
# Request For Clarification
As a banking software provider we are seeking clarification on the compliance of our proposed approach for provided Product data for Lending Products with different rates based on LVR ranges.
Our system currently does not support a LVR rate tiering structure but caters for this by allowing LVR ranges to be described within the "sub" product level descriptions.
We have noted instances where the major banks provide LVR tiering rates within a single Open Banking product however due to the our current data structure this is not an option readily available and we are proposing to provide separate products for each LVR range.
As an example the following would be presented as four individual products:
1)  Standard Home Loan with LVR 60% and below
2)  Standard Home Loan with LVR 60-80%
3)  Standard Home Loan with LVR 80-90%
4)  Standard Home Loan with LVR over 90%
Our question is - will this representation be an acceptable format and conform to CDR rules?

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA the approach you suggest is allowable under the standards.

At the moment, some interpretation by data holders at the moment is expected as long as the specification is met. If in future:
* a common convention for products emerges, or 
* problems begins to arise for consumers of the data with too much complexity, 

then the DSB may become more specific and standardise these conventions.

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA if there are no more questions related to this query it will be closed in 7 days.

**Comment by markt-amp** [comment]
@BH-UDA I believe the implementation of BankingProductLendingRate is somewhat inefficient and the presence or absence of BankingProductRateTier open to ambiguity. 

This is further confused if you apply tiers to owner occupied vs investor & have different repayment types (P&I vs IO) - however it looks like change https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/48 will resolve that complexity.

Further the removal of subTier would be helpful too.

**Comment by CDR-API-Stream** [comment]
Hi @markt-amp, noting that subTier has been removed as part of [v1.3.0 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.3.0.html#v1-3-0-release-notes). 

Similarly #48 was addressed in v1.3.0.

Is there anything specifically that remains ambiguous in BankingProductLendingRate?

**Comment by markt-amp** [comment]
Hi @CDR-API-Stream - 
With respect to this clarification it's clear to me.

I've raised https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/184 for further improvement and representation of data within the schema

Best
-Mark

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
