### ISSUE TITLE
OAuth 2.0 MTLS-CA & CBAT

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#146]
# Request For Clarification
The Standards specify that support for [OAuth 2.0 Mutual TLS Client Authentication and Certificate Bound Access Tokens](https://tools.ietf.org/id/draft-ietf-oauth-mtls-07.html)  is mandatory but neither the [Tokens](https://consumerdatastandardsaustralia.github.io/standards/#tokens) nor the [Claims](https://tools.ietf.org/id/draft-ietf-oauth-mtls-07.html#x5t256) ever mention the resulting components, notably this part from the spec:

>To represent the hash of a certificate in a JWT, this specification defines the new JWT Confirmation Method RFC 7800 member x5t#S256 for the X.509 Certificate SHA-256 Thumbprint. The value of the x5t#S256 member is a base64url-encoded SHA-256[SHS] hash (a.k.a. thumbprint or digest) of the DER encoding of the X.509 certificate[RFC5280] (note that certificate thumbprints are also sometimes known as certificate fingerprints). 

Is this an oversight?

**Comment by deboraelkin2** [comment]
In addition to this, can you clarify whether access tokens have to be JWT, or can they be opaque?
If opaque tokens are acceptable, then please clarify whether using SHA256 certificate fingerprints are still mandatory, or whether another method for uniquely identifying a certificate bound to an access token when issued is acceptable.

**Comment by perlboy** [comment]
@deboraelkin2 Presumably if opaque tokens are in use the verification occurs using the [Confirmation Method for Token Introspection](https://tools.ietf.org/id/draft-ietf-oauth-mtls-07.html#rfc.section.3.2).

**Comment by deboraelkin2** [comment]
Yes, but that then requires implementation of an /introspection endpoint that returns cnf property with the certificate fingerprint. This contradicts the /introspection endpoint definition in [Endpoint](https://consumerdatastandardsaustralia.github.io/standards-staging/#end-points), which only allows _active_ and _exp_ property. Unless I'm missing something?

**Comment by perlboy** [comment]
> Yes, but that then requires implementation of an /introspection endpoint that returns cnf property with the certificate fingerprint. This contradicts the /introspection endpoint definition in [Endpoint](https://consumerdatastandardsaustralia.github.io/standards-staging/#end-points), which only allows _active_ and _exp_ property. Unless I'm missing something?

The Standards specify an introspection endpoint for Data Recipients to use, they don't specify how an introspection endpoint between the RS and OP is setup. I guess that goes to your original question of whether the SHA256 fingerprint must be used although alternatives are very likely to be less secure and quite possibly proprietary in nature.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

@deboraelkin2 some clarity on token types provided here https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/197

Regarding the original request, no response has been received so this ticket will be closed.
