### ISSUE TITLE
Clarification of admin/metrics - 'High Priority' and 'Unauthenticated' performace tiers

### ISSUE THREAD

**Issue by imesh94** [ConsumerDataStandardsAustralia/standards-maintenance#147]
# Request For Clarification

In [1], 'Get Status' and 'Get Outages' endpoints are mentioned under 'High Priority' tier. But according to the specification, those are 'Unauthenticated' as well. In metrics calculation, should they be added under both performance tiers, or is there a specific one?

[1] - [https://consumerdatastandardsaustralia.github.io/standards/#performance-requirements](https://consumerdatastandardsaustralia.github.io/standards/#performance-requirements)

**Comment by CDR-API-Stream** [comment]
Hi @imesh94 these should be treated as High Priority as per the [Performance Requirements](https://consumerdatastandardsaustralia.github.io/standards/#performance-requirements) section.

**Comment by imesh94** [comment]
Thanks. 
Should the '/register' (dcr) endpoint be considered for metrics? If so, what is the priority tier?

**Comment by perlboy** [comment]
@CDR-API-Stream There is an additional question here and it is unanswered.

**Comment by CDR-API-Stream** [comment]
Hi @imesh94 this was clarified in v1.5.0 of the standards. DCR end points should be considered for metrics in the High Priority tier.

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.5.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134). 

This issue will be closed accordingly.
