### ISSUE TITLE
Admin API Metrics - Suggestion to have separate endpoints for different metrics

### ISSUE THREAD

**Issue by imesh94** [ConsumerDataStandardsAustralia/standards-maintenance#148]
# Description
Current Admin API metrics[1] contains a single endpoint. Upon receiving a request, the Data Holder should calculate all the metrics and send a single response. 

[1] - [https://consumerdatastandardsaustralia.github.io/standards/#get-metrics](https://consumerdatastandardsaustralia.github.io/standards/#get-metrics)

# Area Affected
Since the response payload demands a high number of different parameters, the response time will be high (considering the database calls and calculations)

# Change Proposed
Instead of requesting all the metrics data from a single endpoint, we can have multiple endpoints to get different metrics (eg: separate endpoints for invocations, average response, tps, etc.)

**Comment by CDR-API-Stream** [comment]
Hi @imesh94 there are no plans to separate metrics data into multiple endpoints. Aggregation and tracking of metrics is typically a SIEM/gateway-level concern and the implementation is at the data holder's discretion to ensure you can meet the NFRs. It may be prudent to consider time series aggregation of metrics within the data holder implementation if you have concern with your current performance.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
