### ISSUE TITLE
A payee may have no nickname provided by the customer

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#151]
# Description
A payee may not necessarily have a nickname provided by a customer, but **nickname** in [BankingPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayee) is mandatory

# Area Affected
**nickname** in [BankingPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayee) which is present in responses from the Get Payees and the Get Payee Detail endpoint.

# Change Proposed
Change **nickname** to optional.

**Comment by WestpacOpenBanking** [comment]
We would appreciate an update on this issue.

**Comment by nils-work** [comment]
Similar to [issue 150](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/150) and questions in other forums, it seems like there may be a need for clarity around the difference between a mandatory field in the JSON schema (a 'required' property) and a mandatory non-empty value.
Prior discussion related to other fields has concluded that empty strings (for example) would be appropriate values for mandatory properties.

**Comment by perlboy** [comment]
@nils-work `required` in a JSON schema is still true when field is `""`. Within [Babelfish](https://github.com/bizaio/babelfish) we use `@NotEmpty` versus `@NotNull` for these.

**Comment by nils-work** [comment]
Hi @perlboy, yes I understand that `required` just means that the property must exist, not necessarily that it must have a certain value. Particularly, as you say, where there is no format, pattern or enumeration defined in the available swagger.

I'm suggesting a clarification about the meaning of the `required` column / `mandatory` keyword as it may relate to the property only, not necessarily the value :)

**Comment by CDR-API-Stream** [comment]
Hi @WestpacOpenBanking, this issue is being considered within [Maintenance Iteration 4](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134).

The payee nickname is important for the BankingPayee as there is no other natural display name to default to. Are DHs able to comment on what would commonly be displayed as a default in an Internet Banking context where there is no nickname available?

Maintaining the reliability of the nickname would be important. When a nickname is not present, defaulting to the a value _defined by the Data Holder_ would be preferred (such as payee's accountName, payId name, CRN, bpay biller etc.).

**Comment by CDR-API-Stream** [comment]
This change request was discussed in the maintenance iteration call: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-4:-Iteration-checkpoint:-Agenda-&-Meeting-Notes-(5th-August-2020)

The current position for this CR is accepted as:
* ``nickname`` remains mandatory
* The description is updated to read _"The short display name of the payee as provided by the customer. Where a customer has not provided a nickname, a display name derived by the bank for the payee consistent with existing digital banking channels."_

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.5.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134). 

The decision is to update the description for the payee, where a customer has not presented a payee nickname, to allow data holders to present a display name for payees in accordance with existing digital banking channels. Payee would remain mandatory.

This issue will be closed accordingly.
