### ISSUE TITLE
CRN in BankingBillerPayee should be optional

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#152]
# Description
A CRN is not necessarily associated with a BPAY payee. This is because the CRN may vary from payment to payment. Currently, CRN in [BankingBillerPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingbillerpayee) is conditional, but no condition is given.

# Area Affected
**crn** in [BankingBillerPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingbillerpayee) which is present in responses from the [Get Payee Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-payee-detail) endpoint. 

# Change Proposed
Change **crn** to optional.

**Comment by perlboy** [comment]
I believe the condition specified relates to  _"If the contents of the CRN match the format of a Credit Card PAN then it should be masked using the rules applicable for the MaskedPANString common type"_. 

Often internet banking applications prepopulate the CRN with the previous payment to the payee, is this not suitable?

**Comment by WestpacOpenBanking** [comment]
We would appreciate an update on this issue.

**Comment by CDR-API-Stream** [comment]
Hi @WestpacOpenBanking, this issue is being considered within [Maintenance Iteration 4](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134).

There is a condition on providing a CRN in the instance a credit card PAN is present the value should be masked. 

The DSB would welcome feedback from DHs on @perlboy's comments and commentary from DHs currently providing this data on how this is being handled.

**Comment by amanuel13** [comment]
There are three types/use cases of the use of CRN with BPay. 
1. Fixed CRN such as indicated credit cards or where the Biller has a fixed reference number identifying a customers account
2. Variable CRN (VCRN) where the biller generates and advises a customer a unique reference number for each bill . Utility companies often do this.
3. Intelligent Customer Reference Number (ICRN) where the reference number is unique to the bill. The reference number generated by the biller and provider to their customers includes values that enable  a customer /payers institution to complete a BPay mandated validation that the amount being paid is exactly the fixed amount of  a bill and the bill is being paid by the due date. if the amount attempted to be paid is different or it is attempted to be paid after the due date the payment attempt is required to be rejected. The use of this for example includes parking or infringement notice fines.

As such the proposal is supported as its supports the actual situation today.

**Comment by WestpacOpenBanking** [comment]
We would not recommend the use of the last CRN value as was suggested by @perlboy. A typical case where the CRN would vary from payment to payment would be where the CRN is used for a bill number rather than an account number of some type. We don’t record the Variable CRNs against payees in these cases because it is likely to result in an erroneous payment.

**Comment by amanuel13** [comment]
Fully agree with Westpac.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by perlboy** [comment]
@WestpacOpenBanking yes, I can see where this is a problem. Is there a way of determining a variable CRN versus a fixed one? I briefly looked for some documentation from BPAY on this but didn't have much success. 

FWIW, other internet banking platforms DO store the CRN (including variable ones) within payee information so this behaviour would be aligned (hence the suggestion in the first place).

**Comment by amanuel13** [comment]
The only indicator of variable versus fixed or in fact intelligent CRN is within a BPay biller file provided periodically by BPay to Paying institutions.

It contains an indicator field value whether the biller uses fixed , variable or intelligent CRNs.

This Biller file is referenced whenever one of the paying institutions customers initiates a bpay payment.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amanuel13** [comment]
There is no indicator in the customers transaction record to indicate though only the CRN value

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by commbankoss** [comment]
Commonwealth Bank currently requires a CRN for saving biller details in the address book. This may change in the future as CRN doesn't need to be tied to biller info i.e. variable CRN.
We prefer making CRN conditional: vCRN being optional, and fixed CRN mandatory, however we don't oppose Westpac's proposal and prefer it to the current standards.

**Comment by CDR-API-Stream** [comment]
This change request was discussed in the maintenance iteration call: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-4:-Iteration-checkpoint:-Agenda-&-Meeting-Notes-(5th-August-2020).

It is recognised that some ADIs allow customers to save payees without a CRN in situations such as iCRNs and vCRNs. In this case, the DSB is interested to get feedback on the proposal to treat CRN as conditional with the introduction of a new mandatory ``crnType`` field. As noted by @commbankoss and @amanuel13, this would cater for iCRN and vCRN with conditional optionality for the CRN in only those situations. ``crn`` would be mandatory if the ``crnType`` is ``FIXED_CRN``.  

This approach was supported in principle on the maintenance iteration call.

Proposed change within ``BankingBillerPayee``:
> ``crn``  &nbsp;&nbsp;&nbsp;**conditional** &nbsp;&nbsp;&nbsp;&nbsp; BPAY CRN of the Biller. If the contents of the CRN match the format of a Credit Card PAN then it should be masked using the rules applicable for the MaskedPANString common type. Mandatory if the type of CRN is ``FIXED_CRN``.
> ``crnType`` &nbsp;&nbsp;&nbsp;**mandatory** &nbsp;&nbsp;&nbsp;&nbsp; Denotes the type of CRN

``crnType`` enumerations:
> ``FIXED_CRN`` A unique reference number such as a credit card or a fixed reference number identifying a customer's account that does not change with each bill.
> ``VARIABLE_CRN`` Biller generated reference number provided to the customer that is unique to each bill.
> ``INTELLIGENT_CRN`` Biller generated reference number provided to the customer that is unique to each bill which fixes the amount of the bill being paid, expiry date or both.

**Comment by perlboy** [comment]
[As noted 15 July 2019](https://github.com/ConsumerDataStandardsAustralia/standards/issues/73#issuecomment-511268647) the use of the generic term _biller_ for BPAY is inappropriate:
> Specifically of note is that BPAY payments (a trademarked and commercially attached payment provider) have been granted exclusivity over generically named attributes notably billerCode, billerName and crn

This change further embeds this exclusivity and is now applying BPAY specific business rules. As a consequence, I'm supportive of the proposed change but also suggest (again) `BankingBillerPayee` be renamed to `BankingBPAYPayee`, `uType` be altered to reference `bpay` and the attribute name within `BankingPayeeDetail` be altered from `biller` to `bpay`.

**Comment by NationalAustraliaBank** [comment]
NAB is in a very similar position to @WestpacOpenBanking. NAB support making this field conditional in the short term and assessing the inclusion of “INTELLIGENT_CRN” for a post Feb 2021 release. We’d also like to point out that the BankingBillerPayee is used by both Get Scheduled Payments and Get Payee Detail API’s. Where this field is required for Get Scheduled Payments but conditional for Get Payee Detail. We suggested updating the description of the crn field so the condition is explicitly defined.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair for inclusion in v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). A change to the data standards was recommended.

This issue will be closed accordingly.
