### ISSUE TITLE
Maturity instructions for a term deposit may not always be known

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#153]
# Description
Maturity instructions for a term deposit may not always be known - it is only necessary for a maturity instruction to be given at some point in time prior to maturity. At present the enumerated value **maturityInstructions** in [BankingTermDepositAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductdiscount) is mandatory, with possible values ROLLED_OVER or PAID_OUT_AT_MATURITY. 

# Area Affected
**maturityInstructions** in [BankingTermDepositAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductdiscount) which is present in responses from the [Get Account Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-account-detail) endpoint

# Change Proposed
Change **maturityInstructions** to optional or add an additional enumerated value to cover the case where the maturity instruction is not yet known.

**Comment by perlboy** [comment]
@WestpacOpenBanking The description of the field is _"Current instructions on action to be taken at maturity"_. Our assumption has been that the "default" behaviour according to the PDS would be specified here unless otherwise specified, admittedly the term "instructions" is misleading. Nonetheless, using the Westpac TD PDS as an example:

> When an Account matures, **if we have not received any renewal instructions** before Maturity, or if you want to vary any previously supplied renewal instructions, you have six Business days commencing the day of Maturity in which to advise us of your instructions (the ‘Variation Period’). You may do so once only during this period of six Business days. **If no new or varied instructions** are received during the period of six Business days, the Account **will be renewed** in accordance with instructions advised before Maturity (if any) or (if none) under the same conditions as applied to the previous term (where available), using the standard interest rate applicable at Maturity. 

So, by my reading of that definition, the maturity instruction agreed by the customer (by agreeing to the terms of the PDS) on WBC TD's is `ROLLED_OVER` unless notified otherwise.

**Comment by commbankoss** [comment]
Commonwealth Bank supports the proposal by @WestpacOpenBanking to change **maturityInstructions** to optional or to add an additional enumerated value to cover the case where the maturity instruction is not yet known.

Commonwealth Bank does not require maturity instructions from customers. In such case where a customer is yet to provide instructions at maturity the term deposit defaults to a "[Holding Facility](https://www.commbank.com.au/banking/term-deposits/term-deposit-at-maturity.html)". Under the current enumeration there is no option to indicate such option. At the current state, the cases in BankingTermDepositAccount where no instruction was provided Commonwealth Bank would be forced to display incorrect and misleading values.

Either of the following options would allow for correct description of such cases:

- Change maturityInstructions to optional; or

- Add an additional enumerated value to cover the case where the maturity instruction is not yet known

**Comment by anzbankau** [comment]
ANZ has the 'default' of `ROLLED_OVER` like Westpac, but we agree with @perlboy that it's implicit at establishment through the terms and conditions. It's somewhat of a subtlety on 'instructions' implying an explicit customer action so we're not in favour of (but don't have a strong objection to) making `maturityInstructions` optional. Including an additional sentence in the description would cover this e.g. '*This includes default actions that may be specified in the terms and conditions for the product e.g. roll-over to the same term and frequency of interest payments*'. Alternatively, '*that may be*' could be removed.

However, Commonwealth Bank's default action is worthy of a new enumeration as it a new, distinct action e.g. 'HOLD' (without any indication of the mechanism or characteristics like 'HOLD_IN_FACILITY').

**Comment by perlboy** [comment]
Agree with @anzbankau and @commbankoss that the holding facility is an additional enumeration, that's a new approach to no-instruction I hadn't seen before!

**Comment by WestpacOpenBanking** [comment]
We would appreciate an update on this issue.

**Comment by CDR-API-Stream** [comment]
Hi @WestpacOpenBanking, this issue is being considered within [Maintenance Iteration 4](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134).

* Given the comments received, it seems reasonable to maintain that maturityInstructions remains mandatory. 
* @anzbankau's recommendation to modify the description to make clear it includes the default maturity instruction is also sensible.
* It seems reasonable to accomodate @commbankoss's proposal to include a separate enumeration for holding facilities as this is a distinct state.

Is it important (and is it practical and would it add value) to ADRs for DHs to differentiate between a customer's explicit instructions and the implied instruction relied upon by the underlying PDS/terms and conditions?

**Comment by WestpacOpenBanking** [comment]
Although it is feasible to populate the field with a default value, we suspect that it would be more useful to share the maturity instructions that have been actually provided by customers as this is what they would expect to see in a third party experience. This could be handled through enumeration types or field optionality.

* Westpac term deposit holders may, but need not, give us a maturity instruction prior to the end of the deposit term. They may either choose to withdraw or roll over to a new term.
* If they have not provided an instruction prior to maturity then the deposit will roll over on to a new term. The customer may, but need not, explicitly chose to withdraw or rollover during a variation period. Westpac does not have a notion of a holding facility.
* If they have not provided instructions at the end of the variation period then the new period will continue until the end of the term. 
* Account numbers are preserved during the term deposit lifecycle.

**Comment by CDR-API-Stream** [comment]
This change request was discussed in the maintenance iteration call: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-4:-Iteration-checkpoint:-Agenda-&-Meeting-Notes-(5th-August-2020)

The current position for this CR is:
* ``maturityInstructions`` remains mandatory
*  The description field should be changed as per @anzbankau's proposal
* The enumerated type is extended to include ``HOLD`` as a differentiated instruction where "funds are held in a facility or similar mechanism managed by the DH for a period of time until the customer provides instructions or the maximum period of the hold has elapsed. Funds may be renewed or withdrawn upon instructions by the customer."

**Comment by commbankoss** [comment]
We support @CDR-API-Stream's proposal to include "Hold" enum value, amend the description, and maintain the field mandatory.

**Comment by NationalAustraliaBank** [comment]
NAB supports @CDR-API-Stream's proposal. We recommend a small change to the “HOLD” enumeration value to be “INSTRUCTION_NOT_PROVIDED”, as it more accurately reflects that the customer’s instruction is not known.

Each bank may have different behaviours in the instance where instructions haven’t been provided. For example, if an instruction hasn’t been provided for a [NAB Term Deposit](https://www.nab.com.au/personal/accounts/nab-term-deposit), it will automatically roll over on the date of maturity.

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.5.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134). 

This issue will be closed accordingly.
