### ISSUE TITLE
scope in Authorisation request and request object

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#155]
# Request For Clarification
`scope` does not appear to be a mandatory claim in OIDC Request Object by value. Within this document it is stated:
> Even **if** a scope parameter is present in the Request Object value, a scope parameter MUST always be passed using the OAuth 2.0 request syntax containing the openid scope value to indicate to the underlying OAuth 2.0 logic that this is an OpenID Connect request. 

Indeed the example given within the [Standards specifies a scope](https://consumerdatastandardsaustralia.github.io/standards/#end-points) value of `openid%20profile` in the urlencoded form post but `"scope": "openid",` in the request object (ie. missing `profile`).

Should Holder's be requiring the `scope` claim within the Request Object? If both are specified which one should a Holder use? If they are not matched what should the error behaviour be?

**Comment by CDR-API-Stream** [comment]
Hi @perlboy as per the OIDC spec referenced, the ``scope`` value in the request object supersedes what is passed in the oAuth query params. The ``openid`` scope passed as a query param is required as a hint to the authorisation server.

> When the request parameter is used, the OpenID Connect request parameter **values contained in the JWT supersede those passed using the OAuth 2.0 request syntax**.

In this case, the non-normative reference in the standards should include both ``openid`` and ``profile`` scopes.

**Comment by perlboy** [comment]
Hi there,

You're absolutely right, in fact this is called out in [6.1.  Passing a Request Object by Value](https://openid.net/specs/openid-connect-core-1_0.html#RequestObject) as:
> Even if a scope parameter is present in the Request Object value, a scope parameter MUST always be passed using the OAuth 2.0 request syntax containing the openid scope value to indicate to the underlying OAuth 2.0 logic that this is an OpenID Connect request.

Could the example be  modified to include `profile` which would be a close alignment  [with the example given](https://openid.net/specs/openid-connect-core-1_0.html#code-id_tokenExample) within the specification.

**Comment by markverstege** [comment]
Yep, an internal issue has been created to address the non-normative example.

**Comment by CDR-API-Stream** [comment]
Hi @perlboy if there are no more questions related to this query it will be closed in 7 days.

**Comment by perlboy** [comment]
Can the documentation be updated first please. Historical experience has been that changes are lost after tickets are closed.

**Comment by CDR-API-Stream** [comment]
Yes, not a problem.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

This wasn't fixed in 1.3.0. Prioritising my backlog and closing.
