### ISSUE TITLE
aud in Request Object

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#156]
# Request For Clarification
The `aud` claim in the request object in the specification states:
>	The aud value SHOULD be or include the **OP's Issuer Identifier URL.** 

But the only mention of `aud` for request object is in the example which appears to mention a recipient Identifier URL:
>   "aud": "https://www.recipient.com.au",

Is this a typo?

**Comment by CDR-API-Stream** [comment]
Hi @perlboy you're correct. This is a typo and the ``aud`` should have the Data Holder in the request object. This will be fixed in a future documentation release. The example in the standards is non-normative so the underlying standards should apply.

**Comment by perlboy** [comment]
> Hi @perlboy you're correct. This is a typo and the `aud` should have the Data Holder in the request object. This will be fixed in a future documentation release. The example in the standards is non-normative so the underlying standards should apply.

Ok, so the next question is that this is specified as `SHOULD`. Are Holder's to assume this is not an enforceable claim?

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

This wasn't fixed in 1.3.0. Prioritising my backlog and closing.
