### ISSUE TITLE
Term Deposit Product Definition and Tiering limitation

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#158]
An ongoing system constraint is that for Term Deposits an offer can be either time tiered OR amount tiered, but not both.

The ability to have offers avilable for both time and amount tiered is done via separate product offerings.
For example: 
Offer A - is amount tiered but can only have 1 term definition (eg. 1 -2 Months), 
Offer B would have the same amount tiering as Offer A, but a different term definition (eg. 3-5 Months).

The current schema allows for a product to be amount and time tiered, but we need to generate a product definition per Offer A & Offer B as above (eg two related product definitions), and recognise that this differs from the approach of other ADIs

Our approach of two product definitions fits within the schema format. Please advise if there is any issue with our approach.

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA the approach you suggest is allowable under the standards.

At the moment, some interpretation by data holders at the moment is expected as long as the specification is met. If in future:
* a common convention for products emerges, or 
* problems begins to arise for consumers of the data with too much complexity, 

then the DSB may become more specific and standardise these conventions.

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA if there are no more questions related to this query it will be closed in 7 days.
