### ISSUE TITLE
Context of agentLastName, agentFirstName and agentRole properties (CommonOrganisation schema)

### ISSUE THREAD

**Issue by JamesJohnsonIBM** [ConsumerDataStandardsAustralia/standards-maintenance#159]
Within the [CommonOrganisation](https://consumerdatastandardsaustralia.github.io/standards/#tocScommonorganisation) schema, the agentFirstName, agentLastName and agentRole properties note these as relating to the individual providing access on behalf of the organisation.

My query is whether this value depends on the context of the user (logged in on behalf of an organisation) or whether this relates to a (semi-static) designated contact person for an organisation.

**Comment by JamesJohnsonIBM** [comment]
@CDR-API-Stream Please can you provide guidance available for the above?

**Comment by perlboy** [comment]
It states:
> of the individual **providing access on behalf** of the organisation.

Which would appear to align with "logged in or behalf of an organisation".

**Comment by CDR-API-Stream** [comment]
It relates to the logged in user initiating the consent process.

**Comment by leetabix** [comment]
Thanks for the response, will close this off

**Comment by JamesJohnsonIBM** [comment]
Thanks for the response, closing the issue.
