### ISSUE TITLE
Expiring authorisation when an accredited data recipient of CDR data becomes a data holder of that CDR data

### ISSUE THREAD

**Issue by da-banking** [ConsumerDataStandardsAustralia/standards-maintenance#16]
# Request For Clarification
The August version of the ACCC rules has a new requirement with an accompanying note under: Part 4, Division 4.4, Section 4.26, (1)(h). 

The note explains that an authorisation to disclose particular CDR data to an accredited person expires when an accredited data recipient of CDR data becomes instead a data holder of that CDR data. 

Does Data61 know what scenarios this rule relates to? Is this rule already catered for in the technical standards?

We are imagining that the accredited data recipient would just send a request to the Token Revocation Endpoint, but not be required to delete or anonymise the data they are holding for that token - as they are now a Data Holder for that data.

**Comment by CDR-API-Stream** [comment]
This rule has not been explictly catered for in the standards.  The assumption from the standards aligns with the suggestion in the query.

In summary, the data recipient would:
- Hold on to the data under the requirements of their new obligation as a holder (but would not need to delete or de-identify the data)
- The data recipient would simply discontinue the use of the existing tokens and allow them to expire naturally, or
- The data recipient would call the revocation end point to cancel the tokens

The standards are not explicit on the approach required for the data recipient.

**Comment by CDR-API-Stream** [comment]
I am closing this issue as there has been no response to the clarification.  Please re-open or re-raise if more clarification is required.
