### ISSUE TITLE
Product Reference Data Conformance to CDS?

### ISSUE THREAD

**Issue by DG-TMBL** [ConsumerDataStandardsAustralia/standards-maintenance#162]
Query for Weekly Data Holder meeting agenda.

One of the items TMBL are concerned with is Consumer Data Standards Validation.

We can be confident that our data is accurate, but we cannot be 100% confident that our product reference data complies with the standards.

•	The CDS standards themselves, are open to interpretation in many areas.
•	The ACCC Rules add complexity.
•	The System which hosts our Product Reference Data, does not enforce the CDS Standards (i.e. it allows us to enter data that does not conform)
•	Our Product Definition Tool, requires manual entry of product reference data.

There are risks that we have misinterpreted the standards or the rules, or that we enter data in the incorrect format.  We imagine this risk exists for all Data Holders.

We’ve been investigating ways to validate our Product Reference Data against the Consumer Data Standards, and we have found:
•	No 3rd party solutions that can do this.
•	The Conformance Tool on CDS GitHub is 14 months out of date and not being maintained.
•	In-house development is possible, however subject to the same risk of misinterpretation.   Anything we develop would need constant maintenance and updating.
•	External Legal review can provide some confidence, however this can be an expensive undertaking and does not completely remove the risk of misinterpretation.

Are there any industry standard practices, for ensuring that our Product Reference data is “up to standard”?  Is there a 3rd party or an official conformance tool that anyone has found in the market?  How is everyone else addressing this risk?

**Comment by perlboy** [comment]
@DG-TMBL For your information [Babelfish](https://github.com/bizaio/babelfish) incorporates full payload validation for all versions of all payloads. Additionally [Deep Thought](https://github.com/bizaio/deepthought) provides a GUI for Product Reference Data definition with validation backed by the 200 rules included in Babelfish. 

Both are free to use under LGPL (Babelfish) or GPL (Deep Thought) and Deep Thought also has a rapidly deployable AMI that means you can start designing product payloads within 15 minutes.

**Comment by DG-TMBL** [comment]
Thank you @perlboy I've asked our internal IT team to investigate Babelfish today. I'll report back if this solution meets our needs.

**Comment by commbankoss** [comment]
Commonwealth Bank supports the importance of up-to-date conformance tests for APIs and security to facilitate the adoption of the ecosystem and reduce amount of work required to interpret the standards by each of the Data Recipients and Data Holders. We believe conformance test should be updated for every version of the standard released.

**Comment by jogu** [comment]
As the Australian specs are using the OpenID Foundation FAPI specifications I'd strongly recommend that for security conformance testing the OpenID Foundation's FAPI conformance suite is used. The tool has been through a considerable amount of development and refinement, has been reviewed by the FAPI working group, improved as a result of feedback from both banks and vendors, and covers both interoperability and security topics, with the scope limited to the security protocols. It has tests for both data holders and data recipients.

I'm a member of the OpenID Foundations conformance team and I'd be happy to discuss how the tool can be used in Australia with the relevant body.

**Comment by jogu** [comment]
For reference, for functional testing, OB UK has an open source test suite they developed and is being used by the UK banks:

https://bitbucket.org/openbankingteam/conformance-suite/src/develop/

**Comment by cdradr** [comment]
@jogu thanks for that. sounds like a good idea.. where doesn’t @CDR-API-Stream needs to sign up?

**Comment by CDR-API-Stream** [comment]
The Data Standards Body maintain an open source project with standards validation that can be used to test recipient and holder implementations against the standards.  This is being maintained by the DSB Engineering team.

The repository for this can be found at:
https://github.com/ConsumerDataStandardsAustralia/java-artefacts

The modifications to this tool to support v1.2.0 of the standards is imminent and v1.3.0 is intended to follow in the new few weeks.

**Comment by perlboy** [comment]
> The Data Standards Body maintain an open source project with standards validation that can be used to test recipient and holder implementations against the standards. This is being maintained by the DSB Engineering team.

Do these cover the Security Profile?

**Comment by CDR-API-Stream** [comment]
Java Artefacts does not cover the security profile at this time.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
