### ISSUE TITLE
Clarifications on Metrics Requirements 

### ISSUE THREAD

**Issue by ryderwj** [ConsumerDataStandardsAustralia/standards-maintenance#163]
A few clarifications on the metrics to be presented via the GetMetrics operation:

**Availability Metrics:** As the non functional requirements for availability excludes planned outages, are planned outages also excluded in the metrics data?
**Performance Metrics**:  Assume that rejected API calls are **not** included and API calls that result in an Error **are** included in the performance metric 
**CustomerCount**: Is the customer count intended to be the number of unique DH customers with at least one in-force consent contract (irrespective of whether that customer has consented to share data with multiple ADR-Software products)?

**Comment by CDR-API-Stream** [comment]
Hi @ryderwj this is the correct interpretation.

**Availability Metrics:** do not include planned or scheduled outages. Unscheduled outages and incidents must be counted.

**Performance Metrics:** your interpretation is correct. Rejected API calls would incorrectly skew performance results. It is still important than when a data holder rejects an API call it does so for valid reasons and it can provide evidence of the reason(s) for rejection.

**CustomerCount:** this should be the count of active customers with one or more active consents across all ADRs. The definition of an active customer is determined by the data holder - for example, many customers may have more than one active digital identity that can be resolved to a single customer record in a CRM. Other times this is not possible. The data holder should consider the customer count in a similar way to how they currently define the term customer.

**Comment by CDR-API-Stream** [comment]
Included in CDR Support Portal Knowledge Article: https://cdr-support.zendesk.com/hc/en-us/articles/900001929123
