### ISSUE TITLE
Error response code for x-v version headers

### ISSUE THREAD

**Issue by SachiniSiriwardene** [ConsumerDataStandardsAustralia/standards-maintenance#164]
# Request For Clarification
I would like to clarify what the exact error code should be for the following scenarios: 

- When the x-v header is missing from the request 

- When a negative value or a decimal value (1.2) is sent for x-v or x-min-v headers

**Comment by CDR-API-Stream** [comment]
Hi @SachiniSiriwardene if a mandatory header is missing a Bad Request error is suitable.

> 400 Bad Request
> **Request has** malformed, **missing** or non-compliant JSON body or URL **parameters**

If an unsupported version is requested, such as a negative or non-integer value, a Not Acceptable error is suitable.

> 406 Not Acceptable
> The request contained an Accept header other than permitted media types, a character set other than UTF-8 or a **version that was not supported**

**Comment by perlboy** [comment]
Deep Thought currently responds 406 for both scenarios. Ticket opened for fixing on our side.

@CDR-API-Stream, we are currently returning a `null` payload despite throwing a descriptive exception internally. We are not aware of any explicit definition of error response payloads for these scenarios. Could you provide clarity on the expected response body in these scenarios?

**Comment by CDR-API-Stream** [comment]
Hi @SachiniSiriwardene and @perlboy in regards to the error payload, and the question about the ``code`` field defined in the ``ResponseErrorList`` (raised during last week's [Data Holder's Working Group](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Meeting-Notes-2020_03_26) call):

The standards have so far only identified specific error scenarios where the error payload is needed. An example being an invalid account ID where the standards specify an explicit error code, title and detail message. 

Outside of the specific error codes documented in the standards, the ``code`` is free to be used by data holders to specify their own error conditions. Apart from where an error payload is specifically nominated, the presentation of the error data payload is optional.

If a data holder does present an error then it must follow the format defined by ``ResponseErrorList`` and a data holder must be consistent. For instance, the ``title`` must be present and be a human readable label that is **constant per ``code``**. Therefore if a data holder does specify their own codes the titles need to be consistent although the ``detail`` and ``meta`` do not.

[Response Payload Structure](https://consumerdatastandardsaustralia.github.io/standards/#response-payload-structure):
> **``code``** field MUST be present: holds an end point specific error code

In certain scenarios, the standards define specific error codes that should be used. See [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist):
> Name | Type | Required | Restrictions | Description
> -- | -- | -- | -- | --
> code | string | mandatory | none | Must be one of the following: 0001 – Account not able to be found

**Comment by perlboy** [comment]
> The standards have so far only identified specific error scenarios where the error payload is needed. An example being an invalid account ID where the standards specify an explicit error code, title and detail message.
> Outside of the specific error codes documented in the standards, the `code` is free to be used by data holders to specify their own error conditions. Apart from where an error payload is specifically nominated, the presentation of the error data payload is optional.

If the intent is to supply specific error codes but allow any others can the description quoted of "Must be one of the following" be fixed then?

> If a data holder does present an error then it must follow the format defined by `ResponseErrorList` and a data holder must be consistent. For instance, the `title` must be present and be a human readable label that is **constant per `code`**. Therefore if a data holder does specify their own codes the titles need to be consistent although the `detail` and `meta` do not.

By the mere definition that the codes are numerical there will likely be overlapping codes used for different responses by data holders. In effect this may be a worse outcome then no error code at all. 

> In ~~certain~~ **one** scenario~~s~~, the standards define specific error codes that should be used. See [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist):

This response seems divergent to the open request for data in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/118

**Comment by CDR-API-Stream** [comment]
The comment provided by the DSB above related to error responses was slightly misleading and has been edited to be more correct.

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
