### ISSUE TITLE
Consent flow - Handling client with personal and business accounts

### ISSUE THREAD

**Issue by vongalex** [ConsumerDataStandardsAustralia/standards-maintenance#166]
Context:
As part of the consent flow, the client number entered on the login page is a client number associated to an individual. However this client can be also the main representative of one or multiple companies.

In this case (when the client is identified as having multiple profiles - Profile to be e.g. individual/personal, company A, company B), do we need an additional screen to be displayed as part of the consent flow after authenticating and validating the eligibility of the client where he/she could select which profile he/she wants to give consent and then select the corresponding accounts which the data is to be shared with the data recipient?

Should the selection on this additional screen be exclusive (i.e radio buttons) meaning that a consent is required per profile and not per client?
From the delivery point of view, is this planned for Phase 1?

**Comment by CDR-API-Stream** [comment]
Hi @vongalex this issue has been answered [here (#167)](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/167) and addressed [here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/167#issuecomment-606305802).

Does this cover off your questions?

**Comment by CDR-API-Stream** [comment]
Hi @vongalex if there are no more questions related to this query it will be closed in 7 days.

**Comment by vongalex** [comment]
Hi,

Confirming that this can be closed.
Thanks for your help!

Regards,
Alex

**Comment by vongalex** [comment]
Hi,
Regarding handling clients having both personal and business accounts, is this part of phase 1 release?
Also it is mentioned that concurrent consent will be introduced in v1.3.0 of the standards. Do you know when this version will be made available?

Thanks.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
