### ISSUE TITLE
Questions raised in Data Holder Working Group call 19-March-2020

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#167]
<p>Clarification questions for <a href="https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC&amp;DSB-Data-Holder-Working-Group-Agenda-&amp;-Notes-2020-03-19">19/03/2020 ACCC &amp; DSB Data Holder Working Group</a>. Pending responses will be published they become available.</p>
<table>
<thead>
<tr>
<th align="left" valign="top">From</th>
<th align="left" valign="top">Question</th>
<th align="left" valign="top">ACCC / DSB Response / Answer</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left" valign="top">Organisation A</td>
<td align="left" valign="top">Is there an estimate on when the revised timetable for non-majors may be published following the consultation that ended on 21 Feb?</td>
<td align="left" valign="top" rowspan="3"><p><strong>Updated 27-03-2020</strong><br/></p>
<p>The ACCC has been carefully considering stakeholder submissions in response to our consultation process on the revised timetable.</p> 
<p>The COVID-19 outbreak is obviously now causing disruption across the economy, including CDR project teams across all participants.  We are taking steps to assess the emerging impacts COVID-19 on all CDR stakeholders, and are considering a range of options to support the successful implementation of the CDR, recognising that responding to the COVID-19 virus may require flexibility.</p> 
<p>We are working to be able to provide industry with clarity on the implementation schedule for non-major banks as soon as possible.</p>
<p>We appreciate your patience and understanding as these matters are considered in the context of a rapidly changing environment.</p>
</td>
</tr>
<tr>
<td align="left" valign="top">Organisation A</td>
<td align="left" valign="top">Are there any firm conclusions you could share in advance following the end of the consultation?</td>
</tr>
<tr>
<td align="left" valign="top">Organisation A</td>
<td align="left" valign="top">Is the ACCC considering changes to the CDR deadlines in light of the extraordinary circumstances around COVID-19 (e.g. travel restrictions and quarantines adversely affecting technology deployment logistics and other CDR-readiness processes at ADIs)?</td>
</tr>
<tr>
<td align="left" valign="top">Organisation A</td>
<td align="left" valign="top">When will the CDR register sandbox access be given? This is needed to test the DCR flow and the meta data caching features.</td>
<td align="left" valign="top">At present there are no specific plans to develop a CDR Register sandbox.<p/>The ACCC's current priority is to launch the CDR in Banking as presently provided for by the Rules and Legislation. We are taking an iterative approach to rolling out the capability required to support industry. The ACCC recognises the feedback from industry around the need for a sandbox to help with assisted development and will monitor Industry needs, noting there are products becoming available in the commercial space that will help with these activities.<p/>The ACCC is developing a Conformance Test Suite (CTS), however it will not be a certification or assisted development tool. The intent is to ensure participants can demonstrate an adequate level of technical capability to enter the CDR ecosystem.<p/>As part of the onboarding process, the ACCC will require participants to pass through the CTS. While it is not a certification tool, it will be used to demonstrate there is a level of confidence participants can operate safely and securely before entering the CDR ecosystem. More information will be provided on the CTS.</td>
</tr>
<tr>
<td align="left" valign="top">Organisation B</td>
<td align="left" valign="top">When will the link to the CDR Participation Portal be available?</td>
<td align="left" valign="top"><p>The intent is to permit access to the CDR Portal for participants to commence accreditation applications from mid-April. Access to the CDR portal will also enable Managed Roll Out activities.<br/></p><i>NOTE: The ACCC understands the impact caused by COVID-19 to CDR participants. This is being considered and dates expressed in this response may be reviewed and amended where required to manage impacts to delivery.</i></td>
</tr>
<tr>
<td align="left" valign="top">Organisation C</td>
<td align="left" valign="top">Are there any estimations on when final Accreditation guidelines will be published.</td>
<td align="left" valign="top"><p><strong>Updated 27-03-2020</strong><br/></p>
<p>The final Accreditation guidelines are scheduled to be published within a fortnight.</p>
</td>
</tr>
<tr>
<td align="left" valign="top">Organisation D</td>
<td align="left" valign="top">When will the next version of the Rules be released? are you still aiming for end of this month?</td>
<td align="left" valign="top">Pending response</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">1. Is there a list of browsers that should be supported for Consent flow? Or is it up to each company to determine?</td>
<td align="left" valign="top">From a CX perspective there are no requirements on which browsers must be supported. At a minimum it should be consistent with a data holder's existing digital banking channels.</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">2. Is a data holder required to offer the client the ability to amend the duration of the consent and the type of data (authorisation scope) or should the DH only reflect whatever was selected by the client on the data recipient side?</td>
<td align="left" valign="top">Consent is immutable; As per the standards today, Data Holder dashboards should reflect the original consent and cannot be amended. <p/>There are no standards which currently allow for re-authorisation or modification of a consent contract. Addressing re-authorisation in the future is currently on the DSB's roadmap but this would first require a CDR Rules change to allow.</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">3. From our understanding, the consent is individual and independent between the organisations, as per the rules and standard. That is to say, you can give consent for accessing your own accounts (personal) or the accounts belonging to one, and only one, company. For each of the profiles (personal, company A, company B,...), the list of accounts that the customer would be able to choose, is different.</td>
<td align="left" valign="top">That is correct. Consent is established between a given Data Recipientsoftware product, a given Data Holder and Consumer. Consent cannot span more than one organisation. In v1.3.0 of the standards, concurrent consent will be introduced. This will allow a single Data Recipient software product to establish one or more active consents for a Consumer to a given Data Holder. This is being introduced to allow Data Recipients to meet their obligations for data minimisation especially where one data recipient software product has many use cases that require different types of data.</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">3a. In this case (when the client is identified as having multiple profiles  e.g. individual/personal, company A, company B), do we need an additional screen to be displayed as part of the consent flow after authenticating and validating the eligibility of the client where he/she could select which profile he/she wants to give consent and then select the corresponding accounts which the data is to be shared with the data recipient?</td>
<td align="left" valign="top">Yes. This flexibility is allowed and is recommended (if required) in the CX Guidelines, p.77</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">3b. If a new screen is required, should the selection on this additional screen be exclusive (i.e radio buttons) meaning that a consent is required per profile and not per client?</td>
<td align="left" valign="top">This should be aligned to how banks recognise their customers today. If the bank allows for multiple customer profiles, banks can provide customers with a way to select the profile they want to share within.</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">3c. Confirming that this scenario is part of the first release in exposing customer data</td>
<td align="left" valign="top">The flexibility is already allowed, but when it applies would be based on rules phasing (e.g. types of accounts in scope)</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">Can a consumer change which accounts relate to consent in the Data Holder Authorisation Dashboard?</td>
<td align="left" valign="top">Yes they could. Accounts are associatedto consent but not part of the immutable consent contract. Whether a data holder provides a service in their dashboard that allows consumers to choose which accounts are being shared as part of an existing sharing agreement is up to the data holder. This is within the competitive space of the CDR.</td>
</tr>
<tr>
<td align="left" valign="top">Organisation E</td>
<td align="left" valign="top">For the Customer API, can you please confirm what are the official descriptions/definitions for the following address types:</td>
<td align="left" valign="top">There is no official definition. This is for each data holder to interpret based on their business logic:<p/><ul><li>REGISTERED</li><li>MAIL</li><li>PHYSICAL</li><li>WORK</li><li>OTHER</li></ul></td>
</tr>
<tr>
<td align="left" valign="top">Organisation F</td>
<td align="left" valign="top">Issue #162</td>
<td align="left" valign="top">Pending response</td>
</tr>
<tr>
<td align="left" valign="top">Organisation F</td>
<td align="left" valign="top">Issue #161</td>
<td align="left" valign="top"><p>There are a few options here. One is that the need to treat "at cost" fees differently requires a new feeType enumeration value and relaxation of the Amount field. The other option is to use a placeholder value for the amount such as "$0.00" and use the additionalInfo fields to describe the "at cost" treatment. If the preference is to explicitly differentiate "at cost" fees then a change request should be raised to update the standards.</p>
<p><strong>Update 27-03-2020</strong><br/>Please note that a CR has been raised by the community to address this issue. See Issue #168.</p></td>
</tr>
</tbody>
</table>

**Comment by spikejump** [comment]
Can there be further clarification to 3a above with respect to whether there's linkage/association between the client, profiles and the 'sub' that's returned from id_token?  For example, if a consent, C1, is provided for Company A profile and another consent, C2, provided for Personal profile for the same consumer then the 'sub' from the two id_tokens will be the same or different?

**Comment by CDR-API-Stream** [comment]
Hi @spikejump the relationship between customer and profile will be dependent on the Data Holder. The definition of "customer" is left to the Data Holder and does not have a specific independent definition and will depend on how the Data Holder defines a customer.  

The ``sub`` should relate to the _authorising customer_ as per the definition in the [CDR Federation section](https://consumerdatastandardsaustralia.github.io/standards/#cdr-federation)

> **Customer:**
> The authorising customer that is authenticated by a Data Holder.

**Comment by CDR-API-Stream** [comment]
If there are no more questions related to this query it will be closed in 7 days.
