### ISSUE TITLE
Client Authentication for API consumption

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#17]
Commonwealth Bank would like to reference this issue as an outstanding problem space. Data61 can we please receive an indication on when you will provide feedback on this [issue](https://github.com/cdr-register/register/issues/24) involving the registry?

**Comment by Adatree** [comment]
Have any of the ADR candidates provided feedback that implementing those endpoints is a risk to the schedule?

**Comment by CDR-API-Stream** [comment]
The issue of client authentication for APIs covered by the standard is a concern for the standards and not the Register.  The DSB team do not actively monitor the Register consultation repository for standards queries.  The only paradigm of client authentication expected to be covered by the Register is Data Recipient or Data Holder accessing Register APIs

Client authentication for all forms of data access covered by the standards was clarified in version 1.0.0.  Please refer to https://consumerdatastandardsaustralia.github.io/standards/#client-authentication.

This section clarifies the mechanisms referred to in the comment referenced.
