### ISSUE TITLE
Planned Outages for Product Request service

### ISSUE THREAD

**Issue by Susan-CDR** [ConsumerDataStandardsAustralia/standards-maintenance#170]
Under Availability Requirements (applies to both authenticated and unauthenticated end points) it states that planned outages should be published to data recipients with at least one week lead time (notification method to be defined). Can you please confirm my assumption that the only notifcaition for unauthenticated end points will be via the Get Outage API?  

Many thanks.

**Comment by CDR-API-Stream** [comment]
Hi @Susan-CDR that's correct.

**Comment by CDR-API-Stream** [comment]
Hi @Susan-CDR if there are no more questions related to this query it will be closed in 7 days.

**Comment by Susan-CDR** [comment]
All good. Many thanks
