### ISSUE TITLE
Negative Available Balance in Get Balances response

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#177]
# Description 

Currently availableBalance contains the description “Assumed to be zero or positive”, however there are legitimate cases where this value may be negative. An example of said scenario: 

1. A customer has a transaction account with a balance of -$400, a overdraft limit of $1,000, and so an available balance of $600. 
2. The customer then deposits a cheque for $700. The account Balance is now $300, though the available balance is still $600 as the cheque hasn't cleared. 
3. The same day the customer’s overdraft limit is removed. The balance doesn’t change at $300, but the available balance is now -$400.  
4. When the cheque clears, the customer’s available balance will be the same as the account balance. 

# Area Affected  

AvailableBalance property of BankingBalance.  

# Change Proposed  

Removal of "Assumed to be zero or positive" from the description of availableBalance.

**Comment by perlboy** [comment]
This looks like the field used to be optional (requiring a declared assumption) and now isn't. Presumably since it's mandatory there is no need for an assumption which I guess is what @commbankoss's change is intended to do?

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss, this change request is being considered in the data standards [4th maintenance iteration](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/projects/3).

In the situation described, the available balance at step 3 would be $0.

The _available balance_ is the balance of funds the customer has available to transfer. If the customer's overdraft is removed, then the expectation would be the customer would have $0 funds available until the cheque clears. Until that time they might have an account balance of $300 however the available balance remains $0.

We'd welcome any further perspectives from Data Holders.

**Comment by commbankoss** [comment]
Thank you for your response @CDR-API-Stream. We agree that when available balance <=$0, no funds are available to the customer. However, our implementation (in our digital channels) allows for negative availableBalance (i.e. -$400 in step 3), and more accurately describes the financial state of the customer's account. For example, the customer in the example in step 3 now knows that they require at least another $400 in the account before they have positive funds again.
Nonetheless, being able to display a negative value for availableBalance allows our digital channels data to be reflected accurately in the open banking ecosystem.

**Comment by CDR-API-Stream** [comment]
This change request was discussed in the maintenance iteration call: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-4:-Iteration-checkpoint:-Agenda-&-Meeting-Notes-(5th-August-2020).

The change to allow a negative ``availableBalance`` will not be supported. No other participants have provided feedback and it was not supported during the maintenance iteration calls.

**Comment by CDR-API-Stream** [comment]
This change was not supported and this issue will be closed accordingly.
