### ISSUE TITLE
Clarification required on Unavailable Accounts in Consent Workflow

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#178]
# Request For Clarification
We are seeking clarification on the provision of Unavailable Accounts in the Consent Workflow.

Within the Consumer Experience Guidelines (v1.2.0) it is stated that Unavailable Accounts SHOULD be displayed in the Data Holder Consent Authorisation Workflow and the reason they are unavailable SHOULD be communicated. The associated screen example displays an Unavailable Account section including a Joint Account.

In reviewing the latest Joint Account Election and Authorisation consultation paper it contains a section stating that Unavailable Accounts are not permitted to be shown.
Both sections are extracted below.

Can we please have clarification of the current requirement around Unavailable Accounts - do current CDR Rules allow unavailable accounts to be displayed in the Consent workflow as described in the guidelines or is this section misleading?

_________________________________________________________________________________________________
Consumer Experience Guidelines v1.2.0 - Account Selection

CX Standard
1. Data holders MUST allow the consumer to select which of their accounts to
share data from if the data request includes account-specific data and if there are
multiple accounts available.
Data holders MAY omit this step if none of the data being requested is specific to an
account (e.g. Saved Payees).
   ● 2. If certain accounts are unavailable to share, data holders SHOULD
           show these unavailable accounts in the account-selection step.
           ○ 3. Data holders SHOULD communicate why these accounts
                  cannot be selected, and this SHOULD be communicated as in-line
                  help or as a modal to reduce on-screen content.
           ○ Data holders MAY provide instructions on how to make these
               accounts available to share, and this SHOULD be communicated
               as in-line help or as a modal to reduce on-screen content.
__________________________________________________________________________________________________
Consultation Draft 5 | Joint Account Election and Authorisation | 26.03.20 - Current Status

Joint Account Election
The following issues need to be considered:
1. The Consent Flow is likely where a consumer will first encounter the concept of CDR and joint account sharing. 
2. Consumers are unlikely to opt-in until they see the value of doing so, and as such we consider it unlikely that consumers will pre-elect via a JAMS. 
3. If a joint account is not available in the authorisation flow, DHs are not permitted to show ‘unavailable’ accounts, nor provide instructions for how to elect those accounts. 
4. If a consumer only has joint accounts with a DH, this means no accounts will be presented. 
___________________________________________________________________________________________________

**Comment by CDR-CX-Stream** [comment]
Hi @BH-UDA,

A response to this query can be found at the below link:

https://github.com/ConsumerDataStandardsAustralia/standards/issues/106#issuecomment-615054953

As follows: 
**Unavailable accounts being shown in the authorisation flow**
Data holders are permitted to show unavailable accounts in the authorisation flow except for unavailable joint accounts. V1.3.0 of the CX Standards/Guidelines will clarify this exception as per the below:

_Data holders are not permitted to show unavailable joint accounts as joint accounts need to be elected via a joint account management service before they are permitted to appear in the authorisation flow (See CDR Rules: Schedule 3, 4.1(1); 4.2; 4.3(3); and CDR Rule 4.24)_

**Comment by BH-UDA** [comment]
Clarification noted - thanks
