### ISSUE TITLE
What's the expected behaviour?   x-v set to a implemented version but a valid implementation version exists between x-min-v and x-v

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#179]
# Request For Clarification

Trying to see how to interpret the specifications:

**Scenario:1** 

x-min-v =1

x-v = 5

Data holders have Implemented versions :  1 and 2.

What should the response be?

I have interpreted the specs as follow
Source: https://consumerdatastandardsaustralia.github.io/standards/#http-headers

> The holder should respond with the highest supported version between x-min-v and x-v.

Interpretation: Though the Data holder does not have a V5 of the implementation, they do have a version (in fact two in our case) between the x-min-v  and x-v.

Source: https://consumerdatastandardsaustralia.github.io/standards/#http-headers
> If all versions requested are not supported then the holder should respond with a 406 Not Acceptable.

I interpreted the "all versions" as version numbers between and including x-min-v and x-v.  

_Outcome_ - Data Holder will respond a 200 with the implementation results of V2.

**Scenario :2** 

x-min-v =3

x-v = 5

Data holders have Implemented versions :  1 and 2.

_Interpretation_ - No supported version between and including x-min-v and x-v.

 _Outcome_ -Data holder will return a 406 Status code stating no supported implementation version.

Wondering how the others are reading and interpreting the specs for these scenarios,

**Comment by perlboy** [comment]
The scenarios you have presented aligns with our interpretation. We have considered whether responding with the nearest payload possible is better than a 406 though in the "hope" that maybe the requestor can still process it. Nonetheless [BabelfishVersioner](https://github.com/bizaio/babelfish/blob/master/src/main/java/io/biza/babelfish/cdr/support/BabelfishVersioner.java) iterates downward until it matches or throws `UnsupportedPayloadException` if it finds nothing. This exception is intended to percolate at the API level as a 406.

**Comment by CDR-API-Stream** [comment]
@bmangalaganesh - your interpretation is correct.
