### ISSUE TITLE
Clarification of authorisation response modes supported

### ISSUE THREAD

**Issue by Adatree** [ConsumerDataStandardsAustralia/standards-maintenance#18]
# Request For Clarification
Hey there. We are requesting clarification as to whether [OAuth 2.0 Form Post Response Mode](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html) is an authorisation response mode that will be supported by Data Holders. At the moment, the response mode we can find mentioned in the standard is 'fragment' which is part of the non normative example in the [endpoints section](https://consumerdatastandardsaustralia.github.io/standards/#end-points).

From [this](https://openid.net/2016/07/16/preventing-mix-up-attacks-with-openid-connect/) security article:
_To aid the implementation of the best practice, we recommend that OPs consider supporting OAuth 2.0 Form Post Response Mode, as it makes it simpler for clients doing code id_token to get both the code and the ID Token on the backend for verification._

Thank you.

**Comment by jogu** [comment]
The normative requirement to support fragment comes from this clause:

> Only a response_type (see section 3 of [OIDC]) of code id_token SHALL be allowed.

as requiring support for the fragment response mode is a requirement of OpeniD Connect for response_type=code id_token

I don't see anything in the spec that would change the default position in OpenID Connect that form post mode is optional to support, and  hence my interpretation of the current spec is that Data Holders may chose to support form post mode if they wish, but they aren't required to.

**Comment by CDR-API-Stream** [comment]
The response provided by @jogu is accurate.  The standards have not sought to constrain or change the normative behaviour in this case.
