### ISSUE TITLE
mutual_tls_sender_constrained_access_tokens metadata value has been superseded by tls_client_certificate_bound_access_tokens

### ISSUE THREAD

**Issue by CDR-Register-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#186]
# Description
As raised in [CDR Register Issue 74](https://github.com/cdr-register/register/issues/74) the `mutual_tls_sender_constrained_access_tokens` value exposed in the OIDC Configuration document has been superseded by the metadata value `tls_client_certificate_bound_access_tokens`

# Area Affected
The [OIDC Provider Configuration Endpoint](https://consumerdatastandardsaustralia.github.io/standards/#end-points) example is out of date 

# Change Proposed
The non-normative example needs to be updated to reflect the latest ratified standards

**Comment by perlboy** [comment]
Just flagging that as part of this change the ACCC should consider explicitly defining this attribute as having a `true` value as the default is `false`.

**Comment by CDR-API-Stream** [comment]
This will be treated as a documentation defect in the next version of the standards.

**Comment by CDR-API-Stream** [comment]
This change request has been addressed in v1.3.1 of the data standards. This issue has been answered and it is being closed accordingly.
