### ISSUE TITLE
Clarification is needed on the issue of ADI brands and endpoint URIs

### ISSUE THREAD

**Issue by Michael-Backhouse** [ConsumerDataStandardsAustralia/standards-maintenance#187]
Clarification is needed on the issue of ADI brands and endpoint URIs - rule 5.25(1)(b)(iii).  This has been a live issue for some time now and resolution is needed so that our system developers can move forward.  Has any progress been made with the brands review and when will we hear the outcome?  

- Do we need one endpoint per sub-brand?  eg: bank.com.au/cdr/{brand-name}/GetProducts
- OR is it acceptable to pass brand as parameter?  eg: bank.com.au/cdr/GetProducts?brand='xx'
- OR return all data as a shared list identified by brand  eg: bank.com.au/cdr/GetProducts ==>  {"brandA", "product-data", "brandB", "product-data"}

Is it up to each data holder to determine which approaches they will do, or do we have to implement all, or, a subset of these approaches.

**Comment by CDR-API-Stream** [comment]
This was discussed on the DH call.  This is a repeat of the answer provided on the call.

The standards provide for two levels of branding in the standards:

1. A brand that appears to a customer like a standalone bank with its own digital presence, login credentials, etc.  This is a common scenario in the banking industry.  UBank and BankWest are both examples of brands of this nature.
1. A brand that is used to differentiate and sell a product but the servicing of the product occurs under the banner of a larger brand.  This is the scenario where a brand may be used to sell a product but, once originated, the customer's servicing relationship will be with the master brand.

The classification of brands is a matter for the Data Holder but the intention of the standards is that brands of type 1 would be a separate entry in the register with independent base URIs and brands of type 2 would be dealt with via tags in the product reference payloads.

A good rule of thumb that has been discussed in multiple forums is that the selection of brand type should be aligned to the understanding of the customer.  If a customer is used to logging into the internet banking site for *Brand X* then *Brand X* should probably be considered a type 1 brand as described above.

**Comment by CDR-API-Stream** [comment]
This issue has been closed as per the [Data Standards Maintenance process](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance#closing-issues). No further questions or comments have been received since an answer was provided.
