### ISSUE TITLE
Status code when a ADRs sotfware product has become inactive

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#188]
# Request For Clarification
After the consent flow, the ADR apps have a valid token (access and refresh tokens).

If the status of the ADR and or the software product changes then the CDR request can be rejected by the data holder (DH)  based on the [DH responsibilities table](https://cdr-register.github.io/register/#data-holder-responsibilities).

What is the expected status code when a token/consent is still valid (e.g ADR status is active , SP status is inactive).

We are returning a 422 error as that seems to be the closest from the list fo status codes in the [response code page](https://consumerdatastandardsaustralia.github.io/standards/#http-response-codes).

403 (Forbidden) is also a potential candidate status code.

What are the other Data Holders implementing for this scenario ? Is there an explicit guideline for this scenario from the standards team?

**Comment by spikejump** [comment]
DSB at one point suggested that 422 is applicable to the scenario when Customers modify the authorised account post consent.  In such a case, a previous authorised account was removed from an active consent and when DRs request the now removed account then 422 is the appropriate error code to return.

403 seems applicable to your scenario as no re-auth will fix this issue (ie 401 is not applicable) and DR's SP is forbidden to access until SP status changes.

**Comment by perlboy** [comment]
@spikejump Do you have a reference for this? I think the original question is focused on DH -> DR status not Consumer Consent status but nonetheless, modification of consents (beyond outright revocation) does not appear to be documented?

**Comment by CDR-API-Stream** [comment]
In the [DH responsibilities table](https://cdr-register.github.io/register/#data-holder-responsibilities) a suspended or revoked ADR is indicated to be handled the same as an SP being made inactive.  In both cases data sharing should not occur and re-authenticating will not resolve the situation.

Based on this @spikejump is correct that 403 would be the appropriate response.

In reference to the use of 422, this was only in the scenario that a previously provided Account ID was included in the request body of one of the "for specific Accounts" APIs but the account that the ID refers to is no longer attached to the consent.  This is a fairly specific scenario.
