### ISSUE TITLE
Masked account number 

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#189]
# Request For Clarification
I wanted to understand the rationale for the masked account number in one API while the same account number is unmasked in another API.

The   GET /banking/accounts API returns a masked account number  (

> A masked version of the account. Whether BSB/Account Number, Credit Card PAN or another number

) as described by this object - [BankingAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccount)

While the GET /banking/accounts/{accountId} returns an unmasked account number (

> The unmasked account number for the account. Should not be supplied if the account number is a PAN requiring PCI compliance.

) 
as described by this object - [BankingAccountDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccountdetail)

Wanted to understand the rationale for disclosing the "unmasked number" for the get Account Details API.  I thought that we either _mask_ or _unmask_ account numbers   (of course the credit card/PAN PCI DSS compliance data will never be in the clear) consistently.

Happy to implement the way the specifications state but would like to understand the rationale. I am sure there must have been discussions in the past (I am not able to locate them during my search in this repo).

**Comment by perlboy** [comment]
@bmangalaganesh Because the two functions are covered by different scopes which have different CX defined descriptions to consumers.

**Comment by CDR-API-Stream** [comment]
@perlboy's answer is correct.  The real account number is sensitive and was limited to the more detailed scope.

The masked account number was included in the less sensitive scope to support the creation of user experiences where customer's need to select or view a list of accounts.

**Comment by bmangalaganesh** [comment]
Thanks @perlboy @CDR-API-Stream  for the inputs.

**Comment by CDR-API-Stream** [comment]
Captured in Knowledge Article: https://cdr-support.zendesk.com/hc/en-us/articles/900001780763
