### ISSUE TITLE
1.3.0: V2 links to V3

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#190]
# Description

Version 1.3.0 released yesterday introduces a new BankingProductDetailV3. It also keeps BankingProductDetailV2 in the specification but alters it to link to BankingProductV3.

https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductdetailv2

# Area Affected

BankingProductDetail

# Change Proposed

Fix the specification.

**Comment by CDR-API-Stream** [comment]
Thanks for highlighting this.  BankingProductDetailV2 should have been revved to BankingProductDetailV3.

This will be amended as a documentation defect in the next version of the standards.

**Comment by perlboy** [comment]
Related to this BankingProductV3 was released but does not appear to have any changes to BankingProductV2 (because the V3 increment was primarily triggered by `subTier` being dropped which is not present in _BankingProductV#_).

**Comment by nealemorison** [comment]
This is fixed in the current version of the CDS: https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductv3

**Comment by CDR-API-Stream** [comment]
A change to fix this issue was included in the v1.3.1 errata release. 

This issue will be closed accordingly.
