### ISSUE TITLE
V1.3.0: Minimum Requirements for Metadata are not Compliant 

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#191]
# Description

The minimum metadata specified within [OpenID Provider Configuration End Point ](https://consumerdatastandardsaustralia.github.io/standards/#end-points) would result in a discovery document which does not comply with the [OpenID Connect Discovery 1.0 Configuration Response](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse).

# Area Affected
`OpenID Provider Configuration End Point`

# Change Proposed
Ensure mandatory metadata specified within the CDS meets the minimum required fields specified within OIDC-D.

**Comment by CDR-API-Stream** [comment]
The section on the discovery end point in the standard specifically refers to section 3 and 4 of the [OIDD] normative standard.  It then goes on to emphasise specific parts of the [OIDD] spec that, because they are referenced elsewhere in the standards, are critical for inclusion.  This does not imply that other fields that are required by section 3 of [OIDD] have been made optional.  For this to be the case it would need to be explicitly stated.

This change request will therefore not be progressed.

**Comment by perlboy** [comment]
> The section on the discovery end point in the standard specifically refers to section 3 and 4 of the [OIDD] normative standard. It then goes on to emphasise specific parts of the [OIDD] spec that, **because they are referenced elsewhere in the standards, are critical for inclusion.** 

So where is  `id_token_signing_alg_values_supported` which is referenced in the spec as _"ID Tokens must be **signed** and encrypted"_ and who's normative example provided specifies what appears to be an invalid signing support of `ES256`?

Conversely `jwks_uri` is specified when it is implied by the extensive use of signed JWT's. 

The provided response appears to be contradictory and focused on ensuring ambiguity continues to exist rather than on providing implementer's clear guidance.

**Comment by perlboy** [comment]
Ambiguity is the preference over accuracy. We see no value in persuing this further because the DSB doesn't appear to care. Thumb implements OIDC compliant discovery parsing and, in the absence of a compliant discovery document, assumes the following defaults:

- Signing algorithm used is `PS256`
- Encryption algorithm used is `RSA_OAEP_256`
- Encryption encoding is `A256GCM`

Clearing backlog and closing ticket.
