### ISSUE TITLE
1.3.0: No GetProducts is valid between Aug 29 2020 and Feb 2021

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#192]
# Request For Clarification

[Get Products V1](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-products-v1.html#get-products-v1) is being retired: August 29th 2020
[Get Products V2](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-products-v2.html#get-products-v2) is being retired:  August 29th 2020
[Get Products V3](https://consumerdatastandardsaustralia.github.io/standards/#get-products) must be implemented by: February 2021

Consequently, between August 29th 2020 and February 2021 there is no mandatory GetProducts specified?

These seem like fairly obvious things that would be brought up in a change control process but based on the commit history it would appear that, after essentially zero activity for 3 months, major changes occurred 3 days ago, a "review" was conducted in <24hrs and then the release was made over the weekend.

**Comment by CDR-API-Stream** [comment]
Thanks for highlighting this.  This is a documentation error on v2 of the two product APIs.  No decommission date has been explicitly set for v2 and when one is set it will be after the mandatory date for v3.

This will be updated in the next version of the standards as a documentation defect.

**Comment by nils-work** [comment]
Hi, could you please update the documentation as soon as possible to avoid confusion?
I thought the 'bug fix' value of the version allowed for corrections like this without the delay of a full minor-version release cycle -
https://consumerdatastandardsaustralia.github.io/standards/index.html#versioning
Thank you

**Comment by CDR-API-Stream** [comment]
Hi @nils-work this will be incorporated into a bug fix release (v1.3.1) in the next few weeks. We will provide another week to collect any other feedback on 1.3.0.

**Comment by CDR-API-Stream** [comment]
This change request was included in release 1.3.1.
