### ISSUE TITLE
Confirm URL for PRD for non majors

### ISSUE THREAD

**Issue by JamesChea** [ConsumerDataStandardsAustralia/standards-maintenance#194]
Hi,

Can you please confirm the URL to use for Product Reference Data release for non-majors. 
Please confirm it should use v1 as opposed to v2 for the endpoint URL.
https://data.holder.com.au/cds-au/v1/banking/products

We know that the header parameter is x-v=2.

Thanks

James

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
