### ISSUE TITLE
Clarification about 'other CDR participants' in Reporting Requirements

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#198]
# Request For Clarification

This question is regarding the **REPORTING - Copy of Rule 9.4 draft reporting forms for Data Holders and ADRs** spreadsheet.

In the fields 2.7-2.9 for both DH and ADR report forms we are asked to provide the reporting on:

2.7. Number of complaints made to you by other CDR participants in relation to compliance with Part IVD of the CCA                                           
2.8. Number of complaints made to you by other CDR participants in relation to compliance with the CDR Rules                                           
2.9. Number of complaints made to you by other CDR participants in relation to compliance with the data standards.               

Can you please clarify what exactly is the meaning of ‘other CDR participants’? Is there guidance on how we should manage the complaints process for ‘other CDR participants’?

**Comment by KaterynaShandro** [comment]
Hi, following up on the request above - will you be able to provide the clarification and guidance regarding complaints from other 'CDR participants'?

**Comment by CDR-API-Stream** [comment]
Hi @KaterynaShandro as this is a CDR Rules question, this has been passed onto the ACCC Rules team for a response.

**Comment by CDR-API-Stream** [comment]
Hi @KaterynaShandro, please find a response from the ACCC Rules team addressing your question:

> We do not expect a data holder to complete items 2.1-2.6 of the reporting form prior to the commencement of the data holder’s obligations relating to consumer data sharing. We do, however, expect data holders to report on the total number of complaints received from other CDR participants in relation to compliance with Part IVD of the Competition and Consumer Act 2010 (Cth), the CDR rules and the binding data standards insofar as those complaints relate to product data requests during the relevant reporting period (item 2.7 of the reporting form). Having said that, we do expect data holders to reasonably manage all complaints they receive, and note that the ACCC is able to consider complaints it receives from the public about PRD data.
> 
> We expect data holders to report on refusals to disclose CDR data and the CDR rules or data standards relied on to refuse to disclose that CDR data (items 4.1-4.2 of the reporting form). Item 4.3, which requests the data holder state the number of times it has relied upon the CDR rules or standards cited in response to item 4.2, is an optional reporting item. Under rule 2.5, a data holder may refuse to disclose required product data in response to a request in circumstances (if any) set out in the data standards. Examples of such circumstances in relation to product data are:
> * When the number of requests the data holder is receiving is above their service level thresholds defined in the non-functional requirements section of the data standards
> * There is a valid security reason that prevents sharing PRD data temporarily or for requests considered as suspicious.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
