### ISSUE TITLE
Clarification about Reporting for Products API (Phase 1)

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#199]
# Request For Clarification

This question is regarding the **REPORTING - Copy of Rule 9.4 draft reporting forms for Data Holders and ADRs** spreadsheet.

We understand that we will need to report on the number of product data requests received, once we go live with Get Products and Get Product Detail APIs in July 2020.
Is there any additional reporting expected for Get Products and Get Product Detail APIs? Specifically:
•       Do we need to report on complaints from CDR consumers (Section 2, fields 2.1-2.9)? If yes, what would be a hypothetical scenario when a CDR consumer would complain about Get Products and Get Product Detail APIs, considering both these APIs don’t expose any CDR consumer data?
•       Do we need to report on refusals to disclose CDR data, CDR rules and data standards relied on to refuse disclosure, number of times relied on each of those (Section 4, fields 4.1-4.3)? If yes, what would be an example of such refusal? Is ‘Too many requests by unique identifier’ security policy that is setup through a gateway such as Apigee considered a refusal to disclose CDR data that needs to be reported on?

**Comment by CDR-API-Stream** [comment]
Hi @KaterynaShandro, please find a response from the CDR Rules team:

> 'CDR participant' is defined in the Competition and Consumer Act 2010 (Cth) (relevantly a data holder or accredited data recipient) and the reporting form adopts the same meaning. Under the current version of the CDR rules, there are no mandatory requirements for managing the complaints process for complaints received from other data holders or accredited data recipients. 
> We will continue to monitor this space to see if there is a need to make further amendments to the rules in relation to internal dispute resolution requirements.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
