### ISSUE TITLE
Commissioning /decommissioning dates of the product APIs

### ISSUE THREAD

**Issue by C-Blatch** [ConsumerDataStandardsAustralia/standards-maintenance#202]
In the latest release of the standards (v1.3) it refers to the commissioning /decommissioning dates of the product APIs.  
For both Get Products and Get Products Detail the Future Data Obligations table states that;
-	V 3 of this end point must be made available by affected data holders by the end of Feb 2021
-	See: https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations

However if you follow through on the V2 link for either of the V2 of the APIs, you get the statement that 
-	This version (V2) is to be ceased to be called by data recipients by August 29th 2020 and can be decommissioned by data holders as of that date 
-	See: https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-product-detail-v2.html#get-product-detail-v2 

Which would mean V2 is to be decommissioned before V3 goes live, by 6 months.  Please confirm if the  above decommission date should be 29-Aug-2021.

**Comment by Camios** [comment]
When I first saw it I assumed it was a copy and past from the v1 endpoint's obsolescence page. If it was a copy and paste mistake, then v2's decommission date may not be in August. 

e.g. When V2 was created to replace V1, the overlap for both being available was only two months (V2 to be available on 1-July-2020 and V1 to be decommissioned by 29-Aug-2020). 

If the same period applies for the V3 to V2 overlap, then V2 would be decommissioned two months after V3 became available. Interestingly V3 only specifies a month of availability: February 2021. Should this be a specific day? 

Assuming for arguments sake it is the end of February, then V2's decommission date would be end of April 2021.

**Comment by CDR-API-Stream** [comment]
This is a [known issue](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/192) and will be fixed in v1.3.1 of the standards.

**Comment by CDR-API-Stream** [comment]
This change has been addressed in the data standards. This issue has been answered and it is being closed accordingly.
