### ISSUE TITLE
Can you be more granular with authorisation than the scopes in the spec?

### ISSUE THREAD

**Issue by mpomery** [ConsumerDataStandardsAustralia/standards-maintenance#203]
# Request For Clarification

Can I, as part of asking a user to consent to the scope "bank:accounts.basic:read", ask them to specify which accounts they want to allow to be read? Or should "bank:accounts.basic:read" always allow all accounts to be seen? Should it be like this for all the scopes and API endpoints?

As someone consuming API's, can I be certain that all the information is available, or could the user limit the data I am able to see?

**Comment by CDR-API-Stream** [comment]
Hi @mpomery, the data recipient cannot ask for specific accounts as part of the authorisation request because the accounts are not known to the data recipient. The account selection is performed on the data holder side where the context between the customer and accounts is known.

As a data recipient, you cannot know which accounts were not selected for data sharing. Instead, the data recipient is requesting to collect and use types of data defined by the data clusters. 

This would be applicable for any account-related endpoint.

**Comment by mpomery** [comment]
So when a user is going through the consent flow, they are able to, if implemented by the data holder, only choose to share specific accounts with a data recipient:

i.e. Only choose to share their transaction account and savings account, but choose to not share their credit card and mortgage.

**Comment by CDR-API-Stream** [comment]
That's correct. 

The data holder may have other entitlements rules or business rules that preclude the sharing of specific accounts and the rules define which types of accounts can be shared under which phase of the CDR. For example, there are different requirements related to the sharing of data for joint accounts.

Data holders may also allows customers to change the account selection after consent is established.

**Comment by CDR-API-Stream** [comment]
We have referred back to the CX team.  To clarify the comment above to ensure there is no ambiguity, Data Holders are required to allow for account selection during the consent process.  

A Data Holder is not required to allow a customer to change the account nomination after consent is established but it is encouraged.  Even if they do not allow this functionality accounts can still be removed from a consent through Joint Account Holder election and other types of events.

**Comment by bmangalaganesh** [comment]
> Data holders may also allows customers to change the account selection after consent is established.

I thought that consent is "immutable" i.e one is not allowed to change parts of the consent once it is granted. The only way change can be realized is via revocation.

Appreciate some clarifications in this space.

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh that is correct the consent contract itself is immutable however accounts are associated to consent. Consent represents the arrangement of the type of data to be shared and the terms related to the data. 

It is recognised that accounts have many different entitlements that mean they change state over time (e.g. frozen, suspended, fraud lock, etc.). 

Another reason is that some accounts have a multi-party owning relationship (joint accounts) where another person must also provide consent election to that account.

**Comment by CDR-API-Stream** [comment]
This issue has been closed as per the [Data Standards Maintenance process](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance#closing-issues). No further questions or comments have been received since an answer was provided.
