### ISSUE TITLE
Availability of openid scope in CDR SSA

### ISSUE THREAD

**Issue by imesh94** [ConsumerDataStandardsAustralia/standards-maintenance#208]
# Request For Clarification
In the sample SSA given at https://cdr-register.github.io/register/#dynamic-client-registration, the openid scope is not present. But it can be seen in the provided sample response at https://cdr-register.github.io/register/#registration-response

Can you please clarify if we can expect the openid scope to be available in the SSA, or should it be added by the data holder?

**Comment by CDR-API-Stream** [comment]
Hi @imesh94 this is a question for the CDR Register and should be posted here: https://github.com/cdr-register/register/issues

**Comment by imesh94** [comment]
Thanks. I will create a new issue.
