### ISSUE TITLE
Account may have multiple deposit rates or lending rates

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#21]
# Description
In [BankingAccountDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccountdetail) at most one lendingRate can be associated with an account. There are cases where the relationship between lending rates and an account is many-to-one. For example a credit card may have different rates associated with lending for purchases, cash advances and balance transfers. See also #9. 

# Area Affected
Definition of [BankingAccountDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccountdetail) which is used in:
* [Get Account Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-account-detail)
 
# Change Proposed
We suggest that the **lendingRate** description is updated to specify that for credit cards the lending rate is the purchase rate. Thought may also be given to allowing the representation of all lending rates for an account (e.g. an **additionalLendingRates** field). Alternatively the **lendingRate** field may already allow this. Although we are not yet aware of any examples, similar issues might apply to **depositRates** and it may make sense to make similar additions or changes in relation to deposit rates.

**Comment by CDR-API-Stream** [comment]
It is currently an implicit assumption that the base lending rate is the "normal" rate for an account (in the case of Credit Cards this would be normal purchases) with the lendingRates array being used for alternative, discount or penalty rates for different circumstances.

The DSB currently feels that this is already addressed in the standards.

**Comment by NationalAustraliaBank** [comment]
NAB agrees that the current standards allow for the accurate representation of multiple deposit and lending rates.
