### ISSUE TITLE
Endpoint 'hosted by' - what does this mean?

### ISSUE THREAD

**Issue by weznagwama** [ConsumerDataStandardsAustralia/standards-maintenance#211]
Hi guys,

just a query around security profile 'end points' (https://consumerdatastandardsaustralia.github.io/standards/#end-points)

For 'hosted by: data holder' what's the definition of 'hosted by'? Is this running the IdP on your physical tin in your own datacenter? Or your physical tin in a co-lo DC? Or does this mean running inside of a VM but hosted in public/private cloud?

Or does this more mean 'you have the ability to augment and extend functionality where required' so for example could be hosted on multi-tenant PaaS services, but you need access to the source-code, or the ability to administer core functionality of the IdP?

Or does it simply mean "originating from a URL the DH owns"?

Hope this makes sense. Cheers.

edit: for @bmangalaganesh - I'm wondering if you can use an IdP such as auth0, or if you can host something like identityserver in public cloud on platform services (elastic beanstalk), or install it on a VM, or if you have to install it on-premise. If none of that makes sense, please let me know why and I can clarify further.

**Comment by CDR-API-Stream** [comment]
@weznagwama the infrastructure choices of the DH are at the discretion of the DH. This may involve a variety of systems and services. Banks already have obligations regarding their use of cloud services and architecture.

Ultimately what technology choices and infrastructure architecture the bank chooses should be determined by the business and IT teams of the bank.

Regarding the reference to "hosted by" it means a service that is controlled/managed by the bank - in other words, the bank must provide the services, such as APIs, required by the data standards - whether it's managed as a service for the bank or developed and deployed within their own DCs is not specified.

The locations of these services may be different as catered for under the different Base URIs that the bank registers with the CDR Register and publishes via their OpenID Discovery endpoint.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
