### ISSUE TITLE
Access Token clarifications

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#212]
Hi, we have two questions related to Access Token:

The access token is bound to the client certificate (irrespective of whether its issued for CDR maintenance or customer in context). On day one, a DH provides an access token to an ADR. The ADR consumes APIs with the access token. What is the expectation in below scenarios:
 
i) On day two, when the client certificate brought by the ADR for MTLS is expired. So, DH rejects the API request in the first place because MTLS will fail due to invalid certificate. The question is what is the next step? Will ADR call the same API with the new / upgraded certificate for MTLS ?
 
ii) On day two, the ADR calls an API with the access token by bringing a new certificate for MTLS. But the hash of the cert. inside the access token contains expired cert. So, DH will reject the API request saying the access token has old certificate, so, ADR will make a token request again to DH to get new access token and/refresh token. This looks to be a time consuming process as multiple requests are involved before a DH can provide the API response needed for the original call. Has this been considered in terms of the impact on customer experience on the ADR side?

Thank you

**Comment by bmangalaganesh** [comment]
@jakubvozarik 
(1) Access Tokens are valid for a very short duration from 2-10 mins. So the scenario that you describe though it can occur is restricted to a very small window (not a day 1 , day 2 scenario).  Once the ADR presents their new certificate to get an access token from a refresh token, they are good to go again.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
