### ISSUE TITLE
Clarification on client registration endpoint

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#214]
Below link for client registration endpoint states:

https://consumerdatastandardsaustralia.github.io/infosec/#13-9-client-registration-endpoint

"Data Holders MUST ensure that the CN (Common Name) in the Client certificate subject field matches the software_id claim present in the software statement."
 
We cannot see this statement in the security profile present in our consumer standards 1.3.0
Is it something missing in 1.3.0 or this requirement of DH removed from 1.3.0 security profile?

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik as discussed on the [Data Holder Working Group call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Meeting-Notes-2020_05_07) this question has been directed to the [CDR Register](https://github.com/cdr-register/register/issues/104).

The endpoint referenced in the original issue is an old version of the standards when the approach to client registration was still being consulted on and before Dynamic Client Registration was introduced.

**Comment by jakubvozarik** [comment]
Thank you @CDR-API-Stream 

I've posted this to CDR Register GitHub for further clarification.
