### ISSUE TITLE
Revocation endpoint is no longer specified for the Data Recipient - as per V1.3.0

### ISSUE THREAD

**Issue by CDR-Register-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#215]
# Description
The Data Recipient is required to expose the revocation endpoint. As per V1.3.0 of the CDS, this requirement has been removed. I believe this is documentation defect

# Area Affected
https://consumerdatastandardsaustralia.github.io/standards/#end-points
Data Recipient is no longer specified in the Revocation Endpoint table

> 
> Description | Value
> -- | --
> Hosted By | Data Holder
> Transport Security | MTLS for Data Holders
> Client Authentication Required | Yes
> Bearer Token Required | No

# Change Proposed
Specify the Data Recipient requirement again

**Comment by da-banking** [comment]
The section "**Race conditions and handling consent revocation with Data Recipients**" will also need modification since it assumes the revocation endpoint is optional for a Data Recipient.

> In this instance, a Data Holder must attempt to call the Data Recipient’s revocation endpoint to notify the Data Recipient that a sharing arrangement has ended. **If the Data Recipient has chosen to no longer support a revocation endpoint, the absence of support will be inferred through the absence of the revocation_endpoint in the Data Recipients software statement assertion (SSA).**

**Comment by andrewclatham** [comment]
Is this removal for the Data Recipient end point in response to a move to cdr_arrangement_id? The refresh_token/revocation API I believe is a legacy approach and the aim is to move away from this model with the reference to the "race condition" as we transition away. I'd expect the revocation end-point to be removed from the Data Holder in the future.

Happy to be corrected.

**Comment by markverstege** [comment]
This change has been made to the standards documentation in v1.3.1 release.

**Comment by CDR-API-Stream** [comment]
This change has been made to the standards documentation in v1.3.1 release.

**Comment by CDR-API-Stream** [comment]
Hi @andrewclatham, in part yes. The intention is to retire the ADR's revocation API in favour of the CDR Arrangement API. The CDR Arrangement API facilitates consent withdrawal as opposed to the OAuth token revocation endpoint which facilitates token management concerns. 

The Data Holder will continue to support a token revocation endpoint because they act as an IdP and manage token issuance for ADRs.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
