### ISSUE TITLE
Validation for jti (JWT ID) parameter required in JWT token for Client Authentication

### ISSUE THREAD

**Issue by AnuradhaHarit** [ConsumerDataStandardsAustralia/standards-maintenance#216]
# Request For Clarification
We need some inputs on how we should validate the jti (JWT ID) which is a required parameter in JWT token for client authentication. 
The spec says that:
https://consumerdatastandardsaustralia.github.io/standards/#client-authentication
**jti - REQUIRED. JWT ID**. A unique identifier for the token, which can be used to prevent reuse of the token. **These tokens MUST only be used once**.

It seems that we would need to store previous JTI somewhere internally ( eg: any database) and every time we have to check that incoming JTI is not getting matched with previous stored JTI value. But It doesn't seem feasible solution. Any help will be much appreciated.

**Comment by CDR-API-Stream** [comment]
Hi @AnuradhaHarit, how the JWT ID is established will depend on vendor software. The best reference is the normative references [[RFC7519]](https://tools.ietf.org/html/rfc7519#section-4.1.7). A GUID value or hashing algorithm would satisfy this requirement but vendor solutions may implement this differently.

> The "jti" (JWT ID) claim provides a unique identifier for the JWT.
> The identifier value MUST be assigned in a manner that ensures that
> there is a negligible probability that the same value will be
> accidentally assigned to a different data object; if the application
> uses multiple issuers, collisions MUST be prevented among values
> produced by different issuers as well.  The "jti" claim can be used
> to prevent the JWT from being replayed.  The "jti" value is a case-
> sensitive string.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
