### ISSUE TITLE
Which APIs are in scope for closed accounts?

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#218]
# Request For Clarification
Closed accounts may not have any scheduled payments associated with them. Direct debits for closed accounts appear to be excluded from the definition of required consumer data in the rules.

Are we still required to provide endpoints with empty responses for these cases or should data recipients use the `openStatus` field from [Get Accounts API responses](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccount) in order to be aware that responses will not be available?

We would appreciate a complete list of which APIs are in scope for closed accounts, and clarification on any special behaviour for each in scope API.

**Comment by CDR-API-Stream** [comment]
Hi @WestpacOpenBanking all APIs are in scope for closed accounts. However scheduled payments and direct debits APIs should return a 200 OK with an empty response. 

It would still be valid to allow ADRs to get the details on an account and any past transactions on the account even if it is closed.

You're correct that the ADRs would use the ``BankingAccount::openStatus`` to deduce if the account is closed or not.

**Comment by WestpacOpenBanking** [comment]
Thank you @CDR-API-Stream. Are you able to comment further on the expected behaviour for the balance APIs? Should a zero balance be returned for closed accounts?

**Comment by CDR-API-Stream** [comment]
Hi @WestpacOpenBanking the assumption would be a zero account balance.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.

**Comment by CDR-API-Stream** [comment]
CDR Support Portal article: https://cdr-support.zendesk.com/hc/en-us/articles/900002843943
