### ISSUE TITLE
International payees can have a BSB and account number.

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#22]
# Description
International payees can have BSB and account number, be known to be international and may or may not have other information as required by the [BankInternationalPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankinginternationalpayee) schema. In this case the BSB and account number effectively act as an alias and a third party acts as a proxy to transfer funds to the payee.

# Area Affected
The following names and definitions are affected:

- [BankInternationalPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankinginternationalpayee) and [BankDomesticPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingdomesticpayee)
- toUType in [BankingScheduledPaymentTo](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingscheduledpaymentto)
- type in [BankingPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayee)
- payeeUType in [BankingPayeeDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayeedetail)

These objects are used in:

- [Get Payees](https://consumerdatastandardsaustralia.github.io/standards/#get-payees)
- [Get Payee Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-payee-detail)
- [Get Scheduled Payments for Account](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-account)
- [Get Scheduled Payments Bulk](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-bulk)
- [Get Scheduled Payments For Specific Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-specific-accounts)

# Change Proposed
An optional domesticAccount field is added to [BankingInternationalPayee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankinginternationalpayee) with type [BankingDomesticPayeeAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingdomesticpayee). This approach avoids breaking changes.

**Comment by CDR-API-Stream** [comment]
Some clarity is requested for this change.

BSB and Account number is a naming standard for Australian accounts which would make the payee a domestic payee for the purposes of the CDR.  Is it necessary to share the fact that the BSB/Account is acting as an international proxy for the purposes of sharing under the regime?

An alternative is to represent these payees as domestic payees.

**Comment by CDR-API-Stream** [comment]
At this point the recommendation of the DSB will be that Payees of this nature should be represented as Domestic Payees as the target account is domestic in nature.  This would appear to be more aligned with the intent of the payees entity which is to represent the address book of the consumer sharing the data to support use cases such as account switching rather than the underlying detail of the payee itself.

This approach would also result in no change being required to the standards beyond a clarification of the use of the structures.
