### ISSUE TITLE
Request for clarification on CDR Registry to DH – Get Metrics API

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#220]
# Request For Clarification

Commonwealth Bank would like clarification on the following:

1. Will the Get Metrics call be made under mTLS or TLS only?
2. In the bearer token JWT [described here](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication), what should the audience claim be set to? Should it be the AdminBaseUri as per the non-normative example?
3. Please clarify the validation requirements for the iat claim (if any).
4. Please confirm the signing algorithms that should be supported for admin api authentication.

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss,

1. MTLS is expected. All backchannel calls are expected to be MTLS.
2. You're correct it should be the ``AdminBaseUri``.
3. ``iat`` should be validated that it is a valid NumericDate [[RFC7519]](https://tools.ietf.org/html/rfc7519#section-2) and not occurring in the future. 
4. Data Holders must align to the [FAPI standards](https://openid.net/specs/openid-financial-api-part-2-ID2.html#jws-algorithm-considerations) which require support of PS256 and ES256 noting that the use of ES256 by the CDR Register is less likely (see [#105](https://github.com/cdr-register/register/issues/105), [#35](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/35), [#66](https://github.com/ConsumerDataStandardsAustralia/infosec/issues/66)).

@CDR-Register-Stream may want to further clarify.

**Comment by CDR-Register-Stream** [comment]
Thanks @CDR-API-Stream and @commbankoss 

The register will use **PS256** as the signing algorithm and expect this to be supported by the Data Holders in the regime aligned to the **FAPI** standards. This position may evolve over time but **PS256** is the obvious choice given we are using this signing algorithm for access tokens and SSAs issued

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
