### ISSUE TITLE
Application Frequency for Unique Term Deposits

### ISSUE THREAD

**Issue by jwaltonBF** [ConsumerDataStandardsAustralia/standards-maintenance#225]
# Request For Clarification

As data holders we are seeking clarification around the JSON file output for specific use cases. 
We have term deposit offering for a number of products, where the criteria for the product changes dependent on the customer choice. For example, 
1.	Flexible term deposits that are known as one product – i.e.  30-90 day Term deposit account (one product) or 120-180 days term deposit account (one product). The number of days for the term deposit is determined by the customer at the time of the opening. 
2.	Regular income term deposit that has an option of crediting the interest fortnightly or monthly, throughout the duration of the term. The options of fortnightly or monthly credits is determined by the customer at the point of opening the account.
3.	And a term deposit that always matures on the 1st of September each year, so depending on when the customer opens the account, determines the application of the interest. 

Our questions relate to the Application & Calculation Frequency in the Get Product Detail schema. And for the above use cases what would be acceptable within the CDR standards. 
Our approach is the stated below:
1.	Flexible term deposits i.e. 30-90 day term deposit– in the JSON file output display in the application frequency to display as P90D and use the additionalinfo field to explain that the application frequency can differ depending on how long the term will be.  
2.	Regular income term deposit – in the JSON file output display application frequency to display as P14D and use the additionalinfo field to explain the conditions the application frequency can differ depending on what the customers chooses. 
3.	Term Deposit – in the JSON file output display application frequency as P365D and use the additionalinfo field to explain the conditions the application frequency can differ depending on when the customer 
Would this be an acceptable approach as per the standards for the above use cases.

**Comment by jwaltonBF** [comment]
Any update on this query?

**Comment by CDR-API-Stream** [comment]
Hi @jwaltonBF, 

It sounds like rate tiers would be applicable here: ``BankingProductRateTierV3``. For the variable period term deposit you would specify a rate and then have tier entries with a minimum of 30 days  minimum duration and 90 days maximum duration. This could be combined with a tier for a range of deposit size (ie. there can be multiple qualifying tiers per rate). 

It may also be useful to use the [DSB Product Comparator tool](https://github.com/ConsumerDataStandardsAustralia/banking-products-comparator) to review how the major banks have modelled their products.

**Comment by anzbankau** [comment]
@jwaltonBF ,
>1. Flexible term deposits that are known as one product – i.e. 30-90 day Term deposit account (one product) or 120-180 days term deposit account (one product). The number of days for the term deposit is determined by the customer at the time of the opening.
>2. Regular income term deposit that has an option of crediting the interest fortnightly or monthly, throughout the duration of the term. The options of fortnightly or monthly credits is determined by the customer at the point of opening the account.
>3. And a term deposit that always matures on the 1st of September each year, so depending on when the customer opens the account, determines the application of the interest.

1. (Agreeing with @CDR-API-Stream 's response) `BankingProductDepositRate' and `BankingProductLendingRate' only support discrete values and `BankingProductRateTierV3` supports value ranges (in a generic way, using `unitOfMeasure`) typical of tiers. However tiers also support a generic single range solution via a single tier object in the `tiers` array.
2. `applicationFrequency` is a property of `BankingProductDepositRate` so it is a discriminating factor for the rate object. Even if the rate was the same, there would be two `BankingProductDepositRate` objects in the `BankingProductDetailV3.depositRates` array - one with `applicationFrequency`  = 'P14D', the other with 'P1M'.
3. Agree with suggestion of using `additionalinfo` for explanation. As a real example not encountered during standards development, it would be good to raise it as a change proposal e.g. `BankingProductDepositRate.annualMaturityDay` (assuming a different rate applies to that maturity option). p.s. `applicationFrequency` would normally be 'P1Y' to cater for leap years (recognising that in this case the period is within one year).

**Comment by anzbankau** [comment]
@CDR-API-Stream ,

>  This could be combined with a tier for a range of deposit size (ie. there can be multiple qualifying tiers per rate).

Note: While the statement is true in the context of the post and your response, the bracketed statement without context would not be true. I'm sure it was not intended and it is hard to imagine anyone doing it, but it deserves qualification.

A set of tiers for a rate should not have multiple ranges **in the same dimension** e.g. a time period. This would imply a logical 'OR'. The array of tiers are logically 'AND'ed for the purposes of qualifying for the tier - to support multiple dimensions. Where the same rate applies to overlapping or contiguous ranges, the ranges can be merged into one. Non-overlapping ranges should be split into separate `BankingProductDepositRate` or `BankingProductLendingRate` objects with the same `rate` and other properties.

We can raise a change proposal to add this rule (with simpler wording) to the Description for `BankingProductRateTier' in the standards.

**Comment by perlboy** [comment]
@anzbankau Well... We've seen overlapping tiers in same dimension: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/244 :smile:

**Comment by anzbankau** [comment]
@perlboy ,

Just for others that aren't following #244 (and didn't notice your emoji) we should state here that `BankingProductRateTier` period ranges should override `BankingProductDepositRate.additionalValue`.

Others may perceive another overlap in the example in #244 of two tiers with 48 MONTH - 60 MONTH and 60 MONTH - (beyond), but that's covered by the Description for `BankingProductRateTier.maximumValue`:
___
Where this is the same as the tierValueMinimum value of the next-higher tier the referenced tier should be exclusive of this value. For example a term deposit of 2 months falls into the upper tier of the following tiers: (1 – 2 months, 2 – 3 months).
___

**Comment by jwaltonBF** [comment]
Thanks @CDR-API-Stream for the response. To provide more context and to have a better understanding on what is required, we thought it would be better to provide what the payload looks like currently and you can confirm that it meets the standards. Our understanding from ANZ response, payloads 1 and 2 would need to be changed:

1.	Flexible term deposits that are known as one product – i.e. 30-90 day Term deposit account (one product) or 120-180 days term deposit account (one product). The number of days for the term deposit is determined by the customer at the time of the opening.

    "depositRates": [
      {
        "depositRateType": "FIXED",
        "rate": "0.01250",
        "calculationFrequency": "P1D",
        "applicationFrequency": "P90D",
        "tiers": [
          {
            "name": "XXXXXXXXXXX",
            "unitOfMeasure": "DOLLAR",
            "minimumValue": 5000.00,
            "maximumValue": 9999999.99,
            "rateApplicationMethod": "WHOLE_BALANCE",
            "applicabilityConditions": null,
            "subTier": {
              "name": "XXXXXXXXXXXXXX",
              "unitOfMeasure": "DAY",
              "minimumValue": 30.0,
              "maximumValue": 90.0,
              "rateApplicationMethod": "WHOLE_BALANCE",
              "applicabilityConditions": null
            }
          }
        ],
        "additionalValue": "",
        "additionalInfo": "Interest will be applied differently dependent on what term is selected by the customer. For example, the customers chooses a term of 45 days, interest would be applied on the 45th day",
        "additionalInfoUri": ""


2.	Regular income term deposit that has an option of crediting the interest fortnightly or monthly, throughout the duration of the term. The options of fortnightly or monthly credits is determined by the customer at the point of opening the account.

   "depositRates": [
      {
        "depositRateType": "FIXED",
        "rate": "0.01250",
        "calculationFrequency": "P1D",
        "applicationFrequency": "P14D",
        "tiers": [
          {
            "name": "XXXXXXXXXXXXX",
            "unitOfMeasure": "DOLLAR",
            "minimumValue": 5000.00,
            "maximumValue": 9999999.99,
            "rateApplicationMethod": "WHOLE_BALANCE",
            "applicabilityConditions": null,
            "subTier": {
              "name": "1 YR REGULAR INCOME TD_Tier",
              "unitOfMeasure": "DAY",
              "minimumValue": 365.0,
              "maximumValue": 365.0,
              "rateApplicationMethod": "WHOLE_BALANCE",
              "applicabilityConditions": null
            }
          }
        ],
        "additionalValue": "P1M",
        "additionalInfo": "Interest will be applied dependent on what interest frequency option is selected by the customer at the time the account is opened",
        "additionalInfoUri": ""
      }

3.	And a term deposit that always matures on the 1st of September each year, so depending on when the customer opens the account, determines the application of the interest.
   "depositRates": [
      {
        "depositRateType": "FIXED",
        "rate": "0.01250",
        "calculationFrequency": "P1D",
        "applicationFrequency": "P365D",
        "tiers": [
          {
            "name": "PRESCH LS SL 1 YEAR TD_Tier",
            "unitOfMeasure": "DOLLAR",
            "minimumValue": 500.00,
            "maximumValue": 999999.00,
            "rateApplicationMethod": "WHOLE_BALANCE",
            "applicabilityConditions": null,
            "subTier": {
              "name": "PRESCH LS SL 1 YEAR TD_Tier",
              "unitOfMeasure": "DAY",
              "minimumValue": 365.0,
              "maximumValue": 365.0,
              "rateApplicationMethod": "WHOLE_BALANCE",
              "applicabilityConditions": null
            }
          }
        ],
        "additionalValue": "",
        "additionalInfo": "This product always matures on the 1st of September each year, so depending on the time the account was opened determines when the interest would be applied",
        "additionalInfoUri": ""
      }

What changes would be required in the above examples? If possible could you provide the payload structures for the above examples?

**Comment by jwaltonBF** [comment]
Any update on the above? Some clarity would be greatly appreciated.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
