### ISSUE TITLE
Clarification : DH - Validation of registered scopes for an ADR Vs requested Scopes

### ISSUE THREAD

**Issue by sona-dhillon** [ConsumerDataStandardsAustralia/standards-maintenance#226]
# Request For Clarification

We are looking to check if there are any requirements or guidelines around the handling of requests that contain authorisation scopes that are not included in an ADR's SSA, but are subsequently requested as part of a consent flow

While this should not happen, we want to safeguard against an ADR registering something with ACCC then asking for out of scope information

An example scenario is that an ADR registers their software product with the CDR Register and with the DataHolder. The SSA includes authorisation scopes for bank:accounts.basic:read and bank:payees:read only. 
However they then send a request through that contains bank:accounts:detail:read. As this is not in their SSA then they are not entitled to include it in their consent flow.

In this scenario, should the Data Holder reject the request OR instead, prompt the user for consent using previously registered scopes that match the request, ignoring the scopes that the ADR has not been registered for (saved as part of the SSA during the client registration process)?

Thank you

**Comment by CDR-API-Stream** [comment]
Hi @sona-dhillon as discussed in the Data Holder Working Group call, the response is summarised here.

Where an ADR has registered their software product with scopes ``{A, C}`` but as part of the authorisation flow they try to ask for a scope outside of what they have registered their use case for (say scope ``{B}``) then the Data Holder must reject the call. Even if they sent an authorisation request as scopes ``{A, B}`` where one or more of the scopes is registered for collection and use. What is important is whether any of the scopes **are not** registered.

This is a situation where the ADR has had their software product accredited for collection and use of certain data clusters but then asks the Data Holder to disclose entirely different data.

You are right this shouldn't happen, but it would be an expected verification check by the Data Holder.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
