### ISSUE TITLE
Remnant vectors of trust references in security profile

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#23]
# Description
Some sentences still remain in relation to vectors of trust in parts of the Infosec profile, including links to a Vectors of Trust section which no longer exists within the standard. Standard still references expired draft on Vectors of Trust in normative references.

# Area Affected

- [Overview section](https://consumerdatastandardsaustralia.github.io/standards/#overview)
- [ID Token](https://consumerdatastandardsaustralia.github.io/standards/#tokens) section and example
- [Claims](https://consumerdatastandardsaustralia.github.io/standards/#claims) section
- [OpenID Provider Configuration End Point](https://consumerdatastandardsaustralia.github.io/standards/#end-points)
- [Normative references section](https://consumerdatastandardsaustralia.github.io/standards/#normative-references)

# Change Proposed
Remove remnant references to vectors of trust in the security profile.

**Comment by perlboy** [comment]
Are Vectors of Trust intended to be removed entirely?

**Comment by CDR-API-Stream** [comment]
The DSB are not intending to remove VOT from the standards entirely as this is both an area for future expansion of the standards but also an area that holders may wish to innovate in to support write APIs using the extension mechanisms in the standard.

It is noted, however, that some of the VOT references and links are currently incorrect so these will be fixed and references to VOT will be reviewed to ensure that usage is voluntary where appropriate.

**Comment by perlboy** [comment]
Based on none of the Holders launching with VoT support by February, the inclusion of VoT is work effort required by Recipients implementing the entire Standard which will not be used. As discussed on planning call I would recommend removing VoT from the Standard then adding "VoT Support" to the backlog for future addition back into the profile at a later stage once there is demand and available testing for it.

**Comment by da-banking** [comment]
DA would like to echo the comments of @perlboy. 

Including something without a clear demand, because it may be of interest later risks introducing needless complexity. It would be better to definitively remove it at present when there is no demand for it, and add it in a later version - perhaps when read/write is in scope - once clear support for it and the benefits have been articulated and endorsed.

**Comment by CDR-API-Stream** [comment]
In response to the above feedback, in relation to reducing ADR build requirements, the recommendation will be for VOT references to be removed unless specifically required
