### ISSUE TITLE
Where should API complaints be lodged?

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#231]
# Request For Clarification
Existing Holders, the ones mandated to deliver PRD last year, are publishing non compliant Product Reference Data responses. Where does the Government expect complaints to be lodged for this?

Contacting the Holder's listed email address (**if** it's listed) provides a number of responses, for example:
_"If you have technical questions about our Open Banking APIs we'll reply to your email within 3 business days. If your question is about something else, your email will not be actioned or responded to. You may be able to find what you're looking for on our website. [...] If you have a general banking question or need to make a complaint, go to: https://holder.com.au/generic/contact.html"_

Attempts to call the "Complaints Team" listed at the contact details resulted in a circular loop to email the listed email address (after I linked them to it).

Does the Government intend to keep a register of known non-conformity?

**Comment by CDR-API-Stream** [comment]
Thanks @perlboy, this question is related to rules enforcement and it has been passed onto the ACCC for review and comment. Their response will be posted in due course.

**Comment by CDR-API-Stream** [comment]
Hi @perlboy, please find a response from the ACCC CDR Rules team:

> The ACCC and OAIC have published their joint [Compliance and Enforcement policy for the Consumer Data Right](https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/cdr-compliance-and-enforcement-policy). The purpose of the policy is to help consumers and CDR participants understand the approach that the ACCC and the OAIC will adopt to encourage compliance with CDR rules, legislation (including Privacy Safeguards) and Consumer Data Standards. The policy also sets out how the ACCC and OAIC will respond to breaches of the CDR regulatory framework. The policy can be found on the ACCC website.
>  
> We use a risk-based approach to monitoring and assessing compliance matters and taking enforcement action. We cannot pursue all matters that come to our attention. Our role is to focus on those circumstances that will, or have the potential to, cause significant harm to the CDR regime or result in widespread consumer detriment.
>  
> Interested parties should make any complaints about data accuracy or how product reference data is being shared directly to the data holder. Interested parties can also report their concerns to the ACCC and we will consider in accordance with our Compliance and Enforcement policy. Reports can be submitted to us directly at accc-cdr@accc.gov.au.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.

**Comment by cdradr** [comment]
@perlboy, ACCC said “No” to your question.

**Comment by perlboy** [comment]
> @perlboy, ACCC said “No” to your question.

Indeed and the power imbalance between a small fintech and a multi-billion dollar organisation continues to exist. I've created https://github.com/cdr-register/register/issues/138 and we will be going down the name and shame path for this.
