### ISSUE TITLE
Responsibility for APIs for white-labelled products

### ISSUE THREAD

**Issue by dgiddy** [ConsumerDataStandardsAustralia/standards-maintenance#232]
# Request For Clarification
In the case of an ADI (A) that provides products to its customers through a white-label arrangement with another ADI (B), for example a credit card, which party is responsible for providing the API for that data, ADI (A) or ADI (B)? If (as I interpret the rules) it is ADI (A), is there an expectation that ADI (B) would provide a conforming CDR API to allow ADI (A) to retrieve the relevant data? In broad terms how is this scenario meant to operate?

**Comment by CDR-API-Stream** [comment]
Hi @dgiddy, the expectation is that ADI (A) would provide the products via CDR APIs to the ADR. The scope and requirements for white labelled products are currently under consultation by the ACCC. How ADI (B) supplies the data to ADI (A) is not defined beyond existing mechanisms the two entities have in place today.

It would be worth following up with the ACCC to clarify these obligations. An overview of the white label consultation is available [here](https://consumerdatastandards.gov.au/wp-content/uploads/2020/06/CDR-rules-White-labels_-presentation-to-DSB-7-May-202011019280.1.pdf].

**Comment by dgiddy** [comment]
Thanks @CDR-API-Stream, that help. I will follow up with ACCC.
