### ISSUE TITLE
Overlapping Rates

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#236]
# Request For Clarification

Many organisations have introductory rates which revert to a standard savings rate.

What is the correct way of describing these within the rates arrays? 

One example we have seen is:
```[
  {
    "depositRateType": "INTRODUCTORY",
    "rate": "0.01",
    "calculationFrequency": "P1D",
    "applicationFrequency": "P1M",
    "additionalValue": "P5M",
    "additionalInfo": "Fixed bonus margin for the first 5 months on your first NetBank Saver. The variable introductory interest rate will not apply to NetBank Saver accounts which are jointly owned where one of the account holders has previously held a NetBank Saver account."
  },
  {
    "depositRateType": "VARIABLE",
    "rate": "0.0005",
    "calculationFrequency": "P1D",
    "applicationFrequency": "P1M"
  }
]
```

Is this meant to be interpreted as an introductory rate of 1% + 0.05% (ie 1.005% for first 5 months then 0.05%) or is it expected to be interpreted as 1% then 0.05% (ie. 1% for first 5 months then 0.05%)?

Based on analysis of PDS information we have seen both in use across Holders (and in fact, within a single Holder).

What is the correct definition?

**Comment by anzbankau** [comment]
ANZ does not believe the "INTRODUCTORY" rate should be represented in the same way as a "BONUS" rate i.e. to be added to the 'base' rate. An 'introductory rate' should be an absolute rate while a 'bonus rate' should be additive.

We believe the treatment of the ANZ Online Saver "INTRODUCTORY" rate as additive has been unduly influenced by the web page that states 'Open your first ANZ Online Saver and get bonus interest for 3 months', followed by the equation:
0.05% p.a. (Current standard variable rate) + 0.75% p.a. (Introductory interest for 3 months for eligible customers) = 0.80% p.a. (Total interest rate for 3 months if current variable rate remains unchanged).

The use of the term 'get bonus interest' in the lead-in sentence emphasises the common usage of 'bonus'. In contrast, we believe the common usage of 'introductory rate' is definitive/absolute.

We will allow some time for CDS guidance or participant consensus before making the proposed correction.

**Comment by perlboy** [comment]
Hi @anzbankau,

Just clarifying your response, are you suggesting the INTRODUCTORY rate is an XOR on the VARIABLE/FIXED that can only be specified once (on account opening) while the BONUS rate is added to the VARIABLE/FIXED rates? Is there a potential that VARIABLES/FIXED rates could also legitimately overlap?

**Comment by anzbankau** [comment]
@perlboy,

I was using BONUS to contrast the additive/absolute distinction between it and INTRODUCTORY - and to suggest the latter option you had in your post i.e. 1% then 0.05% (so an additional 0.95% for the first 5 months if you want to express it in 'bonus' terms, but I contend that that's confusing for an introductory rate).

The interaction of INTRODUCTORY and BONUS is a somewhat different question as multiple combinations are possible i.e. the BONUS rate applies to the 'base' rate after the introductory period (aligning with INTRODUCTORY being an absolute rate) or to both periods (introductory and thereafter). If we don't agree that INTRODUCTORY is an absolute rate, providers would have to use additionalInfo to convey the intended meaning or propose an additional property (or multiple properties if it was to support more than this specific combination of enums).

In regards to VARIABLE/FIXED, if by 'overlap' you mean concurrent fixed and variable rates, you would no doubt be aware of home loans with variable and fixed components split by loan amount (acting somewhat like separate loans to 'hedge your bets' on rate movements), so I'm not sure if I have misinterpreted your ancillary question.

**Comment by perlboy** [comment]
> @perlboy,
> I was using BONUS to contrast the additive/absolute distinction between it and INTRODUCTORY - and to suggest the latter option you had in your post i.e. 1% then 0.05% (so an additional 0.95% for the first 5 months if you want to express it in 'bonus' terms, but I contend that that's confusing for an introductory rate).
> The interaction of INTRODUCTORY and BONUS is a somewhat different question as multiple combinations are possible i.e. the BONUS rate applies to the 'base' rate after the introductory period (aligning with INTRODUCTORY being an absolute rate) or to both periods (introductory and thereafter). If we don't agree that INTRODUCTORY is an absolute rate, providers would have to use additionalInfo to convey the intended meaning or propose an additional property (or multiple properties if it was to support more than this specific combination of enums).

And I guess that's where my question started from. My initial interpretation was that you would use INTRODUCTORY as "start of account" then after that (not during) BONUS was "sometime after the start of account" and FIXED or VARIABLE as the base rate. From your response it seems there is reasonable grounds to suggest my initial interpretation was inaccurate.

We don't really have a preference or thought on this other than noting that existing Holders are applying different approaches and this is only going to get worse over time. The text describing these enumerations isn't explicit and detecting inaccuracies like this automatically is essentially impossible (short of creating a PDS language processor).

> In regards to VARIABLE/FIXED, if by 'overlap' you mean concurrent fixed and variable rates, you would no doubt be aware of home loans with variable and fixed components split by loan amount (acting somewhat like separate loans to 'hedge your bets' on rate movements), so I'm not sure if I have misinterpreted your ancillary question.

Ah, of course I had forgotten about those so I guess the answer to that question is "Yes". 😄

**Comment by anzbankau** [comment]
@perlboy ,

> And I guess that's where my question started from. My initial interpretation was that you would use INTRODUCTORY as "start of account" then after that (not during) BONUS was "sometime after the start of account" and FIXED or VARIABLE as the base rate. From your response it seems there is reasonable grounds to suggest my initial interpretation was inaccurate.

If a product had INTRODUCTORY, BONUS and either VARIABLE or FIXED rates without additionalInfo explanations, I would have thought the common interpretation would be an initial period with the INTRODUCTORY rate, followed by a VARIABLE + BONUS rate or FIXED + BONUS rate. So I'm agreeing with your initial interpretation.

**Comment by perlboy** [comment]
> @perlboy ,
> 
> If a product had INTRODUCTORY, BONUS and either VARIABLE or FIXED rates without additionalInfo explanations, I would have thought the common interpretation would be an initial period with the INTRODUCTORY rate, followed by a VARIABLE + BONUS rate or FIXED + BONUS rate. So I'm agreeing with your initial interpretation.

Yes ok. I haven't checked BONUS situations but INTRODUCTORY seems to be used in both additive and absolute contexts. I guess we will wait for clarity from the DSB.

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 
As the confusion around rate presentation was raised on the call yesterday (relating to #321 and #283), could some clarification of the discussion in this issue (#236) be provided and the [descriptions in the standards](https://consumerdatastandardsaustralia.github.io/standards/#tocSproductdepositratetypedoc) reviewed?

**Comment by perlboy** [comment]
See #354.
