### ISSUE TITLE
BankingScheduledPaymentTo clarification

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#237]
Description of payeeId reads:
Present if toUType is set to payeeId. Indicates that the payment is to registered payee that can be accessed using the payee end point. If the Bank Payees scope has not been consented to then a payeeId should not be provided and the full payee details should be provided instead

Does this mean to say that if Bank Payees scope is consented to, a DH will share payee details as payeeId's instead domestic/biller/international? Or are we expected to share both in this instance?

**Comment by bmangalaganesh** [comment]
@jakubvozarik 

This is indeed an Interesting one and here is my interpretation.

Believe the question is related to this API - _Get Scheduled Payments for Account_  which as a scope of **`bank:regular_payments:read`**
 
However the object that is returned appears to be dependent on another scope - **`bank:payees:read`**

if the UType is PayeeID, 

- if the user has not consented to  **`bank:payees:read`** then the payeeID should not returned. Instead the full payee details should be returned which is one of BankingDomesticPayee/BankingINternationalPayee/BankingBillerPayee.

- If the user had consented to **`bank:payees:read`** then the payeeID should be returned.

Would love to see the comments and interpretation from others.

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik thanks for the question. If the consumer's scope **does not** include the bank:payees:read scope the ``payeeId` will be null and one of the (domestic, biller, international) payee must be provided be provided. 

If the consumer's scope **does** include the bank:payees:read scope then ``payeeId` is populated with the ID representing a payee resource (adhering to the rules of ID permanence).

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
