### ISSUE TITLE
Testing Clarification:Order of the response object fields in the payload

### ISSUE THREAD

**Issue by Srimitra** [ConsumerDataStandardsAustralia/standards-maintenance#238]
# Request For Clarification
Brief description of the issue that is leading to the clarification
when the testing is being performed the order is not being maintained. please see the attached document. 

[ordering of objecs within the response.docx](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/4785336/ordering.of.objecs.within.the.response.docx)

**Comment by bmangalaganesh** [comment]
@Srimitra  JSON objects are unordered based on the information in the [RFC](https://tools.ietf.org/html/rfc4627).

> An object is an **_unordered_** collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

My understanding of the CDS specification is that it does not dictate the JSON objects to be in a specific order.

**Comment by perlboy** [comment]
Agree with @bmangalaganesh, if a parser is expecting object data to be ordered it is broken.

Also, from that tiny slivver a screenshot I'd highlight that `x-IBM-Client...`, `account_id`, `x-user-type`, `x-min-v` are either invalid for a CDR request (`x-IBM-Client...` is a vendor header), incorrectly formatted (`account_ids` is POSTed and is not applicable to customer) or impossible (`x-min-v` > `x-v`) to deliver.

Also, P.S, your content includes content to the bank in question. I assume they are ok with this....

**Comment by CDR-API-Stream** [comment]
Hi @Srimitra, the order of attributes in a JSON object is not required for the response to be valid JSON.

Please refer to the most recent applicable [JSON RFC](https://tools.ietf.org/html/rfc8259).

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
