### ISSUE TITLE
Issues with non-normative authorization endpoint request examples

### ISSUE THREAD

**Issue by jogu** [ConsumerDataStandardsAustralia/standards-maintenance#242]
# Description

The non-normative examples contain potentially misleading things.

# Area Affected

https://consumerdatastandardsaustralia.github.io/standards/#end-points

# Change Proposed

The examples should be reviewed against the underlying standards or compared against examples from the FAPI conformance suite.

For example:

1) 'nonce' generally shouldn't be in the unsigned part of the authorization endpoint request. (It must be present inside the signed request and there is no advantage in repeating it outside the signed request object, and repeating it has the disadvantage of bloating the query string size.)

2) The decoded request object is missing 'exp' (required by FAPI-RW)

There may be other issues too, I've not done a full review. Although they're non-normative, people do definitely end up using them as a basis for their work, so it's worth getting them right.

**Comment by jogu** [comment]
The configuration endpoint example, https://consumerdatastandardsaustralia.github.io/standards/#end-points

includes:

`  "id_token_encryption_alg_values_supported": [ "RSA1_5", "RSA-OAEP",  "RSA-OAEP-256", "dir", "ECDH-ES", "ECDH-ES+A128KW", "ECDH-ES+A192KW", "ECDH-ES+A256KW", "A128KW", "A192KW", "A256KW", "A128GCMKW", "A192GCMKW", "A256GCMKW" ],
`
but RSA1_5 is not allowed by FAPI:

https://bitbucket.org/openid/fapi/annotate/master/Financial_API_WD_002.md?at=master&fileviewer=file-view-default#Financial_API_WD_002.md-389

**Comment by perlboy** [comment]
@jogu You've mentioned this before https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/12#issuecomment-547144867

**Comment by CDR-API-Stream** [comment]
Thanks @jogu, these will be reviewed.

**Comment by spikejump** [comment]
Just for reference, some DH is currently requiring 'nonce' in the request URL.  If it is not supplied then an error is thrown back.

Would be helpful if the spec can clarify whether 'nonce' is required in the request URL.

**Comment by jogu** [comment]
> Would be helpful if the spec can clarify whether 'nonce' is required in the request URL.

I think it's dangerous for the CDR spec to try and "clarify" upstream specs, as there is a large danger of the clarification being incorrect and introducing new interoperability problems and resulting in vendors who are compliant with the underlying specs not being compliant with CDR and vice versa. If it's really necessary it should be very clearly labelled as non-normative clarifications.

It's clear to me that nonce is not required in url query parameters (i.e. it should only be inside the signed request object), but it's understandable that the non-normative example including nonce there might have led people astray. (I do have the advantage of being the person that wrote the relevant clause in the FAPI spec...)

This kind of thing is the reason it's important for DH to run the available FAPI conformance tests, and to run them early, before they de-facto force misunderstandings onto DRs, resulting in an ecosystem where OpenID Connect compliant software fails to work and ultimately creating an unnecessary barrier to entry for new data recipients.

**Comment by CDR-API-Stream** [comment]
Hi @jogu thanks for the CR. Regarding 'nonce', it isn't accurate to say the 'nonce' shouldn't be in the unsigned part of the authorisation request. 

[OIDC](https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests) (emphasis added).
> When the ``request`` parameter is used, the OpenID Connect request parameter values contained in the JWT supersede those passed using the OAuth 2.0 request syntax. However, parameters MAY also be passed using the OAuth 2.0 request syntax even when a Request Object is used; this would typically be done to enable a cached, pre-signed (and possibly pre-encrypted) Request Object value to be used containing the fixed request parameters, while **parameters that can vary with each request, such as ``state`` and ``nonce``, are passed as OAuth 2.0 parameters.**

But the point you're making is valid that duplication of claims is redundant. Ultimately, DHs should align to the normative standards here to correctly handle the presence of claims in the request object or query string or both. The salient section of the OIDC spec:
> the OpenID Connect request parameter values contained in the JWT supersede those passed using the OAuth 2.0 request syntax.

This is similarly described in [JAR](https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-20#section-5):
> The client MAY send the parameters included in the request object
>   duplicated in the query parameters as well for the backward
>   compatibility etc.  However, the authorization server supporting this
>   specification MUST only use the parameters included in the request
>   object.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump thanks for the question.
> Just for reference, some DH is currently requiring 'nonce' in the request URL. If it is not supplied then an error is thrown back. 

``nonce`` is required for the Hybrid Flow, however it is valid to provide it in the request object. If you are providing it in the request object (hence, not in the request URL string) an error shouldn't be returned.

> Would be helpful if the spec can clarify whether 'nonce' is required in the request URL.

Rather than clarify in the CDS standards if ``nonce`` is required in the request URL, this is better referred to the normative references.

Can you confirm you are passing in the ``nonce`` claim in the request object?

**Comment by CDR-API-Stream** [comment]
> RSA1_5 is not allowed by FAPI

Thanks @jogu and @perlboy - this will be reviewed and an updated non-normative example proposed on this thread.

**Comment by perlboy** [comment]
> Hi @jogu thanks for the CR. Regarding 'nonce', it isn't accurate to say the 'nonce' shouldn't be in the unsigned part of the authorisation request.

Keyword here is "shouldn't" which using RFC definition would be:

> This word, or the adjective "RECOMMENDED", mean that there may **exist valid reasons in particular circumstances to ignore a particular item**,

On that basis @jogu appears to be accurate.

From [FAPI R/W](https://openid.net/specs/openid-financial-api-part-2-ID2.html#authorization-server), for write operations:

> shall require **that all parameters** are present inside the signed request object passed in the request or request_uri parameter;

So, passing `nonce` on the query string is "ok" but would be invalid for write operations which are planned.

**Comment by spikejump** [comment]
@CDR-API-Stream 

> Can you confirm you are passing in the `nonce` claim in the request object?

Yes it is passed in the request object.  But DH is requiring it to be in request URL.

**Comment by perlboy** [comment]
> Yes it is passed in the request object. But DH is requiring it to be in request URL.

Well that's just totally wrong and breaks spec in so many ways.

**Comment by jogu** [comment]
I agree with all the above.

To confirm there's basically three points I'm making:

1) requests that have nonce only inside the request object must be accepted by data holders

2) All requests must have nonce inside the request object

3) it's pointless for data recipients to pass nonce both inside and outside the request object, and whilst DH must generally accept requests that do so, there is no benefit to passing it in both places, and it has the downside of bloating the request size, which may cause problems in certain browser/gateways depending on the size of the nonce and other items in the request. I agree it's not quite the strength of a 'should'.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump 

> Yes it is passed in the request object. But DH is requiring it to be in request URL.

If this is the case, it is best raised in the ACCC test working group to ensure the issue can be tracked and remediated.

**Comment by CDR-API-Stream** [comment]
In respect to the original content of this thread, the proposal is to update the non-normative examples in four areas.

**1. Update OpenID Connect Metadata Discovery non-normative example**
Update the OpenID Connect Metadata non-normative example.
Change ``id_token_encryption_alg_values_supported`` to:

```
"id_token_encryption_alg_values_supported": [ "RSA-OAEP", "RSA-OAEP-256", "dir", "ECDH-ES", "ECDH-ES+A128KW", "ECDH-ES+A192KW", "ECDH-ES+A256KW", "A128KW", "A192KW", "A256KW", "A128GCMKW", "A192GCMKW", "A256GCMKW" ],
```

---

**2. Update OpenID Connect Metadata description for id_token_encryption_alg_values_supported**
Change standards description for ``id_token_encryption_alg_values_supported`` to:
```
id_token_encryption_alg_values_supported: The list of the supported JWE algorithms for securing the issued ID tokens. Must conform to [FAPI-RW] and [OIDD].
```

---

**3. Update the ACR non-normative examples to use correct scopes**
Update the "Non-Normative Example - acr as an Essential Claim" example.

Change the scopes to be:
```
"scope": "openid profile common:customer.basic:read common:customer.detail:read",
  
```

---

**4. Update the Authorisation endpoint non-normative example to align to FAPI R/W 5.2.2**
Update the Authorisation endpoint non-normative example to align to FAPI R/W 5.2.2 request object requirements and use of "exp" claim in the request object. Whilst these are more specific to write operations, the point is that it moves towards a single consistent expectations for ADR implementations.

Changes:
* Add "exp" claim to JWT
* Add "essential: true" key/value to "acr" claim request
* Move all query params into the request object per FAPI R/W
* Provide example scopes for a data sharing request

Explicitly:
```
10. shall require that all parameters are present inside the signed request object passed in the request or request_uri parameter;
13. shall require the request object to contain an exp claim; and
```

Change to:

```
GET /authorise?
   request=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEyMyJ9.ey ...
HTTP/1.1
Host: www.holder.com.au

## Decoded request JWT
{
  "alg": "PS256",
  "typ": "JWT",
  "kid": "123"
}
{
  "iss": "12345",
  "exp": 1516239322,
  "aud": "https://www.recipient.com.au",
  "response_type": "code id_token",
  "client_id": "12345",
  "redirect_uri": "https://www.recipient.com.au/coolstuff",
  "scope": "openid profile bank:accounts.basic:read, bank:accounts.detail:read",
  "state": "af0ifjsldkj",
  "nonce": "n-0S6_WzA2Mj",
  "claims": {
    "sharing_duration": 7776000,
    "userinfo": {
      "given_name": null,
      "family_name": null
    },
    "id_token": {
      "acr": {
        "essential": true,
        "values": ["urn:cds.au:cdr:3"]
      }
    }
  }
}
```

**Comment by CDR-API-Stream** [comment]
For consistency, the PAR non-normative examples will be updated to include the subsequent authorisation request.

```
## This is used by the ADR in the subsequent authorisation request as follows 
## (note that until PAR is an RFC standard, the mandatory oAuth parameters as 
## per FAPI R/W for confidential clients must be replayed in the request URL):

GET /authorise?client_id=s6BhdRkqt3&
   response_type=code%20id_token&
   scope=openid%20profile%20bank:accounts.basic:read%20bank:accounts.detail:read&
   request_uri=urn%3Adata.holder.com.au%3Abwc4JK-ESC0w8acc191e-Y1LTC2
HTTP/1.1
Host: data.holder.com.au
```

**Comment by ttranatping** [comment]
Hi just confirming if the scope parameter need to be aligned to the request object?
Unlike client_id and response_type, the OIDC specifications only state that it needs to contain the "openid" value, and does not specify that it needs to align to the value in the request object.

https://openid.net/specs/openid-connect-core-1_0.html#RequestObject

> Even if a scope parameter is present in the Request Object value, a scope parameter MUST always be passed using the OAuth 2.0 request syntax containing the openid scope value to indicate to the underlying OAuth 2.0 logic that this is an OpenID Connect request.

**Comment by ttranatping** [comment]
> The implementer's draft for FAPI R/W has been improved to make it explicitly clear which parameters must be included in the request URL. See 5.2.3 https://bitbucket.org/openid/fapi/src/master/Financial_API_WD_002.md

Ok... this seems to have answered my question (I was going on published FAPI specifications and missed this comment). I find this contradicts the OIDC specifications as it only requires scope=openid. So if we are going by the draft FAPI changes then we'll need to validate the scope claim is duplicated as a parameter. Confirming we are pushing ahead with this?

**Comment by jogu** [comment]
@ttranatping 

> So if we are going by the draft FAPI changes then we'll need to validate the scope claim is duplicated as a parameter

There's no requirement (and no benefit) for a data holder to validate the scope outside the request object. as per https://bitbucket.org/openid/fapi/src/master/Financial_API_WD_002.md the authorization server:

> shall only use the parameters included in the signed request object passed in the request or request_uri parameter;

The requirement on clients to send duplicates is there to remain technically compliant with the underlying OAuth2/OIDC specs, and some vendor products do not behave correctly if the scope parameter is missing outside the request object.

**Comment by ttranatping** [comment]
Thanks @jogu I also didn't see the benefit of the AS validating the scope is duplicated. Your response was exactly what I was hoping for!

**Comment by ttranatping** [comment]
@jogu 
On a slightly separate topic, OpenID Connect specifications does not require client_id and response_type in the Request Object. Requiring client_id and response_type in the Request Object deviates from OIDC core 1.0.
https://openid.net/specs/openid-connect-core-1_0.html#RequestObject

> So that the request is a valid OAuth 2.0 Authorization Request, values for the response_type and client_id parameters MUST be included using the OAuth 2.0 request syntax, since they are REQUIRED by OAuth 2.0. The values for these parameters MUST match those in the Request Object, **if present**.

It says:
1. client_id and response_type are required request parameters.
2. The AS only needs to validate they are matching if it is present in the Request Object. So it is optional in the Request Object.

It shouldn't be a problem seeing as the ADR's will be providing both however, the AS may not actually be using the client_id and response_types from the signed Request Object (if they are not present).

**Comment by jogu** [comment]
> On a slightly separate topic, OpenID Connect specifications does not require client_id and response_type in the Request Object. Requiring client_id and response_type in the Request Object deviates from OIDC core 1.0.

Correct. It does not require, but does allow them to be inside. The requirement for them to be inside is a deliberate deviation in FAPI to only used fields that are inside the request object, and hence resistant to tampering.

> It shouldn't be a problem seeing as the ADR's will be providing both however, the AS may not actually be using the client_id and response_types from the signed Request Object (if they are not present).

They must be present in the signed request object (as per FAPI), and the AS must only use the values in the request object.

If response_type (or more importantly, other required fields like nonce) are missing from the request object (or only present outside the request object), the DH's AS must reject the request.

**Comment by ttranatping** [comment]
> If response_type (or more importantly, other required fields like nonce) are missing from the request object (or only present outside the request object), the DH's AS must reject the request.

Thanks @jogu. I understand there are important claims like nonce that must be in the signed request object to be tamper proof. However, client_id (which would need to be extracted without verification to validate signature) and response_type in particular were called out in OIDC as not having to be in the request object but having to be available as request parameters.

If FAPI requires it in the request object then the AS can verify its existence as OIDC specifies the AS should already be validating the client_id and response_type claims matches the parameters if they exist in the request object. IMO it just seems a bit redundant but it isn't difficult to comply.

**Comment by jogu** [comment]
> Thanks @jogu. I understand there are important claims like nonce that must be in the signed request object to be tamper proof. However, client_id (which would need to be extracted without verification to validate signature) and response_type in particular were called out in OIDC as not having to be in the request object but having to be available as request parameters.

Importantly, even in OIDC, if they're both inside and outside the request object, the AS must only use the values inside.

> If FAPI requires it in the request object then the AS can verify its existence as OIDC specifies the AS should already be validating the client_id and response_type claims matches the parameters if they exist in the request object. IMO it just seems a bit redundant but it isn't difficult to comply.

FAPI just says you should only process values in the signed request - same as OAuth JAR. It time (possibly where the transition to PAR happens?) there'll be no need to pass the values (other than client_id, which is required for various reasons) outside the request object.

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.4.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/137). 

This issue will be closed accordingly.
