### ISSUE TITLE
Expected behaviour for scopes presented by an ADR to a DH

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#243]
# Request For Clarification
A question received by email and was discussed during the ACCC CDR Register call on 17/06/2020. The answer has been posted here for visibility.

> We are seeking clarification on the follow:
> * Would an ADR’s SSA issued for July go-live contain future dated scopes that are not currently supported (e.g.: Scheduled payments and direct debits)?
> * If it would, what behavior is expected when in authorization flow an ADR requests a scope that is currently not supported? 
>    * Should the ADH accept the request; or
>    * Should the ADH reject the request; or
>    * Should the ADH allow the request if there are other valid scopes, but ignore scopes currently not supported?
> * If it won’t, then do we expect ADRs to submit a new SSA when additional scopes are introduces?

# Answer

1. Whilst an ADR may include scopes not currently designated for a DH, the DH would return a response with the "scope" claim populated with the scopes supported by the DH. This ensures that an ADR knows the subset of scopes that a given DH can accept

2. As described, the DH would allow the request but accept the client registration with the subset of scopes the DH supports per [RFC7591](https://tools.ietf.org/html/rfc7591). This would be acknowledged in the Dynamic Client Registration ``/register`` response payload.

3. Not applicable. However, an ADR would need to periodically check the scopes supported by the DH through the DH's ``/.well-known/openid-configuration`` endpoint. When additional scopes are supported by a DH it may be in the interest of the ADR to expand their use case to handle those extra capabilities. This is important for different scopes tied to different phasings of obligation dates as well as DHs being able to support competitive extensions represented under additional scopes.

**Additional scopes presented during the consent flow**
These questions also give rise to what is the expected behaviour during the authorisation flow?
If an ADR requests authorisation with a set of scopes beyond what the DH supports (say the DH supports ``bank:accounts.basic:read`` but the ADR requests consent for both ``bank:accounts.basic:read`` and ``bank:accounts.detail:read``) then as per [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) a Data Holder should ignore the extraneous scopes. This ensures there is alignment with the RFC but it also doesn't penalise ADRs as they are developing software products that span a number of DHs with different obligations.

_Consumer Experience_
That being said, there is an expectation that an ADR will tailor their use case to the data cluster support offered by a given Data Holder ahead of time. An ADR that does not negotiate their use case may create unnecessary consumer friction where successful consent establishment must be immediately revoked because the authorisation grant does not include the required scopes to fulfil the ADR use case. This negotiation is possible prior to the consent flow by calling the Data Holder's OIDC ``/.well-known/openid-configuration`` endpoint.

_No scopes supported_
If the ADR attempts to establish consent but the DH does not support any of the scopes request, the DH must reject the authorisation request.

**Comment by perlboy** [comment]
Regarding consent flow.

OpenID Connect Core states the following:

>OpenID Connect uses the following OAuth 2.0 request parameters with the Authorization Code >Flow:
>scope
>REQUIRED. OpenID Connect requests MUST contain the openid scope value. If the openid scope value is not present, the behavior is entirely unspecified. Other scope values MAY be present. Scope values **used that are not understood by an implementation SHOULD be ignored**. See Sections 5.4 and 11 for additional scope values defined by this specification.

On the above bolded basis, if an ADR requests scopes that are unavailable the compliant approach would be to ignore them. The Recipient can discover what scopes they haven't been granted during token response phase and make a decision if they are insufficient for their value proposition (and give the user a message + immediately revoke the consent) or if they can operate without them in degraded capability mode.

Either way, the alternative of rejecting at authorize initiation is probably the highest friction impact to a consumer and also precludes future states that allow for the user to "uncheck" permissions during the Data Holder consent flow.

**Comment by ryderwj** [comment]
Of a similar nature to the unsupported scopes question, can the behaviour be clarified for a situation when an ADR updates their registration, presenting a software statement with a reduced set of scopes compared to their current registration and less scopes than those contained within their existing in-force consent arrangements with the DH. 
Is this a plausible scenario?
Should this registration request be rejected?

**Comment by CDR-API-Stream** [comment]
Thanks all for the discussion - we've begun to capture this knowledge article here: https://cdr-support.zendesk.com/hc/en-us/articles/900001781826

**Comment by CDR-API-Stream** [comment]
This issue has been answered and an associated knowledge article created. Accordingly, the issue is closed.
