### ISSUE TITLE
What are the 'reasonable step' requirements to maintain Data-quality, and how will we be asked to demonstrate this?

### ISSUE THREAD

**Issue by DeanJonesBrisbane** [ConsumerDataStandardsAustralia/standards-maintenance#249]
# Request For Clarification
Section https://consumerdatastandardsaustralia.github.io/standards/#data-quality states that ;
 _Data holders are required to take reasonable steps to ensure that CDR data, having regard to the purpose for which it is held, is accurate and up to date.
A data holder is required to be able to demonstrate that reasonable steps to maintain data quality are being undertaken_

How, and when, will data holders be required to 'demonstrate reasonable steps' have been taken? 
What form will these demonstrations take?
There appears to be no guidance in the ACCC rules, as regards this, so is it a DSB requirement?

Thank you

**Comment by CDR-API-Stream** [comment]
Hi @DeanJonesBrisbane, thanks for the question. Reasonable steps should be in line with existing digital banking channels today and expectations set by the CDR rules. As with any digital banking experience the intent is to provide as clean and correct a set of banking data as is possible and to be confident that, say for example, 
* the consumer's contact details are theirs and not another customers;
* that product reference data correctly represents the fees, rates and features of the product as displayed on the ADI's website and within any PDS and satisfies any other requirements the ADI must fulfil to hold its banking license. 

The Rules do provide guidance regarding quality of the CDR Data including, but not limited to, section "Subdivision 7.2.4—Rules relating to integrity and security of CDR data". 

Regarding what constitutes demonstration of reasonable steps, this is best put to the ACCC. Given that this question asks guidance on CDR rules, reporting and enforcement, the question has been referred to them and an answer will be posted when available.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.

**Comment by nils-work** [comment]
Hi @DeanJonesBrisbane 
There is detail related to your question under [Privacy Safeguard 11](https://www.oaic.gov.au/consumer-data-right/cdr-privacy-safeguard-guidelines/chapter-11-privacy-safeguard-11-quality-of-cdr-data/#what-constitutes-reasonable-steps) at OAIC.
