### ISSUE TITLE
Payee name is not always known

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#25]
# Description
In [BankingDomesticPayeeAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingdomesticpayeeaccount), the field accountName is mandatory. There are many cases where we do not have a payee name or a name entered by a customer whilst scheduling a payment.

# Area Affected
Definition of [BankingDomesticPayeeAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingdomesticpayeeaccount) which is used in:

- [Get Payees](https://consumerdatastandardsaustralia.github.io/standards/#get-payees)
- [Get Payee Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-payee-detail)
- [Get Scheduled Payments for Account](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-account)
- [Get Scheduled Payments Bulk](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-bulk)
- [Get Scheduled Payments For Specific Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-specific-accounts)

# Change Proposed
We propose that **accountName** is changed from mandatory to optional.

**Comment by CDR-API-Stream** [comment]
The change proposed is seen as reasonable by the DSB and will be the recommended proposal unless counter feedback is provided.

It should be noted that making this field optional does not make it optionally implementable.  It only means that a response payload that does not contain the field will still be seen as valid.  There is still an obligation for the data holder to populate the field if the relevant data is held.
