### ISSUE TITLE
Use case for a Single Use Consent 

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#252]
# Request For Clarification
The scheme supports the construct of a Single use consent.

We are wondering what would be good use case(s) for this single use consent.

In the case of a Single (one-time use only) consent,  only an access token is provided. If the ADR does not make a call within that period (2-10 mins) then the consent expires. 

> If the sharing_duration value is zero or absent then once off access will be assumed and only an Access Token (without a Refresh Token) will be provided on successful authorisation.

Also the data has to be either de-identified or deleted (based on what the user states as their preference in the consent flow). 

If a DH has set their AT validity to 2 mins there might not be enough time to make multiple API calls to the Data Holder (to get some data and make some meaningful inferences from that data)

What use would this ephemeral data be for the ADRs?

Would love to hear the thoughts in this space

**Comment by nils-work** [comment]
Hi @bmangalaganesh 

Just acknowledging this is an older issue and you are likely now aware of possible use-cases for one-time consents.

In reply to your question though, and for further reference, in [version 1.7](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.7.0.html#information-security-profile) of the Standards, changes were made to the [sharing_duration](https://consumerdatastandardsaustralia.github.io/standards/#request-object) of one-time consents.

Under certain conditions they could be available for 24 hours to allow the necessary API calls to be successfully completed.

Questions such as this can now be directed to the [CDR Support Portal](https://cdr-support.zendesk.com/hc/en-us).
