### ISSUE TITLE
Get Products documentation - results ordering

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#253]
# Description
Current documentation for the [Get Products API](https://consumerdatastandardsaustralia.github.io/standards/#get-products) states -
"Note that the results returned by this end point are expected to be **ordered** according to **updated-since**"
(Noting that 'updated-since' is a filtering parameter.)

# Area Affected
Documentation

# Change Proposed
Was the intention that the product array be 'ordered according to **lastUpdated**' (the product property, perhaps in descending order), whereas the response may optionally be filtered by the 'updated-since' parameter?

**Comment by CDR-API-Stream** [comment]
Hi @nils-work thanks for this. This is a documentation error and it should be the ordered according to the ``lastUpdated`` date of the product (BankingProductV3).

This will be fixed in an upcoming version of the standards.

**Comment by CDR-API-Stream** [comment]
As part of release v1.4.0, the proposal is documentation will be updated from:

> Note that the results returned by this end point are expected to be ordered according to ``updated-since``


To:

> Note that the results returned by this end point are expected to be ordered in descending order according to ``lastUpdated``.

**Comment by nils-work** [comment]
This has been updated in the [documentation](https://consumerdatastandardsaustralia.github.io/standards/#get-products) and can be closed.
Thank you
