### ISSUE TITLE
Request For Clarification on CDR Arrangement ID

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#254]
# Request For Clarification on CDR Arrangement ID

## Question 1
Under "CDR Arrangement ID" section in the latest version of the specification, it is stated that

> The CDR Arrangement ID is represented as a claim "cdr_arrangement_id" in the ID Token

In the non-normative response example next to this section shows cdr_arrangement_id outside of id_token

```
{
  "access_token": "2YotnFZFEjr1zCsicMWpAA",
  "expires_in": 3600,
  "refresh_token": "tGzv3JOkF0XG5Qx2TlKWIA",
  "id_token": "eyJraWQiOiIxZTlnZGs3IiwiYWxnIjoiUl...",
  "cdr_arrangement_id": "02e7c9d9-cfe7-4c3e-8f64-e91173c84ecb"
}
```

It is assumed that non-normative example is incorrect.  In such a case, please remove cdr_arrangement_id from the above example to avoid confusion.

## Question 2
Please clarify the below statement?

> A CDR Arrangement ID can span multiple historical consents which are not active

Assume the intent is for the same CDR arrangement ID to be used in a re-auth flow and NOT a new full consent flow? If so, please add statements in the spec to clarify this use-case.

If v1.3 is not meant to tackle re-auth, we're recommending this to be clarified as well.  If re-auth is a use-case please clarify on the meaning/definition of re-auth?  Does it mean no change of scopes and accounts from the previous consent but simply extending the consent sharing duration?  Change of scopes and accounts seem to warrant a full flow.

## Question 3
Under "Retrospectively obtaining a CDR Arrangement ID" section, it is stated that

> For consents The Data Holder must provide the CDR Arrangement ID as a claim in the Token endpoint response and Token Introspection endpoint response.

However, in "Introspection End Point" section there is the following conflicting information that disallows cdr_arrangement_id being returned.

> An Introspection End Point Response SHALL only include the following fields:
> * active: Boolean indicator of whether or not the presented token is currently active.
> * exp: A JSON number representing the number of seconds from 1970-01-01T00:00:00Z to the UTC expiry time.

Assume cdr_arrangement_id should be added in the above statement?

Also is it really necessary to preclude optional fields as defined in [RFC7662 Introspection Response](https://tools.ietf.org/html/rfc7662#section-2.2)?

## Question 4
Pre-version 1.3, it was possible for ADRs to use the Introspection Endpoint to understand if the consent is still active or not.  However, with the introduction of cdr_arrangment_id it does not seem possible any more as the Introspection will return the status of the refresh token and not the status of the consent.

Please clarify what's the new mechanism for ADRs to check the consent status as we may have missed it in our reading.

**Comment by spikejump** [comment]
Following our requests for clarification above we have additional questions related to this topic below.

### Question 5
In the Pushed Authorisation End Point section, there is the following statements
> If the cdr_arrangement_id is not related to the consumer being authenticated it MUST be rejected
> If the cdr_arrangement_id is not related to the Data Holder it MUST be rejected

What will be the error code to be used for the above rejection?  Will there be an error response object? If so will it be a CDS style [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist) or OAuth2 style ({error: <val>, error_description: <val>})?

Clarity on this would help interoperability between DR and DH.  Lack of clarity in this area has caused a lot of confusion during Industry testing.

### Question 6
Under the CDR Arrangement Management End Point section there is a statement of
> For Data Holders, Data Recipients must be authenticated when they call this end point using a valid Access Token as specified in section 10.3 of [OAUTH2]

Please clarify what Access Token this is?  The Arrangement Endpoint uses Client Authentication when DR calls DH.  There is no use of an Access Token.  Assume this is a typo?

### Question 7
Also under the CDR Arrangement Management End Point section there is a statement of
> A call to this end point should be responded to with HTTP status code 422 if the client submitted an invalid identifier

Please clarify whether there is a response body when returning 422. If there is one please clearly defined its schema. Lack of clarity in this area has caused a lot of confusion during Industry testing.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump thanks for these questions. The DSB will be posting a change request shortly to cover the changes to the standards to make clear the transition requirements for concurrent consent and November 2020 obligations. We'll address the questions you've raised accordingly.

**Comment by ttranatping** [comment]
I have further queries relating to Question 5:

> If the cdr_arrangement_id is not related to the Data Holder it MUST be rejected

Is this validation performed on the PAR call, or during the consent flow?

> If the cdr_arrangement_id is not related to the consumer being authenticated it MUST be rejected

This validation seems like it can only be performed on the consent flow. We do not know who the consumer is until they've performed OTP validation.

**Comment by CDR-API-Stream** [comment]
Hi @ttranatping 

> If the cdr_arrangement_id is not related to the Data Holder it MUST be rejected
> Is this validation performed on the PAR call, or during the consent flow?

You are correct @ttranatping, this should be updated to correctly validate this condition during the consent flow once authentication has been performed.

> If the cdr_arrangement_id is not related to the consumer being authenticated it MUST be rejected
> This validation seems like it can only be performed on the consent flow. We do not know who the consumer is until they've performed OTP validation. Unless the term consumer is in relation to the requesting client?

You are correct @ttranatping, this should be updated to correctly validate this condition during the consent flow once authentication has been performed.

This answers [Question 5](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/254#issue-647805192) from @spikejump.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 1
> It is assumed that non-normative example is incorrect.  In such a case, please remove cdr_arrangement_id from the above example to avoid confusion.

This has been updated in [Decision Proposal 135](https://github.com/ConsumerDataStandardsAustralia/standards/issues/135). It is expected to be a claim in the Token and Token Introspection JSON responses not the ID Token. Longer-term it is anticipated that CDR specific claims can exist within the ``authorization_details`` per [RAR draft-lodderstedt-oauth-rar-03](https://tools.ietf.org/html/draft-lodderstedt-oauth-rar-03#section-3.4).

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 2
> Please clarify the below statement?
> > A CDR Arrangement ID can span multiple historical consents which are not active

This statement has been removed in [Decision Proposal 135](https://github.com/ConsumerDataStandardsAustralia/standards/issues/135). The intent is that there can only be one active consent using the same ``cdr_arrangement_id`` at any given time.

> Assume the intent is for the same CDR arrangement ID to be used in a re-auth flow and NOT a new full consent flow? If so, please add statements in the spec to clarify this use-case.
> 
> If v1.3 is not meant to tackle re-auth, we're recommending this to be clarified as well.  

Re-authorisation is not supported in November 2020. The rules covering re-authorisation are being considered for a future date. When the ``cdr_arrangement_id`` is provided in the request object via the PAR endpoint, the expectation is withdrawal of the existing consent and creation of a new consent under the same ``cdr_arrangement_id`` until such time that the rules permit re-authorisation and separation of data collection and use.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 3
> Assume cdr_arrangement_id should be added in the above statement?

Thanks. This issue will be corrected in the upcoming v1.4.0 release of the Consumer Data Standards. See [Decision Proposal 137](https://github.com/ConsumerDataStandardsAustralia/standards/issues/137).

> Also is it really necessary to preclude optional fields as defined in [RFC7662 Introspection Response](https://tools.ietf.org/html/rfc7662#section-2.2)?

No it is not, however the current v1.3.1 of the CDS precludes it and there are potential breaking change impacts to consider. [Change request 273](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/273) has been raised to consult on this issue.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 4
> Pre-version 1.3, it was possible for ADRs to use the Introspection Endpoint to understand if the consent is still active or not.  However, with the introduction of cdr_arrangment_id it does not seem possible any more as the Introspection will return the status of the refresh token and not the status of the consent.

This is a known gap and will be consulted on as a separate change request. One option already presented by the community in [Issue 273](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/273#issuecomment-665340276) was introspection of an Arrangement ID.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 5

> What will be the error code to be used for the above rejection?  Will there be an error response object? If so will it be a CDS style [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist) or OAuth2 style ({error: <val>, error_description: <val>})?

This question has been addressed in response to @ttranatping's [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/254#issuecomment-665404911). See https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/254#issuecomment-671738734.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 6
> Please clarify what Access Token this is?  The Arrangement Endpoint uses Client Authentication when DR calls DH.  There is no use of an Access Token.  Assume this is a typo?

This is an error and it has been addressed in [Decision Proposal 135](https://github.com/ConsumerDataStandardsAustralia/standards/issues/135). DRs will call DHs using ``private_key_jwt`` client authentication. See [Data Recipients calling Data Holders](https://consumerdatastandardsaustralia.github.io/standards/#data-recipients-calling-data-holders).

**Comment by CDR-API-Stream** [comment]
Hi @spikejump,
### Question 7
> Please clarify whether there is a response body when returning 422. If there is one please clearly defined its schema. Lack of clarity in this area has caused a lot of confusion during Industry testing.

The expectation is that the error response conforms with error structure and standards defined in [Payload Conventions](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions). No error code has been proposed, but the DSB would be open to including an explicit error code similar to "0001 – Account not able to be found" noting that the code defined for November would be a transition until [Decision Proposal 120](https://github.com/ConsumerDataStandardsAustralia/standards/issues/120) is finalised.

**Comment by spikejump** [comment]
@CDR-API-Stream Thanks for all the response above.

Just to follow up on Question 5, not sure if the original questions have been answered.  Essentially, when DH rejects the supplied cdr_arrangement_id, what is the HTTP Status code that will be returned?  As well as whether a [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist) or something else MUST (?) be returned?

With respect to the above response to Question 7, is our interpretation correct in that an error response body MUST be returned but the schema definition and the precise code that needs to be returned will be pending Decision Proposal 120?

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
