### ISSUE TITLE
Direct Debit authorised entity

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#255]
# Request For Clarification
In the schema for BankingAuthorisedEntity -
https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingauthorisedentity

The description field states -
'Description of the **authorised entity** derived from previously executed direct debits'

Should this be taken to mean a description of the direct debit transaction - for example the transaction reference field where available?
If not, what kind of description for an 'authorised entity' may be expected apart from the institution name which would be in the financialInstitution property?

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 

Would this be a reasonable representation for description and institution? 
The description value would be taken from the transaction remit name.

description|financialInstitution
------------|-----------------
ABC PTY LTD|WBC
PAYPAL AUSTRALIA|WBC
XYZ ENERGY|CBA

**Comment by CDR-API-Stream** [comment]
Hi @nils-work the example descriptions look correct. The intention of this field is to provide who the original merchant was within reasonable efforts taken by the data holder. In some situations this may not be available however it's up to the data holder to execute best efforts.

In your example, the ``financialInstitution`` is the merchant's financial institution initiating the direct debit, but the intention of the ``description`` field is this is the original authorising merchant.
