### ISSUE TITLE
Potential confusion over charset parameter in media types

### ISSUE THREAD

**Issue by jogu** [ConsumerDataStandardsAustralia/standards-maintenance#256]
# Description

The standard says things like:

> Content-Type | Standard HTTP Header. Represents the format of the payload provided in the request. Must be set to application/json

It's unclear to me exactly what this means. Clearly this is valid:

`Content-Type: application/json`

However as per the underlying standards, this has exactly the same meaning:

`Content-Type: application/json;charset=UTF-8` (this being the default value sent by some REST libraries)

and for that matter:

`Content-Type: application/json         ;          charset=UTF-8` 

and:
`CONTent-type: aPPliCatION/JsOn;chaRset=UTF-8`

Given these are all required to have the same meaning, they should all be accepted by DH/DR.

Similar concerns apply to the `Accept` header where a client may indicate it can accept several mime types whilst also indicating a preference.

references:

https://www.ietf.org/rfc/rfc4627.txt  

https://tools.ietf.org/html/rfc7231#section-3.1.1.1

# Area Affected

https://consumerdatastandardsaustralia.github.io/standards/#http-headers

# Change Proposed

Included some variants in the non-normative examples to make it clear the underlying standards continue to have effect.

Possibly slightly change the language in the spec to say "the requested media type must be application/json" instead of "Must be set to application/json".

**Comment by perlboy** [comment]
@jogu FYI, this was discussed in November 2019: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/27

**Comment by CDR-API-Stream** [comment]
Hi @jogu you're correct, the intention is to support the UTF-8 charset. In the HTTP Response Codes section (for HTTP Status Code 406 Not Acceptable), the character set of UTF-8 is supported. 

Case insensitivity should be per-the RFCs.

An update to the documentation and non-normative examples will be considered in the next maintenance iteration.

**Comment by CDR-API-Stream** [comment]
Five changes are proposed based on this CR and feedback received:

**1. Update the "Content-Type" Request Header description to reference media type correctly**
Make it clear that the Content-Type headers will also accept a character set encoding.

> Standard HTTP Header. Represents the format of the payload provided in the request. The media type must be set to application/json. Mandatory for PUT and POST calls. 

---

**2. Add Content-Type header non-normative example**

In the HTTP Headers section, add the following non-normative example:

> A Data Holder must be able to process Content-Type headers in accordance with **[RFC7231]**. The following would be valid.
> ```
> Content-Type: application/json;charset=UTF-8
> Content-Type: application/json
> Content-Type: AppliCAtion/JSon;Charset=uTf-8
> ```

--- 

**3. Update "Accept" Request Header description to reference media type correctly**

Make it clear that the Accept headers will also accept a character set encoding.

> If specified, the media type must be set to application/json, unless otherwise specified in the resource end point standard.
> If set to an unacceptable value the holder must respond with a 406 Not Acceptable. If not specified, or a wildcard (\*/\*) is provided, the default media type is application/json.

---

**4. Add Accept header non-normative example**
In the HTTP Headers section, add the following non-normative example:

> A Data Holder must be able to process Accept headers in accordance with **[RFC7231]**. The following would be valid.
> ```
> Accept: */*
> Accept: application/json;charset=UTF-8
> Accept: application/json
> Accept-Encoding: charset=UTF-8
> Accept: AppliCAtion/JSon;Charset=uTf-8
> ```

---

**5. Add RFC2713 to the Informative References section**
In the Informative References table add the following row:

> Reference | Description
> :-- | :--
> **[RFC7231]** | Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content: https://tools.ietf.org/html/rfc7231

**Comment by jogu** [comment]
Sounds good! One further example for Accept might be worthwhile, e.g.:

```
Accept: application/json, application/*+json; q=0.9; charset="utf-8", */*
```

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.4.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/137). 

This issue will be closed accordingly.
