### ISSUE TITLE
Clarification of expected duration of new consent replacing existing consent

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#258]
In the Weekly Data Holders meeting of the 2nd July it was mentioned that when a consent request is received that relates to an existing active consent (same cdr.arrangement.id) then the existing consent is withdrawn and a new consent created that has a maximum 12 month duration from the date of the new request.

Reviewing documentation from Decision #99 on Concurrent Consents the below extract indicates the new arrangement will have an expiration calculated by adding the specified duration to the expiration time of the current consent.

Can you please confirm the correct interpretation for this scenario?

++++
_If a cdr_arrangement_id is provided then, upon successful authorisation, the data holder would
revoke the existing consent associated with the provided refresh token. In addition, the expiration of
sharing would be calculated as the addition of the specified sharing duration to the expiration time
of the current consent rather than to the time of authorisation. This would allow for an existing
consent to be extended for the full twelve-month allowable period._

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA 

At present, if an ADR provides an existing ``cdr_arrangement_id`` within the authorisation flow, the DH will revoke the current consent and establish a new consent. This new consent's duration will be determined by the ``sharing_duration`` which can only be up to 12 months. Consent cannot be additive within one active consent. In other words, an ADR can't use the remaining time of the current consent and add 12 months to get a ``sharing_duration`` greater than 12 months.

Admittedly the statement you've quoted is ambiguous. The intention was to describe that logically the duration of the sharing arrangement (which spans active and expired consents) could be greater that 12 months. For example, if consent is authorised three times each with a 12 month duration, the duration of collection over the lifetime of the arrangement would be 36 months. This doesn't have a bearing on the ``sharing_duration`` within an active consent.

**Comment by spikejump** [comment]
> if an ADR provides an existing cdr_arrangement_id within the authorisation flow, the DH will revoke the current consent and establish a new consent.

@CDR-API-Stream Can you please clarify the wording on "revoke the current consent"?

Our understanding is that the consent (cdr_arrangement_id) is not revoked but the refresh token associated to the cdr_arrangement_id is revoked.  The implications here is there is no new cdr_arrangement_id generated in this case.  The consent essentially got refreshed with an extension on its sharing_duration.

If this is correct, it might help in the spec not to use the term of revocation of consent unless it is a true revoke where the cdr_arrangement_id is "deactivated" forever.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
