### ISSUE TITLE
Clarification of BPAY CRN masking requirements

### ISSUE THREAD

**Issue by jroyals** [ConsumerDataStandardsAustralia/standards-maintenance#259]
# Request For Clarification

According to the data standards relating to "BankingBillerPayee", https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingbillerpayee it is...

> BPAY CRN of the Biller. If the contents of the CRN match the format of a Credit Card PAN then it should be masked using the rules applicable for the MaskedPANString common type

I have two questions relating to BPAY CRNs.

1. Is there a CDR definition of "the format of a credit card PAN" so these rules can be applied consistently by data holders? One loose definition may be any 15-19 digit number but that will mean some CRNs that are not PANs will also be masked. A more sophisticated approach might look for known BINs and applying a Luhn check but that adds complexity and in some cases may still over-match and under-match. Any thoughts on this?
1. The Australian Taxation Office issues CRNs that include the Tax File Number. It's not a PAN, but I'd expect this would also need to be redacted due to rules around sharing TFNs?

**Comment by CDR-API-Stream** [comment]
Hi @jroyals, thanks for raising these questions.

For both questions, where the account identifier or CRN contains sensitive information, it should be masked inline with how the Data Holder currently displays account identifiers in their existing online banking channels. 

In the case of TFNs, DHs should handle masking in accordance to their current practices.

**Comment by jakubvozarik** [comment]
Hi @CDR-API-Stream - just a quick follow-up regarding masking.

In the account detail API the schema says 

accountNumber - The unmasked account number for the account. Should not be supplied if the account number is a PAN requiring PCI compliance. Is expected to be formatted as digits only with leading zeros included and no punctuation or spaces

Does the same expectation as you stated above ("it should be masked inline with how the Data Holder currently displays account identifiers in their existing online banking channels.") apply in case of account numbers here?

Also for payee details - are DHs expected to share unmasked account numbers here as well or follow their current practices?

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
