### ISSUE TITLE
Error in description of amount in BankingScheduledPaymentSet

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#26]
# Description
The description of **amount** in [BankingScheduledPaymentSet](https://consumerdatastandardsaustralia.github.io/standards/#schemabankingscheduledpaymentset) is clearly incorrect, duplicating the description of **isAmountCalculated**.

# Area Affected
Definition of [BankingScheduledPaymentSet](https://consumerdatastandardsaustralia.github.io/standards/#schemabankingscheduledpaymentset) which is used in:

- [Get Scheduled Payments for Account](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-account)
- [Get Scheduled Payments Bulk](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-bulk)
- [Get Scheduled Payments For Specific Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-specific-accounts)

# Change Proposed
The description should be updated to reflect the [Decision 051 – Scheduled Payments](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251514/Decision.051.-.Scheduled.Payments.pdf):

“The amount of the next payment if known. Mandatory unless the **isAmountCalculated** field is set to true. Must be zero or positive if present.”

**Comment by CDR-API-Stream** [comment]
The proposed change will be recommended by the DSB unless counter feedback is received.
