### ISSUE TITLE
Reporting requirements in relation to Data Recipients

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#260]
The Consumer data Standards provide requirements that caters for ACCC to obtain operational statistics from Data Holders (see extract below).
Are there any requirements for similar reporting from Accredited Data recipients (or will there be in the future)?

_GET /admin/metrics
This end point allows the ACCC to obtain operational statistics from the Data Holder on the operation of their CDR compliant implementation. The statistics obtainable from this end point are determined by the non-functional requirements for the CDR regime._

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA 

There are no reporting requirements for ADRs under the data standards (i.e. the Get Metrics API is only required for data holders).

However, ADRs *are required* to provide the ACCC and the OAIC with a report in accordance with rule 9.4. The form to be used by ADRs for the purposes of reporting under rule 9.4 is available on the ACCC website: https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/reporting-forms-rule-94

**Comment by BH-UDA** [comment]
Thank you @CDR-API-Stream for the confirmation. 
This aligns with our understanding and allows us to communicate with our client base.
