### ISSUE TITLE
Request for clarification on concurrent consent

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#261]
Hi, 

We'd like a clarification around concurrent consent and how it is established. From Decisions 85 and 99 we understand that this is to allow customers "to sign up for multiple use cases with a data recipient where a customer wishes to
specify different sharing durations for these use cases." 
Are these use cases meant to be separate Software Products or are these meant to support concurrent consents between one Software Product and a DH?

We might have some follow-up questions based on this clarification.

Thank you

**Comment by nils-work** [comment]
My understanding of the intent of the concurrent consent model is that it's where a customer creates two different consent arrangements for **one** software product.
As a broad example, the ADR service may offer some kind of analysis of transactions and payees.
The ADR realises that customers may not want to give the same consent for different types of data on the same terms.
In that case, a customer may create one arrangement for payee data sharing with only a one-time consent and another arrangement for transaction data ongoing for 12 months.

I suppose an ADR may want to have two software products if those services were different enough and they wouldn't want any potential changes to the status of one product to impact the other.

**Comment by bmangalaganesh** [comment]
@nils-work In the previous model, single extant consent was defined as:

> A data holder MUST support only one extant consent arrangement (being an arrangement between a single Customer, a single Data Recipient and a single Data Holder) at a time. If a second consent is authorised then the tokens associated with the previous consent MUST be revoked.

This was at a Data Recipient level and not at a Software product level. 

Now with concurrent consents, you can have multiple consents with the same ADR across multiple brands and software products (with a single Data Holder)

One can also have multiple concurrent consents with the same Software product too like you described (Payee having one consent duration while transaction having a different duration).

Besides the use case that you had described, I think another primary use case for concurrent consent is the ability to provide a new consent before the old one expires thereby allowing the ADRs to retain data (and not be subjected to delete or de-identification rules when a consent expires).

**Comment by nils-work** [comment]
Hi @bmangalaganesh 

Are you saying there is a use case to create a concurrent consent instead making a renewal, so data can be retained?

I thought renewal would be handled by the arrangement approach detailed [here](https://consumerdatastandardsaustralia.github.io/standards/#identifiers-and-subject-types) and [here](https://consumerdatastandardsaustralia.github.io/standards/#request-object) -
"To allow for an existing consent to be reliably revoked upon the establishment of a new consent **intended as a replacement**"

I think an ADR would still have to delete or de-identify any data that was associated with an expired or revoked consent, regardless of whether they had another active concurrent consent?

**Comment by bmangalaganesh** [comment]
@nils-work If the new consent is intended as a replacement, I don't believe the ADRs have to delete or de-identify the data.

My reading is that the replacement is the equivalent of "renewal of the consent".

Would love to see how others are interpreting this.

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik,

Concurrent consent facilitates multiple active consents per ADR **software product** for a given consumer. This will allow ADRs within one software product to offer:
* multiple use cases within one software product
* separate consent that is granted for discrete uses ensuring the ADR can observe the Data Minimisation Principle
* allow consumers to establish multiple consents within one use case - say to share transaction and savings accounts in one consent and credit cards in another consent, possible with different terms such as durations and data clusters.

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh and @nils-work thanks very much for your comments.

A few remarks.

> This was at a Data Recipient level and not at a Software product level.

The intent was a single extant consent per ADR software product. With concurrent consent, the intent is an ADR may establish multiple active consents within the same software product.

> Besides the use case that you had described, I think another primary use case for concurrent consent is the ability to provide a new consent before the old one expires thereby allowing the ADRs to retain data (and not be subjected to delete or de-identification rules when a consent expires)

The current Rules preclude ongoing use of data when consent is revoked. For November 2020, concurrent consent will not allow an ADR to continue to use previously collected data. They must delete or de-identify that data. The Rules are currently under review to facilitate separation of collection and use. Questions regarding the timeframe for rules changes should be addressed to the ACCC.

**Comment by InfosysFinacle** [comment]
Hi CDR-API-Stream
Whilst from ADR perspective this is clear as you said:
Concurrent consent facilitates multiple active consents per ADR software product for a given consumer. This will allow ADRs within one software product to offer:
1. multiple use cases within one software product
2. separate consent that is granted for discrete uses ensuring the ADR can observe the Data Minimisation Principle
3. allow consumers to establish multiple consents within one use case - say to share transaction and savings accounts in one consent and credit cards in another consent, possible with different terms such as durations and data clusters.

But most importantly from ADH perspective: One point that is still not clear how will ADH capture concurrent consent from a Consumer and an ADR. This need to be clearly explained with examples.

**Comment by CDR-API-Stream** [comment]
Thanks @InfosysFinacle the DSB is working on some revisions which will be proposed to clarify aspects of concurrent consent documentation. Examples will be considered. 

Concurrent consent should be captured as per any other authorisation request from a client to the data holder. It simply means that one client software can establish multiple authorisations (each with associated access tokens and/or refresh tokens) for the one user subject (consumer). Are there any specific questions related to the capturing of consent (concurrent or otherwise) that you have which could be cleared up?

**Comment by jakubvozarik** [comment]
Thanks @CDR-API-Stream  
Is the DH expected to provide each individual authorisation on their consumer dashboard with the option to withdraw each authorisation individually? If so, how would a DH notify an ADR about that specific withdrawal, as the DH would only call CDR Arrangement Management API with the CDR arrangement id ?

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik where each consent is its own separate arrangement, there will be a different ``cdr_arrangement_id`` for each of the active consents and they would show up separately on the DH and ADR dashboards. A DH would notify the ADR using the ``cdr_arrangement_id`` related to the active consent being withdrawn. This wouldn't change the other active consents that the consumer has with the ADR software product and DH.

There shouldn't be a scenario where there is more than one active consent for the same ``cdr_arrangement_id``.

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
