### ISSUE TITLE
Clarification about Joint Account Management Service - Closed Accounts

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#262]
We are seeking clarification about the requirements for Closed Joint Accounts election in the Account Management Service in the next scenario: one of the Closed Joint Account holders has left the bank and is no longer a customer (does not have the ability to access online banking, does not have client number), and the other Joint Account Holder is still an active customer and wants to share the data for this Closed Joint Account. How should the election process work in this case?

**Comment by nils-work** [comment]
I'm guessing that at the time of any joint account holder leaving, their sharing elections would be reset - meaning that a remaining account holder would no longer have access to the accounts that require election.

**Comment by KaterynaShandro** [comment]
Hi @nils-work , thanks for your reply, but my question wasn't about revoking elections when a customer leaves. 

The question we have is in the state where no prior elections were made. As part of the requirements, Closed Joint Accounts need to be included in Joint Account Management Service. In a case where one of Joint Account Holders is still a customer, the Closed Joint Account will still be displayed for his/her client number in Joint Account Management Service. I want to get clarification of what is the suggested solution in this case, as the second Account Holder is no longer a customer and can not make an election to make the account available for data sharing. The solution might be to exclude Closed Joint Accounts where one of Account holders has left the bank from the requirements, but I don't think this is clarified in the CDR rules at this stage.

**Comment by nils-work** [comment]
Sorry @KaterynaShandro, I thought you meant access to joint accounts on the consumer dashboard.

I know there is a requirement for closed individual accounts to be available for sharing within a defined time frame, but I couldn't see anything specific about closed joint accounts having to appear in the JAMS?

Slightly related from CX guidelines page 80 -
> Data holders are not permitted to show unavailable joint accounts as joint
> accounts need to be elected via a joint account management service before
> they are permitted to appear in the authorisation flow (See CDR Rules:
> Schedule 3, 4.1(1); 4.2; 4.3(3); and CDR Rule 4.24)

and from the rules, Schedule 3, 4.2(3) -
> If no election is made on a particular joint account, it will not be possible to make consumer data requests for CDR data relating to the account under these rules.

I guess there may be no point in having only one remaining account holder of a closed joint account making an election for that account?
Maybe affected accounts could be shown to the customer in the JAMS, with a note stating that they are now unavailable for sharing as joint election cannot be made?

**Comment by KaterynaShandro** [comment]
Hi @nils-work thanks for your reply, it's very helpful. I think the solution you proposed could work (to show affected closed joint accounts to the customer in the JAMS, with a note stating that they are now unavailable for sharing as joint election cannot be made), but I think it will be good to get confirmation from ACCC that it is the correct interpretation of the rules. 

With regards to Closed Joint Account, earlier we reached out to ACCC for clarifications and got the below response. It doesn't specify that closed accounts relate to only single accounts, so we included closed joint accounts to scope.

_To clarify the position on closed accounts, under the CDR Rules:

Provided a CDR consumer is ‘eligible’ to make consumer data requests in relation to a particular data holder, they are able to make requests that relate to closed accounts.
To be eligible, the consumer must have at least one open account with the data holder that can be accessed online.
A data holder is only required to respond to a request to share data from a closed account if the request is made within 24 months of the account closing being closed. 
If the request is made within 24 months of the account being closed, a data holder is only required to share up to 12 months of historical transaction data, going back from the date the account was closed. 
For example, if I close an account on 1 January 2023, but still have an online account with the same data holder, I could make a request to share data from that closed account up until 1 January 2025.  Any request to share data could contain a maximum 12 months of transaction data dating back from the closure of the account (i.e. back to 1 January 2022). 

Importantly:

The above is subject to the concept of the “earliest holding day” in the Banking Designation Instrument for the CDR.  The earliest holding day is the earliest date from which data can be required to be shared under the regime, which is 1 January 2017. 
While the above is required consumer data, data holders are able to provide additional historical data (e.g. more than 12 months’ worth), or data from accounts that were closed earlier than 24 months ago, on a voluntary basis should they wish._

**Comment by nils-work** [comment]
ACCC/DSB answer is [here](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Meeting-Notes-(16th-of-July-2020)) (search for issues/262)

**Comment by CDR-API-Stream** [comment]
Hi @KaterynaShandro, in response to your question the following ACCC answer has been provided:

The policy intent is that both joint account holders must be ‘eligible’ (eligible is as defined in cl 2.1(2) of schedule 3). Therefore, in this scenario the joint account would not be able to be shared as one of the joint account holders is not ‘eligible’ given they do not have an open account that can be accessed online with the data holder.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.

**Comment by cdradr** [comment]
What if some data from closed joint account is required  for Data Recipient’s use case?

And, in some circumstances, it is not practical or possible to reach out to the other ex holder. 

Customer can login to their online banking and see the data but can’t exposes it via CDR?

Is this encouraging screen scraping?
