### ISSUE TITLE
Consumer Experience Changes for v1.4.0

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#263]
# Description
For the next release of the Consumer Data Standards there are a number of minor changes to the Consumer Experience Standards and Guidelines.

# Area Affected
Permitting Data Holders to show unavailable joint accounts in authorisation flow

# Impact & Type:
CX Standards and Guidelines: clarification

# Change Proposed
CX Standards v1.3.0 reflected ACCC’s position that DHs were not permitted to show unavailable joint accounts in the authorisation flow. The ACCC have revised this position to allow DHs to show unavailable joint accounts in the authorisation flow.
 
We will seek to reflect this revised position in a V1.4.0 release as optional for November 2020. This change will (1) remove the statement on data holders not being permitted to show unavailable joint accounts and (2) add a clarification on how unavailable accounts are to be interpreted.

**This will result in the 'Unavailable Account' component of [CX Standard #14](https://consumerdatastandards.gov.au/wp-content/uploads/2020/05/CX-Standards-v1.3.0.pdf) being changed from:**
If certain accounts are unavailable to share, data holders SHOULD show these unavailable accounts in the account-selection step.
- Data holders SHOULD communicate why these accounts cannot be selected, and this SHOULD be communicated as in-line help or as a modal to reduce on-screen content.
- Data holders MAY provide instructions on how to make these accounts available to share, and this SHOULD be communicated as in-line help or as a modal to reduce on-screen content.
- Data holders are not permitted to show unavailable joint accounts as joint accounts need to be elected via a joint account management service before they are permitted to appear in the authorisation flow (See CDR Rules: Schedule 3, 4.1(1); 4.2; 4.3(3); and CDR Rule 4.24)

**To:**
If certain accounts are unavailable to share, data holders SHOULD show these unavailable accounts in the account-selection step.
- Data holders SHOULD communicate why these accounts cannot be selected, and this SHOULD be communicated as in-line help or as a modal to reduce on-screen content.
- Data holders MAY provide instructions on how to make these accounts available to share, and this SHOULD be communicated as in-line help or as a modal to reduce on-screen content.
- _Note: Unavailable accounts are to be interpreted in accordance with the rules on eligible consumers and required consumer data_

# Origin:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/106
https://github.com/ConsumerDataStandardsAustralia/standards/issues/123

**Comment by CDR-CX-Stream** [comment]
These changes were incorporated into the [v1.4.0 release](https://consumerdatastandardsaustralia.github.io/standards/#consumer-experience) and this issue is being closed accordingly.
