### ISSUE TITLE
Decrement BankingProduct

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#266]
# Description
`BankingProduct` is specified as payload V3 within the results for GetProducts however from what we can tell there is zero changes to `BankingProduct` itself. As far as we can tell the last known change on `BankingProduct` is the addition of `cardArt` between V1 and V2.

While `BankingProductDetail` has changed between V2 and V3, the `BankingProduct` class has not. As a consequence the generic for `BankingProduct` is unaltered between V2 and V3 (resulting in class casting failures).

Biza.io intends to implement this non-change in [Babelfish](https://github.com/bizaio/babelfish) as a multi-versioned response with the same underlying class of `BankingProductV2`.

# Area Affected
`BankingProductV2` and `BankingProductV3`

# Change Proposed

Remove payload version 3 for `GetProducts` as the payload has not changed

**Comment by CDR-API-Stream** [comment]
Thanks @perlboy this issue is being reviewed as part of Maintenance Iteration 4.

**Comment by perlboy** [comment]
I note in the minutes for [Maintenance Iteration 4](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-4:-Final-iteration-review:-Agenda-&-Meeting-Notes-(19th-August-2020)) this change was not supported and "intentional". As a consequence, are we to assume therefore that the payloads for `x-v=2` and `x-v=3` for Get Products are the same?

**Comment by nils-work** [comment]
Related to #311  ?

**Comment by perlboy** [comment]
@nils-work Similar but not the same. #311 is about a payload changing without being incremented, this one is about a payload incrementing without being changed.
