### ISSUE TITLE
Value of payee label in BankingTransactionDetail

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#268]
# Request For Clarification
Related to [issue 25 - Payee name is not always known](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/25) and the subsequent change for accountName to be optional in [BankingDomesticPayeeAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingdomesticpayeeaccount) from version 1.2.0, I'd like some clarification about the expectation for a payee in [BankingTransactionDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransactiondetail).

The description for the field currently states -

> ...Mandatory for an outbound payment. The name assigned to the BSB/Account Number...

Assuming the `extendedData` object is not only for NPP detail, how should the `payee` value be presented if no name is available/provided by the customer? For [issue 25](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/25), the mandatory `bsb` and `accountNumber` provided the required detail.

Also for consideration is the change made to the CX Standards as a result of [issue 139](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/139).

An empty string may meet the requirements for the schema, but it may not be useful for a customer...

Any suggestions?

**Comment by CDR-API-Stream** [comment]
Hi @nils-work ``extendedData`` is only currently used for NPP data. It could be used for other payment types in future but it was only initially expected to be NPP.
