### ISSUE TITLE
Update to Content-Type

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#27]
Content-Type is currently listed as a mandatory request header. We recommend that it is only mandatory for verbs where there is a body (most commonly PUT and POST) and optional for the verbs where there is no body. It should not be mandatory to send a request type as the content may not be present in all scenarios.

**Comment by perlboy** [comment]
`Content-type` is currently specified within [FAPI Part 1 Section 6.2.1](https://openid.net/specs/openid-financial-api-part-1.html#protected-resources-provisions) as:
`shall send the Content-type HTTP header Content-Type: application/json; charset=UTF-8 if applicable;`

However, [as of the past 2 weeks](https://bitbucket.org/openid/fapi/issues/236/charset-not-needed-for-application-json) the FAPI specification is proposed to change to:
`shall send the Content-type HTTP header Content-Type: application/json; if applicable;`

On this basis the CDS could change this section to simply refer to FAPI Part 1 Section 6.2.1, add `if applicable` or both.

**Comment by CDR-API-Stream** [comment]
This highlights something we will need to address in the near term within the CDR standards.

Basically, if the normative standards iterate what are the implications on data holder and data recipient compliance with those changes?  As we are nearing our second implementation milestone and the first to include substantial normative references this will become an issue to manage within the standards.  This will be raised internally within the DSB for discussion to consider the implications.

To ensure clarity for the time being the treatment of Content-Type will be retained in the standards.

In response to this specific change request the recommended approach would be to clarify the mandatory status of the Content-Type request header to PUT and POST calls only.

**Comment by CDR-API-Stream** [comment]
For normative standards the DSB will also recommend that the normative reference table have an additional version/date column indicating the version of the normative reference that is applicable to the CDR standards.
