### ISSUE TITLE
Single Value Arrays

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#270]
# Request For Clarification
For results involving arrays of primitive values (for instance an array of strings) could guidance be given on whether single value arrays are considered acceptable. By way of example, `CommonPerson` contains an attribute of `middleNames`.

The strictly accurate method would be to present this as:
```"middleNames": ["Geoff"]```

However, many serialisation libraries (particularly ones of XML origin) will present this as:
```"middleNames": "Geoff"```

While treating multiple values as intended, ie:
```"middleNames": ["Geoff", "John"]```

Could the DSB provide guidance as to whether single value arrays presented as Strings is considered acceptable?

**Comment by CDR-API-Stream** [comment]
Hi @perlboy the expectation is arrays are explicitly defined. The same applies for object arrays. Suggestive examples:

Many-values:
```javascript
"middleNames": ["Geoff", "John"]
"errors": [
    {
      "code": "...",
      "title": "...",
      "detail": "..."
    }, {
      "code": "...",
      "title": "...",
      "detail": "..."
    }
]
```

Single-value:
```javascript
"middleNames": ["Geoff"]
"errors": [
    {
      "code": "...",
      "title": "...",
      "detail": "..."
    }
]
```

Empty array:
```javascript
"middleNames": [ ]
"errors": [ ]
```

**Comment by perlboy** [comment]
@CDR-API-Stream Ok but be aware this is a different behaviour within JWT specs (particularly `aud`) which, if there is a cross over of domains (for instance Consent Metadata) will be problematic.
