### ISSUE TITLE
Update Get Metrics rejections counts and clarify affected APIs

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#271]
# Description
The section in Get Metrics describing rejection counts is only supposed to cover authenticated APIs however this is not clear in the current description:
> Number of calls rejected due to traffic thresholds over time

[Issue #136](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/136) raised this issue and the DSB has prioritised this change in [Maintenance Iteration 4](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134).

# Area Affected
[RejectionMetrics](https://consumerdatastandardsaustralia.github.io/standards/#tocSrejectionmetrics) in GetMetrics API

# Change Proposed
**Option A - Update the description to make it clear that rejection counts only apply to authenticated resource APIs**.

> Number of calls rejected due to traffic thresholds over time for authenticated APIs

This would clarify the purpose and application of rejections as currently expected and make it clear that public APIs such as Get Products and Get Outages do not apply to rejection counts.

**Option B - Provide more granular metrics for rejections based on performance tiers**. 
This may be included as a future dated obligation with a clarification in line with Option A in the short term.

This would allow DHs to report on rejections across public (unauthenticated) and authenticated endpoints and provide visibility of performance across high-use public APIs.

Specifically, change ``rejections`` counts from:
```
 "rejections": {
      "currentDay": 0,
      "previousDays": [
        0
      ]
    },
```

to be:
```
"unauthenticated": {
    "currentDay": 0,
    "previousDays": [
      0
    ]
  },
  "highPriority": {
    "currentDay": 0,
    "previousDays": [
      0
    ]
  },
  "lowPriority": {
    "currentDay": 0,
    "previousDays": [
      0
    ]
  },
  "unattended": {
    "currentDay": 0,
    "previousDays": [
      0
    ]
  },
  "largePayload": {
    "currentDay": 0,
    "previousDays": [
      0
    ]
  }
``` 

**Option C - Authenticated and Unauthenticated rejection counts**
Rather than provide a details breakdown of rejections, simply aggregate as authenticated vs unauthenticated APIs.

Similar to Option B, one limitation may be that unauthenticated rejection counts would be high and may not be countable under all situations (e.g DoS). 

The advantage is that there is visibility and consistency across unauthenticated APIs not just authenticated APIs.

**Comment by ryderwj** [comment]
Support Option A. 

Depending on the DH implementation, coarse-grained and fine-grained rate limits (if applied), may be achieved in different infrastructure components and categorising the API calls into the structure proposed by option B will require additional effort. If the goal is to segregate unauthenticated rejections,  is having a simple authenticated/unauthenticated breakdown an option?

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 
Is it expected that data from Get Metrics APIs will be aggregated and shared with participants in the form of benchmarks, or will they only be visible to the ACCC?

**Comment by CDR-API-Stream** [comment]
Hi @ryderwj, as a third option, providing authenticated + unauthenticated rejection counts could be considered. Would Option C (updated in the original issue above) have similar concerns to Option B or do you see this as more feasible?

**Comment by CDR-API-Stream** [comment]
Hi @nils-work, one of the purposes for the Get Metrics data is for high level reporting of performance and system quality to the ACCC along with assisting in the creation of ecosystem performance dashboards.

**Comment by ryderwj** [comment]
Option C is certainly easier than B from my perspective as it can be handled at a more coarse-grained level

**Comment by CDR-API-Stream** [comment]
This change request was discussed in the maintenance iteration call: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-4:-Iteration-checkpoint:-Agenda-&-Meeting-Notes-(5th-August-2020)

Option C was supported. This would result in a breaking change giving rise to Get Metrics v2 with future dated obligations. To cater for authenticated and unauthenticated rejection counts, the following structure is proposed:

```
"rejections": {
   "authenticated": {
      "currentDay": 0,
      "previousDays": [
         0
      ]
   },
   "unauthenticated": {
      "currentDay": 0,
      "previousDays": [
         0
      ]
   }
}
```

**Comment by NationalAustraliaBank** [comment]
NAB supports the adoption of Option C.

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.5.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134). 

This issue will be closed accordingly.
