### ISSUE TITLE
Request for Clarification on data cleanup during consent renewal

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#275]
# Request For Clarification
We are seeking clarification on thee expected behavior of DRs when a consent is renewed.

On Data Holder Work Group 02/07/2020, Q&A Q3 noted:

> It is our assumption based on the rules that sharing duration of any consent cannot be greater than 12 months even in the case of a consent renewal/linked consent (through use of CDR_arrangement_id). Can you please confirm the appropriate behaviour as DP 99 is a little unclear on this front?

James Bligh noted that currently it is not possible to extend a consent, and it is only possible to revoke a consent and establish a new one instead (which is aligned to our understanding). James also added that **data recipients have an obligation to identified or to delete the data as a result of this revocation**. Could you confirm our understanding is correct? Would November standards updates change this behavior?

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss, 

> > It is our assumption based on the rules that sharing duration of any consent cannot be greater than 12 months even in the case of a consent renewal/linked consent (through use of CDR_arrangement_id). Can you please confirm the appropriate behaviour as DP 99 is a little unclear on this front?  
>
> James Bligh noted that currently it is not possible to extend a consent, and it is only possible to revoke a consent and establish a new one instead (which is aligned to our understanding).

That is correct. At present, if an ADR provides an existing ``cdr_arrangement_id`` within the authorisation flow, the DH will revoke the current consent and establish a new consent. This new consent's duration will be determined by the ``sharing_duration`` which can only be up to 12 months.

> James also added that **data recipients have an obligation to identified or to delete the data as a result of this revocation**. Could you confirm our understanding is correct? 

As is the case now, in November ADRs must delete or de-identify the data previously collected. Until Rules changes support separation of collection and use this will remain the case.

> Would November standards updates change this behavior?

No. This remains the case in November. Noting that the standards aren't envisaged to require changes to facilitate separation of collection and use when these Rules would come into effect.

**Comment by spikejump** [comment]
@CDR-API-Stream Similar to our comment in #258, our understanding is there is no revocation of consent on a renewal.  What's revoked are the refresh token & access token on that consent.  The same cdr_arrangement_id is still active and just got extended into a "new" consent with a new sharing duration.  The "new" consent will still use the same cdr_arrangement_id.

In addition, the assumption of the renewal, is all accounts and scopes remain as they were.  i.e. DHs do not offer changes to customers.  Please confirm if this is the case or not.  If not, then what's getting renewed when supplying the existing cdr_arrangement_id?  Thanks.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
