### ISSUE TITLE
HTTP headers applicable to Infosec end points?

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#276]
# Request For Clarification

The infosec end points are standard well known end-points.

What are the HTTP headers that are expected in the calls to Infosec end points? (I assumed it would be the standard ones dictated by OAuth2/FAPI )

Looking at the NFR sections, customer present for Info sec end points raises a few questions in my head.

Tier | Response Time | Applies To…
-- | -- | --
Unauthenticated | 1500ms | All unauthenticated end points
High Priority | 1000ms | Customer Present calls to the following end points:  **_InfoSec end points_** ....

Is the expectation that the ADR app will send the customer present header (x-fapi-customer-ip-address) when they invoke theinfo sec end points?

My reading and understanding so far was that the HTTP headers  referenced in the [standards](https://consumerdatastandardsaustralia.github.io/standards/#http-headers)
apply to the Banking and admin APIs (and not the infosec APIs).

Would love to hear thoughts and advice from the community and the Big4 folks who have already implemented these.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
