### ISSUE TITLE
Client authentication requirements for PAR

### ISSUE THREAD

**Issue by ttranatping** [ConsumerDataStandardsAustralia/standards-maintenance#277]
# Description
The [CDR specifications](https://consumerdatastandardsaustralia.github.io/standards/#end-points) suggests that Client Authentication is not required for initiating PAR. This is in contrast to the [OAuth2 specifications (draft-ietf-oauth-par-02)](https://tools.ietf.org/html/draft-ietf-oauth-par-02) where it mentions "The rules for client authentication as defined in [RFC6749] for token endpoint requests, including the applicable authentication methods, apply for the pushed authorization request endpoint as well."

draft-ietf-oauth-par-02 also mentions: 'The "request_uri" MUST be bound to the client that posted the authorization request.' It may be difficult to enforce this requirement without client authentication when initiating PAR.

# Area Affected
The PAR endpoint for CDR 1.3 compliance.

# Change Proposed
Update the CDR specifications so that the PAR endpoint requires Client Authentication.

**Comment by CDR-API-Stream** [comment]
Hi @ttranatping thanks for this. This change request has been addressed in [Decision Proposal 135](https://github.com/ConsumerDataStandardsAustralia/standards/issues/135).

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.5.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134) incorporating this fix. 

This issue will be closed accordingly.
