### ISSUE TITLE
Do we require DH to present Customer ID retrieval when specifying cdr_arrangement_id?

### ISSUE THREAD

**Issue by ttranatping** [ConsumerDataStandardsAustralia/standards-maintenance#280]
# Request For Clarification
When specifying an arrangement_id, it's possible to derive the DH customer ID. 

Question: Is the data holder required to request for the Customer ID if it can derive it from cdr_arrangement_id? I.e. treating the specified cdr_arrangement_id as a "login_hint" value.

I have found through testing that it can be confusing to the customer if they have multiple Customer ID's at the DH. When managing existing arrangements, they may not know which Customer ID to enter in (and it needs to match).

**Comment by spikejump** [comment]
This sound like a use-case where a customer has multiple Customer IDs at the bank.  He/she used one Customer ID to obtain a consent on day 1 then used a different Customer ID on day 2 to obtain another separate consent with the same DR.

When DR presents cdr_arrangement_id back to DH it would help for DH to be able to determine from the cd_arrangement_id which Customer ID the customer used in the first place and so the customer does not provide incorrect Customer ID for the wrong consent.

@ttranatping Is this a scenario that you had in mind?  If so, sounds like a good way for DH to determine this and pre-populate the consent screen.

**Comment by ttranatping** [comment]
Thanks @spikejump - yes that is the scenario I have in mind.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
