### ISSUE TITLE
PAR Endpoint Consumer Validation

### ISSUE THREAD

**Issue by ttranatping** [ConsumerDataStandardsAustralia/standards-maintenance#281]
# Request For Clarification
Relating to a query I raised in [254](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/254).
The PAR endpoint requires the following validation:
- If the “cdr_arrangement_id” is not related to the consumer being authenticated it MUST be rejected

We do not have the ability to request user identification when calling the PAR endpoint so I want to clarify whether consumer is the requesting user or whether it is the requesting client.

Another query is whether any cdr_arrangement_id validation is necessary as it will be performed during authentication.

**Comment by andrewclatham** [comment]
Further to this and in relation to the recent decision proposal #135 https://github.com/ConsumerDataStandardsAustralia/standards/files/4998725/Decision.Proposal.135.-.November.2020.Consent.Obligations.pdf, with respect to Current Recommendation #3 

_"Clarify that a Data Recipient can use PAR to initiate authorisation when a Data Holder supports PAR. It is not limited to the presence of the “cdr_arrangement_id”. In fact, it is encouraged that Data Recipients use PAR when it is supported by a Data Holder. The Data Recipient MAY initiate authorisation by calling using the PAR End Point."_

Can the statement "It is not limited to the presence of the “cdr_arrangement_id”" be interpreted that the following rerquirements for the Pushed Authorisation End Point are being removed given the presence of “cdr_arrangement_id” is not required?
- If the cdr_arrangement_id is not related to the consumer being authenticated it MUST be rejected
- If the cdr_arrangement_id is not related to the Data Holder it MUST be rejected

**Comment by ttranatping** [comment]
Comment here says we'll be moving the cdr_arrangement_id validation to the consent/authentication flow.

https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/254#issuecomment-671738734

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
