### ISSUE TITLE
Product Reference Data - compliance regime should match PDS and advert standards

### ISSUE THREAD

**Issue by aj-mozo** [ConsumerDataStandardsAustralia/standards-maintenance#286]
We believe that compliance standards for Product Reference Data published under CDR should be held to the same standards and compliance regime as data displayed in product disclosure materials and advertisements.

We have seen a number of instances of incorrect or incomplete information in live APIs including:
- missing fees
- mis-characterised fees
- failure to follow DSB standards in the display of rates (#283)
- incorrect 'last updated' dates

We are concerned that data holders may not be applying sufficient rigour to ensuring the CDR data is complete, accurate and not misleading.

We are concerned that there are no mechanism established for the users of PRD to raise data quality issues with data holders.

We are concerned that the compliance framework, regulator ownership and oversight, etc may be unclear.

**Comment by nils-work** [comment]
Hi @aj-mozo 

I do agree with some of your general points about standards, but in terms of the [lastUpdated](https://consumerdatastandardsaustralia.github.io/standards/index.html#tocSbankingproductv3) field, I have interpreted this as being the content of the API, which may not be the same as the published date of a PDS.

That's not to say there aren't any incorrect or invalid values being surfaced, but content of the API that may change without impacting the essence of the product (compared to the PDS date), could be the URIs, description, or cardArt fields for example.

**Comment by nils-work** [comment]
Hi @aj-mozo 

For the compliance-related aspects of this issue, I would refer to the following guidance from the ACCC - 
- [Compliance and Enforcement Policy](https://cdr-support.zendesk.com/hc/en-us/articles/900001932646-Compliance-and-Enforcement-Policy)
- [Clarification of specific Data Quality obligations](https://cdr-support.zendesk.com/hc/en-us/articles/7044968934799-Clarification-of-specific-Data-Quality-obligations)
- [Guidance on lastUpdated and lastUpdateTime fields](https://cdr-support.zendesk.com/hc/en-us/articles/6887000692879-Guidance-on-the-lastUpdated-field)

For issues related to fees and rates, consultation may be continued in -
- [#285 Product Ref Data - leeway within standards makes fee comparison difficult](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/285)
- [#306 Decision Proposal 306 - Updates to Banking Product and Account Detail](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306)

This issue will be closed on 28 July 2023 if there are no further comments or changes to the Standards expected as an outcome.
