### ISSUE TITLE
Why are non-ADI lenders excluded from CDR requirements?

### ISSUE THREAD

**Issue by aj-mozo** [ConsumerDataStandardsAustralia/standards-maintenance#287]
We believe that a CDR regime should apply to all players in a market, in order to maximise the benefits that open data is supposed to deliver. 

CDR in Banking has been applied to ADIs only, but not all lenders in the mortgage and personal loan space are ADIs, or white-label an ADI product. Examples include FirstMac, Athena, RateSetter, Latitude.

We believe a timetable should be established to expand the scope to include all providers of retail banking products.

**Comment by nils-work** [comment]
Hi @aj-mozo 

You may be interested in this consultation - [Consumer Data Right rules and data standards design paper for non-bank lending sector](https://treasury.gov.au/consultation/c2022-341682)

**Comment by nils-work** [comment]
Hi @aj-mozo 

Exposure draft rules to expand the CDR to the non‑bank lenders sector have now been published for consultation -
- [Consumer Data Right rules – expansion to the non-bank lending sector](https://treasury.gov.au/consultation/c2023-434434-expansion)

**Comment by ajduncanson** [comment]
Thanks Nils. I’ll be fascinated to learn why potentially identical products
from different entities would need different standards.

**Comment by nils-work** [comment]
Recent [statements](https://ministers.treasury.gov.au/ministers/stephen-jones-2022/media-releases/albanese-government-reset-consumer-data-right) have indicated an intention to expand CDR to the non-bank lending sector by 2026.
