### ISSUE TITLE
Australian/American spelling of Authorization Code

### ISSUE THREAD

**Issue by cdswizard** [ConsumerDataStandardsAustralia/standards-maintenance#289]
There seems to be a gap and ambiguity in the CDS as to the spelling of Authorisation 
(sometimes with 'S', sometimes with 'Z'). It seems to be used interchangeably.

In general, it isn't an issue - except for the references to the field 'authorization_code', which should 
use the American spelling as per international standards.

However:

1) Under Client Authentication (Data Recipients calling Data Holders), the 'S' spelling is used:
"grant_type: This parameter MUST only be included when invoking the Token End point and MUST be set to authorisation_code or client_credentials."

2) Under Scopes and Claims/ID Token: 
"c_hash: Hash of the authorisation_code value."

But all the non-normative examples detail it as 'authorization_code'.

I suggest the two need to align, at least where the specific parameter name is concerned,
(so when writing about Authorisation Codes, it is fine to use the Australian spelling,
but whenever the actual parameter derived from international standards is concerned - 
it should use the standardised American spelling with a 'z').

**Comment by CDR-API-Stream** [comment]
Hi @cdswizard where the parameter is defined by a normative standard it is correct to use the spelling of the normative standard. In the example above, ``authorization_code`` would be correct.

**Comment by spikejump** [comment]
@CDR-API-Stream Something related to this is the use of /authorize vs /authorise for the Authorisation Endpoint.  Assuming /authorise is valid for the DHs?

**Comment by perlboy** [comment]
> @CDR-API-Stream Something related to this is the use of /authorize vs /authorise for the Authorisation Endpoint. Assuming /authorise is valid for the DHs?

Technically anything advertised in the discovery document is valid. Ie. It could be ```  "authorization_endpoint": "https://www.dh.com.au/tim-buck-two" ``` and be entirely valid.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
