### ISSUE TITLE
Expectations when a consumer closes their account/relationship with an ADR

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#293]
# Request For Clarification

Using the scenario below to understand what is the expectation from Mary (Consumer) and Better Money (ADR)

> Mary uses Better Money’s Budget Tracker (Better Money is an Accredited Data Recipient) as her financial budgeting tool to connect all of her banking data together to understand her expenses and assets across all of her bank accounts. After a couple of months, Mary is not happy with the services of Budget Tracker and closes her account/relationship with them.

**_Note:_** Account here is used in the context of the service provided by the ADR (and not an account that Mary holds with the Data Holders)

What should happen when Mary closes her account?

1.  Mary being a good consumer, **_revokes_** all the consent associated with Better Money and then proceeds to close her account with Better Money.

2. Budget Tracker as an application does the right thing when Mary attempts to terminate the services. They initiate the revocation of consents that they hold for Mary and then close her account. 

3. Mary closes the account with Better Money and then logs into Consumer Dashboard at the DH and notices that Better Money has not revoked the consents. She then proceeds to revoke the consents via the DH's consumer dashboard.

I think all three activities are valid (and can be performed by the respective parties). However I believe "2" MUST be performed by the ADR.  I can't see anything in the rules that talk about this. 

Would love to see what the two ADRs do today (or plan to do)  in this space.

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh, here is the response from the ACCC:

> Rule 4.13 allows a consumer to withdraw consent either via the ADR’s dashboard or an alternative simple method. Closing or deleting/uninstalling an application may not satisfy the intention of rule 4.13 if it is relying on implied withdrawal of consent. Our expectation is that that if the consumer took steps to close their account or end their relationship with the ADR, this should prompt the ADR to advise the consumer that doing so would also withdraw their consents with the ADR to collect and use CDR data and seek the consumer’s confirmation. The ADR could allow the consumer to withdraw their consent as part of the process of the consumer closing their account but this would not be automatic.
>  
> Our expectation of express withdrawal of consent is consistent with the different potential intentions of the consumer in closing an account or withdrawing consent. For example, a consumer may uninstall an application and expect that action to terminate the relationship with the ADR, or a consumer may uninstall an application but wish to continue to use the ADR’s good or service through another channel. In these examples, the consumer’s preference for withdrawal of consent will likely be different and confirmation of the consumer’s intention is required. If as a result of the consumer closing an account or uninstalling an application is that the ADR is no longer providing a good or service to the consumer (under rule 4.3), then the ADR cannot continue to use the data and the data may become redundant.  
>  
> If a consent is still current after a consumer has closed an account or deleted an app, the ADR is subject to the ongoing notification requirements under rule 4.20. As the notification under rule 4.20(3) must be given otherwise than through the consumer dashboard, the consumer would be able to withdraw their consent without having to re-sign up to the ADR’s service.
>  
> We are currently consulting on proposed amendments to the CDR Rules relating to consents to collect and use CDR data. Under the proposed rules, a consumer withdrawing consent to disclose with the data holder will not automatically withdraw the consent for the ADR to continue using the data already collected.

**Comment by bmangalaganesh** [comment]
@CDR-API-Stream Thanks for the clarifications.

By closing an account, I did not mean un-installing an app. I was referring to closing the account as a formal process at the ADR end (just like one would close a bank account).

> If as a result of the consumer closing an account or uninstalling an application is that the ADR is no longer providing a good or service to the consumer (under rule 4.3), then the ADR cannot continue to use the data and the data may become redundant.

I am confused when you say the data may become redundant. I thought the data SHOULD become redundant when I close the account with ADR (as they are not providing any data or service to me as a consumer).

It becomes simple if we mandate the ADRs to revoke all consents (at least provide the option to the consumer as part of the closing process to revoke any associated consents) associated with an account when the account is closed at the ADR end.

**Comment by CDR-API-Stream** [comment]
Community requests for clarification are now responded to via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  Given this question is related to the CDR Rules and interpretation of the rules, it would be best raised via the CDR support portal. If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
