### ISSUE TITLE
JAMS impact on Data Holder Dashboard and Consent flow - requirements clarification 

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#294]
Hi, we are seeking clarification for a number of questions related to JAMS impact on Data Holder Dashboard and Consent flow.

**Question 1** 
What is meant by 'equivalent' in the CDR guidelines when the guidelines state that ... 'the data holder must also provide an equivalent consumer dashboard to the other joint account holder'?

```
Example scenario

Joint Account Holder 1 (JAH1) consents to share his Single account and a Joint account in the consent flow. This action creates an equivalent dashboard for both Joint Account Holders (JAH1 and JAH2).

Since JAH1 & JAH2 are both provided with an 'equivalent' dashboard, Does that mean that JAH2 is going to have visibility over which accounts were consented to in the original consent flow that JAH1 has gone through?

i.e. Does JAH2 have visibility over the the single account of JAH1? or Is JAH2 only provided with a dashboard that gives visibility of ONLY the joint account that was shared by JAH1
```

**Question 2** 
How does the functionality to withdraw authorisation fit in the above scenario?

Should both account holders be provided with the functionality to withdraw authorisation from the Data Holder dashboard, or only the joint account holder who provided the original consent?
If both account holders are to be provided with the functionality to withdraw authorisation from the Data Holder dashboard, how should the withdrawal be treated for a joint account holder who did not provide the original consent - can this account holder withdraw the whole authorisation, or only remove the joint account(s) from the authorisation (that can potentially include other joint account holder's single accounts?

```
Relevant section Pg 118 in CDR guidelines (Joint account - pg's 117-119)

4.4 Consumer dashboard for joint accounts—data holder

If, for a particular joint account with a data holder:

(a)  the election referred to in paragraph 4.2(1)(a) of this Schedule, or paragraph 4.2(2)(b) of this Schedule (if offered by the data holder), has been made; and

(b)  the data holder provides a joint account holder with a consumer dashboard in accordance with subrule 1.15(1) of these rules;

the data holder must also provide an equivalent consumer dashboard to the other joint account holder.

Note: A data holder is required to provide consumer dashboards only if a consumer data request is made by an accredited person. Such requests are made under Part 4 of these rules.

Note: This clause is a civil penalty provision (see rule 9.8).
```
**Question 3**
We understand that if election is removed via JAMS for a joint account that is part of an active data sharing arrangement, the data for this account should not be shared. What does it mean for implementation, specifically what should happen to this account from the below two options:

```
a) The joint account should be removed from the authorisation permanently.
b) The joint account stays in the authorisation, but the data for it is not shared. 
```

What should happen if a customer adds an election back anytime for this joint account while the data sharing arrangement is still in place?

**Question 4**
This question is about JAMS impact on Consent. Assumption that JAH1 was the account holder that went through the consent flow:

- Are both JAHs sharing the same arrangement ID or should they have a separate one although the JAH2 didn’t go through the consent?
- After JAH1 went through the consent flow what if JAH2 wants to go through the consent flow using the same data recipient and share his/her single accounts? Is this allowed as this is considered as a new data sharing arrangement or is this considered as a consent update.

**Comment by CDR-API-Stream** [comment]
Hi @KaterynaShandro thanks for your questions. Responses have been provided by the ACCC.

**Question 1**
Clause 4.4 of Schedule 3 of the rules outlines that JAH2 should have an equivalent consumer dashboard.  Scenario 3 of the recently published [Joint Account Guidance](https://cdr-support.zendesk.com/hc/en-us/articles/900002040606-Joint-Account-Guidance) outlines that the equivalent consumer dashboard needs to only display authorisations relevant to JAH2.

**Question 2**
Scenarios 5 and 6 in the [Joint Account Guidance](https://cdr-support.zendesk.com/hc/en-us/articles/900002040606-Joint-Account-Guidance) address this scenario.

**Question 3**
Scenarios 4 and 7 in the [Joint Account Guidance](https://cdr-support.zendesk.com/hc/en-us/articles/900002040606-Joint-Account-Guidance) address this scenario.

**Question 4**

> Are both JAHs sharing the same arrangement ID or should they have a separate one although the JAH2 didn’t go through the consent?

At this stage, it is the same CDR Arrangement ID representing the sharing arrangement of JAH1.

> After JAH1 went through the consent flow what if JAH2 wants to go through the consent flow using the same data recipient and share his/her single accounts? Is this allowed as this is considered as a new data sharing arrangement or is this considered as a consent update.

Yes this is allowed. JAH2 would establish their own separate consent independent of JAH1. This would have a different CDR Arrangement ID and the joint account, as well as any ‘single accounts’, would need to be independently authorised by JAH2.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
