### ISSUE TITLE
Standards version 1.4.0 Implementation Timelines for second tier ADIs

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards-maintenance#295]
With the release of Standards version 1.4.0 there does not appear to be any timelines referenced for implementation of changes relating to this version for the second tier data holders (ie. non-majors).
Will version 1.4.0 implementations be aligned with those of version 1.3.0 or a future date.
These dates are critical for project planning purposes.
Can we have clarification on the required implementation target dates please?

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
