### ISSUE TITLE
Use of ADR name and logo in CX

### ISSUE THREAD

**Issue by Susan-CDR** [ConsumerDataStandardsAustralia/standards-maintenance#296]
Where the CX designs refer to an ADR name and logo should this be ADR name/logo or where provided - Brand or Software product?   The CX should be consistent from consent through to authorisation establishment and management

**Comment by CDR-CX-Stream** [comment]
Hi @Susan-CDR, this relates to the following issue, which we are working through with the ACCC at the moment: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/222

**Comment by nils-work** [comment]
Hi @Susan-CDR 
There's a similar question and replies in [issue 222](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/222)

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
