### ISSUE TITLE
Reporting invocations and rejections in Get Metrics

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#298]
# Request For Clarification
Related to [issue 271](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/271), a concern with including rejection counts for unauthenticated endpoints (or authenticated, for that matter) in the Get Metrics API, is that these may in some circumstances occur in third-party systems like a CDN/security vendor/edge service.

There may not be an ability to retrieve data for some rejection reasons like DDoS or WAF rules in near-real time.
Is latency of 24 hours+ for some types of data in the Get Metrics API an option in these cases or undesirable/incorrect?

It seems like many Data Holders may currently pass most requests through to origin services where reporting data is more easily accessible, but in some cases successful cache-able responses may be returned from (third-party) edge servers as well - the counts for these may also be difficult to include in the Metrics API in real-time.

Obtaining all counts infrequently (in retrospect) for the six-monthly ACCC reporting form is more feasible.

Could further guidance be provided/sought around the requirements for reporting with regard to different levels of infrastructure, category of API and expectations of timeliness of the data in some different cases?

Any thoughts from Data Holders or other participants on the handling of these issues would be welcome.

Thank you

**Comment by perlboy** [comment]
Specifically regarding DDoS/WAF shutdown, the further question here is if the ACCC is getting rejected what the resolution time would be expected. 24hrs would imply that non-business days would need resolution and thus such a rejection would be classified as an "emergency" out of hours call out.

Given Metrics is 7 day window, suggest "next business day" clarification.

**Comment by nils-work** [comment]
This appears to have been answered on this support article - [CDR Register Metrics Collection](https://cdr-support.zendesk.com/hc/en-us/articles/900005182383-CDR-Register-Metrics-Collection)

> **How old can the data be?**
> The ACCC understands metrics data may be distributed between different systems in a Data Holder’s implementation and that collection and consolidation may be a batch process. This type of process makes it difficult to guarantee the data collected represents the latest and most up to date without detailed coordination of collection. Therefore, it is deemed acceptable for the data presented to be up to 24 hours old.
