### ISSUE TITLE
Inclusion of Card Art

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#3]
# Description
The submission from Visa restated previous feedback that digital card art information should be included in the standards to enable card-centric experiences.

# Area Affected
This change affects the banking API end points and payloads.  Specifically, Account Details may be impacted although it is possible that an alternative end point could address this issue.

# Change Proposed
The submission from Visa stated as follows:
> * Recommend adding option for Card Art support
> * URL for Card Art
> * Card Art Height/Width size in pixel fields

**Comment by CDR-API-Stream** [comment]
In researching this issue it is clear that the relationship between account and card is many to many.

A single account can have multiple cards associated with that account with different card holders.

A single card could be linked to multiple accounts for different payment schemes (ie. credit payment or EFTPOS).

Due to this complexity there are a number of options that can be taken to address this change request.

## Option 1 - Do nothing
In this option we simply leave card art out of the standards and maintain the current standards as they are.

## Option 2 - Single card per account
We add optional fields for a URL to a card image and image size to structures representing an account.  This would impact PRD, account basic and account details structures.

## Option 3 - Cards as a resource
We add a new end point (and security scope) that allows information on cards to be obtained separately with IDs used to link accounts with cards and vice versa.

## Recommendation
The DSB do not recommend option 3 as this would be a substantial extension of the standards and it is unclear as to whether the introduction of cards as a resource in their own right aligns with the rules and the designation instrument.

Option 1 and option 2 are both reasonable approaches.  Option 1 represents zero cost. Option 2 would worth inclusion if the additional fields are considered to add value and the lack of the representation of the many to many relationship is not considered a detractor.

**Comment by commbankoss** [comment]
Commonwealth Bank would like to recommend a 4th option to support card art in the regime. 

We suggest extending the product reference API to include an optional array to represent URLs for product card art. We do not recommend the inclusion of this information at the account basic or detailed structure endpoints, and concur with the stated complexities cited by  Data61. By including card art as a feature in the product reference data we introduce it in the regime without significant change.

Additionally Data61 have previously stated that the payloads have been designed so that there is no dependency on account from product reference data. By creating a resource specific to additional card features we would be creating a product family specific API. Commonwealth Bank prefer to keep the product reference data consolidated as a single end point.

**Comment by CDR-API-Stream** [comment]
Barring additional feedback the DSB would recommend the proposal from CBA be adopted.  Specifically;
- Card art would be added as an optional structure to the PRD end point
- Card art (and cards) will not be added as a resource
- Card art will not be added to the account end points (although this could be considered in the future)

**Comment by da-banking** [comment]
DA is supportive of the recommendation. 

Would the DSB specify the dimensions and required file formats for the card art URLs, and will there be some guidance on image quality and file size?

**Comment by CDR-API-Stream** [comment]
In response to the question above the DSB will additionally recommend:
- Images should be limited to PNG, JPEG or GIF formats
- Images should be proportionally sized according to the standard credit card size defined by ISO/IEC 7810 ID-1
- Images should not be wider that 512 pixels

If additional feedback is provided to amend this or refer to an existing standard then this recommendation may be changed to accommodate this feedback.

**Comment by NationalAustraliaBank** [comment]
NAB supports Option 4 and the justification outlined by commbankoss, https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/3#issuecomment-554121094 (optionally include Card Art in the Product Details endpoint).
