### ISSUE TITLE
Minor errors in v1.4.0 standards release

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#302]
# Description
We have noticed a number of minor documentation errors or formatting inconsistencies in the v1.4.0 release of the data standards. These are:
* In the description for ``id_token_encryption_alg_values_supported`` for [OpenID Provider Configuration End Point](https://consumerdatastandardsaustralia.github.io/standards/#openid-provider-configuration-end-point) the formatting for OIDD and FAPI doesn't follow the typical method to reference normative references.
* In the [release notes for v1.4.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.4.0.html) there are some spelling errors, e.g. "Upated example to include authorisationn step".
* In the [Identifiers and Subject Types](https://consumerdatastandardsaustralia.github.io/standards/#identifiers-and-subject-types) section, the ``cdr_arrangement_id`` appears in the 'Decoded JWT' ID token, but the documentation (e.g. the scopes and claims section) does not appear to indicate that the claim should be provided in the ID token. That the ID token does not include this claim is further supported by [Noting Paper 136](https://github.com/ConsumerDataStandardsAustralia/standards/issues/136).

# Area Affected
* [OpenID Provider Configuration End Point](https://consumerdatastandardsaustralia.github.io/standards/#openid-provider-configuration-end-point) section.
* [Release notes for v1.4.0].(https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.4.0.html)
* [Identifiers and Subject Types](https://consumerdatastandardsaustralia.github.io/standards/#identifiers-and-subject-types) section.

# Change Proposed
* Use e.g. **[FAPI]** rather than **FAPI** as in other parts of the specification.
* Fix the release notes for v1.4.0.
* Remove ``cdr_arrangement_id`` from the example ID token in the identifiers and subject types section.

**Comment by CDR-API-Stream** [comment]
A fix to this errata was included with the v1.5.0 data standards release which was [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/134). 

This issue will be closed accordingly.
