### ISSUE TITLE
Format of cdr_arrangement_id

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#303]
# Request For Clarification
In the latest spec there is only a sentence that describes the format of `cdr_arrangement_id`.  That being

> The CDR Arrangement ID is a string representing a unique sharing arrangement ...

Potentially, the arrangement ID can be an UUID, or it can be an encrypted JWT.  The non-normative examples use UUID.

We'd like to understand whether there is or should be some boundaries placed on the definition of the format.

As an example, if UUID is used then it can be easily used as a key for lookup for consents/arrangements.  However, if a DH supplies an encrypted JWT (so DH can easily look up internal details later) then the length of such ID can be quite big compared to UUID making it unsuitable as a key for lookup.

Some guidance on what ADRs are likely to encounter would help with the design in terms of usage and storage of the ID.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
