### ISSUE TITLE
Should x-fapi* headers be stored or logged?

### ISSUE THREAD

**Issue by miador** [ConsumerDataStandardsAustralia/standards-maintenance#305]
# Request For Clarification
So far, we know that the implementation of `x-fapi*` headers(`x-fapi-interaction-id, x-fapi-auth-date, x-fapi-customer-ip-address`) is necessary for authenticated users. I searched in the CDS webpage but coult not find anything about whether we should store or log the headers. I the [OpenID specs](https://openid.net/specs/openid-financial-api-part-1-wd-01.html) it says:

> shall log the value of x-fapi-interaction-id in the log entry.

Is that what you also want us to do? What exactly you expect to do from us? If you have already clarified that, can you provide a link? 
Regards.
Yusuf

**Comment by bmangalaganesh** [comment]
@miador, there is no explicit statement or requirement from the CDS Specs that states ` x-fapi* ` headers must be logged.

Having said that I honestly don't see any reason why one wouldn't log the relevant info (in particular what I see value in logging both `x-fapi-interaction-id` and `x-fapi-customer-ip-address`).

This helps both from an audit and a troubleshooting perspective (i.e I can only see benefits in logging key information)

BTW, the [FAPI Read profile](https://openid.net/specs/openid-financial-api-part-1-wd-01.html) speaks specifically about only the  `x-fapi-interaction-id` (from a logging perspective)

> 6.2.1
> The resource server with the FAPI endpoints
> shall log the value of x-fapi-interaction-id in the log entry.

**Comment by miador** [comment]
Dear @bmangalaganesh,
Thank you for your answer.
