### ISSUE TITLE
Error response for a Hok Check - 401 or a 403?

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#306]
# Request For Clarification
What is the expectation on the status code  returned if the  Holder of Key (Hok) Check fails?

https://consumerdatastandardsaustralia.github.io/standards/#http-response-codes

| Situation | HTTP Status  |
| --- | --- |
| Authorization header missing or invalid token | 401 Unauthorized  |
| Token has an incorrect scope or a security policy was violated | 403 Forbidden  |

I can see some valid reasoning for both 401 and 403 status codes

**401** - Token is invalid (in the sense it was destined for this caller). The reasoning here is not that validation of token includes - checking whether it is active as well as being associated with the right x5t thumbprint. 

**403** - HoK failure can also be interpreted as a violation of  security policy - hence returning a 403 

What are the big 4 doing in this space and do we have explicit guidance on the status code for HoK failures?

**Comment by NationalAustraliaBank** [comment]
NAB will be returning 401 http status with “Invalid Token”.

**Comment by perlboy** [comment]
As specified in the linked MTLS method: https://tools.ietf.org/id/draft-ietf-oauth-mtls-07.html#SenderConstrainedAccess

> The protected resource MUST obtain the client certificate used for mutual TLS authentication and MUST verify that the certificate matches the certificate associated with the access token. If they do not match, the resource access attempt MUST be rejected with an error per [RFC6750] **using an HTTP 401 status code** and the invalid_token error code.

**Comment by bmangalaganesh** [comment]
Thanks @perlboy for the link to the docs. 

@perlboy thanks for all your answers. You have been awesome with your contributions here and the other forums. 


FYI Located this RFC - [OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens](https://tools.ietf.org/html/rfc8705) 

> The protected resource MUST obtain, from its TLS implementation layer, the client certificate used for mutual TLS and MUST verify that the certificate matches the certificate associated with the access token.  If they do not match, the resource access attempt MUST be rejected with an error, per [RFC6750], using an HTTP 401 status code and the "invalid_token" error code.

**Comment by perlboy** [comment]
@bmangalaganesh Thanks for your kind comments.

Yes, sorry, I linked the draft (which is what is linked in this screenshot from the Standards):
![image](https://user-images.githubusercontent.com/4291448/91791023-6dfe9e80-ec55-11ea-835a-fd1ca38dfb29.png)

But you are correct, RFC8705 is the formalised spec.
