### ISSUE TITLE
Make Metrics API Brand Aware

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#307]
# Description
Currently the Get Metrics API has no brand in the response. We request the addition of brand so that we can report per-brand metrics rather than metrics that are aggregated across brands.

# Area Affected
[Get Metrics](https://consumerdatastandardsaustralia.github.io/standards/#get-metrics)

# Change Proposed
Include brand in Metrics API response so that metrics can be reported by brand.

**Comment by commbankoss** [comment]
Commonwealth Bank has decided to withdraw this change request at this time.

**Comment by alex-histon** [comment]
Hi @CDR-API-Stream , this change request appears to have been withdrawn and closed in Oct 2020, yet it has now been moved to Iteration 5. Can you please clarify?
