### ISSUE TITLE
Seeking clarification on maximum traffic expectations for data holders

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#308]
# Request For Clarification
The [non-functional requirements in the standards](https://consumerdatastandardsaustralia.github.io/standards/#non-functional-requirements) note the following: 

> "Maximum traffic expectations for data holders. Included to ensure there is a ceiling for the amount of traffic that a data holder is expected to service."

We interpret this to mean that these thresholds apply at the Data Holder level, and thus mean the aggregate traffic for all brands of a Data Holder. Can the DSB confirm our interpretation is correct?

**Comment by nils-work** [comment]
This looks similar to an earlier request for clarification - #264

**Comment by CDR-API-Stream** [comment]
This interpretation is incorrect.  In the [CDR Federation](https://consumerdatastandardsaustralia.github.io/standards/#cdr-federation) section of the standards a Data Holder is clarified as being represented by a single entry in the Register:

> For the purposes of this standard a single designated organisation may be represented via the Register as multiple separate Data Holders to support multiple brands or market identities.

This means that each master brand with a separate registration must support the NFRs.

**Comment by neale-morison** [comment]
Draft support article created: https://cdr-support.zendesk.com/hc/en-us/articles/900003286246-Maximum-traffic-for-Data-Holder-brands

**Comment by CDR-API-Stream** [comment]
This issue has been answered and an associated knowledge article created. Accordingly, the issue is closed.
