### ISSUE TITLE
ANZSIC 2006 is specified as String but is a Number

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#31]
# Description
The ANZSIC 2006 `industryCode` field in the standards is specified as a string but is actually a 2-4 digit zero padded number.

# Area Affected
`CommonOrganisation`

# Change Proposed
a) Create a string field format for ANZSIC numbers similar to `MaskedPANString`
b) Change to a `PositiveInteger` on the basis of maintaining a consistent approach to zero padded values as [previously communicated](https://github.com/ConsumerDataStandardsAustralia/standards/issues/79#issuecomment-522355201) for `thoroughfareNumber1` and `thoroughfareNumber2`

**Comment by CDR-API-Stream** [comment]
As stated in the issue description `industryCode` values have leading zeroes so a string is appropriate.

**Comment by perlboy** [comment]
> As stated in the issue description `industryCode` values have leading zeroes so a string is appropriate.

And as stated in the issue description the creation of a String field similar to `MaskedPANString` would be aligned with other behaviours adopted.

**Comment by CDR-API-Stream** [comment]
This is another case of the general issue raised in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/30

This issue will be closed so that the dialogue can be focussed there.

**Comment by commbankoss** [comment]
Commonwealth Bank recommends adding support for multiple versions of the ANZSIC code. Data holders will be using a variety of code version and potentially not supporting the 2006 revisions.
