### ISSUE TITLE
Implement Redirects for old Consumer Data Standards links

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#312]
# Description
There are a significant number of links, as recently as July, within GitHub threads which link to locations on the old consumerdatastandards.org.au website. (for instance https://github.com/ConsumerDataStandardsAustralia/standards/issues/106).

This means that the historical record is now broken and finding responses, even those as recently as a month ago, are difficult.

# Area Affected
Consumer Data Standards website.

# Change Proposed

Implement appropriate redirections on old consumerdatastandards.org.au addresses so that historical back references continue to work.

**Comment by CDR-API-Stream** [comment]
Hi @perlboy URL redirection has been fixed. Historical links should be correctly pointing to the new consumerdatastandards.gov.au website.

**Comment by CDR-API-Stream** [comment]
Since the URL redirection issues have been fixed, this issue is being closed. If you believe the issue has not been fully resolved, please re-open or open a new issue.
