### ISSUE TITLE
FAPI to require PKCE for PAR

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#314]
# Request For Clarification
The FAPI WG, [for a variety of security and client implementation concerns](https://bitbucket.org/openid/fapi/issues/307/fapi-rw-require-pkce-when-using-par), for FAPI1 approaching Final state,  is introducing a requirement for [all PAR requests to be executed using Proof Key for Code Exchange](https://bitbucket.org/openid/fapi/pull-requests/189/fapi-rw-require-pkce-when-using-par/diff) (PKCE). 

The currently listed November obligations required Pushed Authorisation Requests to be implemented by November but the Standards do not utilise PKCE.

As a consequence, CDR implementations implementing PAR will no longer be FAPI compliant.

Could the DSB give guidance on if, and if so when, PKCE support will be introduced into the Standards?

**Comment by jogu** [comment]
It's not answering your question, but I would presume that in general CDR will transition from the FAPI-RW implementers draft onto the shortly-to-be-voted-on final version of FAPI-RW? (Or, put the other way around, it doesn't appear to make medium to long term sense for CDR standards to continue to reference the draft FAPI spec when vendors will presumably coalesce around the final version of the spec.)

**Comment by perlboy** [comment]
See #354.
