### ISSUE TITLE
Unsupported but mandatory enumerations in downgraded payloads

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#317]
# Request For Clarification
`VARIABLE` enumeration was introduced into `BankingProductFeeType` which itself is a mandatory field within `BankingProductDetail`.`fees`. While this is functional for the intended payload version, what is the expected behaviour for older version requests?

That is to say, when presenting older payloads of products which include new enumerations, should the payload:

a) Specify a `null` value for the (mandatory) enumeration, resulting in a technically invalid payload
b) Omit the tuple associated with the impossible field for older payloads? This would be a valid payload but an invalid product description

**Comment by nils-work** [comment]
Hi @perlboy 

I know it's not available in `BankingProductDetailV2`, but if there was an `OTHER` Fee Type, could you automatically convert newer enums to the `OTHER` in older schemas?

`additionalInfo` may still be relevant to support the meaning of any newer types,

This may apply to Constraint, Fee, Discount, Deposit Rate, Lending Rate, and maybe even Product Categories enums.

**Comment by perlboy** [comment]
@nils-work Well, firstly, as you say `OTHER` does not exist in `feeType`. Secondly and not withstanding that the specific request here is about `VARIABLE` which has no `additionalValue` field, `OTHER` does not include an `additionalValue` field so exposing whatever value it is would be invalid.

**Comment by deepsol-oba** [comment]
@CDR-API-Stream - is there a response to this inquiry? Really keen to understand the expected behaviour and how we would compare v2 with v3 for VARIABLE fee types.

**Comment by DG-TMBL** [comment]
This is a good question, logged over 1 month ago with no response. 

TMBL request a response on this as well please.  

@nils-work has just linked to related item #168 where the same question was asked by @Deepsol-oba today - quoted here:

"@CDR-API-Stream - apologies if this has been asked before ... x-v 2 and 3 need to be supported currently concurrently. What is the expected behaviour for v2 if a product has a fee with fee type "VARIABLE". What is the DSB expecting where the VARIABLE fee type for v2 would be represented (as it obviously needs to be as otherwise the data holder would not disclose a fee). Obviously, if v3 is requested, it will show as a VARIABLE fee type, but if v2 is requested?
Hope the question makes sense."

**Comment by perlboy** [comment]
FWIW we have implemented option (a) much to the chagrin of our Conformance suite but in the interest of disclosing a complete view of fees to customers. Given the lack of response and the production release of information now having passed date we request any modification to this behaviour to be a Future Dated Obligation.

**Comment by deepsol-oba** [comment]
@CDR-API-Stream - Dear DBS Team, appreciate that there is quite a lot going on at the moment. From a consumer perspective - it would be very helpful to receive guidance to support the meaningful interpretation of a payload and the subsequent implementation of a comparison. I can only imagine that this specific topic (correct disclosure of fees across versions) is important to the Data Holders in the context of maintaining the data across different versions in their respective systems.

Would it be worthwhile considering - looking at future changes to endpoints - that part of the changelog, the direction - where relevant - is given on how a lower version has to handle the change?
E.g the challenge of maintaining data compatible across versions without having to maintain a v2 and a v3 (in the example of VARIABLE feeType) for the same product. Hope this makes sense.

**Comment by deepsol-oba** [comment]
Just found this on the topic https://cdr-support.zendesk.com/hc/en-us/articles/900003112483-Get-Product-Detail-v2-v3-feeType-impact

suggesting "Use ‘variable’ feeType in version 3 and NOT provide/send this fee in version 2"

**Comment by anzbankau** [comment]
Recognising the general issue as stated in the title, the solution to the specific case of `BankingProductDetail.fees.BankingProductFeeType[VARIABLE]` could be in the historical usage in the absence of the v3 enum i.e. an amount of $0. This has been ANZ's convention for `BankingProductDetail` and `BankingAccountDetail` as an interim solution. While a distinction could not be made between these $0 amounts meaning a calculated/discretionary/pass-through fee and those highlighting the lack of a fee (without referencing `additionalInfo`), this would only be the case until recipients move to v3. We also propose that a fee with $0 amount where no fee exists for 'marketing' purposes should not be permitted in the standards for consistency and complexity of consumption reasons.

**Comment by DG-TMBL** [comment]
> Just found this on the topic https://cdr-support.zendesk.com/hc/en-us/articles/900003112483-Get-Product-Detail-v2-v3-feeType-impact
> 
> suggesting "Use ‘variable’ feeType in version 3 and NOT provide/send this fee in version 2"

That's very helpful (thanks @deepsol-oba), but I wonder if the response is a DSB point of view or an ACCC point of view?  That is, would the ACCC support the omission of At Cost fees in V2 responses, when the rules state that we must include all fees?  Can this be raised at the CDR Implementation Meeting for ACCC confirmation?

Note:  Prior to the announcement of V3, ACCC direction for At Cost Fees was to include them, and to use a "typical" value in the amount field. This direction contradicts the response in the linked ZenDesk article.

**Comment by deepsol-oba** [comment]
@DG-TMBL - I was also wondering if not showing a known fee (disclosed on other channels) would bring a data holder in non-compliance - have my thoughts but won't share as I am qualified to talk about compliance;-) Unfortunately, there hasn't been any further update shared by @CDR-API-Stream on this topic.
Appreciate that the underlying challenge of supporting downgraded payloads - which result in a material difference between the data disclosed in a different version and its potential impact on compliance - won't be an easy one and there is some careful pondering on the topic required.

@CDR-API-Stream - as suggested by @DG-TMBL - maybe something to be discussed in the Implementation Meetings for ACCC confirmation?

**Comment by perlboy** [comment]
It was noted in the implementation call that the solution for implementations was to "Give James a call" because we are "out of time".

This isn't a solution to the request and so I reiterate:
> Given the lack of response and the production release date of information now having past we request any modification to this behaviour to be a Future Dated Obligation.

**Comment by CDR-API-Stream** [comment]
In response to the query initiating this thread the response to the situation described should never be to provide data that makes the payload invalid according to the standards.

Options that are available to the data holder in this circumstance are:

1. Provide a schema compliant response that is as accurate as possible.  In the case of a variable fee this may be achieved by selecting a different fee type and specifying an appropriate indicative amount for the fee.  In many circumstances this will be entirely acceptable.
1. Exclude the record entirely.  In the case of a product fee this is not desirable but, for minor fees that are infrequently applied, it may be considered less inaccurate than choosing a fee type that could be misleading to a customer.

The choice of these options is up to the data holder and should be made considering all regulatory obligations, including those unrelated to the CDR.

Note that the referenced article on the support portal recommended option 2 above due to the contextual information in the original request.  This nuance did not make it into the resulting article which has now been amended.

**Comment by perlboy** [comment]
This does not clarify what obligations Holders, who may be non compliant following this guidance which was given after the initial obligation date, have to rectify their now production deployments.

**Comment by JamesMBligh** [comment]
Hi @perlboy 

> It was noted in the implementation call that the solution for rectification related to implementations was to "Give James a call" because we are "out of time".

I clearly made this offer because we were out of time and It wasn't appropriate to hold the call for the other 160 participants. 
 If you would like to clarify the point you were making that I didn't understand I am still more than happy to chat about it.

-James

**Comment by perlboy** [comment]
> I clearly made this offer because we were out of time and It wasn't appropriate to hold the call for the other 160 participants.
> If you would like to clarify the point you were making that I didn't understand I am still more than happy to chat about it.
> -James

The point has been made above and discussing it with you, a shareholder of a service provider delivering PRD solutions in competition with my organisation seems like a clear conflict of interest.

**Comment by cdradr** [comment]
Can one work for the government defining the standards and financially benefit from selling solutions that offer compliance to these standards?

“Interesting” setup. I want this gig.

**Comment by bazzat** [comment]
@cdradr I feel I need to step in and point, again, to the [Code of Conduct](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-forum-code-of-conduct) for this forum - specifically the bit about “stay on topic”. If you have something to say about the way the DSB is governed there are other, more appropriate, channels you are very welcome to use.
