### ISSUE TITLE
[1.5.0] Missing Changelog Item: (Nearly) All Enumerations Reordered

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#318]
# Description
Every significant enumeration appears to have been reordered resulting in large diffs of changes: https://github.com/bizaio/dsb-standards-upstream/pull/13/files#diff-87f50966f0e729b965babcd60b176019

Alteration of enumeration order has flow on impacts to anyone who relies on an enumeration retaining order rather than storing it's value as a String. 

Further explanation of Enumerated Types can be found on [Wikipedia](https://en.wikipedia.org/wiki/Enumerated_type#:~:text=In%20computer%20programming%2C%20an%20enumerated,or%20enumerators%20of%20the%20type.) and this line in particular is worth highlighting to the DSB: _"In some languages, the declaration of an enumerated type also intentionally defines an ordering of its members; in others, the enumerators are unordered; in others still, an implicit ordering arises from the compiler concretely representing enumerators as integers."_

# Area Affected

Essentially all enumerations of significance, in particular those used in Product Data.

# Change Proposed

Document that all enumerations were reordered in what appears a non-determinant way ("sort of" alphabetically doesn't cut it).

**Comment by perlboy** [comment]
It is noted that in 1.5.1 the enumerations were reordered again.

**Comment by CDR-API-Stream** [comment]
Hi @perlboy whilst enums were re-ordered they weren't strictly alphabetically ordered, they were ordered for human readability. If adopting a strict alphabetical or natural sort order is preferred this can be considered.

The enumerated values themselves are textual values and the index of each value in an an array shouldn't be relied upon for inferring the enum value.

**Comment by perlboy** [comment]
> Hi @perlboy whilst enums were re-ordered they weren't strictly alphabetically ordered, they were ordered for human readability. If adopting a strict alphabetical or natural sort order is preferred this can be considered.

This is a highly interpretive assessment of ordering and there was no request to reorder them. What grounds did the DSB have for doing so? Yes, a strict ordering would be preferred.

> The enumerated values themselves are textual values and the index of each value in an an array shouldn't be relied upon for inferring the enum value.

I don't think the DSB should be dictating what an implementer relies upon and at a bare minimum, as noted in the linked diff, this resulted in a large diff of no change.

The point being made here is that the DSB decided not only that they needed to be reordered without a request to do so but indeed went and ordered them according to a highly subjective way. Why isn't the DSB following it's own change process?

**Comment by deepsol-oba** [comment]
@perlboy, @CDR-API-Stream - hope I am not getting myself in trouble here, but it seems we are looking at two set of requirements - human-readable vs machine comparable.
Would it make sense to consider adding to the HTML page machine-readable identifiers to elements - which would allow to find and compare items the tool needs to compare?
Example: This would allow the tool to find all the attributes for a schema and sort them as needed prior to comparing without compromising the need to make it readable for humans (for which the standards are targeted for - as I understand it).

That would also have the benefit that it can be coupled up checking changes to swagger.

Ignore my comment if you feel it is non-relevant or is missing the pint.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair for inclusion in v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). A change to the data standards was recommended.

This issue will be closed accordingly.
