### ISSUE TITLE
[1.5.0] Missing Changelog Item: Maturity Instructions

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#319]
# Description
`BankingTermDepositAccount` [added an enumeration](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtermdepositaccount) of `HOLD_ON_MATURITY` to the maturity instructions but this is not documented in the changelog.

In addition, the version of the payload was not incremented.

# Area Affected
Change Log, Payload Version
# Change Proposed
**At least** add it to the changelog. The errors in the changelog are only highlighting further how unreliable relying on it is.

Increment Versions: Multiple changes have occurred which will not only trigger the issue outlined in #317 but also means recipients will now be likely to receive enumerations they do not support within payloads that were previously stable.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair for inclusion in v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). A change to the data standards was recommended.

This issue will be closed accordingly.
