### ISSUE TITLE
DepositRateType - Valid list of enumerations

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#321]
# Request For Clarification

Looking at the [enumeration for](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductdepositrate) "_depositratetype_" 

![image](https://user-images.githubusercontent.com/12740620/93837243-b3e4da80-fcc8-11ea-9ddc-f19192957de1.png)

The description talks about **_base_**, bonus etc however the enumeration does not have a value of **base**.

![image](https://user-images.githubusercontent.com/12740620/93837220-a62f5500-fcc8-11ea-81d4-cad8b1548936.png)

Assuming this is a typo error and that base is not an enumerated value for the depositratetype.

Appreciate some clarifications.

**Comment by CDR-API-Stream** [comment]
This is not a typo.  The expectation is that the base rate for an account would be of type FIXED, FLOATING, INTRODUCTORY, MARKET_LINKED or VARIABLE.

A BONUS or BUNDLE_BONUS could then be articulated as a discount to the applicable base rate if the stated criteria are met.
