### ISSUE TITLE
Incorrect x-fapi-auth_date Example

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#322]
# Request to Update Incorrect Example

Based on #138 it is clear that the correct date format for `x-fapi-auth-date` is HTTP-date.  However, in the latest spec the example in the section https://consumerdatastandardsaustralia.github.io/standards/#http-headers still has incorrect date format.  In fact, the example also shows incorrect header for `x-fapi-auth-date`.

> x-fapi-auth_date : 2020-01-16 16:50:15.507399

Should be like

`x-fapi-auth_date : Thu, 16 Jan 2020 16:50:15 GMT`

**Comment by CDR-API-Stream** [comment]
Thanks @jogu, this issue will be fixed in the next version of the standards.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair for inclusion in v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). A change to the data standards was recommended.

This issue will be closed accordingly.
