### ISSUE TITLE
Is the joint account consent authorization driven off by how the account is set up on the data holder side? 

### ISSUE THREAD

**Issue by Hope1914** [ConsumerDataStandardsAustralia/standards-maintenance#323]
Is the joint account authorization, in regards to whether the joint account holders need to provide joint authorization or they can provide individual authorization, driven off how the account is set up on the data holder side? For example, if the account has been set up as  a 2 to sign, does the CDR authorization need to honor that arrangement or can the members set up as a separate arrangement for the purposes of CDR?

**Comment by nils-work** [comment]
Hi @Hope1914 

There was a similar question and reply on a previous call, [noted here](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Meeting-Notes-(16th-of-July-2020)#user-content-actions:~:text=Existing%20%E2%80%98either%20to%20sign%E2%80%99%20or%20%E2%80%98both%20to%20sign%E2%80%99%20may%20not%20be%20used%20to%20meet%20the%20JAMS%20election%20requirements.).

Search for this text - `‘either to sign’ or ‘both to sign’`

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
