### ISSUE TITLE
Changes to Standards Iteration Process

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#328]
# Description

The way changes to the Standards are proposed, evaluated, executed and released results in a number of issues for participants including:
1) Significant resourcing impact analysing new releases due to 100,000+ line differentials
2) Tickets which are [abandoned](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/56) or lost with no progress or responses leading requester's to close them because they wish to remain organised themselves
3) "Maintenance Iterations" which [overlap](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/projects/4) [resulting](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/projects/4) in unknown state
4) Tickets in Project View which enter a status which [is confusing](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/projects/4)g (ie. "In Progress" when a maintenance iteration hasn't started)
5) Changes being executed which [are the opposite](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/320) of the consultation and even the decision proposal
6) Changes being executed within internal repositories [which reference internal](https://github.com/ConsumerDataStandardsAustralia/standards/commit/12adc95888985ad8180727310cd1f795579ce245) non public issues and are not exposed until release
6) Roll backs that involve [multiple](https://github.com/ConsumerDataStandardsAustralia/standards/commit/4f8db465f6a44970340f5858d63ff5c1cf0f1556) [rereleases](https://github.com/ConsumerDataStandardsAustralia/standards/commit/23dae86cb62c48fde1cb1e6cd4a102a55f8e6a85) rather than clearly traceable source code reverts
7) [Non repeatable retrofitting](https://github.com/ConsumerDataStandardsAustralia/standards/commit/9bb3c82a89a0444f700666952605716db67a46c1) of artefacts to avoid rereleases
8) [Undocumented changes](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/318) which are further reverted in undocumented ways
9) Backporting of changes to existing payload versions with limited prior warning and ambiguous reasoning

# Area Affected

Fundamentally the issues highlighted above are a combination of diverting away from industry standard methods of project management, a lack of sufficient change and release management systems, a lack of appropriate source control methods coupled with an apparent lack of overall governance and oversight on the release process.

# Change Proposed

There are a number of changes to the release process which would significantly alleviate the issues highlighted above

1) Repeating #56: Adopt the use of CI/CD for releases such that the published versions including the archives occurs from git tags and branches specified in source with no output data committed in branches other than the designated place github pages is served from. This could be coupled with a version selector allowing for hotfix/feature branches and resolves (1)
2) Use a single Project Board that has a continuous backlog rather than creating a new one per iteration. GitHub Project's supports multiple lists within a board and beyond trying to hide the growing backlog separating per sprint is only hiding this reality. This would assist with (2), (3), (4) especially if coupled with a typical agile release strategy.
3) Include a diff specific to the issue at hand inside the "decision proposal" effectively making this document analogous to a Change Request. This would mean that a feature branch could be bound to a DP and the actioned change would be aligned with the developed feature. This would resolved (5) and would be trivial if an appropriate branch model is adopted.
4) Adopt a [git-flow or similar model](https://nvie.com/posts/a-successful-git-branching-model/) (I'd recommend Git Flow as CDR has multiple versions in the wild) that would allow for historical versions and feature branches to be seen. 
5) Couple the adoption of git-flow with the use of feature branches can efficiently assess the actual proposed change on the Standard without impacting the published state. This would also facilitate rollbacks being specific to a feature resolving (6) and (7) and, with branch protection enabled on `master` resolves (8). Additionally the issue raised in (9) would at least be made visible through this process as what is reviewed by implementers and what goes live is known.
6) Abandon the internal `standards-staging` repository that no-one except the government sees. In the early days this repository was a stop gap because certain individuals did not want the public to have visibility of issues other individuals were raising, now it is confusing external implementer's who must fish through lagged commit histories. Internal review is still entirely possible through the use of feature branches.
7) Clearly document a Change Release process, aka "implement governance aligned with the industries". This has been raised numerous times with various answers from government representatives stating either "it is the same as always" or "it is up to the Chair" which is ironic because the current maintenance iteration was defined as a trial using a [Noting Paper](https://github.com/ConsumerDataStandardsAustralia/standards/issues/50) that became the defacto and changes proposed to the Chair have not being accurately delivered or decision proposals historically have not had visibility until post approval leading to errors and rework.

Finally, as a footnote more than anything, stop reinventing the wheel. I've personally raised this a number of times and have never received any reasonable answer as to why the government deems it necessary to redefine change release processes that are proven to work in very large organisations.

**Comment by CDR-API-Stream** [comment]
Several changes have been made, or are planned to be made for v1.7.0, based on feedback to this issue and other similar issues related to the DSB's publishing processes:  
1. The DSB has recently published a noting paper regarding DSB's standards promotion process. The DSB is now trialling a new staging area for standards so that changes can be drafted before they are formally adopted into the Consumer Data Standards.
2. The DSB is also reviewing its publishing tools and has recently trialled using redoc for publication of standards.
3. The DSB has launched a more interactive site for Consumer Experience guidelines: https://www.notion.so/Consumer-Experience-Standards-and-Guidelines-dffe42d39d4942c5b4f2c7612ba4f6e0.
4. The DSB has ported the Consumer Experience Data Standards from the previous PDF format
to the Technical Data Standards page to be released as part of v1.7.0
5. The Future Dated Obligations table in the standards is being enhanced based on feedback
arising from Change Request #315.

This change request will be kept open so that further feedback can be tracked. The original poster may wish to close this issue or create a separate issue that specifically targets other areas for consideration as they see fit.

**Comment by perlboy** [comment]
None of these changes are aligned with the change request.

**Comment by CDR-API-Stream** [comment]
As stated in the past a number of times, the DSB internal process for developing and publishing the standards are not part of the standards themselves.  While we welcome feedback, and take it into account, these processes are internal to the DSB and not subject to formal consultation.  In developing these processes we have to take into account the needs of multiple community stakeholders and, more importantly, the capacity of the DSB team that has to operate these processes.

We make this distinction between formal consultations leading to standards decisions and informal consultations on non-standards related issues when we initiate our consultation threads.  Specifically, we make a clear separation between "Decision" documents, which are formal and may lead to a binding obligation, and "Noting" documents that are for informational purposes and will not result in a binding obligation.

We will take your feedback seriously, as we always do, but we are unlikely to simply adopt your suggestions verbatim, as we have not done in the past.  Also, we will not consider this a standards change request.  The avenues for this type of feedback that we suggest is via the standards staging repo or via the iteration retrospective calls that we hold on a regular basis.
