### ISSUE TITLE
Alternative channels to withdraw authorisation

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#329]
**1. Questions about rule 4.25 Withdrawal of authorisation to disclose CDR data and notification in CDR rules.**

We noticed that in CDR rules PDF file published on ACCC website on 06 Mar 2020 the point (1) from rule 4.25 reads as follows:

4.25 Withdrawal of authorisation to disclose CDR data and notification
(1) The CDR consumer who gave, to a data holder, an authorisation to disclose particular CDR data to an accredited person may withdraw the authorisation at any time:
(a) by communicating the withdrawal to the data holder in writing; or
(b) by using the data holder’s consumer dashboard.

On the Australian Government Federal Register of Legislation website there is a different version of the rules that has the below version of  the point (1) from rule 4.25:

4.25  Withdrawal of authorisation to disclose CDR data and notification
(1)  The CDR consumer who gave, to a data holder, an authorisation to disclose particular CDR data to an accredited person may withdraw the authorisation at any time:
(a)  by using the data holder’s consumer dashboard; or
(b)  by using a simple alternative method of communication to be made available by the data holder for that purpose.

Question 1. Which is the latest version of the rules that we should follow?
Question 2. What can be the options of a simple alternative method of communication?

**2. We understand that according to the rule 4.25, the Data Holder has to provide an alternative method to withdraw authorisation. Is there a similar requirements for Joint Account Management Service, such as to provide an alternative way to elect or remove election for a joint account to be available for data sharing? Or can Joint Account Management Service be online only?**

**Comment by bmangalaganesh** [comment]
@KaterynaShandro 

With respect to Q1:

As of today (Oct 11, 2020) this is the [document that is in force](https://www.legislation.gov.au/Details/F2020C00554)

![image](https://user-images.githubusercontent.com/12740620/95708939-4e718180-0ca9-11eb-8005-3ba4e6242884.png).

The version prior to that was dated 6th Feb 2020 (don't recall a published version in March 2020).


With respect to Q2:
There is a support ticket in this space in the support portal -[ TIcket 202](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-(8th-of-October-2020)) and the Rules team will respond on this soon( it was discussed last week).

**Comment by bmangalaganesh** [comment]
During the CDR implementation call, there was a discussion about this and I thought this image would be helpful to the community.

The version/document with the text "In force - Latest Version" is the version that can and should be relied on for the correct/latest information.

Each version of these Rules document (Competition and Consumer (Consumer Data Right) Rules 2020) has a text (refer to picture below) that provides information about the state of that document

![image](https://user-images.githubusercontent.com/12740620/97372031-bdd0ad80-1906-11eb-92bb-7118f05492bd.png)

**Comment by CDR-API-Stream** [comment]
This query appears to have been responded to by the community.

If further clarification is sought it is recommended to raise an issue on the [CDR Support Portal](http://cdr-support.zendesk.com/) so that a response from both the ACCC and the DSB can be provided.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and an associated knowledge article created: https://cdr-support.zendesk.com/hc/en-us/articles/900004849223-Alternative-channels-to-withdraw-authorisation. Accordingly, the issue is closed.
