### ISSUE TITLE
Remove x-cds-subject header

### ISSUE THREAD

**Issue by jogu** [ConsumerDataStandardsAustralia/standards-maintenance#33]
As discussed in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/13 the x-cds-subject header:

1) Serves no useful purpose as it is not included in unattended calls, so the iDP cannot rely on it's presence to perform lookups (meaning all the information has to be accessible via the access token, and if the information is available via the access token there's no gain from including it in a header)

2) Serves no useful purpose as it is defined as replaying information the iDP already has (i.e. the sub from the id_token the idp issued), and hence cannot be a useful input into fraud detection

Hence I'd strongly recommend removing it. It's a significant deviation from the underlying specs, and has the potential to introduce new flaws and hence Australia would not be benefiting from the significant amount of formal security analysis that has already been done on OAuth2, OpenID Connect and FAPI specifications.

This is particularly there doesn't seem to be any **valid** documented reason for diverging from the standards and introducing extra work for data recipients to do - the clear model in OAuth2 is that the access token is the method to communicate from the OAuth client to the resource server, and that is how other ecosystems do it. There is no reason I can see to add this extra element.

**Comment by CDR-API-Stream** [comment]
This issue has been brought into the iteration as it is continuation of a clarification issue that was previously prioritised.

As the addition of this header was requested by a data holder feedback from the data holder community is requested.  In the absence of a stated need from the data holder community the DSB recommendation would likely be to remove the requirement for this header from the standard.

**Comment by jogu** [comment]
Thanks! Interestingly it seems something got lost between the original request and the text that actually made it into the standard - I think this shows the importance of the requestors of changes reviewing the final text of a proposed change before it's put into a published standard.

**Comment by CDR-API-Stream** [comment]
There has been no data holder feedback so the recommendation will be to remove the x-cds-subject header.
