### ISSUE TITLE
Request for clarification for Vulnerable customers requirement 

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#330]
In CDR rule 4.6  Exception to rule 7.9―physical or financial harm or abuse it specifies that:
```
Rule 7.9 of these rules does not apply if:
(a)  a data holder discloses CDR data to an accredited person as a result of a consumer data request that was made by a joint account holder of a joint account; and
(b)  the data holder considers it necessary, in order to prevent physical or financial harm or abuse, not to update the consumer dashboard of the other joint account holder to indicate the matters referred to in paragraphs 7.9(a), (b) and (c).
```

Will you be able to provide guidance on expected implementation of the above rule and possible scenarios?

As the point (b) in the 4.6 rule specifies, it’s for Data Holder consideration to update or not to update the dashboard of the second account holder. Does it mean that the decision needs to be taken on a case by case basis after speaking to a customer to clarify their situation? Or can the option to update/not update other joint account holder’s Dashboard be provided to all joint account holders during Consent flow?

**Scenario:** A customer in an abusive relationship wants to share data for his/her joint account with a 3rd party and doesn’t want the second joint account holder (the abuser) to find out about this data sharing arrangement.

**Implementation options:**

**Option 1**
Before starting the consent flow, vulnerable customer gets in touch with the Data Holder and explains his/her situation. If Data Holder considers it necessary, Data Holder marks the customer as ‘vulnerable’ which results in any Data Sharing arrangements this customer establishes for the joint accounts not to be visible for the second account holder(s). 
**Option 2**
Before starting the consent flow, vulnerable customer gets in touch with the Data Holder and explains his/her situation. If Data Holder considers it necessary, Data Holder marks the customer as ‘vulnerable’ which results in giving this customer choice to have some of Data Sharing arrangements this customer establishes for the joint account not to be visible for the second account holder(s). In this case, a functionality will be added inside Consent flow to select which account to show or not to show on other joint account holder’s dashboard. 
**Option 3**
Before starting the consent flow, vulnerable customer gets in touch with the Data Holder and explains his/her situation. If Data Holder considers it necessary, Data Holder marks the joint account(s) affected as ‘vulnerable’ which results in any Data Sharing arrangements this customer establishes for the joint account not to be visible for the second account holder(s). 
**Option 4**
For all joint account holders, during the Consent flow the option is displayed to update other joint account holder’s Dashboard or not (in this case, this option is provided to all joint account holders and Data Holder won’t be participating in determining if the customer is vulnerable or not).

Can you please provide guidance, which of implementation options is in line with the rules, or if there’s some other way to meet this requirement.

**Comment by bmangalaganesh** [comment]
@KaterynaShandro 

Assuming in all the options that you have presented, election(s)  have been made (by both joint account holders) which makes the account eligible for CDR Consent.

Within the CDR rules (based on my understanding) you can't achieve what you are after.

If the Data Holder marks an account and/or customer as "vulnerable" then a CDR request is declined (atleast the DH has the authority within the rules to decline those requests).

What you are after in your scenario is to prevent the "abusive partner"  from having visibility to a sharing arrangement that the customer gets into with an ADR.

How does the customer convince the abusive partner to make an election in the first place?

**Comment by CDR-API-Stream** [comment]
This would appear to be a request for clarification of the CDR rules.  If this is the case it can't be addressed in this forum which is focussed on the standards.

It would be appreciated if you could raise this issue via the [CDR Support Portal](http://cdr-support.zendesk.com/) so that a response from the ACCC can be provided.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and an associated knowledge article created: https://cdr-support.zendesk.com/hc/en-us/articles/900004849223-Alternative-channels-to-withdraw-authorisation. Accordingly, the issue is closed.
