### ISSUE TITLE
Clarification on OIDC endpoint

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#332]
Posting a question raised on today's DSB call that did not get answered:

The response of OIDC endpoint " GET /.well-known/openid-configuration HTTP/1.1 " provides information about different API URIs like authorise, token, introspection end point URIs. Some of the URIs like /authorise needs some request parameters to be passed by the ADR.  For example, 

GET /authorise?   response_type=code%20id_token&client_id=12345&
   scope=openid%20profile%20bank:accounts.basic:read%20bank:accounts.detail:read&
   request=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEyMyJ9.ey ...

The non-normative example for well-known configuration endpoint  from the standards website shows authorise  URIs like 
"authorization_endpoint" : "http://www DH.com.au/authorise"
1) How does an ADR know what additional parameters to be passed in /authorise endpoint ?
2) Can a DH add some custom parameters in request in addition to standard parameters(client_id, response_type)

**Comment by jogu** [comment]
> How does an ADR know what additional parameters to be passed in /authorise endpoint ?

I'm not sure if I'm understanding the question. The answer seems to be that the ADR should follow the specification and add the parameters the specification requirements, in this case:

https://consumerdatastandardsaustralia.github.io/standards/#authentication-flows

(and the underlying specifications it references, like FAPI, OpenID Connect and OAuth2.)

> Can a DH add some custom parameters in request in addition to standard parameters(client_id, response_type)

Not really. The Data Holders are required to accept requests that are compliant with the standards and can't add on random extra requirements to pass extra parameters.

Unless you mean can the entry in the well-known be:

"authorization_endpoint" : "http://www DH.com.au/authorise?foo=bar"

in which case, yes, it can, that's allowed by https://tools.ietf.org/html/rfc6749#section-3.1

**Comment by CDR-API-Stream** [comment]
The specification of the authorisation end point is deferred to the normative standard unless otherwise specified.  In this context the DSB would agree with the response from @jogu.

**Comment by neale-morison** [comment]
FAQ available for review by Agents and Admins only: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/332

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
