### ISSUE TITLE
Holder Dashboard Account Access Recipient Notification

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#333]
# Request For Clarification
In #167 a question was raised regarding the modification of the accounts of a consent:
> Question: Can a consumer change which accounts relate to consent in the Data Holder Authorisation Dashboard?
>
> Answer: Yes they could. Accounts are associated to consent but not part of the immutable consent contract. Whether a data holder provides a service in their dashboard that allows consumers to choose which accounts are being shared as part of an existing sharing agreement is up to the data holder. This is within the competitive space of the CDR.

In this scenario there does not appear to be a prescribed method of notifying the recipient of this change. Presumably it is expected that such changes should trigger data deletion on the recipient side of information they no longer have access to?

While it _may_ be possible to determine the loss of account access through _Get Accounts_ this **may not** be possible in situations where _Get Accounts_ scope has not been granted. Consequently, how is a Data Recipient notified of this change and/or how should they detect that they have lost access to an account?

**Comment by nils-work** [comment]
Hi @perlboy 
You may have already seen it, but there's more detail in #126

**Comment by perlboy** [comment]
@nils-work While the question raised here is about what to do if _Get Accounts_ is not available (which is what was recommended in #126) it's also more broadly around whether a Holder Dashboard change represents a _replacement_ of a sharing arrangement, which is what it would be in a reauthorise and/or recipient initiate update from our read of #272.

**Comment by CDR-API-Stream** [comment]
There is no prescribed mechanism to actively communicate a change as described in the query, however, the ADR would be able to identify the change through the account list API or a 422 response from an account specific API.

It should be noted that the removal of an account from a consent does not change the consent so no deletion/de-identification process should be triggered.

**Comment by perlboy** [comment]
See #354.
