### ISSUE TITLE
Arrangement Endpoint Delete on ADR Initiated Revocation?

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#334]
# Request For Clarification
Not sure if this has been asked however in the situation where the ADR issues a token revocation request to the Holder, is the expectation that this call will trigger an arrangement delete request back to the ADR?

Vice versa, if a Consumer cancels an arrangement in the Holder's dashboard this should trigger a revocation request to the Recipient. Should the Recipient also initiate a token revocation back to the Holder?

**Comment by CDR-API-Stream** [comment]
A revocation request should only be triggered in circumstances where the other party would otherwise be unaware of the revocation.  For instance, a revocation via the DH's dashboard would trigger a revocation call to the ADR.

**Comment by perlboy** [comment]
See #354.
