### ISSUE TITLE
x-v for ResponseErrorList

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#335]
# Request For Clarification
When `ResponseErrorList` is produced (which presumably is v1 although it's unversioned), what should the `x-v` of the response be populated with?

Ie. If a call is made to an endpoint of `x-v`=3, `x-min-v`=2 but an error occurs should the response be `x-v`=1 ?

**Comment by bmangalaganesh** [comment]
@perlboy I am trying to walk-through this using product API as an example  (to see if I am following your question)

![image](https://user-images.githubusercontent.com/12740620/95704479-a9e94280-0c9c-11eb-942b-9bf00de3a8d9.png)

Depending on where the error occurs the x-v response header could be different.

(A) possibly return `x-v`=1 

(B) request reached a specific implementation version so return `x-v`=2 (returning this for both errors as well as 200 OK responses) 

(C) request reached a specific implementation version so return `x-v`=3 (returning this for both errors as well as 200 OK responses) 

The question in my mind is should the ADR **_infer_** anything from the `x-v` (in the response header) in an error scenario?

**Comment by perlboy** [comment]
@bmangalaganesh Essentially it comes down to whether an ErrorListResponse is globally versioned or versioned per endpoint. Globally Versioned would mean `x-v` represents the error response version regardless of the endpoint version, versioned per endpoint would mean that the _"standardised"_ error responses are actually per endpoint which, in the event of the global error responses being changed (as foreshadowed in https://github.com/ConsumerDataStandardsAustralia/standards/issues/120) then every endpoint version would be incremented.

**Comment by CDR-API-Stream** [comment]
Currently there is no specific answer to this question in the standards.  The intention of version negotiation is to respond with a successful response in one of the versions requested.  The idea of versioning the error response is worthy of investigation but is not a topic that has previously been canvassed.

If a specific approach is preferred then a change request would be welcome.

**Comment by perlboy** [comment]
See #354.
