### ISSUE TITLE
seeking clarification on Payee type and UType in PayeeDatail response

### ISSUE THREAD

**Issue by SongqingGu** [ConsumerDataStandardsAustralia/standards-maintenance#336]
# Request For Clarification
Our team is seeking clarification on Payee type and UType in PayeeDatail response. The response schema specifies three possible values, Domestic, Biller and International for payee type, which are mutually exclusive if my understanding is right. But sample response message gives us a different view, shown as below: 
{
"payeeId": "string",
"nickname": "string",
"description": "string",
"type": "BILLER",
"creationDate": "string",
"payeeUType": "domestic",
"domestic": {
"payeeAccountUType": "account",
"account": {
"accountName": "string",
"bsb": "string",
"accountNumber": "string"
},
.....
},
"biller": {
"billerCode": "string",
"crn": "string",
"billerName": "string"
},
"international": {
"beneficiaryDetails": {
"name": "string",
"country": "string",
"message": "string"
},
....
}
}

There are 2 questions around payee type:

1. what is the rationale to have pay type and UType at the same time? it looks both of them tell the same thing.
2. the sample payeeDetail response message as shown above, shows type of "Biller" and payUType of "domestic", followed by all three options. The combination is right? or it should be one type, one payUType and one corresponding detailed section?

**Comment by bmangalaganesh** [comment]
@SongqingGu can you update the title of this issue with a quick summary of your query instead of Brief summary of question]?

**Comment by SongqingGu** [comment]
Looks to me the sample response data is  more on technical explanation to list all possible values by one goal. but in the same time it creates some confusion from business perspective. 
If this questions could be  answered as early as possible that will be much appreciated.  Dev team is waiting for the clarification to move forwards.

**Comment by perlboy** [comment]
@SongqingGu uType's are explained in payload conventions but in summary, yes, there is only expected to be one object provided and this is designated by `uType`. The overlap of payeeType has been noted but is an artefact of `Payee` vs. `PayeeDetail` and in some respects may not explicitly be the same (although just happens to be here).

![image](https://user-images.githubusercontent.com/4291448/96942195-cba5bd80-1517-11eb-944f-2a82c1465eab.png)

**Comment by nils-work** [comment]
Hi @SongqingGu 

The `type` property provides the [Payee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayee) type -
`"type": "BILLER"`

The `payeeUType` provides a reference to the respective [Payee Detail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayeedetail) object -
`"payeeUType": "biller"`

You are correct, they should have the same value.

I think a minor update to the documentation (to make those values match) could remove some of the confusion, but the [Payee Detail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayeedetail) example would still show all possible objects.

As the three 'type' objects in the Payee Detail are conditional, only the object corresponding to the `payeeUType` is required.

**Comment by CDR-API-Stream** [comment]
@perlboy's response on this query is correct.

It should be noted that the `type` field is a standard enum (so the values are uppercase) and the `payeeUType` field is a union discriminator so the value matches the field name of the object that is present (so that the value can be used to do a field reference in the client application).  This means that the two fields have entirely separate conceptual meanings and the value `BILLER` and `biller` should not be considered equivalent in any way.

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 

I understand that these properties have separate purposes, but could you clarify why there may be a payee of one type with its related payeeUType object as another? 

Would it seem valid to present for a [single payee](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingpayeedetail), for example -

`"type": "DOMESTIC"`
`"payeeUType": "international"` 

I would think that stating a payee as domestic, while providing international bank details would erroneous.

**Comment by CDR-API-Stream** [comment]
Hi Nils, thanks for the follow up.

In general you are correct.  It would represent inconsistent data if the types did not align, however, this isn't the case in all situations.  For instance, we have had feedback from some banks that they offer a service whereby an international payment can be proxied via a domestic account number in which case it would be valid to label the payee as INTERNATIONAL/domestic.

Also the model allows for future extension.  For instance, at the moment a BILLER type implies a BPay payee but there are other possible bill paying services that may be represented in the future if broad-based adoption occurs.  It also allows for multiple payee structures to be used like we do for addresses (for instance, we could have a `domesticSimple` vs `domesticComplex`)

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
