### ISSUE TITLE
Clarification on Paginated Responses to POST Requests (Get Balances for Specific Accounts)

### ISSUE THREAD

**Issue by d11wtq** [ConsumerDataStandardsAustralia/standards-maintenance#337]
# Request For Clarification

https://consumerdatastandardsaustralia.github.io/standards/#get-balances-for-specific-accounts

On the endpoint `POST /banking/accounts/balances`, a request is received with a list of `accountIds` present in the payload. The response includes `LinksPaginated`, which implies it must therefore also be possible to `GET` balances for specific accounts.

Is it expected that:

  1. The client follows the pagination links by re-submitting the same POST but to the new URL; or
  2. The server implements a `GET`-compatible variant of the endpoint and refers to this in the links?

**Comment by nils-work** [comment]
Hi @d11wtq 

This question was asked recently on the implementation call - the answer was equivalent to your option 1 - that the client would re-submit the initial POST body to the pagination URLs and the Data Holder would respond with the respective page of results according to the query parameters (on the pagination URLs.)

**Comment by d11wtq** [comment]
@nils-work Thanks, that makes sense. It's probably worth something added to the section on Pagination that explicitly states how pagination works on POST requests.
