### ISSUE TITLE
Claims returned within ID_Token and the updated_at claim

### ISSUE THREAD

**Issue by sona-dhillon** [ConsumerDataStandardsAustralia/standards-maintenance#340]
# Request For Clarification
Hi 

We had a few questions around the requirements for the profile-related claims (name, given_name, family_name and updated_at) , listed at https://consumerdatastandardsaustralia.github.io/standards/#scopes-and-claims

1.The above are in the must-be supported list
Question: Based on the guidance on the ID_Token under Tokens, The ID Token returned from the Authorisation End Point MUST NOT contain any Personal Information (PII) claims.

Are we correct in inferring that the profile-related claims must be returned at both userinfo endpoint, 
as well, as in the ID_Token returned as part of the token response (request made to the /token endpoint )?

2. How is the updated_at intended to be used by the client? 
we believe this is to indicate the time when user’s personal information was last updated in Dataholders backend systems? please confirm.

Thank you!

**Comment by CDR-API-Stream** [comment]
> Are we correct in inferring that the profile-related claims must be returned at both userinfo endpoint,
> as well, as in the ID_Token returned as part of the token response (request made to the /token endpoint )?

Yes.

> 1. How is the updated_at intended to be used by the client?
>    we believe this is to indicate the time when user’s personal information was last updated in Dataholders backend systems? please confirm.

That is correct.  It aligns with the `lastUpdateTime` field in the payload returned from the customer end point.  It can be used by the ADR in any way they wish but would presumably be useful in determining the relative accuracy of the data in the customer profile.

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
