### ISSUE TITLE
End of support for Token revocation endpoint

### ISSUE THREAD

**Issue by jas8BEN** [ConsumerDataStandardsAustralia/standards-maintenance#341]
Hello @CDR-API-Stream 

Clarification is needed on the following statement mentioned in the CDR specification in the Revoke Consent section [here](https://consumerdatastandardsaustralia.github.io/standards/#end-points).

> NOTE: Data Recipients MUST continue to support this Token Revocation End Point until February 2021.
> 
> NOTE: Data Holders MUST continue to support consent revocation via the oAuth Token Revocation end point until February 2021.

Does the above statement imply following:
1. Data Holder and Data Recipients must support the CDR Arrangement Revocation endpoint by Feb 2021.
2. Post Feb 2021 , the Data Holders are expected to decommission the Revoke Consent via Refresh Token endpoint and the  output for OIDC config must ONLY reflect the cdr_arrangement_revocation endpoint and NOT revoke consent (via token).

**Comment by bmangalaganesh** [comment]
@jas8BEN 

These statements apply primarily to the actors who are currently in play (i.e  Big4 and the 3 ADRs ).

These dates are primarily a transition state for the existing players.

These dates do not affect the others such as the Non-Big 4 banks or ADRs who are starting say in 2nd Feb 2021 (or later). They would not support the revocation endpoint and would expose the  CDR Arrangement Revocation End Point (CARE) to provide the revocation functionality.

https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations states the following:

> Data recipients may obsolete this end point from February 1st 2021.
> Data holders may obsolete consent revocation via this end point from February 1st 2021, however they must still support oAuth token revocation. Data recipients must upgrade their implementations to use the Data Holder CDR Arrangement Revocation End Point by this time.

The big 4 and 3 CDRs need not support the revocation end point from 1st February is the way I read this.

This [FAQ on Revocation end point ](https://cdr-support.zendesk.com/hc/en-us/articles/900001579626-Revocation-Endpoint) Support portal shows the following info:

The Revocation Endpoint _is not required for participants_ who have delivered the CDR Arrangement Management Endpoint, the Revocation Endpoint is considered deprecated once the  CDR Arrangement Endpoint scope for revoking Consent is published for consumer consumption.

**Comment by jas8BEN** [comment]
@CDR-API-Stream : Could you please confirm if the understanding from @bmangalaganesh is valid.

**Comment by CDR-API-Stream** [comment]
@bmangalaganesh comments are accurate.  The statements referenced in the question are intended to support transition arrangements for existing implementations.

@jas8BEN, if you have further questions we would encourage you to ask them via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
