### ISSUE TITLE
CX Guidelines when only Customer info scope is selected

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#343]
# Request For Clarification
This is likely not a realistic use-case but the scheme allows this.

ADRs can ask for just the Customer authorization scopes (e.g _common:customer.basic:read_ and _common:customer.detail:read_) without asking for any of the other scopes (such as _bank:accounts.basic:read_).

The CX Guidelines assume that one of the Banking APIs scopes would be chosen by the ADR/Customer.

In this scenario, I am guessing the flow would skip the pages related to authorize accounts with the rest of the flow continuing as-is.

Appreciate inputs/guidance from the CX workstream.

**Comment by CDR-CX-Stream** [comment]
Hi @bmangalaganesh,

That is correct. [CX Standard #14](https://consumerdatastandardsaustralia.github.io/standards/#consumer-experience) caters to this scenario as follows:

>Data holders MUST allow the consumer to select which of their accounts to share data from if the data request includes account-specific data and if there are multiple accounts available. **The Data holder MAY omit this step if none of the data being requested is specific to an account (e.g. Saved Payees).**
