### ISSUE TITLE
Q: Consumers personal access of their data

### ISSUE THREAD

**Issue by michael-letcher** [ConsumerDataStandardsAustralia/standards-maintenance#344]
# Question
Is there any word or recognition on giving a user real control/access over their own data?

This article here from 2017 summarises quite well what I asking: [Will I Really Have Control Of My Data?](https://www.finextra.com/blogposting/14858/open-banking-will-i-really-have-control-of-my-data)

We see everywhere how open banking will free consumers giving them control over data; as the Australian Banking Institution puts it "You have control over how your data is used, and to whom it is given." [REF](https://www.ausbanking.org.au/policy/the-future/open-banking/) ... unless it's you. Currently the only way to get access to your own data, is to get very uninformative CSVs from your institution or to go old school and create a service that scrapes as much data off your institution websites as we can.

I gather that core concept of Open Banking is to allow other companies to get access to this data to profit from it. But for the lowly consumer whom is savvy enough to create their own applications, why not allow them to create things like open source tools and budgeting software for personal use?

Giving the users ability to request access to such an API that makes actual interactions (transfers, payments, etc.) is definitely dangerous, but I see no harm in readonly access to things such as accounts, balances and transactions. Something that we can already access freely with a username and password (in Westpac's case an insecure alpha-numeric password of 6 characters only).

I'd love to know if there has been any consideration on this front and if there are any long term plans to consider this?

**Comment by CDR-API-Stream** [comment]
Consideration is being given to a "Direct To Consumer" access mode for obtaining CDR data that does not require an intermediary ADR.  This model has been considered as important since the inception of the CDR and is included in the foundational legislation.

The rules and standards for the development of this access mode have not yet been developed and an exemption have been provided to Data Holders until November 2021.

**Comment by neale-morison** [comment]
FAQ available for review by Agents and Admins only: https://cdr-support.zendesk.com/hc/en-us/articles/900003387446

**Comment by CDR-API-Stream** [comment]
Since this issue was raised and the corresponding response from the DSB, consultation was conducted and concluded on Direct To Consumer scope: https://github.com/ConsumerDataStandardsAustralia/standards/issues/167

Current Direct To Consumer obligations have been deferred.
