### ISSUE TITLE
Remove duplicate Get Product Detail items from FDO

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#346]
# Description
There appears to be duplicate items for the **Get Product Detail** V2 and V1 in the [Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations) section of the documentation.

![image](https://user-images.githubusercontent.com/60594671/96802459-9b95e600-1455-11eb-9bb8-ba92976880e1.png)

# Area Affected
[Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations) documentation.

# Change Proposed
Remove the duplicate items.

**Comment by nils-work** [comment]
This may have some impact to #315

**Comment by CDR-API-Stream** [comment]
A fix to this errata was included with the v1.5.1 data standards release which was [approved by the Data Standards Chair]https://github.com/ConsumerDataStandardsAustralia/standards/issues/134#issue-651199297). 

This issue will be closed accordingly.
