### ISSUE TITLE
Behaviour for lost/stolen cards

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#348]
We seek some feedback on a scenario when a customer informs a DH that their credit card was lost or stolen and asks for a card reissue, in which case a new card number would be generated for that customer.

If the card was already a part of a sharing arrangement with an ADR:
Would the new card number be treated essentially as "the same card", i.e. would the sharing arrangement continue seamlessly? If yes - would this mean that the accountId for this new card number would be the same as for the "old" card number?

Thank you

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal: https://cdr-support.zendesk.com/hc/en-us/articles/900003356146-Stolen-Credit-Card-Scenario. Accordingly, the issue is closed.
