### ISSUE TITLE
Clarification on allowed session count as per NFRs

### ISSUE THREAD

**Issue by imesh94** [ConsumerDataStandardsAustralia/standards-maintenance#349]
# Request For Clarification

The specification mentions that the number of sessions allowed is limited to "20 sessions per day, per customer, per data recipient" (https://consumerdatastandardsaustralia.github.io/standards/#traffic-thresholds). However, this is mentioned under 'Unattended traffic', where a customer is not present. Could you please clarify how the "per customer" phrase comes into the context here?

If we have to consider the customer, is the number of sessions allowd for one Data Recipient per day is 20*20? 
Also, should the sessions created for purposes like registration requests (DCR) be taken into account here?

Thanks

**Comment by bmangalaganesh** [comment]
@imesh94  

Reference : https://consumerdatastandardsaustralia.github.io/standards/#tocSresponsemetricslistv2
> Note that a session is defined as the provisioning of an Access Token.

DCR flow does not require a session.

I am not sure I am following the logic of 20*20 that you mention here.

> If we have to consider the customer, is the number of sessions allowed for one Data Recipient per day is 20*20?

Can you elaborate on how you arrived at this figure?

My reading of this statement (

> 20 sessions per day, per customer, per data recipient

) is as follows:

During low traffic periods, if an ADR makes unattended traffic (i.e. customer is not present in the ADR Software product app) then the  Data Holders can restrict 20 sessions per customer (requests coming from that ADR).

Note that the customer info (can be inferred from the  Access Token by the Data Holder) even though this is a "customer not present" scenario.

**Comment by imesh94** [comment]
@bmangalaganesh 

> Can you elaborate on how you arrived at this figure?

I assumed one customer is allowed 20 sessions through an ADR. And 20 customers can use the same ADR to access data. So the total session count would be 20*20. Is it not the case? Should we only consider the ADR here and lmit the ADRs session count to 20?

**Comment by bmangalaganesh** [comment]
@imesh94 , There are no threshold limits on the number of consumers (per ADR) based on my understanding of the specs.

**Comment by CDR-API-Stream** [comment]
Hi @imesh94,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal. A general article addressing traffic thresholds has been created: https://cdr-support.zendesk.com/hc/en-us/articles/360004493255-Traffic-thresholds. Accordingly, the issue is closed.
