### ISSUE TITLE
Request for clarification on JWKS key selection algorithm

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#350]
# Request For Clarification
Can Data61 please clarify key selection algorithm for choosing encryption key from ADR's JWKS endpoint, i.e. how to determine which key should be used to encrypt ID token? Different participants will have different number of keys in different order used for signing and encryption, and different keys can have different parameters configured or not.

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal: https://cdr-support.zendesk.com/hc/en-us/articles/900004420583. Accordingly, the issue is closed.
