### ISSUE TITLE
Request for Clarification when Joint Account nomination is revoked

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#351]
# Request For Clarification
We are seeking clarification on the following scenario: Both Joint account holders provided their nominations on Joint Account A. JAH1 created a data sharing consent on the joint account. JAH2 then revokes their nominations. What should be returned for a generic Get Accounts call?

**Comment by bmangalaganesh** [comment]
@commbankoss here is my understanding, using the table below as a reference scenario

| Account  | Individual/Joint   | Owner A | Owner B
| --- | --- |--- |--- |
| Account 01 | Individual  | John| N/A
| Account 02 | Joint  | John| Mary
| Account 03 | Joint  | John| James
| Account 04 | Individual  | Mary | N/A

| Account  | Joint Account Election Status    | Owner A | Owner B
| --- | --- |--- |--- |
| Account 01 | Not Applicable  | John| N/A
| Account 02 | Complete  | Elect to Share| Elect to Share
| Account 03 | Not Complete  | Elect to share| No election perofmred
| Account 04 | Individual  | Mary | N/A

John provides consent to an ADR for accounts 01 and 02.

Now data is shared by the Data holder for accounts 01 and 02.

Now looking at your question,  Mary decides to revoke her election for account 02 and if the ADR makes a `getAccounts` API call then the DH will return just the account info for Account 01.

Account 02 information will not be returned.

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.  This will be especially helpful for questions like this that may need ACCC input.

**Comment by CDR-API-Stream** [comment]
Knowledge article has been created here: https://cdr-support.zendesk.com/hc/en-us/articles/900004428406
