### ISSUE TITLE
What is future-plan

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#352]
# Request For Clarification
What is the [future-plan](https://github.com/ConsumerDataStandardsAustralia/future-plan) repository? Is the published change process the new one? Was this intended for consultation?

**Comment by CDR-API-Stream** [comment]
Hi @perlboy,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by perlboy** [comment]
See #354.
