### ISSUE TITLE
Clarification on transaction fields

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#353]
Can you please provide clarification about below fields as the description provided seems a bit vague and can have differing interpretations based on individual providers' internal systems:

description - The transaction description as applied by the financial institution
is this meant to be a simple description along the lines of "online banking transfer" or "ATM withdrawal" ?

reference - The reference for the transaction provided by the originating institution. Empty string if no data provided
is this meant to be a message a customer could potentially enter into a transaction or is this meant to be an internal reference number of a transaction?

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal: https://cdr-support.zendesk.com/hc/en-us/articles/900003355406-Transaction-Fields-Description-and-Reference-clarification. Accordingly, the issue is closed.

**Comment by CDR-API-Stream** [comment]
This issue was answered via the CDR Support Portal: https://cdr-support.zendesk.com/hc/en-us/articles/900003355406-Transaction-Fields-Description-and-Reference-clarification. Accordingly, the issue is closed.
