### ISSUE TITLE
DSB Response Time SLA

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#354]
# Request For Clarification
Could the DSB please provide guidelines on the response time SLA that participants can expect to questions and responses? An example of the end state when the DSB fails to respond in a timely way to requests is demonstrated in #317.

This problem will only get significantly worse as implementation of CDR API's is completed and is particularly relevant given Christmas closures and the likely probability that many implementer's will not be (nor really can) stopping implementations to achieve their delivery timelines.

**Comment by CDR-API-Stream** [comment]
The DSB attempts to respond in as timely manner as possible to queries and clarifications and facilitates multiple mechanisms to escalate issues that participants feel are not being attended to such as the advisory committee and the weekly implementation call.  We have also recently invested in the support portal to help improve throughput of clarifications.

Unfortunately we are not in a position to commit to SLAs on responding to questions.

As mentioned in recent announcements it would be appreciated if you could, in the future, raise questions or requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us) as this will likely improve the response time.

**Comment by perlboy** [comment]
Timely manner? @WestpacOpenBanking asked back in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/41 almost a year ago the definition of breaking change to be defined and yet this request was responded to in 13 minutes.

The support portal is opaque and limits discussion for a path forward while implementers wait for a response at the DSB's leisure, the conversion to it has had basically zero consultation during the maintenance iterations, the DSB simply decided to dictate "the new way" (in a similar way to how standards-maintenance happened). In addition the DSB's own [README.md](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/README.md ) indicates to open issues here.

While I'm broadly supportive of a knowledge base the speed and timing of this forced migration in the midst of so many unanswered queries makes me question whether the motivations are primarily political. Channelling some historical web hosting support days the typical way of migrating would be to leave both options open and provide responses which are direct links to published knowledge base articles. This way the use of the knowledge base becomes a desired behaviour rather than a forced adoption. 

As noted by at least one participant in the call when it was announced, GitHub presents an opportunity for implementers to have shared visibility of other implementers views particularly in the midst of no explicit commitment of how quickly the government will respond. On the face of it, this seems disingenuous and hardly in the spirit of the open discussion the government purports to encourage.

**Comment by perlboy** [comment]
What's proven in this ticket is that ultimately the DSB decides what is a priority is what is not based on political sensitivities. I'm done bothering with the government "consultation" when in reality the outcome is predetermined. Closing all tickets.
