### ISSUE TITLE
Clarififation on MTLS requirements

### ISSUE THREAD

**Issue by hfszeto1982** [ConsumerDataStandardsAustralia/standards-maintenance#355]
We have questions around what the requirements are around establishing MTLS connections - based on the diagram outlined in https://cdr-register.github.io/register/#overview it appears to be pre-requisite for the retrieving the access token from the CDR register and also for the Data Recipient-facing Register API endpoints https://cdr-register.github.io/register/#consumer-data-right-cdr-register-apis .

However, we want to confirm there are any formal specifications or requirements around how to establish and support those MTLS connections to the CDR Register? There doesn't appear to be much existing documentation around this either on the CDR documentation (https://cdr-register.github.io/register/#introduction) or on the CDS documentation (https://consumerdatastandardsaustralia.github.io/standards/#introduction).

Also, in https://consumerdatastandardsaustralia.github.io/standards/#transaction-security there is mention that there are endpoints that are classified as not requiring authentication and those will not require use of MTLS. Is there an explicit list of those endpoints someewhere in the documenation that we can refer to so that it's clear which ones are does not require MTLS?

**Comment by CDR-API-Stream** [comment]
Hi @hfszeto1982,

The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us). It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by bmangalaganesh** [comment]
Hi @hfszeto1982 

I had this diagram created for our internal team. Hoping this would help you and others.

Note: Intentionally I had kept the getMetrics API out of this picture (I haven't explicitly called every single CDS API as that would clutter the picture). This should provide a clear view of mTLS and TLS used in the various APIs) 

![image](https://user-images.githubusercontent.com/12740620/100029113-9658fc00-2e44-11eb-8f45-9f71331c598b.png)

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal and this associated issue will be closed.
