### ISSUE TITLE
Term Deposits - Lodgement Date

### ISSUE THREAD

**Issue by LizLau** [ConsumerDataStandardsAustralia/standards-maintenance#356]
Hello,
Can we please clarify the definition of lodgementDate on the schema in the standards document for BankTermDepositAccount.
Definition is Lodgement Date of the Original Deposit.

At AMP:-

When a TD is first created, we have a start date (date of when the TD starts accumulating interest).
When a TD is renewed and it's the same term as the original TD (the original TD continues and the original start date remains unchanged)
When a TD is renewed and the terms are different, we terminate the original TD and create a new one. In this scenario, there is no relationship kept between the original TD and the new one. We will need to use the new start date
We wanted to confirm the definition of lodgement date:-

Is it the original start date OR
Date of renewal
If option 1 is correct, then are you ok for us to use the original start for renewals on the same term, and the new start date for new term deposits and renewals with different terms.

Kind regards
Liz

**Comment by CDR-API-Stream** [comment]
Hi @LizLau, 

The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
