### ISSUE TITLE
Endpoint registry (obligation) for data holders

### ISSUE THREAD

**Issue by deepsol-oba** [ConsumerDataStandardsAustralia/standards-maintenance#358]
# Description
Currently, API endpoints are published by the data holder on their website.

With the aim to "improve consumers’ ability to compare and switch between products and services, and will encourage competition between service providers, leading not only to better prices for customers but also more innovative products and services." new implementations and changes to endpoints require constant scanning/URL harvesting of the data holders websites.

We are suggesting an endpoint registry/address book with the obligation for data holders to keep their endpoint's current.
This registry will be able to be consumed by consumers of the APIs without the need of having to monitor the data holder websites.

The registry can then be referenced by the consumers to a) use the current API endpoint for the data holder in question b) access new implementations.

While something similar exists in the realm of the product comparator (datasource.json) it is not mandatory to be used or to be kept up-to-date by the data holder.

# Area Affected
Not sure

# Change Proposed
Introduce a data holder registry for their API (e.g. holder path URI component), ideally with added information as to endpoints and they versions supported.

**Comment by CDR-API-Stream** [comment]
Hi @deepsol-oba, this is being considered under an active Decision Proposal: https://github.com/ConsumerDataStandardsAustralia/standards/issues/158. Can you please provide any specific feedback to that DP in regards to the changes you'd like to see supported?

This issue will be closed as it covers the same problem space.
