### ISSUE TITLE
Clarification request on Mandatory/Optional Fields in Payload Conventions section in CDR

### ISSUE THREAD

**Issue by KaterynaShandro** [ConsumerDataStandardsAustralia/standards-maintenance#359]
In Mandatory/Optional Fields section:  https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions it is specified that _‘Note that for optional fields are not considered optionally implementable by a Data Holder. For instance, if a Data Holder holds data in digital form for a Customer that is represented in a payload then it is expected that this data will be shared when authorised by the Customer. For payloads unrelated to Customers, such as product reference data, there is more discretion for the Data Holder but other drivers, such as complementary regulation or the requirement to align to other channels, should be taken into consideration.’_ 

**Question:** Does it mean that if a Data Holder holds the data directly in a table, we have to provide it, but if the data is a calculation, it can be left out?

**Comment by CDR-API-Stream** [comment]
Hi @KaterynaShandro, noting this may have been answered on the ZenDesk portal, you may find the existing knowledge base article useful.

https://cdr-support.zendesk.com/hc/en-us/articles/900001580606-Voluntary-Product-Data

The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  It would be appreciated if you have any follow up queries, could you please raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
