### ISSUE TITLE
Precision of ANZSCO and ANZSIC values

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#361]
# Description
If a Data Holder only maintains ANZSCO values representing (for example) the 'Minor Group' level of occupations (first three digits), would there be any value in sharing those in lieu of full six-digit codes?

A similar question was posted to the support portal related to higher levels of ANZSIC -
https://cdr-support.zendesk.com/hc/en-us/articles/900005241363-Omitting-incomplete-industry-code

# Area Affected
May require changes to documentation or a convention to explain the possibility of variable-length codes -
https://consumerdatastandardsaustralia.github.io/standards/#tocScommonperson
https://consumerdatastandardsaustralia.github.io/standards/#tocScommonorganisation

# Change Proposed
Requesting community feedback on the value of partial codes in these cases.

**Comment by perlboy** [comment]
The response you've linked indicates schema compliant responses is the focus and that's been the prevailing behaviour we've promoted including with ANZSCO approaches.

Consequently our recommendation to customers has been to deliberately suffix pad to 6 digits. Ie. Taking your "Minor Group" example if you have a Minor Group of 121 (Farmers and Farm Managers nfd) a presentation of `121000` would be both schema valid and ANZSCO valid as per the [published spreadsheet](https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1220.02013,%20Version%201.3?OpenDocument) _Table 6_ tab.

**Comment by nils-work** [comment]
Thanks @perlboy - that looks like it could be a good option.
