### ISSUE TITLE
Security Profile: Request Object - Inconsistency in example for sharing_duration and cdr_arrangement_id

### ISSUE THREAD

**Issue by da-banking** [ConsumerDataStandardsAustralia/standards-maintenance#362]
In Security Profile: Request Object ( https://consumerdatastandardsaustralia.github.io/standards/#request-object ) sharing_duration and cdr_arrangement_id are specified as claims of the request object, but the example shows them as members of the claims request object within the request object. As written, it seems like they should be individual claims alongside others, such as state and nonce, however this conflicts with the example. I believe this ambiguity is caused by the claims request parameter being itself a claim of the request object.

It seems like an inconsistency in the example, which needs to be fixed.

# DSB Proposed Solution
The proposed solution can be found in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/362#issuecomment-2146672589

**Comment by CDR-API-Stream** [comment]
As discussed during the MI call on March 29, the upstream [OIDC specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) notes that the `claims` request parameter must be represented as an object within the request object:

> **5.5.  Requesting Claims using the "claims" Request Parameter**
> OpenID Connect defines the following Authorization Request parameter to enable requesting individual Claims and specifying parameters that apply to the requested Claims:
> 
> claims
> OPTIONAL. This parameter is used to request that specific Claims be returned. **The value is a JSON object listing the requested Claims.**

Therefore, specifying the `sharing_duration` and `cdr_arrangement_id` claims in the `claims` object is correct and in alignment with the upstream specification.

As a result the DSB recommends no change for this CR.  

Feedback is welcome on this and if further guidance can be provided to help clarify.
