### ISSUE TITLE
Get Transaction API - Amount Range Parameters

### ISSUE THREAD

**Issue by rsaeed83** [ConsumerDataStandardsAustralia/standards-maintenance#363]
# Description
In the real-world, when users search transactions on any platform (Internet or Mobile Banking), it gives the option to choose incoming /outgoing payments. However, In Open Banking we are assuming from signs if it’s a negative amount; the transaction is outgoing, positive then incoming. Can you please confirm our standing with different input parameter combinations:

Min Amount | Max Amount | Incoming /outgoing logic | Sample output | CDR Comments
-- | -- | -- | -- | --
40 | Not Specified | All Incoming 40 (inclusive) and above | 40,50,100,…. |  
Not Specified | 40 | All Outgoing and Incoming till 40 (inclusive) | …. -10, -5, 0, 10,20,30, 40 |  
-80 | -36 | Outgoing between 36 and 80 | -80,-50,-30,… -36 |  
-80 | 250 | Simple maths range.. all between input numbers | -80, -70, -40, -20,1,2,3,…, 250 |  
40 | 250 | Incoming payment between $40 and $250 | 40,60,100,200,----,250 |  
Not Specified | -40 | All outgoing payments from 40 (inclusive) and above | ….,-1000,-900, --50, -40 |  
-40 | Not Specified | All outgoing payments from -40 (inclusive) and all   incoming payments as well | -40,-30,-20,10,20,….1000… |

**Comment by CDR-API-Stream** [comment]
Hi @rsaeed83,
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
