### ISSUE TITLE
Request For Clarification : Get Transaction Detail Response when BankingTransaction.isDetailAvailable is FALSE

### ISSUE THREAD

**Issue by Randima-ibm** [ConsumerDataStandardsAustralia/standards-maintenance#364]
# Description
As per the standards definition, the purpose of isDetailAvailable of BankingTransaction object is to inform the caller that caller can get additional/extended information from the **Get Transaction Detail end point**.

This was further clarified in Github issue [130](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/130)

**_If a call to the detail endpoint would result in a successful response, the isDetailAvailable attribute should be true, false otherwise._**

Question: Going by that clarification standards definition, what is the unsuccessful response (error code) detail end point result when isDetailAvailable attribute set to false?

Further info: [268](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/268)
extendedData is only currently used for NPP data. It could be used for other payment types in future but it was only initially expected to be NPP.
In such cases, BankingTransaction.isDetailAvailable  should set to True. Otherwise set to False.

**Comment by CDR-API-Stream** [comment]
Hi @Randima-ibm,
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal: https://cdr-support.zendesk.com/hc/en-us/articles/900004342886. Accordingly, the issue is closed.
