### ISSUE TITLE
What type of product should be displayed for Accounts with linked Cards

### ISSUE THREAD

**Issue by VladPNBank** [ConsumerDataStandardsAustralia/standards-maintenance#366]
Hello,

Could you please clarify expectations for the following configuration of Debit/Credit cards.
- credit card configured as an overdraft account with card linked to it
- debit card configured as a savings account with card linked to it

Shall we as part of consent flow and further API responses show cards as "CRED_AND_CHRG_CARDS" or "TRANS_AND_SAVINGS_ACCOUNTS" for Debit and "OVERDRAFTS" for Credit?

Thank you,
Vlad

**Comment by CDR-API-Stream** [comment]
Hi @VladPNBank,
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by VladPNBank** [comment]
Thank you, submitted
