### ISSUE TITLE
Consideration of granular DH metadata management.

### ISSUE THREAD

**Issue by kaveenr** [ConsumerDataStandardsAustralia/standards-maintenance#37]
# Description
Currently, the Data Holder Metadata Management takes place using periodic polling and Metadata AdminAPI call from the CDR registry for immediate updates.

The concern is scalability, Hypothetically with a large number of ADRs on-boarded with the CDR registry, the DH will have to query the complete ADR statuses through the Registry API. 

The proposal is to make the APIs more granular allowing query of individual ADRs for metadata updating.

# Area Affected
- CDR Registry **`GET /{industry}/data-recipients/brands/software-products/status`**
- CDR Registry **`GET /{industry}/data-recipients/status`**
- CDS AdminAPI **`POST ​/admin​/register​/metadata`**

# Change Proposed
- _CDR Registry **`GET /{industry}/data-recipients/brands/software-products/status`**_
  - Pagination _(in the case of the number of software products are unsendable in one payload)_
  - Allow retrieving the status of a single software product using the **`softwareProductId`** using a query parameter or path parameter.
- CDR Registry **`GET /{industry}/data-recipients/status`**
  - Pagination _(in the case of the number of ADRs are unsendable in one payload)_
  - Allow retrieving the status of a single software product using the **`dataRecipientId `** using 
- _CDS AdminAPI **`POST ​/admin​/register​/metadata`**_
  - Send the **`softwareProductId`** or  **`dataRecipientId `** allowing invalidation of a singular software product/ data recipient.

This proposal will allow DHs to do JIT(Just In Time) provisioning of metadata instead of periodically having to completely retrieve the whole metadata list from the CDR registry.

**Comment by CDR-API-Stream** [comment]
@kaveenr, this item has been reviewed and also discussed with the ACCC Register team.

As this change is actually a change proposal for end points being defined by the Register team that are not part of the CDR Standards it is appropriate that this issue be dealt with on the [ACCC Register GitHub repository](https://github.com/cdr-register/register).

The DSB would recommend submitting or cross posting this proposal there for consideration.
