### ISSUE TITLE
transactionId conditional documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#370]
# Description
Apart from some previous [discussion](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/113), it's not clear why the transactionId is marked as `conditional` in the [BankingTransaction](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransaction) schema.

# Area Affected
[BankingTransaction](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransaction) schema documentation

# Change Proposed
Consider extending the Description of the field to include something to the effect of `Mandatory if isDetailAvailable is set to true` (according to comment [here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/113#issuecomment-583198997), if that is still correct)

**Comment by CDR-API-Stream** [comment]
Hi @nils-work this can be added as a clarification for existing documentation without any implementation impact. Obviously, if `isDetailAvailable` is true a `transactionId` is required. Your text does state that more explicitly.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.0...maintenance/370

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903) and is included in v1.11.0. A change to the data standards was recommended.

This issue will be closed accordingly.
