### ISSUE TITLE
Customer schemas optional documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#371]
# Description
The `person` and `organisation` properties are marked as `optional` in the [documentation](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponsecommoncustomer), but are marked as `x-conditional` in the [1.6.0 Swagger JSON](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.json), which makes more sense as the `customerUType` value is mandatory.

# Area Affected
[ResponseCommonCustomer](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponsecommoncustomer) and [ResponseCommonCustomerDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponsecommoncustomerdetail) schema documentation.

# Change Proposed
The `person` and `organisation` properties should be marked as `conditional` based on the `customerUType`.

The current `x-conditional` property on the `ResponseCommonCustomer` object should probably be on the `ResponseCommonCustomer_data` property instead.

**Comment by CDR-API-Stream** [comment]
This is a g in the swagger schema definition. The intended meaning was that person and organisation were conditional based on the associated UType and this is consistent with the guidance provided via Implementation Calls and ZenDesk. The conditional definition was incorrectly applied to the higher level member's properties. This has been corrected. The bug has been corrected and is available for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.10.0...maintenance/371

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 

Thanks for the update. 

Sorry, it looks like one small part was missed - this line that was removed from `ResponseCommonCustomer` and `ResponseCommonCustomerDetail` -

`"x-conditional" : [ "person", "organisation" ]`

should have been moved to the corresponding `ResponseCommonCustomer_data` and `ResponseCommonCustomerDetail_data` objects.

**Comment by CDR-API-Stream** [comment]
Hi @nils-work this has been confirmed to be a bug in one of the Swagger documentation build dependencies. This dependency has been updated on the DSB's build servers. Version 1.11.0 will correct this issue. The correctly build Swagger file can be viewed here: http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/includes/swagger/cds_full.json

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 
The customer schema looks fixed in the version you posted, but it seems like the update may have also fixed one more issue and highlighted another -
1. The status response schema now correctly shows `explanation` as conditional - **fixed**
2. The `extendedDescription` property is now showing as `x-conditional` in `BankingTransactionDetail_extendedData` (but it's not directly in this object), and `required` in `BankingTransactionDetail_extendedData_x2p101Payload` (where it is present). 
The standards documentation show that field as **mandatory**, but the Description includes a condition - 
_An extended string description. Only present if specified by the extensionUType field_ - **new issue?**

**Comment by CDR-API-Stream** [comment]
Hi @nils-work, this should be handled as a new issue / change request.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903) and is included in v1.11.0. A change to the data standards was recommended.

This issue will be closed accordingly.
