### ISSUE TITLE
Define deprecation date for Get Metrics v1 

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#372]
# Description
Get Metrics v2 is required to be supported by DHs no later than July 31st 2021. A suitable retirement date for Get Metrics v1 needs to be defined to allow DHs supporting v1 to retire this version within a reasonable timeframe. This retirement date it dependent on the production release of the CDR Register to consume the Get Metrics v2 payload response. The CDR Register is the only client that consumes this data, thus this change does not affect ADRs. 

It is expected that any DHs who commence consumer data sharing from July 1st 2021 only need to support Get Metrics v2. The end of July obligation date for Get Metrics v2 was defined to allow existing DHs (i.e. major ADIs and reciprocal DHs) sufficient time to deploy v2 if required without coupling to non-major ADI consumer data sharing obligations.

# Area Affected
Get Metrics v1 API

# Change Proposed
Define a deprecation date for the Get Metrics v1 API. A retirement date of three months after v2 obligation dates is proposed: specifically 31 October 2021.

Feedback from @CDR-Register-Stream is requested regarding the release schedule for the CDR Register to support Get Metrics v2. This will assist in determining a reasonable retirement date for Get Metrics v1.

**Comment by CDR-Register-Stream** [comment]
The ACCC is supportive of the deprecation date of 31st October 2021. 

We acknowledge the need to balance flexibility in the V2 deployment time vs the overhead of maintaining deprecated APIs and support a 3 month period where both versions are live.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/161#issue-806886083) for inclusion in v1.9.0. A change to the data standards was recommended.

This issue will be closed accordingly.
