### ISSUE TITLE
Inconsistency in new CX Standards scope detail

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#375]
# Description
The CX Standards detail introduced in 1.7.0 has a typo and incorrect colouring compared to the previous 1.4.0 PDF version as per the highlighted detail below -

![image](https://user-images.githubusercontent.com/60594671/114020157-9ff27600-98b2-11eb-81f1-029ff0d51b29.png)

# Area Affected
Table 1. detail in the CX Standards [documentation](https://consumerdatastandardsaustralia.github.io/standards/#consumer-experience-standards)

# Change Proposed
1. Change the `:` to `‡` and apply the grey background to match the description.

2. Potentially remove all un-merged `detail` scope examples, as the merged language **MUST** be used when the detail scope is requested. This was discussed and clarified previously in the last two points of [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/224#issuecomment-730695166).

**Comment by CDR-CX-Stream** [comment]
Hi Nils,

Thanks for pointing this out. 

Item 1 is being actioned and will be reflected in an upcoming v1.8.0 release.

For item 2, the un-merged language will be retained to provide flexibility to CDR Participants based on the following rationale:

1. The data language standards are structured in a way that allows ADRs and DHs to apply the standards to a range of scenarios, including (1) use cases we have not anticipated now or in the future; (2) where an ADR requests scopes that aren't ostensibly useful
2. An ADR may provide a consumer with a choice as to whether to include one or both of the scopes. For example, a use case may require basic data for the service to function and optionally request detailed scopes for added value functionality.
3. While the expectation is for DHs to use the merged language whenever a detailed scope is requested, the standards specify that this should apply '[i]f a scenario requires it' in case there are circumstances the DSB has not anticipated where the merged language is not appropriate for a DH to use

**Comment by CDR-API-Stream** [comment]
A fix to this errata was included with the v1.8.0 data standards release.

This issue will be closed accordingly.
