### ISSUE TITLE
Metadata API Requires Clarification

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#38]
The description for metadata API as defined says:

> Indicate that a critical update to the metadata for Accredited Data Recipients has been made and should be obtained

However, https://cdr-register.github.io/register/#cache-refresh-metadata-request says 

> Data Holders and Accredited Data Recipients will be required to implement the Admin endpoint

Assuming the Register spec is correct in that both DH and DR are required implement the metadata API?

Thanks.

**Comment by CDR-API-Stream** [comment]
The DSB will need to check with the ACCC Register team to validate the current requirement for the metadata update end point.

**Comment by CDR-API-Stream** [comment]
It is the current understanding of the DSB that this issue is being dealt with by the Register team.  If the result is that the Register requires data recipients to implement the metadata end point then the standards will be modified, otherwise the standards will remain as they are.

**Comment by CDR-API-Stream** [comment]
If there is no further discussion on this query it will be closed on Friday.
