### ISSUE TITLE
9.3 Records to Be Kept and Maintained

### ISSUE THREAD

**Issue by PaulaAF11** [ConsumerDataStandardsAustralia/standards-maintenance#380]
-	9.3 Records to be kept and maintained 
Records to be kept and maintained—data holder
(g) the processes by which the data holder asks CDR consumers for their authorisation to disclose CDR data and for an amendment to their authorisation, including a video of each process
And;
Records to be kept and maintained—accredited data recipient
(h) the processes by which the accredited data recipient asks CDR consumers for their consent and for an amendment to their consent, including a video of each process;
What is the requirement, what does the video need to exhibit or demonstrate to be compliant?

**Comment by CDR-API-Stream** [comment]
Hi @PaulaAF11, as this pertains to clauses in the CDR Rules, could you please raise your question on the [Consumer Data Right Portal](https://cdr-support.zendesk.com/hc/en-us). This question can then be assigned to the appropriate person to answer for you.
