### ISSUE TITLE
Typos in HTTP Headers documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#381]
# Description
There are a couple of typos in the [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) section of the documentation -
![image](https://user-images.githubusercontent.com/60594671/116183667-a497a500-a761-11eb-9d1f-22f899bc4d0f.png)

# Area Affected
[HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) documentation

# Change Proposed
Encode the new lines correctly and fix the wildcard example `*/*`

**Comment by CDR-API-Stream** [comment]
Thanks @nils-work this change has been corrected in a staging branch viewable here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.9.0...maintenance/381

It will be integrated into an upcoming release.

**Comment by CDR-API-Stream** [comment]
This change was addressed as a documentation fix and included in v1.10.0.

This issue will be closed accordingly.
