### ISSUE TITLE
Fix typos in CX Standards

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#382]
# Description
Typos as shown in the attached image comparing [CX Standards PDF v1.4.0](https://consumerdatastandardsaustralia.github.io/standards/pdfs/CX-Guidelines-v1.4.0.pdf) against [v1.9.0](https://consumerdatastandardsaustralia.github.io/standards/#consumer-experience-standards).

![image](https://user-images.githubusercontent.com/60594671/117120668-f8943080-add6-11eb-9848-e6072b8d0123.png)

# Area Affected
CX Standards Permission language documentation.

# Change Proposed
1. Include italic styling and symbol for additional context information
2. Correct other typos

**Comment by CDR-CX-Stream** [comment]
Hi Nils,

Thanks for noting these - we'll correct these changes and incorporate them into the v1.10.0 release.

**Comment by CDR-API-Stream** [comment]
These changes have been staged. The changes can be reviewed here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.10.0...maintenance/382

**Comment by CDR-API-Stream** [comment]
This change was addressed as a documentation fix and included in v1.10.0.

This issue will be closed accordingly.
