### ISSUE TITLE
Levels of Assurance (LoAs) navigation bug

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#385]
# Description
In the Security Profile section, there is an additional anchor with the id `levels-of-assurance-loas` just before the title **Levels of Assurance (LoAs)** that causes an incorrect scroll point to be selected when clicking through the navigation.

![image](https://user-images.githubusercontent.com/60594671/119091100-e90c1d00-ba4f-11eb-97be-d25591bd2fb7.png)

# Area Affected
Documentation fix

# Change Proposed
Move or remove the redundant anchor element or change the id value.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.0...maintenance/385

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903) and is included in v1.11.0. A change to the data standards was recommended.

This issue will be closed accordingly.
