### ISSUE TITLE
Minor typo in Product Fee Types documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#386]
# Description
There appears to be a typo in the Description of the EVENT feeType - 'e.g. **NA** ...' -

`A fee in relation to a particular event (e.g. NA ordering a new card, viewing a balance or stopping a cheque)`

Also in the description of the UPFRONT feeType 'product **NA** lifecycle' -
`A fee paid at the beginning of the product NA lifecycle, such as an establishment fee, loyalty program fee or application fee`

https://consumerdatastandardsaustralia.github.io/standards/#tocSproductfeetypedoc

# Area Affected
Documentation only

# Change Proposed
Remove the **NA** in the Description text.

**Comment by CDR-API-Stream** [comment]
https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.0...maintenance/386

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903) and is included in v1.11.0. A change to the data standards was recommended.

This issue will be closed accordingly.
