### ISSUE TITLE
Typo in TRADE FINANCE enum in Product Categories table

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#388]
# Description
`TRADE FINANCE` is missing an underscore; it should be `TRADE_FINANCE`

# Area Affected
Documentation in the [Product Categories tables](https://consumerdatastandardsaustralia.github.io/standards/#product-categories)

# Change Proposed
Update to `TRADE_FINANCE`

Thank you

**Comment by CDR-API-Stream** [comment]
Hi @nils-work this is a documentation defect and will be fixed in the next release. This defect *does not* affect the Swagger which correctly includes the underscore.

**Comment by CDR-API-Stream** [comment]
This documentation fix has been staged for candidate release 1.11.1. Changes are available for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.1...maintenance/388

**Comment by CDR-API-Stream** [comment]
This documentation fix has been staged for candidate release 1.11.1. Changes are available for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.1...maintenance/399

**Comment by CDR-API-Stream** [comment]
This issue has been included in the [v1.11.1](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.11.1.html#v1-11-1-release-notes) documentation errata and patch release. 

This issue will be closed accordingly.
