### ISSUE TITLE
ID Token and UserInfo endpoint

### ISSUE THREAD

**Issue by versent1Jas** [ConsumerDataStandardsAustralia/standards-maintenance#39]
As per Data 61, the ID token should not contain any personally Identifiable data. Is this statement still valid when the DR passes profile scope in the authorisation request(grant consent), could you please confirm that claims(firstname, lastname, name and updated_at) are NOT required to be returned  ID token and will ONLY be available via userInfo endpoint for any scope (openId or profile) passed in the request.

**Comment by CDR-API-Stream** [comment]
That is correct.  The `name`, `given_name` and `last_name` claims should not be provided in the ID Token but only in the response to a request to the user_info end point.

Note that `updated_at` is not personally identifiable.
