### ISSUE TITLE
Error Response Structure - Does it contain "description" or "detail"?

### ISSUE THREAD

**Issue by deboraelkin2** [ConsumerDataStandardsAustralia/standards-maintenance#392]
# Description
In v1.10 of the standards the error response structure has been changed. The [Error Codes](https://consumerdatastandardsaustralia.github.io/standards/#error-codes) section specifies that the Error response structure should contain:

> **detail** field MUST be present: holds a human readable description of this specific error

However all examples provided include a _"description"_ field instead

# Area Affected
Error Codes

# Change Proposed
Please clarify whether the field should be named _"detail"_ or _"description"_ and modify Error Response Structure section or examples, accordingly.

**Comment by CDR-API-Stream** [comment]
Thank you @deboraelkin2, the field is `detail`. The documentation will be fixed to refer to the `detail` field so it is not ambiguous in meaning.

**Comment by CDR-API-Stream** [comment]
The fix to correct the documentation has been made and is available for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.0...maintenance/392

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903) and is included in v1.11.0. A change to the data standards was recommended.

This issue will be closed accordingly.
