### ISSUE TITLE
Missing Standard Error codes for authentication/authorisation and rate limiting errors 

### ISSUE THREAD

**Issue by deboraelkin2** [ConsumerDataStandardsAustralia/standards-maintenance#393]
# Description
V1.10 introduced standard error codes for a variety of typical errors. However none of the existing error codes seem to fit the type of errors that are related to authentication or authorisation errors, such as

- Missing or invalid bearer token
- Invalid authentication code, client_id and/or state provided in /token endpoint request
- Invalid PAR request (eg: expired JWT, reused JWT, etc.)
- ...

Similarly, there is no standard code for rate limiting (`429 Too many requests` would typically be returned in such situations).

With the existing codes, _urn:au-cds:error:cds-all:GeneralError/Expected_ would need to be used in these situations.

# Area Affected
Error Codes

# Change Proposed
Create one or more standard codes for authentication/authorisation errors and one for rate limiting errors.

For example:
- urn:au-cds:error:cds-all:AuthError/Expected_
- urn:au-cds:error:cds-all:Service/TooManyRequests

**Comment by CDR-API-Stream** [comment]
Hi @deboraelkin2, CDR error codes were intentionally not defined where upstream standards apply for Information Security. 

Given rate limiting is explicitly understood by the HTTP status code it would seem of limited value to define a standard CDR error code. It is most likely that Data Holders will handle rate limiting at their WAF or API Gateway level, so responding with a standard error code may also prove difficult.

The DSB would welcome any other perspectives from the community.

**Comment by deboraelkin2** [comment]
Thank you for the advice. Even for well understood HTTP status codes, there are benefits on returning an error payload, especially for the detail that can be provided. So if an error payload is returned, what should the general structure be. Would something like the following example (for an 429 HTTP Too many requests) be compatible with the standards definition?

```
{
  "errors": [
    {
      "code": "429",
      "title": "Too many requests",
      "detail": "APIs have traffic limits. Please retry after 1 second",
      "meta": {
        "urn": "urn:au-cds:error:cds-all:GeneralError/Expected"
      }
    }
  ]
}
```

**Comment by CDR-API-Stream** [comment]
Hi @deboraelkin2, 

> @deboraelkin2
> Even for well understood HTTP status codes, there are benefits on returning an error payload, especially for the detail that can be provided

That's true. Where the community sees benefit in well described error codes for specific scenarios, the error code structure supports it. Please note that 429 has a specific optional response header `Retry-After` which indicates the time (in seconds) that the client should wait before retrying an operation. 

Implementations can respond with additional information where they wish to provide a custom error code. Please note that where implementers seek to do so they must make the custom error codes available via a developer friendly mechanism (e.g. Developer Portal). This would allow you to describe any custom error code specific context (for example how to parse the retry message).

Per the data standards:

> v1.10.0, Consumer Data Standards:
> * If the Data Recipient or Data Holder supports application-specific error codes they MUST publish a mapping of those codes to the standard CDR error codes in a developer friendly way that is discoverable and freely available.
> * Data Recipients and Data Holders MAY publish this mapping any time prior to February 1st 2022.

 
> @deboraelkin2
> Would something like the following example (for an 429 HTTP Too many requests) be compatible with the standards definition?

Your representation of a custom error code is correct and it would be considered compliant.
