### ISSUE TITLE
Does DHs' PAR endpoint require enabling private key jwt client authentication in addition to request object validation?

### ISSUE THREAD

**Issue by charithadeshapriya** [ConsumerDataStandardsAustralia/standards-maintenance#395]
# Description
We observed that the CDS mandates private key JWT client authentication at the Data Holder's Pushed Authorization endpoint.
Therefore the pushed authorization request carries both client_assertion and the request object where both are signed JWTs sent by the ADR.
Successful validation of the request object (signature and parameters) itself guarantees that a successful client authentication has already happened.  In that context validation of client assertion again is purely a duplication of the same validation.
Shouldn't we remove client_assertion from the pushed authorization request?

# Area Affected
Client Authentication Mechanism of Pushed Authorization Endpoint

# Change Proposed
Private Key JWT client authentication is redundant at data holders' pushed authorization endpoint as the client authentication happens as a part of a successful request object validation.

**Comment by CDR-API-Stream** [comment]
Hi @charithadeshapriya, the requirements for client authentication are defined by the PAR specification: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-par-01.

Note, the latest version of the PAR specification is documented here: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-par-10 and this will be a consideration in the consultation opened [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/203) and [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/209).

**Comment by CDR-API-Stream** [comment]
Hi @charithadeshapriya if there are no further questions regarding this issue I will close the issue Friday 24/09/2021 with no changes required.

**Comment by CDR-API-Stream** [comment]
As there has been no further feedback, it is assumed the above explanation is sufficient and this issue will be closed.
