### ISSUE TITLE
Transport security for JWKS endpoints

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#40]
# Request For Clarification
Data Holders, Data Recipients and the Register must all host JWKS endpoints to allow for verification of public keys for a variety of purposes. Typically, these endpoints do not require mutually authenticated TLS. This approach allows distribution via a CDN and increased resiliency without security impact.
 
Currently, the transport security required for Data Recipient implementations is not specified. If intended, we would need to customise our security infrastructure to support TLS-MA instead of TLS. To align with standard approaches, and the approach used for the registry hosted JWKS endpoint we suggest that TLS without mutual authentication is the most pragmatic option for February.
 
We also query as to if the [requirement](https://consumerdatastandardsaustralia.github.io/standards/#json-web-key-set-end-point) for Data Holders to require TLS-MA for their JWKS endpoint was intended, and if so, the rationale for this approach.

**Comment by anzbankau** [comment]
ANZ support the need for further clarification on this topic.

**Comment by commbankoss** [comment]
Commonwealth supports Westpac’s proposal that TLS without mutual authentication on JWKS endpoints should be considered for February implementation.

**Comment by CDR-API-Stream** [comment]
Currently, the valid interpretation of the standards is that these end points are server to server and therefore MTLS is required.

This is, however, being discussed on a change proposal at: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/43

**Comment by perlboy** [comment]
> Currently, the valid interpretation of the standards is that these end points are server to server and therefore MTLS is required.

This (requiring MTLS) represents a direct change to essentially all existing OIDC Client Discovery libraries.

> This is, however, being discussed on a change proposal at: #43

This is a confusing linkage. JWKS endpoints are OIDC, #43 relates to CDR specific endpoints. The former has many existing implementations impacted (as per above), the latter is CDR specific so backlog items aren't really impacted because it's likely TLS/MTLS setup will occur in Participant software.
