### ISSUE TITLE
Consider additional featureType enumerated values

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#401]
# Description
There are product features commonly listed by data holders under the enumerated value of OTHER. We suggest adding additional enumerated values as this will help to make the data between data holders more consistent. We recommend that this issue only be prioritised if there is data recipient demand. Example additional enumerated values that may be considered include:

* CASHBACK_OFFER
* RELATIONSHIP_MANAGEMENT
* INSTALMENT_PLAN – an ability to pay back purchases in instalments.
* FRAUD_PROTECTION
* EXTRA_REPAYMENTS
* GUARANTOR 

# Area Affected
* The [BankingProductFeature](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductfeature) definition which is used in the [Get Product Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-product-detail) and [Get Account Detail APIs](https://consumerdatastandardsaustralia.github.io/standards/#get-account-detail).
* The [Product Feature Types](https://consumerdatastandardsaustralia.github.io/standards/#product-amp-account-components) table.

# Change Proposed
Add additional enumerated values based on common use of the OTHER feature type, expected scope of features to be included in responses and desirability for data recipients.

**Comment by WestpacOpenBanking** [comment]
Westpac suggests the following descriptions for the proposed enumerated values:

Value | Description | Use of additionalValue Field
-- | -- | --
CASHBACK_OFFER | Subject to terms, conditions and eligibility criterion, a customer may receive a cashback offer for opening an account or by spending at a certain retailer. | The amount of the cashback offer (in AUD)
RELATIONSHIP_MANAGEMENT | Relationship management is available for eligible customers. | NA
INSTALMENT_PLAN | The product has the option to pay for eligible purchases over time with a set number of payments. | NA
FRAUD_PROTECTION | The product includes fraud protection features. | NA
GUARANTOR | Subject to terms and conditions, the customer may be able   to nominate a guarantor during the origination process. | NA


We suggest that DSB and the community consider whether RELATIONSHIP_MANAGEMENT makes sense to include as a feature – RELATIONSHIP_MANAGEMENT is usually advertised as a separate service.

**Comment by CDR-API-Stream** [comment]
These changes have been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.15.0...maintenance/401

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.
