### ISSUE TITLE
Alternative mechanisms for OTP

### ISSUE THREAD

**Issue by NeilSansomeMBL** [ConsumerDataStandardsAustralia/standards-maintenance#405]
# Description
As part of our CDR implementation, we support our customers authenticating through our Macquarie Authenticator App utilising a One-Time Password (OTP). This streamlines the authentication process by submitting the OTP automatically rather than requiring manual entry. For customers who have not installed the Macquarie Authenticator, the OTP is distributed via SMS and manually entered.

The Authenticator process uses the same OTP authentication service that we offer to customers who have not installed the Authenticator (SMS) but automatically submits it when the client confirms their intention to begin the authorisation process. It is at our view that this is within the intent of the requirements set out for the consent model and consistent with the use of an OTP.

In summary, it is our view that by automating the OTP via the Authenticator, our implementation is:
-	consistent with the use of an OTP for authentication,
-	an improved customer experience, 
-	more secure than an SMS-based OTP (which could be ported), and
-	does not impact the CDR ecosystem as this is an existing app that our customers use everyday to manage their banking security.

# Area Affected
Security Profile – Authentication Flows

# Change Proposed
Rephrase the below term to allow for the automated distribution of the one-time password on a customer’s behalf via a secure channel.

Current: Data Holders MUST provide a one-time password (OTP) to the customer through an existing channel or mechanism that the customer can then enter into the redirected page

Proposed change: Data Holders MUST provide a one-time password (OTP) to the customer through an existing channel or mechanism that the customer can then enter or is entered on behalf of the customer into the redirected page.

**Comment by NeilSansomeMBL** [comment]
For more details, please see attached Sequence Diagram.
![CDRWithAuthenticator](https://user-images.githubusercontent.com/89842961/134262989-f359a113-ed7b-4db6-9388-88eab9cd9e3d.png)

**Comment by JJLWHarrison** [comment]
We are supportive of this change.

**Comment by JohnHarrison-Truelayer** [comment]
We are supportive of this change.

**Comment by ShaneDoolanAdatree** [comment]
Adatree is also supportive of this change.

**Comment by CDR-API-Stream** [comment]
A Decision Proposal is required to consider alternative mechanisms for OTP, [#91 DSB Item - Consider alternative mechanisms for OTP](https://github.com/ConsumerDataStandardsAustralia/future-plan/issues/91) has been added to [DSBs future-plan](https://github.com/ConsumerDataStandardsAustralia/future-plan/projects/1) backlog.

**Comment by joshuanicholson** [comment]
As an ADR, we fully support alternate methods like  Mac Bank have suggested. The feedback from the current implementation of OTP mechanisms is there is significant variance across the different DHs. While the outcome of different methods is essentially the same, there are a couple of DHs that push to the banking app on the consumer's device, and these DHs have a significantly better user experience, leading to quicker consents, less friction, fewer abandoned consents, more trustworthy and 'appearance' of high security (I appreciate some people could argue the validity of this last point - but from a consumer perspective, an in-app push are known & expected)

**Comment by CDR-API-Stream** [comment]
Closing this issue as it will be considered as a Decision Proposal, see [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/405#issuecomment-1283439944) above.
