### ISSUE TITLE
400 Error code missing in swagger for some endpoints

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#413]
# Description
`400 - Missing Required Field` is a **MUST** in the error section. But this error is not present in the swagger files and resulting markdown

# Area Affected
The resource API sections are affected

# Change Proposed
Modify the swagger to include the `400 - Missing Required Field`.

**Comment by perlboy** [comment]
This change was apparently staged at the last MI? Please provide a link to the staged change.

**Comment by nils-work** [comment]
The proposed change for this issue has been staged here - https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/283/commits/93bc2fae19a06602932ffe73bea49386928b3aea

**Comment by nils-work** [comment]
[Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html) version 1.25.0 has now been published, incorporating this change.
It has been noted that this change may have caused the `400 - Invalid Version` response code to be duplicated in some Banking endpoints. That issue will be reviewed in the next release.
