### ISSUE TITLE
Properties in BankingTransactionDetail objects

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#414]
# Description
The swagger JSON and the documentation of properties in the BankingTransactionDetail schema seem to be misaligned.

# Area Affected
[BankingTransactionDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransactiondetail) extendedData schema documentation  and related Swagger objects.

# Change Proposed
The `extendedDescription` property shows as `x-conditional` in the `BankingTransactionDetail_extendedData` object (but it's not present there), and also shows as `required` in the `BankingTransactionDetail_extendedData_x2p101Payload` object (where the property is actually present).

The standards documentation shows that field as `mandatory`, but the Description includes a condition -
_An extended string description. Only present if specified by the extensionUType field_

![image](https://user-images.githubusercontent.com/60594671/138243163-4325deae-0e24-43b7-a48b-6f8e1af33b7c.png)

Can these details be clarified?

![image](https://user-images.githubusercontent.com/60594671/138241828-d506c6c9-9e17-434c-a613-5182e2549da4.png)

# DSB Proposed Solution
The current DSB proposal for this issue is in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/414#issuecomment-1217347176)

**Comment by CDR-API-Stream** [comment]
This appears to be a defect and it is proposed that it is simply fixed according to the **Change Proposed** section of the issue.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.19.0...maintenance/414

**Comment by CDR-API-Stream** [comment]
This change has been updated to target v1.20.0: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.20.0...maintenance/414
