### ISSUE TITLE
Modification of energy billing and invoicing enumeration values

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#419]
# Description
In the recently published candidate standards for energy there were a number of enumeration fields included in the payloads.  Initial values and descriptions for these enumerations were defined but these may not be comprehensive

# Area Affected
Energy APIs and payloads

# Change Proposed
Review the enumeration fields across the energy APIs, specifically the billing and invoicing payloads to ensure the enumeration lists are well described and comprehensive

**Comment by priyaH-OriginEnergy** [comment]
**Time Of Use enumeration within “usage” transactions**

This field should be made optional as some C&I usage charges do not have a time band associated with the charges. For example, charges could be based on total consumption, a percentage of total consumption or another calculation method. There needs to be flexibility to be able to support these charges. If this field cannot be made optional then include “FLAT” as an enumeration value

**Enumeration list for usage units & billing units**

Enumeration for quantity unit

- kWh
- kVA
- kVAR
- kVARh
- kW
- Days
- Meter
- Month

Enumeration for rate unit 

- c/kWh
- $/kVA
- $/Day
- c/Day
- $/Meter
- c/Meter
- $/Month
- $/kW
- $/kVAR
- $/kVARh
- c/kVAR
- c/kVARh

**Comment by CDR-API-Stream** [comment]
Thank you for your feedback @priyaH-OriginEnergy 

> **Time Of Use enumeration within “usage” transactions**
> 
> This field should be made optional as some C&I usage charges do not have a time band associated with the charges. For example, charges could be based on total consumption, a percentage of total consumption or another calculation method. There needs to be flexibility to be able to support these charges. If this field cannot be made optional then include “FLAT” as an enumeration value

At the moment we are proposing no change to the "Time Of Use" enumeration because we believe single use charges can accommodate within "onceOff" transaction. 





> **Enumeration list for usage units & billing units**
> 
> Enumeration for quantity unit
> 
> * kWh
> * kVA
> * kVAR
> * kVARh
> * kW
> * Days
> * Meter
> * Month
> 
> Enumeration for rate unit
> 
> * c/kWh
> * $/kVA
> * $/Day
> * c/Day
> * $/Meter
> * c/Meter
> * $/Month
> * $/kW
> * $/kVAR
> * $/kVARh
> * c/kVAR
> * c/kVARh

We will add the above ENUMs within optional fields with kVa as default for quantity unit and $/kVA as default for rate unit.

We can discuss the above changes further in implementation calls and amend the recommendation if required.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.
