### ISSUE TITLE
Modification of energy account enumeration values

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#420]
# Description
In the recently published candidate standards for energy there were a number of enumeration fields included in the payloads.  Initial values and descriptions for these enumerations were defined but these may not be comprehensive

# Area Affected
Energy APIs and payloads

# Change Proposed
Review the enumeration fields across the energy APIs, specifically the account and tariff payloads to ensure the enumeration lists are well described and comprehensive

**Comment by CDR-API-Stream** [comment]
This change request covers, but is not limited to, the following feedback re enumeration values:
* The enumeration list against "fee term" should also include a VARIABLE option to cater to fees where the term is not fixed. For example, if a customer terminates their contract before the agreed end date, they may be charged a variable fee that is calculated using different elements or factors 
* pricingModel – “C&I uses other types of pricing e.g. spot price, progressive purchasing, which do not in any way fit these descriptions. A completely new category for these types of pricing will need to be defined – for consistency.”

Full feedback can be found on decision proposal 197: 
* https://github.com/ConsumerDataStandardsAustralia/standards/issues/197

**Comment by priyaH-OriginEnergy** [comment]
We support both the changes proposed

**Comment by CDR-API-Stream** [comment]
Thank you for the response @priyaH-OriginEnergy .

> * The enumeration list against "fee term" should also include a VARIABLE option to cater to fees where the term is not fixed. For example, if a customer terminates their contract before the agreed end date, they may be charged a variable fee that is calculated using different elements or factors

The above feedback has already been incorporated into v1.14 of the standards.  Given there is no further feedback to the contrary, the DSB will leave it as is.


> * pricingModel – “C&I uses other types of pricing e.g. spot price, progressive purchasing, which do not in any way fit these descriptions. A completely new category for these types of pricing will need to be defined – for consistency.”

Given the lack of feedback with specific changes to address the above feedback, the DSB will not make any changes as part of this CR.  This issue can be revisited in future CRs.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.
