### ISSUE TITLE
Review of rates in energy account payload

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#421]
# Description
In the recently published candidate standards for energy feedback on the representation of pricing and rates, specifically for demand based plans and for C&I customers, was received.  This was not able to be fully addressed during the consultation on the account endpoints

# Area Affected
Energy APIs and payloads

# Change Proposed
Review the existing representation of rates in the energy account details payload with specific reference to C&I customers to determine if changes need to be made

**Comment by CDR-API-Stream** [comment]
This change request covers, but is not limited to, the following feedback about rates:
* "demandCharges", "controlledLoad" and "dailySupplyCharges" blocks within the Account Detail API are not applicable for C&I customers
* unitPrice – “This will need a lot more review for C&I customers. e.g. There is no unit price for a spot price customer. The unit price changes for some customers for different periods and may not be available up front depending on their contract” 

Full feedback can be found on decision proposal 197 
* https://github.com/ConsumerDataStandardsAustralia/standards/issues/197

**Comment by priyaH-OriginEnergy** [comment]
- We support this change and request for these to be made optional → “demandCharges", "controlledLoad" and "dailySupplyCharges" blocks within the Account Detail API are not applicable for C&I customers
- For spot pricing and progressive purchasing contracts, our assumption was to not provide any rates if they were not available. Open to other suggestions

**Comment by CDR-API-Stream** [comment]
> * We support this change and request for these to be made optional → “demandCharges", "controlledLoad" and "dailySupplyCharges" blocks within the Account Detail API are not applicable for C&I customers

We propose the following

- controlledLoad - No changes as this is a conditional object based on pricing model values.  For C&I customers, the appropriate pricing model without controlledLoad could be selected.
- demandCharges - No changes as this is already optional
- dailySupplyCharges - Make it optional to accommodate feedback.

> * For spot pricing and progressive purchasing contracts, our assumption was to not provide any rates if they were not available. Open to other suggestions

The DSB agrees with the above comment and proposes no change to unitPrice . We can revisit this specific item in future maintenance iterations if required.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.
