### ISSUE TITLE
EnergyPlanSolarFeedInTariff.tariffUType enum contains incorrect values

### ISSUE THREAD

**Issue by joe-parkin-aer** [ConsumerDataStandardsAustralia/standards-maintenance#432]
# Description
The `EnergyPlanSolarFeedInTariff.tariffUType` enumeration contains the incorrect values of `GOVERNMENT` and `RETAILER`. These values look to have been accidentally copied down from the `payerType` enumeration.

# Area Affected
This change will affect the `EnergyPlanSolarFeedInTariff` object returned by the `Get Generic Plan Detail` endpoint.

# Change Proposed
The proposed change is for the current enumeration values to be removed and replaced with the correct values of `singleTariff` and `timeVaryingTariffs`.

**Comment by priyaH-OriginEnergy** [comment]
Noted. Thanks!

**Comment by CDR-API-Stream** [comment]
Thank you for raising the change request @joe-parkin-aer. We will make the recommended changes.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.
