### ISSUE TITLE
Data Holder behaviour is not defined when a software product id goes "missing"

### ISSUE THREAD

**Issue by dsbivan** [ConsumerDataStandardsAustralia/standards-maintenance#433]
# Description
The [data holder responsibilities](https://consumerdatastandardsaustralia.github.io/standards/#participant-statuses) section of the CDS outlines the responsibilities for a data holder based on the status of a data recipient and their associated software product. 

There is currently no specifications on how a data holder should treat a software product if their status is no longer published on the [status APIs](https://consumerdatastandardsaustralia.github.io/standards/#get-data-recipient-software-products-statuses).

It is conceivable that the CDR Register could inadvertently publish missing software products or an empty array at the status API. This scenario would currently lead to ill-defined behaviour. It is conceivable data holders may be treating a missing software product the same way as a software product that has reached its end state. This would then lead to consents being invalidated.

A certain level of tolerance should be considered if the CDR Register mis-publishes status information.

# Area Affected
Data holder responsibilities within the [participant statuses](https://consumerdatastandardsaustralia.github.io/standards/#participant-statuses) section

# Change Proposed
Specification needs to be provided to define Data Holder behaviour for software products that are no longer published on the CDR Register Status APIs.

**Comment by CDR-API-Stream** [comment]
This issue highlights the need to prevent an outage affecting 1 or more data recipients if there is an issue deploying status information on the Register status endpoints.

## The change proposed is as follows:
The [Participant Statuses](https://consumerdatastandardsaustralia.github.io/standards/#participant-statuses) section of the CDS will be updated to state the following:

If an entity, which has not reached an end state, is not returned from the status endpoint, or a status is returned that does not match those described in the state model (e.g. blank string), the data holder must continue to use the previous status value retrieved.

Once the entity and status returned aligns to the [state model](https://consumerdatastandardsaustralia.github.io/standards/#participant-statuses), the data holder must react to this status as described in the[ Data Holder Responsibilities](https://consumerdatastandardsaustralia.github.io/standards/#participant-statuses) matrix

**Comment by biza-io** [comment]
While Biza.io supports the intent of this change we note that the _normal_ behaviour of the CTS is to behave in the error condition noted (_"issue deploying status information"_). This has cascading atomicity issues in a scenario where _many_ software products go missing (as is the case in CTS).

**Comment by WestpacOpenBanking** [comment]
Westpac recommends putting an upper bound on the validity period of an active state to prevent undetected errors introducing potential security issues. That is we recommend to amend the proposed change by modifying the statement “…the data holder must continue to use the previous status value retrieved.” to “…the data holder must continue to use the previous status value retrieved for a period of 24 hours.”

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/212) for further details.

**Comment by CDR-API-Stream** [comment]
@WestpacOpenBanking I have raised issue #453 to work through your recommendation of adding an upper bound to this period.
