### ISSUE TITLE
rfc2119 broken link

### ISSUE THREAD

**Issue by ALiu-DA** [ConsumerDataStandardsAustralia/standards-maintenance#436]
# Description
http://tools.ietf.org/html/rfc2119 is broken. When i search in google for RFC2119, the link shows this instead: https://datatracker.ietf.org/doc/html/rfc2119
The URL redirection probably broke on a wrong day for me when I encountered this the week before. It seems to be working now though. 

![Screenshot 2021-11-15 130447](https://user-images.githubusercontent.com/94575946/142299089-f84b7197-6437-44ef-a0d0-a6ab9db30672.png)
# Area Affected
![Screenshot 2021-11-15 130442](https://user-images.githubusercontent.com/94575946/142298521-7f92e49f-aa00-4586-8e4f-385599236df9.png)

# Change Proposed
Use the correct URL in the hyperlink

**Comment by CDR-API-Stream** [comment]
@ALiu-DA Thank you for raising this issue.

We encountered the same issue as yourself, receiving 404s from the link initially and after several requests, the redirect seemed to resolve.

We have addressed this issue by linking directly to datatracker.ietf.org.


This change was incorporated into [release v1.16.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.16.0.html#v1-16-0-release-notes).
