### ISSUE TITLE
GetAccountDetails API : BankingLoanAccount Object - Request to change Mandatory fields to Optional

### ISSUE THREAD

**Issue by Sohini-Gupta** [ConsumerDataStandardsAustralia/standards-maintenance#437]
# Description
In the [BankingLoanAccount ](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingloanaccount)Object, following attributes should be changed from Mandatory to Optional:

- LoanEndDate
- nextInstalmentDate
- repaymentFrequency

For loans where the loan funds have not been disbursed, the LoanEndDate and nextInstalmentDate are not known until the funds have been disbursed.

For closed loan accounts, the nextInstalmentDate and repaymentFrequency are either not applicable or not held in digital form.

In order to share the BankingLoanAccount Object the fields have to be made optional so that these fields do not have to be returned in the API. We need this change because the direction we received from ZenDesk is that a mandatory attribute can not be left unpopulated as that would be non-compliant with the standards.

# Area Affected
This will Impact GetAccountDetails API BankingLoanAccount Object, attribute list as below:
- LoanEndDate
- nextInstalmentDate
- repaymentFrequency

# Change Proposed
In the GetAccountDetails API [BankingLoanAccount ](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingloanaccount)Object, following attributes should be changed from Mandatory to Optional:

- LoanEndDate
- nextInstalmentDate
- repaymentFrequency

**Comment by perlboy** [comment]
Believe this already covered https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/150

**Comment by nils-work** [comment]
This change was delivered through [issue 150](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/150#issuecomment-1000569092).

The difference in the Standards can be viewed by comparing the archives of the **BankingLoanAccount** schema from [v1.14.0](https://consumerdatastandardsaustralia.github.io/standards-archives/standards-1.14.0/#schemacdr-banking-apibankingloanaccount) (the initial version) and [v1.15.0](https://consumerdatastandardsaustralia.github.io/standards-archives/standards-1.15.0/#tocSbankingloanaccountv2) (version 2).
