### ISSUE TITLE
Representing adjustment transactions within the Billing Payload for C&I customers

### ISSUE THREAD

**Issue by priyaH-OriginEnergy** [ConsumerDataStandardsAustralia/standards-maintenance#438]
# Description
Adjustments are currently only displayed as relating to usage transactions whereas for C&I adjustments can arise due to various reasons (that are not usage related) such as environmental rate update, tariff change, etc. 

# Area Affected
Energy APIs and payloads

# Change Proposed
Options to denote back dated adjustments (may or may not be usage related)

- Use “otherCharges” if an enumeration can be added for “adjustments”
- Introduce a new category of charge type for adjustments

Attributes to include: start & end date, quantity, rate, reason, calculation factor (similar structure to usage transactions, but made optional to cater to non-usage adjustments)

**Comment by CDR-API-Stream** [comment]
Given this change request was raised late during the iteration, the DSB proposes it be carried over to the next maintenance iteration.

**Comment by CDR-API-Stream** [comment]
The DSB proposes the following amendment to the [otherCharges](https://consumerdatastandardsaustralia.github.io/standards/#tocSenergybillingothertransaction) schema to cater for the issue raised in the CR. 

```json
"otherCharges": {
  "servicePointId": "string",
  "invoiceNumber": "string",
  "startDate": "DateString",
  "endDate": "DateString",
  "type": [ "ENVIRONMENTAL", "REGULATED", "NETWORK", "METERING", "RETAIL_SERVICE", "RCTI", "OTHER"],
  "amount": "AmountString",
  "description": "string",
  "calculationFactors": [ //Optional object to capture additional calculation factors that inform the transaction
    {
      "value": "number",
      "type": [ "DLF", "MLF"]
    }
  ],
  "adjustments": [ //Optional array of adjustments arising for this transaction
    {
      "amount": "AmountString",
      "description": "string"
    }
  ]
}
```
The change involves including 'calculationFactors' and 'adjustments' arrays within ‘otherChargers’. The arrays are currently used within the usage and demand charges of [EnergyBillingTransaction](https://consumerdatastandardsaustralia.github.io/standards/#tocSenergybillingtransaction). 

This should allow consistent representation of any calculation factors (i.e. DLF or MLF) used for deriving other charges and any adjustments arising from other types of charges such as environmental charge.

**Comment by Ram-Origin** [comment]
Hi DSB,

The proposed changes address the problem and agree with the solution proposed.

Regards,
Ram

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.17.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.17.0.html#v1-17-0-release-notes). Refer to https://github.com/ConsumerDataStandardsAustralia/standards/issues/237 for further details.
