### ISSUE TITLE
Review Pricing Model & Time Zone attributes within Account Detail Payload

### ISSUE THREAD

**Issue by priyaH-OriginEnergy** [ConsumerDataStandardsAustralia/standards-maintenance#439]
# Description
Pricing Model & Time Zone should be represented at the charge level not at the plan level

# Area Affected
Energy APIs - Account Detail API

# Change Proposed
Pricing Model (such as TOU, Single Rate etc.) and Time Zone for C&I customers are specific to charge categories such as usage, environmental, metering etc. and can therefore vary. These attributes are currently defined at the plan level within the Account Detail API, these should instead be defined at a charge category level

**Comment by CDR-API-Stream** [comment]
Given this change request was raised late during the iteration, the DSB proposes it be carried over to the next maintenance iteration.

**Comment by CDR-API-Stream** [comment]
@priyaH-OriginEnergy, could you provide an example use case or scenario that can help understand the problem.  It will help work through solution options.

**Comment by CDR-API-Stream** [comment]
To help facilitate discussion, the DSB would like to summarise our understanding of the problem:

1. A C&I customer can have an energy contract with different pricing models applied to different charges.  For example, there could be environmental charges that are based on time of use whilst the usage charges could be single rate
2. The time zone in which certain charges have the time of use threshold calculated can also be different per charge
3. Currently, both pricing model and time zone are specified at the contract level

If the above understanding is correct, the current structure should allow representation of point 1 within the [EnergyPlanTariffPeriod](https://consumerdatastandardsaustralia.github.io/standards/#tocSenergyplantariffperiod) schema using the ‘type’ attribute to specify the charge type (e.g. ENVIRONMENTAL) and specifying rateBlockUType as timeOfUseRates.

The second point can be addressed by including an optional ‘timeZone’ attribute within EnergyPlanTariffPeriod so charge specific time zones can be provided.  If absent, contract level timezone would be assumed.

**Comment by Ram-Origin** [comment]
Hi DSB,

The above statement is correct for first point and agree with the solution proposed. 
With the second agree with the the proposed solution for time zone attribute.

Regards,
Ram

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.17.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.17.0.html#v1-17-0-release-notes). Refer to https://github.com/ConsumerDataStandardsAustralia/standards/issues/237 for further details.
