### ISSUE TITLE
RegisterDataHolderAuth schema in GetDataHolderBrands descriptions to be clarified

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#441]
This issue has been raised to track [CDR Register issue 189](https://github.com/ConsumerDataStandardsAustralia/register/issues/189) through the standards maintenance process.

Please refer to [CDR Register issue 189](https://github.com/ConsumerDataStandardsAustralia/register/issues/189) for details

**Comment by perlboy** [comment]
Ideally CDR specific metadata for both Holders and Recipients is advertised at a well-known endpoint designated as such (ie. `/.well-known/cdr-configuration`). Given the likelihood of changes to the Register in 2022 it seems there may be greater mileage in effectively retiring this part of the Holder Brands response in favour of the definition of a base uri providing such a document.

**Comment by CDR-API-Stream** [comment]
@perlboy Thanks for your comments.

Feature negotiation and change management are topics we will focus on early this year. Opportunities for improvement for advertising endpoints will be a good topic to cover in this piece of work.

I will provide a link once this decision proposal is created.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/212) for further details.
