### ISSUE TITLE
Documentation improvement: JWT Signature verification requirements during the DCR flows

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#442]
This issue has been raised to track [CDR Register issue 186](https://github.com/ConsumerDataStandardsAustralia/register/issues/186) through the standards maintenance process.

Please refer to [CDR Register issue 186](https://github.com/ConsumerDataStandardsAustralia/register/issues/186) for details

**Comment by perlboy** [comment]
Does the CTS support ES256 signed DCR requests yet? If not it will be difficult to formally document these requirements because the Regulators own toolset would have a 100% failure rate of otherwise compliant parties.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/212) for further details.

**Comment by CDR-API-Stream** [comment]
@perlboy I'll leave this ticket open for the CTS team to provide a response to your inquiry

**Comment by ACCC-CDR** [comment]
Thank you for your query @perlboy. ACCC confirms that CTS does support ES256 signed DCR requests.

**Comment by perlboy** [comment]
> Thank you for your query @perlboy. ACCC confirms that CTS does support ES256 signed DCR requests.

Does this include testing whether Data Recipients properly support ES256 for all operations?
