### ISSUE TITLE
Query about TLS renegotiation

### ISSUE THREAD

**Issue by JoeGunnion** [ConsumerDataStandardsAustralia/standards-maintenance#446]
As per CDR Tech team we have been informed to raise this issue with Standards Maintenance and a Zendesk Query #1240

Request as a result of ADR - Fiskil - testing
**Summary:**
TLS renegotiation is enabled on our server and Fiskil was expecting it not to be. By temporarily enabling it on their end, Fiskil was able to bypass the issue.
**Query :**
Do we, at CFCU,  need to specify the disable flags in the registry on our server to NOT allow TLS renegotiation? Our server is not specifying the disable flag and is enabled hence expecting TLS renegotiation
Please advise

Regards,
Joseph Gunnion

**Comment by nils-work** [comment]
Hi @JoeGunnion 

Just acknowledging that this is an older issue and the CDR Support Portal query (Zendesk 1240) appears to have been responded to.

In reply to your question though, the Standards are silent on the specifics of TLS renegotiation, but do provide requirements for [Transaction Security](https://consumerdatastandardsaustralia.github.io/standards/#transaction-security) including specifying TLS >= 1.2, the use of MTLS, and also references to other normative standards.

Further questions such as this may now be directed to the [CDR Support Portal](https://cdr-support.zendesk.com/hc/en-us).
