### ISSUE TITLE
EnergyPlanDiscounts contains optional fields that should be conditional

### ISSUE THREAD

**Issue by joe-aer** [ConsumerDataStandardsAustralia/standards-maintenance#448]
# Description
The following fields of the `EnergyPlanDiscounts` object are marked as optional when they should be conditional based on the value of the `methodUType` field:

- `percentOfBill`
- `percentOfUse`
- `fixedAmount`
- `percentOverThreshold`

# Area Affected
This change will affect the `EnergyPlanDiscounts` object returned by the `Get Generic Plan Detail` endpoint.

# Change Proposed
The proposed change is for these fields to be marked as conditional, both in documentation and in the Energy Swagger docs.

**Comment by CDR-API-Stream** [comment]
These changes have been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.16.1...maintenance/448

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.17.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.17.0.html#v1-17-0-release-notes). Refer to https://github.com/ConsumerDataStandardsAustralia/standards/issues/237 for further details.
