### ISSUE TITLE
EnergyPlanSolarFeedInTariff days field should be mandatory

### ISSUE THREAD

**Issue by joe-aer** [ConsumerDataStandardsAustralia/standards-maintenance#449]
# Description
The `EnergyPlanSolarFeedInTariff.timeVaryingTariffs.timeVariations.days` field is marked as optional when it should be mandatory.

With this field as optional along with the other `timeVaryingTariffs` optional fields, a time varying tariff can be configured without any element of time variation, i.e. a `singleTariff`.

# Area Affected
This change will affect the `EnergyPlanSolarFeedInTariff` object returned by the `Get Generic Plan Detail` endpoint.

# Change Proposed
The proposed change is for the `days` field to be marked as mandatory, both in documentation and in the Energy Swagger docs.

**Comment by CDR-API-Stream** [comment]
These changes have been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.16.1...maintenance/449

**Comment by perlboy** [comment]
This diff has been polluted with version bumps?

**Comment by CDR-API-Stream** [comment]
Apologies, the above compare link was incorrect.  Here is the correct link: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.17.0...maintenance/449

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.17.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.17.0.html#v1-17-0-release-notes). Refer to https://github.com/ConsumerDataStandardsAustralia/standards/issues/237 for further details.
