### ISSUE TITLE
(v1.13.0) Code samples for GetOpenIdProviderConfig and GetJWKS incorrectly changed example URLs as part of merge of registry standards

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#450]
# Description
The code samples for the GetOpenIdProviderConfig and GetJWKS endpoints have changed in a way which appears to be unintentional as part of the merge of the registry standards in v1.13.0. In particular both of those code samples now use ‘https://register.cdr.gov.au’ instead of ‘<register-base-url>’, but the register base URL is still https://api.cdr.gov.au. This change appears to be unintentional as it was not noted in the change log and the new code samples are non-functional.

# Area Affected
[GetOpenIdProviderConfig](https://consumerdatastandardsaustralia.github.io/standards/) and [GetJWKS](https://consumerdatastandardsaustralia.github.io/standards/) endpoint code samples

# Change Proposed
Substitute ‘[https://register.cdr.gov.au/](https://register.cdr.gov.au/)’ for ‘[https://api.cdr.gov.au/](https://api.cdr.gov.au/)’ in the code samples for the relevant endpoints.

**Comment by nils-work** [comment]
Hi @WestpacOpenBanking
This issue appears to have been partially resolved [from version 1.15.0](https://consumerdatastandardsaustralia.github.io/standards/#archives) of the Standards (See current [Register APIs](https://consumerdatastandardsaustralia.github.io/standards/#register-apis)). 
A [related issue](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/552) has been raised to further review references to Base URLs and paths in code samples.

**Comment by nils-work** [comment]
Hi @WestpacOpenBanking 

As noted [above](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/450#issuecomment-1318157079), the code samples now refer to `<register-base-url>` and the Register API [Base URLs](https://consumerdatastandardsaustralia.github.io/standards/index.html#base-urls) appear to align to your proposed change.

Please add a comment if there are further concerns, or this issue will be closed on 25 August 2023.

Thanks

**Comment by nils-work** [comment]
Closing as noted in the [previous comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/450#issuecomment-1631992929). No impact to the Standards.
