### ISSUE TITLE
cds_banking.yaml & cds_banking.json both reference a definition which does not exist.

### ISSUE THREAD

**Issue by tomred-net** [ConsumerDataStandardsAustralia/standards-maintenance#454]
# Description
cds_banking.yaml & cds_banking.json both reference a definition which does not exist.

Specifically cds_banking.yaml refers to $ref: '#/definitions/ResponseBankingProductList':1472 which does not exists in definition. This I expect is a bug as ResponseBankingProductList seems to have been replaced by ResponseBankingProductListV2.

# Area Affected
cds_banking.yaml:1472
cds_banking.json:1676
```
  /banking/products
    responses:
      "200": 
        schema:
          $ref: '#/definitions/ResponseBankingProductList'
```
# Change Proposed
cds_banking.yaml:1472
~~$ref: '#/definitions/ResponseBankingProductList'~~ > $ref: '#/definitions/ResponseBankingProductListV2' 

cds_banking.json:1676
~~"$ref" : "#/definitions/ResponseBankingProductList"~~ > "$ref" : "#/definitions/ResponseBankingProductListV2"
```
  /banking/products
    responses:
      "200": 
        schema:
          $ref: '#/definitions/ResponseBankingProductListV2' 
```

**Comment by CDR-API-Stream** [comment]
@tomred-net Thank you for raising this issue.

This change was incorporated into [release v1.16.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.16.0.html#v1-16-0-release-notes).

The cds_banking swagger files have been updated so the `ResponseBankingProductListV2` definition is used. This can also be reflected in the schema documentation:

![image](https://user-images.githubusercontent.com/52149325/152705460-56dd418b-3dee-4537-82fc-65dff1078706.png)
