### ISSUE TITLE
Duplicate Section "Data Holders calling Data Recipients" in Client Authentication (Security Profile)

### ISSUE THREAD

**Issue by abhishekv290691** [ConsumerDataStandardsAustralia/standards-maintenance#455]
# Description
The section "Data Holders calling Data Recipients" is repeated twice.
![image](https://user-images.githubusercontent.com/49511747/148713313-4d7b7783-95c6-4879-b501-73fe04e804f8.png)

# Area Affected
Client Authentication Section under Security Profile

# Change Proposed
 The first one should be "CDR-Register Calling Data Holders"

**Comment by CDR-API-Stream** [comment]
@abhishekv290691 Thanks for raising this issue and yes you are correct, there is duplication here in the documentation..

This change was incorporated into [release v1.16.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.16.0.html#v1-16-0-release-notes). 

The [Client Authentication](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) section has been updated to remove this duplication.
