### ISSUE TITLE
Energy - Get Service Point Detail register suffix should be optional

### ISSUE THREAD

**Issue by OpalRussAEMO** [ConsumerDataStandardsAustralia/standards-maintenance#457]
### Description

Register suffix is specified as mandatory for the energy Get Service Point Detail API.  
AEMO require this field to be changed to optional to allow for service points in MSATS with older meter / register records that do not have this information captured and for which a value cannot be derived.  

### Area Affected
Affected URL [https://consumerdatastandardsaustralia.github.io/standards/#tocSenergyservicepointdetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSenergyservicepointdetail)

### Change Proposed
Please change "Required" from mandatory to optional for RegisterSuffix

![image](https://user-images.githubusercontent.com/94660449/150294238-b830d6a5-a2c1-4e24-b402-c5ae0375b6e2.png)

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.17.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.17.0.html#v1-17-0-release-notes). Refer to https://github.com/ConsumerDataStandardsAustralia/standards/issues/237 for further details.
