### ISSUE TITLE
Point in time from which a consent should be considered valid

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#46]
# Request For Clarification
There are a number of steps in the Hybrid flow which is initiated at the data recipient. At which point in this flow should a customer be considered to have granted consent (triggering consequent update of consent dashboards)? 

Options for consideration include:
1.	After the customer has pressed the authorise button and the authorisation has been successfully recorded in the data holder’s systems.
2.	At the point where the customer is redirected back to the data recipient from the data holder following a successful authorisation.
3.	At the point where the data recipient claims the access token from the token endpoint.
4.	Data holder discretion.

**Comment by anzbankau** [comment]
ANZ's expectation was option 1

**Comment by spikejump** [comment]
From Intuit's perspective successful consent/authorisation is established after DR gets access & refresh tokens.  Without tokens DRs can't do anything even if DHs consider completion of consent immediately after click of a button by customers.

**Comment by CDR-API-Stream** [comment]
In responding to this question the specific question asked in the issue will be addressed.  This interpreted as "when should the consent appear in the Data Holder dashboard".

From a standards perspective this is not specifically determined and is left to the Data Holder's discretion.
