### ISSUE TITLE
Documentation Improvement: EnergyPlanContract.variation

### ISSUE THREAD

**Issue by DannyDuong** [ConsumerDataStandardsAustralia/standards-maintenance#461]
# Description
The EnergyPlanContract.variation is a conditional field, but the condition described is wrong and needs to be corrected.

# Area Affected
Energy APIs - Get Generic Plan Detail

# Change Proposed
Change the Properties Description for the EnergyPlanContract.variation field.

From:
Free text description of price variation policy and conditions for the contract. Mandatory if isFixed is true

To:
The Free text description of price variation policy and conditions for the contract. Mandatory if isFixed is **false**

**Comment by CDR-API-Stream** [comment]
This CR is now included in MI11. This is a result of re-prioritisation work the DSB carried out as per action raised in [MI11 session](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(25-May-2022)) on 25th May.

This will be addressed as documentation fix as part of CR https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/511.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.18.0...maintenance/461

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.18.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.18.0.html#v1-18-0-release-notes). Refer to [Decision 249](https://github.com/ConsumerDataStandardsAustralia/standards/issues/249) for further details.
