### ISSUE TITLE
Account holder name(s)

### ISSUE THREAD

**Issue by JohnHarrison-Truelayer** [ConsumerDataStandardsAustralia/standards-maintenance#463]
# Description

The Get Accounts API does not currently provide account holder name(s). Use cases such as verification and validation would benefit from this extra data. Currently, it is only possible to determine whether the consenting user owns the account using the isOwned flag in the [BankingAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccount) object which may be a poor proxy. 

# Area Affected

The [BankingAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccount) object definition.

# Change Proposed

- Add an accountHolderNames list to the [BankingAccount](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingaccount) definition. This list would be mandatory. 

    - Each element of the list would contain an account holder name as a string. 
    - If known, it would be helpful to identify the account holder as a person or organisation. 

- Depending on the perceived sensitivity the data could be made available only when the bank:accounts.detail:read scope is provided.

**Comment by CDR-API-Stream** [comment]
Hi @JohnHarrison-Truelayer is there a reason you cannot request the `common:customer.basic:read` and/or `profile` scopes to obtain the name of the consumer establishing consent?

**Comment by perlboy** [comment]
@CDR-API-Stream Because @JohnHarrison-Truelayer is looking for the _other_ account holder names I believe.

**Comment by nils-work** [comment]
If I've understood this request correctly, I don't think it would be permitted under the Rules, for the reasons stated in this [related comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/513#issuecomment-1217288825).

**Comment by nils-work** [comment]
This issue will be considered as a query with an answer provided and scheduled to be closed on 19 May 2023 if there are no further comments or changes to the Standards expected as an outcome.
