### ISSUE TITLE
Use of Open Data Principles

### ISSUE THREAD

**Issue by riannella** [ConsumerDataStandardsAustralia/standards-maintenance#466]
Hi, Was wondering if the use of "open data principles" has been discussed by this group (and/or decisions made)?

Specifically was keen to see how all the "enumerated values" can be turned from "strings" to "things".
That is, use URIs to identify each, which are resolvable in a vocabulary service.

So, instead of (string) categories like "BUSINESS_LOANS" and "TERM_DEPOSITS", these are URIs.
(note, they still can be parsed as strings, but the URI will enable global uniqueness, compassion, and sameness - as well as the possibility to resolve them and return more metadata...eg SKOS)

As well, the move towards supporting JSON-LD is highly recommended to support identity, typing, lists...and mapping to semantic models.

Look forward to your responses...

Cheers - Renato

**Comment by nils-work** [comment]
As part of a backlog review in Maintenance Iteration 21, it was [suggested](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Meeting-notes-(18-September-2024)#issues-that-will-be-closed) that this issue could be closed. 
If there are no further comments, this issue will be closed on 25 October 2024.
