### ISSUE TITLE
Missing link between Account and Plan

### ISSUE THREAD

**Issue by rvillaes** [ConsumerDataStandardsAustralia/standards-maintenance#467]
# Description
There is no direct link between Account and Plan associated with it.

# Area Affected
API - Get Energy Account Detail

# Change Proposed
Include Plan ID in the response in the **Get Energy Account Detail** API. The Plan ID is required in getting the plan details associated to this account using the **Get Generic Plan Detail** API.

**Comment by CDR-API-Stream** [comment]
@rvillaes, Get Energy Account Detail is not expected to include a Plan ID as instantiated plans are not expected to be directly linked to the generic plans base in Get Generic Plans. This is similar to how it is done in banking as well.

**Comment by nils-work** [comment]
As part of a backlog review in Maintenance Iteration 21, it was [suggested](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Meeting-notes-(18-September-2024)#issues-that-will-be-closed) that this issue could be closed. 
If there are no further comments, this issue will be closed on 25 October 2024.
