### ISSUE TITLE
Timezone of "High Traffic Period"

### ISSUE THREAD

**Issue by james-callahan** [ConsumerDataStandardsAustralia/standards-maintenance#47]
# Request For Clarification
"High Traffic Period" is defined as:
> Any time in the 18 hour period between 6am and 12am (midnight) is considered to be a high traffic period

In which timezone is this specified?
  - UTC (normal for computer specifications)
  - Timezone of the server
  - Timezone of the server owner's headquarters
  - Timezone of the customer
  - Timezone of the data recipient

If not UTC, then what should occur on the days before/after daylight savings?

**Comment by CDR-API-Stream** [comment]
These times are to be interpreted as being expressed in Australian Eastern Standard Time.

**Comment by james-callahan** [comment]
> These times are to be interpreted as being expressed in Australian Eastern Standard Time.

Is that to be understood as permanent AEST? As in ignoring Australian Eastern Daylight Time?

If not, what is the expected behaviour around daylight savings changes?

**Comment by CDR-API-Stream** [comment]
For simplicity it is understood as permanent AEST.  The time window was selected to be reasonable for the various timezones across Australia (ie. to include WA) and to accommodate movement for DST.
