### ISSUE TITLE
Add RFC8174 to list of normative references and update the use of Requirements Levels

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#473]
# Description
[RFC8174 - Ambiguity of Uppercase vs Lowercase in RFC 2119 Key Words](https://datatracker.ietf.org/doc/html/rfc8174) provides an update to normative reference [RFC 2119 - Key words for use in RFCs to Indicate Requirement Levels](https://datatracker.ietf.org/doc/html/rfc2119) for Requirement Levels such that requirement levels must be capitalised. This change considers the options for inclusion of RFC8174 as a normative reference and standardisation of requirements level usage in the Data Standards to be capitalised.

# Area Affected
Normative References - Requirements Levels and non-capitalised usage of requirement levels.

# Change Proposed

A) Update all usage of requirements levels to adopt the capitalised form.
B) Update normative references with [RFC8174] _in addition to_ [RFC2119]
C) Update the Data Standards [introduction](https://consumerdatastandardsaustralia.github.io/standards/#interpretation) with respect to requirements levels as appropriate with reference to [RFC8174]

Optionally:
Community feedback has also identified [BCP14 - Key words for use in RFCs to Indicate Requirement Levels](https://tools.ietf.org/rfc/bcp/bcp14) as an option for best practice usage of requirements levels and usage within the Data Standards. This best practice document communicates the appropriate use of words and capitalisation similar to RFC8174.

Further analysis:
Analysis of the update are published here: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/reviews/2021-05/analysis/analysis-rfc2119-rfc8174-20210519.md

# DSB Proposed Solution
The current DSB proposal for this issue is in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/473#issuecomment-2139255321.
The other changes noted in this issue will be carried forward to a new issue.

**Comment by nils-work** [comment]
As a starting point, proposing the following changes to be made:

- Replace 'must' with '**MUST**' in the following sentence:
  > An [**[RFC4122]**](https://consumerdatastandardsaustralia.github.io/standards/index.html#nref-RFC4122) UUID used as a correlation id. If provided, the data holder **MUST** play back this value in the _x-fapi-interaction-id_ response header. If not provided a [**[RFC4122]**](https://consumerdatastandardsaustralia.github.io/standards/index.html#nref-RFC4122) UUID value is required to be provided in the response header to track the interaction.
- Replace 'must' with '**MUST**' in the following sentence:
  > If all versions requested are not supported then the data holder **MUST** respond with a `406 Not Acceptable`.

**Comment by nils-work** [comment]
[This initial update](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/473#issuecomment-2139255321) has been staged - https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/450/files
