### ISSUE TITLE
Energy - Representation of Spot price based contracts for C&I customers

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#475]
# Description
In a workshop held with Australian Energy Council (AEC) last year, it was highlighted that Commercial & Industrial (C&I) customers can have spot pricing based contracts.

The DSB is unclear on how best to represent such contracts and is raising this CR for input/feedback.

# Area Affected
Energy Account APIs

**Comment by CDR-API-Stream** [comment]
The AEC and DSB held a workshop  on December 1 2022 to review the standards and identify any potential changes required to accommodate C&I consumers and Spot price base contracts.  No significant changes to the standards were identified.

Below are the notes from the discussion:

### **Get Energy Accounts/Get Energy Account Detail**
|**Questions**|**Feedback**|
|----|----|
|Are metering charges applicable to spot price contracts? <br />Are there any changes required to meteringCharges? | • Metering charges can be applicable for spot price contracts; they could be a pass-through charge under a DMA (direct metering agreement) or SLA metering charge. <br />• No change to standards identified as current structure appears suitable|
|Are the ENUM values currently defined for EnergyPlanContract.pricingModel sufficient to represent C&I or spot price based contracts?|• The current `FLEXIBLE` ENUM value describes spot price precisely. Structure/ENUM values suitable for C&I contracts and no further changes required<br />• Only other contract that could fit under `FLEXIBLE` ENUM value is Flexible Power Purchase agreement (FPP) which gives consumers flexible pricing (which is not too dissimilar to spot price).  FPP are flexible contracts where customers can purchase their electricity in blocks. A rate is determined every year/quarter, gives customer flexibility.<br /> • Adding a new ENUM value specifically for spot price contracts (e.g. `SPOT_PRICE`) could help apply conditionality to various objects/fields was discussed but no such need was identified.<br />• No change/new ENUM required.|
|Is EnergyPlanContract.greenPercentage applicable to C&I consumers or spot price contracts?|• Participant feedback stated C&I consumers can take on green power.<br />• However, current structure deemed suitable to cater for C&I consumers and no change to standard identified|
|Is EnergyPlanControlledLoad applicable to plans for C&I consumers (including spot price based)|• Controlled Load is for residential customers to heat water, or underfloor heating.<br />• It is unlikely that C&I meter will have controlled load, will be rare especially on spot price contract.<br />• No standards change required/identified|
|Is EnergyPlanTariffPeriod applicable to plans for C&I consumers (including spot price based)?|• Participants don’t anticipate any challenges in providing data for the tariff structure for C&I consumers|
|General Comments|• Participants don’t anticipate any challenges in providing data for the tariff structure for C&I consumers|

<br />

### **Get Agreed Payment Schedule**
|**Questions**|**Feedback**|
|----|----|
|Are the current payment agreement/schedule sufficient to cater C&I consumers?|• Existing structure is suitable for C&I consumers<br /> • No standards change required/identified|

<br />

### **Get Concessions**
|**Questions**|**Feedback**|
|----|----|
|Do C&I consumers receive concessions/rebates?|• Yes, C&I consumer can, for e.g. in QLD for embedded network concession can be applied.<br />• Current structure is flexible enough to cater for C&I consumers.  There may be need to revisit the ENUMS for appliedTo field|

<br />

### **Get Balance For Energy Account**
|**Questions**|**Feedback**|
|----|----|
|Assuming current structure is sufficient to reflect balance of a given C&I consumer account|• C&I consumers can have current and outstanding balance (carried forward from a previous period of time). Current API only caters for current balance<br />• The intent of balance API is to only return current outstanding balance. If the need for sharing carried over balance is identified the structure can be updated|

<br />

### **Get Invoices For Account**
|**Questions**|**Feedback**|
|----|----|
|What changes are required to the EnergyInvoice structure to cater for C&I consumers (including ones on spot price based contracts)? Note: Most of the fields/objects are optional|• Participants don’t anticipate any changes given the blend of mandatory and optional elements here<br />• No standards change required/identified|

<br />

### **Get Billing For Account**
|**Questions**|**Feedback**|
|----|----|
|What changes are required to the EnergyBillingTransaction structure to cater for C&I consumers (including ones on spot price based contracts)?|• Existing structure is suitable for C&I consumers, don’t anticipate any issues given the blend of mandatory and optional fields<br />• No standards change required/identified|

<br />

### **Other Items**
|**Topic**|**Feedback**|
|----|----|
|**CX Considerations**|• C&I customers can have up to 1000 accounts. In terms of consent flow and accounts selection - how will that show up for C&I consumers?<br />• Another retailer stated they are not in need in more prescription to address the C&I customer from CX. Happy with the flexibility from the guidelines|

<br />

### Next Steps
- This change request will be closed as no changes have been identified thus far
- The DSB will raise a separate decision proposal to consult on any further changes for C&I consumers that may be identified at a later stage

**Comment by nils-work** [comment]
The decision proposal mentioned in the [previous comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/475#issuecomment-1343903524) can be found here - https://github.com/ConsumerDataStandardsAustralia/standards/issues/287
