### ISSUE TITLE
Provide timeline of when multiple sectors per data holder brand will be supported

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#481]
# Description
Issue #424 and #425 introduced changes to the Register API to support multiple sectors, specifying changes to the API path and payload definitions.

However, as part of this change, a constraint was defined that in the short-term, data holder brands will only be able to align to a single sector:

> ### Add Constraint to Data Holder Brand to support one industry only
> **Rationale:**
> With the introduction of the energy sector to the Consumer Data Right, the relationship between data holder brands and sectors needs to be defined.
> 
> With the initial roll-out of energy, the current model will NOT change and data holders which span multiple industries will be required to create one brand per industry on the CDR Register.
> 
> Further design work is scheduled to examine how multiple industries may be facilitated by one brand on the CDR Register. This work will happen in parallel but is not guaranteed to be complete and available in the initial energy rollout timeframe.

This issue has been raised to track when multiple industries/sectors may be facilitated by one brand on the CDR Register

# Area Affected
Schema definition [RegisterDataHolderBrand ](https://consumerdatastandardsaustralia.github.io/standards/#tocSregisterdataholderbrand)

The following statement would need to be updated:

![image](https://user-images.githubusercontent.com/52149325/155431956-798a3fd6-e46a-48fe-8395-5f1eb55fbe07.png)

# Change Proposed
A date will need to be specified for when this constraint will be lifted

**Comment by perlboy** [comment]
Not sure if this is the right place but it relates to the screenshot posted above. It is unclear at this stage how a single brand can represent multiple legal entities. Existing energy providers have a long list of legal entities (and consequently Financially Responsible Market Participants) courtesy of acquisitions, mergers etc. but retail them out a single branded channel. The Register does not appear to currently cater to this problem space and I suspect the `industries` definition is the tip of the iceberg.

**Comment by CDR-API-Stream** [comment]
The DSB is keen to get feedback from participants on how their data holder brands will span multiple industries/sectors.

This will help identify the priority of this issue, as well as ensure the use cases for cross-sector support are well understood.

**Comment by perlboy** [comment]
Have a common CX language for common or use separate scopes for starters: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/485#issuecomment-1153055262

Energy in particular already has Telco brands and already sells it under the same brand as far as the consumer is concerned. I think it's probably going to be necessary that registrations and consent flows are going to be cross sector. Separating brands per industry is likely to be confusing to consumers.

**Comment by CDR-API-Stream** [comment]
@perlboy thanks for your input. The intersection between energy and telco is an important data point and would indicate a cross-sector entity model would need to be in place for the introduction of telco.

However, is there demand for a cross-sector entity model to support the intersection of banking and energy? It would be beneficial for participants to provide insight here so priorities can be determined.

Does the ACCC have any operational insight into the demand for cross-sector support for the banking and energy sectors?

**Comment by ACCC-CDR** [comment]
In relation to the ‘industries’ value of the response to the Get Data Holder Brands API, this will not be a constraint as a result of the CDR Register entity model when the ACCC has released v2 of the Get Data Holder Brands API. The ACCC has updated the entity model to ensure that a single data holder brand can support multiple sectors.

In response to the recent comment by @CDR-API-Stream, currently the ACCC is not aware of any Data Holders that would provide data for both the energy and banking sectors.

**Comment by CDR-API-Stream** [comment]
This issue has been staged at: https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/198

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.18.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 249](https://github.com/ConsumerDataStandardsAustralia/standards/issues/249) for further details.
