### ISSUE TITLE
Common Data Clusters altered for Energy Data Language

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#485]
# Description
For Individuals, Occupation has been removed from the Common clusters for Energy sector. The scope remains the same between Energy and Banking but the data cluster has been altered. Since the scopes overlap it is unclear _why_  **common** data clusters are being redefined per sector. Nonetheless, the payload for common continues to contain `occupationCode` and therefore the data cluster for energy is potentially misleading.

For Business Accounts, the following items have been removed for Energy clusters but the payloads keep them present:
- Charity status;
- Establishment date;
- Industry;
- Organisation type
- Country of registration;

While it may be assumed that Energy retailers do not hold this data this is not the case industry wide and the payloads are consistent across industry. Reviewing the [Decision Proposal 213](https://github.com/ConsumerDataStandardsAustralia/standards/issues/213) the reasoning given is that the Rules more specifically define the meaning of customer data for energy _however_ this doesn't resolve the fact that the payloads for common payloads are not changed and in some cases the removed data clusters are **mandatory** for schema validation.

# Area Affected
Common Language Clusters for "Energy" changing the Oxford definition of _"common"_

# Change Proposed

- Align Common language data clusters to be consistent regardless of data is available or;
- Fix the rules which don't appear to understand the concept of common and were **proposed** at the time of the DP or;
- Split common endpoints to be industry specific (not preferred)

**Comment by perlboy** [comment]
Footnote: It is unclear why there is disfunction between Rules and Standards teams but dynamically redefining "common" per sector is a lesson in idiocy. Either define endpoints per industry and abandon common _or_ get consistent in what is common customer information.

**Comment by Adatree** [comment]
As we're in the Open Energy implementation phase it would be helpful to get clarity on this issue and whether any consideration to changing the common API language standards will be made or not based on the above.

If not, as software products can apply to all industries, some guidance on what common API language standards would apply in that situation would be appreciated.

**Comment by perlboy** [comment]
There is a further question here regarding the Get Customer Detail endpoint for Energy. Should Energy omit the occupation details _even if_ they have this information in their systems?

**Comment by CDR-CX-Stream** [comment]
Thanks for engaging on this issue @perlboy and @Adatree. 

The rules do not treat the meaning of customer data as 'common' in the same way as the technical standards do. The CX standards reflect the rules, and the data language standards have not treated customer as common in the past. The CX standards have remained consistent and aligned in this regard.

We have discussed this issue further with Treasury to identify how we might achieve greater consistency across rules, CX standards, and technical standards, and to clarify if any ostensible misalignment is a material issue with regard to the rules.

In relation to the technical standards for customer data, the inclusion of data such as _occupation_ and _organisation type_ for the energy sector (in addition to banking) do not raise any rules issues. This is because rule 1.3(1)(a) in both the banking and energy schedules state that, as well as the specified data, customer data also refers to 'information that identifies or is about the person'. If desirable, we welcome a change request that outlines alternatives to this approach in the technical standards.

In relation to the CX standards for customer data language, we can confirm that the language for customer can be sector specific _or_ sector agnostic - neither approach will bring the CX standards into conflict with the rules. We do however see value in the CX standards for customer data language being sector agnostic, i.e. 'common'.

To this end, we are interested in views from the community on the following options:
1. No changes to the CX standards for customer data language, which will maintain sector-specific customer data language where the rules treat customer in this way
2. Propose amendments to the CX standards for customer data language, which would seek to achieve sector-agnostic (i.e. common) customer data language as per the technical standards. This would likely require the banking customer language to be made common data language standards, and the energy specific customer data language to be removed.
3. Update the energy customer data language to reflect the technical standards (and by extension, the banking customer data language standards), to provide energy stakeholders with clarity for implementation. This approach would result in CX standards for customer data remaining sector-specific in the interim, with a view to revisit this in the near term for future sectors, such as telecommunications.

The DSB's preference is to pursue option 2. If supported, this change could be dealt with as part of a maintenance iteration, or as a separate decision proposal. The changes and timing would need to be consulted on to identify impacts to existing banking implementations and upcoming July 2022 obligations, as well as the November 2022 energy implementations that are currently underway. A separate decision proposal may be required to validate this position for future sectors, such as telecommunications.

We welcome feedback on these options and approaches from the community.

**Comment by perlboy** [comment]
> The rules do not treat the meaning of customer data as 'common' in the same way as the technical standards do. The CX standards reflect the rules, and the data language standards have not treated customer as common in the past. The CX standards have remained consistent and aligned in this regard.

This is either untrue or the application is so broad as to be of little value. The Rules in the Banking Sector _do not_ include _Occupation_ being part of _customer data_ but, like Energy do include a broad statement related to information provided at the time of acquiring a particular product. It's unclear why the DSB included the Occupation component in Banking in the first place because it wasn't specifically included in the Rules.

Banking definition of _customer data_:
![image](https://user-images.githubusercontent.com/4291448/173211545-824ec087-97ab-4c59-89ee-d2e8d289baf7.png)

Energy definition of _customer data_:
![image](https://user-images.githubusercontent.com/4291448/173211523-c2d65190-06e6-4b4a-a46c-874088dfd838.png)

The broad catchall statement aside (which isn't covered in CX standards) the definition of _customer data_ for individuals is word for word _the same_ except for a DOB exclusion which isn't in the Standards anyway.

> We have discussed this issue further with Treasury to identify how we might achieve greater consistency across rules, CX standards, and technical standards, and to clarify if any ostensible misalignment is a material issue with regard to the rules.
> In relation to the technical standards for customer data, the inclusion of data such as _occupation_ and _organisation type_ for the energy sector (in addition to banking) do not raise any rules issues. This is because rule 1.3(1)(a) in both the banking and energy schedules state that, as well as the specified data, customer data also refers to 'information that identifies or is about the person'. If desirable, we welcome a change request that outlines alternatives to this approach in the technical standards.

It's hard to see through the double speak but I think this says that the original data cluster was sufficient and the DSB took it upon itself to alter it in https://github.com/ConsumerDataStandardsAustralia/standards/issues/213 for no _actual_ reason but now the expectation is that some other party will propose to undo something that was never asked for...

 If the DSB had introduced `energy:customer.basic:read` scope this would have been fine. The issue is that the DSB **overloaded** a single authorisation scope with different descriptions.

> In relation to the CX standards for customer data language, we can confirm that the language for customer can be sector specific _or_ sector agnostic - neither approach will bring the CX standards into conflict with the rules. We do however see value in the CX standards for customer data language being sector agnostic, i.e. 'common'.

Fundamentally it is less about multiple data clusters and more about overlapping scopes. If/When a dual industry Holder comes online (eg. Gas, Telco) it will be impossible for a Data Holders to differentiate between the same scope name with two different data clusters. This is not only a technically complex addition it is also a potential security vulnerability as the CDR infosec profile is, at this stage, fundamentally controlled using course-grained authorisation.

If the government wishes to have multiple definitions of the same thing the only way to make this sustainably work is for it to be different scopes. Whether this impacts endpoints themselves is a case by case situation but it most definitely will require an alteration to the authorisation behaviour of the endpoint.

> To this end, we are interested in views from the community on the following options:
> 1. No changes to the CX standards for customer data language, which will maintain sector-specific customer data language where the rules treat customer in this way

The DSB can't choose to do one part of this and not the other. Either the data clusters are treated as sector specific and therefore the scopes are different or they are not. Living in the fairy land of presentation level with no regard at all for the underlying authorisation scopes is _guaranteed_ to implode as more sectors are added.

> 2. Propose amendments to the CX standards for customer data language, which would seek to achieve sector-agnostic (i.e. common) customer data language as per the technical standards. This would likely require the banking customer language to be made common data language standards, and the energy specific customer data language to be removed.

This IS what was proposed in _Change Proposed_ section. It is disappointing it has taken the DSB 3 months to reply with a suggestion to put forward a change to a change request that proposes a change.

> 3. Update the energy customer data language to reflect the technical standards (and by extension, the banking customer data language standards), to provide energy stakeholders with clarity for implementation. 

I _think_ this says that the Data Cluster language would remain the same between Banking & Energy but revisited in the future. This is, in essence, an unwinding of the split of the two and therefore a No Change to existing implementations.

> This approach would result in CX standards for customer data remaining sector-specific in the interim, with a view to revisit this in the near term for future sectors, such as telecommunications.

I do _not_ agree this means it is sector-specific but rather that the CX standards align with the authorisation scopes. As stated before the issue here is _less_ about Data Clusters being sector specific (although confusing to a consumer) and more about the misuse of a single authorisation scope to do so.

> The DSB's preference is to pursue option 2. If supported, this change could be dealt with as part of a maintenance iteration, or as a separate decision proposal. The changes and timing would need to be consulted on to identify impacts to existing banking implementations and upcoming July 2022 obligations, as well as the November 2022 energy implementations that are currently underway. A separate decision proposal may be required to validate this position for future sectors, such as telecommunications.

I oppose Option 2 on the basis that it seeks to change an existing industry without clarifying the need for the DSB to stop misusing overlapping authorisation scopes.

The specification as it stands requires existing cross-sector implementers to modify their solution to achieve Energy objectives. It also requires them to ensure they can "undo" the scope overlap in the future of an environment whereby scopes are used across infrastructure. This is a technically complex requirement in a large scale infrastructure deployment for limited benefit and in violation of quite a few fundamental security principles.

As a representative of an organisation which is responsible for delivering a _majority_ of the energy majors by November 2022 I request the DSB treat this request as urgent and roll it into the Energy MI. If this is not aligned prior to Go Live we will require a Future Dated Obligation and, given the nature of the potential change, this may need to be as long as 12 months in accordance with the longest sharing duration without amendment possible so that Consumers can see the change in Data Language. 

Further we note that our Energy customers have expressed a preference to share Telecommunications sector data (if/when it is designated) via the same mechanisms, realms, consent flows etc. This will essentially accelerate the implosion forecast above.

Our preference would be to implement **Option 3** because it neither impacts Banking and aligns Energy with the rest of the industry. If the DSB wishes to introduce a sector specific data cluster in the future it can do so with a sector specific scope.

**Comment by CDR-CX-Stream** [comment]
Thanks for this response @perlboy.

To clarify, options 2 and 3 amendments were conceptualised as follows:

**Option 2**
- No changes to the technical standards for authorisation scopes.
- The CX data language standards for customer data in banking and energy would be removed from their current sector-specific sections. 
- The common section of the data language standards would include a new entry for customer data. This new entry would precisely reflect the language standards currently used for customer data in banking. 
- This new entry would then be the language used to describe customer data regardless of sector, i.e. in banking, energy, and future sectors.

**Option 3**
- No changes to the technical standards for authorisation scopes.
- The CX data language standards for customer data in banking would remain as-is.
- The CX data language standards for customer data in energy would be amended to precisely reflect the language standards currently used for customer data in banking. 
- The language used to describe customer data for banking would be the same as the language used to describe customer data in energy.

If Option 3 were supported we would revisit Option 2 for future sectors (such as telecommunications), but expect that any supported changes would be phrased as a future dated obligation in line with any future sector implementation dates.

If the above clarification is consistent with your interpretation @perlboy then we will seek to mark this CR as urgent and we can address this further in next week's MI call.

**Comment by perlboy** [comment]
As discussed in call following clarification in the MI, we support the clarified Option 2 above.

**Comment by CDR-CX-Stream** [comment]
The Data Standards Chair has approved the classification of this issue as urgent and the DSB has identified the preferred change.

The DSB proposes that **Option 2** be incorporated as an urgent change in MI11.

This change:
- would amend the CX language standards for customer data to be sector-agnostic
- based on the DSB's interpretation, would not alter any banking obligations. It would only result in a superficial change to the presentation of the banking standards.
- would require energy DHs to adopt language standards for customer data that directly reflect the language currently listed in the [banking section](https://consumerdatastandardsaustralia.github.io/standards/#banking-language), which will be found in the [common section](https://consumerdatastandardsaustralia.github.io/standards/#data-language-standards-common) following MI11
- would not require energy DHs to make more (or less) data available than already required. The CX standards only specify the descriptions to be used, not the data to be made available for sharing. Separate to [designation](https://www.legislation.gov.au/Details/F2020L00833) and rules requirements, the specific data to be shared is determined by the technical standards (see [Common APIs](https://consumerdatastandardsaustralia.github.io/standards/#get-customer) and [Schemas](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponsecommoncustomer)).
- would not have a future dated obligation (i.e. if/when the Chair approves the MI11 changes, the change would be effective immediately )
- would apply to all sectors by default

To incorporate this change into the data standards, the below tables would be added to the [common section](https://consumerdatastandardsaustralia.github.io/standards/#data-language-standards-common) of the data language standards, and the customer data language entries in the [banking section](https://consumerdatastandardsaustralia.github.io/standards/#banking-language) and the [energy section](https://consumerdatastandardsaustralia.github.io/standards/#energy-language) would be removed.

<h3 id="individual-consumer">Individual Consumer</h3>

Data cluster language | Permission language | Authorisation Scopes
-- | -- | --
Name and occupation | Name; Occupation | common:customer.basic:read
Contact Details | Phone; Email address; Mail address; Residential address; | common:customer.detail:read
Name, occupation, contact details ‡ | Name; Occupation; Phone; Email address; Mail address; Residential address; | common:customer.detail:read

<h3 id="business-consumer">Business Consumer</h3>

Data cluster language | Permission language | Authorisation Scopes
-- | -- | --
Organisation profile * | Agent name and role; Organisation name; Organisation numbers (ABN or ACN);† Charity status; Establishment date; Industry; Organisation type; Country of registration; | common:customer.basic:read
Organisation contact details * | Organisation address; Mail address; Phone number; | common:customer.detail:read
Organisation profile and contact details *‡ | Agent name and role; Organisation name; Organisation numbers (ABN or ACN),† Charity status; Establishment date; Industry; Organisation type; Country of registration; Organisation address; Mail address; Phone number; | common:customer.detail:read

**Comment by CDR-CX-Stream** [comment]
CR485 was incorporated into v1.18.0 of the published standards (see: https://consumerdatastandardsaustralia.github.io/standards/#change-log). 

This issue can now be closed.
