### ISSUE TITLE
v1.15.0 More ambiguity into x-fapi-auth-date not less

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#489]
# Description

#430 and the Maintenance Iteration decision https://github.com/ConsumerDataStandardsAustralia/standards/issues/212 "clarified" `x-fapi-auth-date` with:
> The decision is to adopt this change based on community feedback and consultation. The change fixes endpoint documentation to align with the mandatory requirements for the x-fapi-auth-date header already defined in the High Level Standards HTTP Headers section of the data standards.

However all authenticated Banking API endpoints were then updated with:
>  _The time when the customer last logged in to the Data Recipient Software Product. Required for all resource calls (customer present and unattended) **if the customer has logged in**. Not to be included for unauthenticated calls._

Which **isn't** what the Decision Proposal outlined and is now ambiguous because it seems to indicate a logged in customer can make unattended calls.

# Area Affected
All Banking APIs received this change.

# Change Proposed

1) Do what the Decision Proposal _actually_ proposed.
2) Fix the change control process so that even trivial changes aren't incorrectly applied

**Comment by CDR-API-Stream** [comment]
This issue was discussed in the [Maintenance Iteration 11 call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(11-May-2022)). It was agreed to incorporate this change request into this maintenance iteration.

**Comment by CDR-API-Stream** [comment]
This issue has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/maintenance/511..maintenance/489
