### ISSUE TITLE
Admin CDR OpenAPI specification missing error definitions

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataStandardsAustralia/standards-maintenance#490]
# Description
In the OpenAPI specification for the admin api a missing definition is referenced twice, once on the metadata endpoint and once on the metrics endpoint. The definition in question is `#/definitions/ResponseErrorListV2` which is defined in the common api specification but missing in the admin API specification.

# Area Affected
This issue is limited to the admin OpenAPI specification.

# Change Proposed
The missing definitions should be added to the admin OpenAPI specification to enable the specification to be used in isolation from the other specifications.

**Comment by CDR-API-Stream** [comment]
This issue was discussed in the [Maintenance Iteration 11 call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(11-May-2022)). It was agreed to incorporate this change request into this maintenance iteration.

**Comment by CDR-API-Stream** [comment]
Hi @Aiden-Ziegelaar this no longer appears to be an issue in v1.17.0 of the data standards. Please confirm if you still have an error when inspecting the Swagger. The ResponseErrorListV2 definition you reference is included in cds_admin.json/yaml.
