### ISSUE TITLE
Admin API Definitions Request Body Incorrectly Nested

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataStandardsAustralia/standards-maintenance#492]
# Description
The admin api has an incorrectly nested request body on the endpoint /admin/register/metadata.
On the endpoint Swagger JSON we see the following definitions: 
```JSON 
"/admin/register/metadata": {
      "post": {
        "tags": ["Admin", "Register"],
        "summary": "Metadata Update",
        "description": "Indicate that a critical update to the metadata for Accredited Data Recipients has been made and should be obtained",
        "operationId": "metadataUpdate",
        "parameters": [
          {
            "in": "body",
            "name": "action",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RequestMetaDataUpdate"
            }
          },
       ...]
    ...}
```

Expanding out the schemas gives us: 
```JSON
        "parameters": [
          {
            "in": "body",
            "name": "action",
            "required": true,
            "schema": {
                "type": "object",
                "required": ["data"],
                "properties": {
                  "data": {
                    "type": "object",
                    "required": ["action"],
                    "properties": {
                      "action": {
                        "type": "string",
                        "description": "The action to take for the meta data. At the moment the only option is REFRESH which requires the data holder to call the ACCC to refresh meta data as soon as practicable",
                        "default": "REFRESH",
                        "enum": ["REFRESH"]
                      }
                    }
                  },
                  "meta": {
                    "$ref": "#/definitions/Meta"
                  }
                }
            },
       ...]
```

This gives us a body parameter `action` that has a field `data` that contains a field `action`.
Thus the final body object type that looks like this: 
```JSON 
{
  "action": {
    "data": {
      "action": "REFRESH"
    },
    "meta": {}
  }
}
```

Compared to the documented type:
```JSON
{
  "data": {
    "action": "REFRESH"
  },
  "meta": {}
}
```

# Area Affected
Admin API, specifically the post endpoint /admin/register/metadata

# Change Proposed
I propose that the admin request bodies be documented the same way that the energy request bodies are documented, using the components/requestBodies area of the OpenAPI specification. This would also allow for type information `application/json` to be included in the definition.

**Comment by CDR-API-Stream** [comment]
This issue was discussed in the [Maintenance Iteration 11 call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(11-May-2022)). It was agreed to incorporate this change request into this maintenance iteration.

**Comment by CDR-API-Stream** [comment]
Hi @Aiden-Ziegelaar can you please confirm this is still an issue in [release 1.17.0](https://consumerdatastandardsaustralia.github.io/standards/index.html?examples#admin-apis). The bug referenced no longer appears to be an issue in the latest Swagger.
