### ISSUE TITLE
Get Transaction Detail - Client Error documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#493]
# Description
Response codes are missing in the links to Client Errors.

# Area Affected
[Get Transaction Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-transaction-detail) 4xx Client Error links

# Change Proposed
Add the missing response codes to the links (highlighted below) -
![image](https://user-images.githubusercontent.com/60594671/159385984-c4f23f06-1b73-4977-9970-9392afa6ee9c.png)

**Comment by CDR-API-Stream** [comment]
This CR is now included in MI11. This is a result of re-prioritisation work the DSB carried out as per action raised in [MI11 session](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(25-May-2022)) on 25th May.

This will be addressed as documentation fix as part of CR #511.

**Comment by CDR-API-Stream** [comment]
This issue has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/maintenance/511..maintenance/493

**Comment by nils-work** [comment]
This has now been fixed, thank you 

![image](https://user-images.githubusercontent.com/60594671/193989641-508b471c-365a-4d92-bb36-bcf0c48341ea.png)
