### ISSUE TITLE
Unauthenticated energy routes have unclear header documentation

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataStandardsAustralia/standards-maintenance#496]
# Description
The `x-fapi-interaction-id` request header is present on authenticated energy routes in the documentation however is not on the unauthenticated energy plan requests. In the OpenAPI specification, this header is present on the unauthenticated energy plan requests.

# Area Affected
Energy documentation

# Change Proposed
Add `x-fapi-interaction-id` request header to documentation for unauthenticated energy plan routes.

# DSB Proposed Solution
The current DSB proposal for this issue is in this [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/496#issuecomment-1482185992)

**Comment by CDR-API-Stream** [comment]
@Aiden-Ziegelaar thank you for raising this CR.

Note that `x-fapi-interaction-id` should not be required in either the request or response headers for any public endpoints. We will correct this as part of MI14 release.

**Comment by nils-work** [comment]
The changes associated with this issue were staged [here](https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/277/commits/5ba5c281148cdd3b2e3a2c3f6a5c8ea8f8df8239) and incorporated into Standards version 1.24.0.
