### ISSUE TITLE
CommonEmailAddress - address format documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#497]
# Description
The Description for the address property has an incorrect name for the email format -
![image](https://user-images.githubusercontent.com/60594671/160509652-a43d96fe-e0c5-4baf-87a8-61d02f4f3378.png)

# Area Affected
[CommonEmailAddress documentation](https://consumerdatastandardsaustralia.github.io/standards/#tocScommonemailaddress)

# Change Proposed
Change `addr_spec` to `addr-spec`.

Thank you

**Comment by CDR-API-Stream** [comment]
This issue was discussed in the [Maintenance Iteration 11 call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(11-May-2022)). It was agreed to incorporate this change request into this maintenance iteration.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/maintenance/511..maintenance/497
