### ISSUE TITLE
Unknown field in Energy Secondary Data Holder OpenAPI spec

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataStandardsAustralia/standards-maintenance#499]
# Description
In the schema `EnergyServicePointDetail_relatedParticipants` required fields are listed as `"location", "party", "role"` however the schema only defines the properties `"party"` and `"role"`. This is causing issues with our type generation code. 

# Area Affected
Energy Secondary Data Holder OpenAPI specification, schema `EnergyServicePointDetail_relatedParticipants`

# Change Proposed
As the field `location` is not present in the schema, it should be removed from the required fields.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.18.0...maintenance/499
