### ISSUE TITLE
Pedantic typo: URI Structure has `\` instead of `/` in URI

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/standards-maintenance#51]
The Standards have a list of URIs in **Resource URIs** that have a  backslash instead of slash in the URI.

i.e. `GET …\accounts` instead of `GET …/accounts`.

**Comment by CDR-API-Stream** [comment]
This is a stylistic change only but if it is a concern we will incorporate this in a future iteration of the standards.

**Comment by CDR-API-Stream** [comment]
This has been fixed in the documentation.
