### ISSUE TITLE
Register API error codes need to be aligned with the CDS standardised error codes

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#510]
# Description
The Register API error codes haven't been updated alongside the updates to the CDS error codes as conducted through [DP 120](https://github.com/ConsumerDataStandardsAustralia/standards/issues/120) and documented in: https://consumerdatastandardsaustralia.github.io/standards/#error-codes. As a result of this, there is an inelegance where the current swagger definitions conflict with optional code usage. This negatively affects the usability of these APIs

An example of this is as follows:

#### Response codes for GetSSA:

![image](https://user-images.githubusercontent.com/52149325/167517079-3aec096b-70fd-4fbb-8fbd-e620b5f2f1a0.png)

#### Potentially conflicting error codes as defined in the CDS (note the **MAY** requirement)

![image](https://user-images.githubusercontent.com/52149325/167517115-d3143bd0-4edc-4b6f-86f5-ddc8c900e5ef.png)

Alignment to these error codes should be sought for completeness and to improve usability.

# Area Affected
[Register APIs](https://consumerdatastandardsaustralia.github.io/standards/?examples#register-apis)

# Change Proposed
Audit response codes and update alignment to the CDS error codes.

**Comment by CDR-API-Stream** [comment]
To address this issue, an audit has been performed on the register response error codes. 

### Proposal:

The following changes are proposed to ensure consistency between the CDS error codes and the Register API swagger definition.

The following represent the API associated error codes which will be added or updated:

|API | Version | Updated Error Codes | New Error Codes|
|-- | -- | -- | --|
| Get Data Holder Brands | V2 | 400:  <br />~Missing   Required Header / Invalid Version / Invalid Path Parameter~ <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry |
| Get Data Holder Brands Summary | V1 | 400:  <br />~Missing   Required Header / Invalid Version / Invalid Path Parameter~ <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field  <br /><br />404: <br />~Industry Not Found~   <br />Invalid Industry |
| Get Software Statement Assertion (SSA) | V3 | 400: <br />~Missing Required Header / Invalid Version / Invalid Path Parameter~ <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field  <br /><br />403: <br />~Invalid BrandId~ <br />The ADR or the ADR's Software Product is not active  <br /><br />404: <br />~Invalid Software Product~  <br /> Invalid Industry / Invalid Brand Id / Invalid Software Product Id |  
| Get Data Holder Statuses | V1 | 400: <br />~Missing Required Header / Invalid Version / Invalid Path Parameter~ <br /> Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry |
| Get Software Products Statuses | V2 | 400: <br />~Missing Required Header / Invalid Version / Invalid Path Parameter~  <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry |
| Get Data Recipients Statuses | V2 | 400: <br />~Missing   Required Header / Invalid Version / Invalid Path Parameter~   <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry |
| Get Data Recipients | V3 | 400: <br />~Missing Required Header / Invalid Version / Invalid Path Parameter~ <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry |

These changes will only apply to the new Register API versions, with the dependency date of **15th November 2022**. 

Please refer to the [Register Dependency Schedule](https://consumerdatastandardsaustralia.github.io/standards/#register-dependency-schedule) for details.

---

One outstanding question is how the 422 error code defined in the [Get Software Statement Assertion (SSA) V3 API](https://consumerdatastandardsaustralia.github.io/standards/#get-software-statement-assertion-ssa) should be specified. The ACCC will need to provide input as to whether the 422 error code is utilised and therefore should be specified in the CDR Register section of the [error codes](https://consumerdatastandardsaustralia.github.io/standards/#error-codes) specification in the CDS, or, is redundant and therefore should be cleared up.

**Comment by perlboy** [comment]
Testing by both AEMO/ACCC for energy sector is scheduled to start in July. Will these changes be applied before, during or after industry testing has occurred?

**Comment by ACCC-CDR** [comment]
The ACCC requests that this issue be restricted to resolving documentation errors related to the usage of the [CDR Register Errors](https://consumerdatastandardsaustralia.github.io/standards/#error-codes:~:text=and%20authenticated%20APIs.-,CDR%20Register%20Errors,-The%20following%20error) of the CDS. While the ACCC supports the changes detailed above,[](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/510#issuecomment-1162556200)we proposed that these should be revisited in a future maintenance iteration and implemented post the 15th November 2022.

The ACCC confirms that the 422 error code for the [Get Software Statement Assertion (SSA) V3 API](https://consumerdatastandardsaustralia.github.io/standards/#get-software-statement-assertion-ssa) is superfluous and can be removed.

@Perlboy the ACCC does not plan to conduct any specific energy sector testing with participants beyond the Conformance Test Suite. There are however tools available to assist energy participants with their build and test, including the [Participant Tooling mock solutions](https://github.com/ConsumerDataRight) and the soon-to-be-released [CDR sandbox](https://www.cdr.gov.au/for-providers/participant-tooling/consumer-data-right-sandbox).

<table data-layout="default" data-local-id="2ed3a253-b1da-44cb-8e3d-83f3f8ff3ac3" class="confluenceTable"><colgroup><col style="width: 194.0px;"><col style="width: 81.0px;"><col style="width: 338.0px;"><col style="width: 146.0px;"></colgroup><tbody><tr><th class="confluenceTh"><p>API</p></th><th class="confluenceTh"><p>Version</p></th><th class="confluenceTh"><p>Updated Error Codes</p></th><th class="confluenceTh"><p>New Error Codes</p></th></tr><tr><td class="confluenceTd"><p>Get Data Holder Brands</p></td><td class="confluenceTd"><p>V2</p></td><td class="confluenceTd"><p></p></td><td class="confluenceTd"><p>404:<br>Invalid Industry</p></td></tr><tr><td class="confluenceTd"><p>Get Data Holder Statuses</p></td><td class="confluenceTd"><p>V1</p></td><td class="confluenceTd"><p></p></td><td class="confluenceTd"><p>404:<br>Invalid Industry</p></td></tr><tr><td class="confluenceTd"><p>Get Software Statement Assertion (SSA)</p></td><td class="confluenceTd"><p>V3</p></td><td class="confluenceTd"><p>404:<br><del>Invalid Software Product</del><br>Invalid Industry / Invalid Brand / Invalid Software Product</p></td><td class="confluenceTd"><p></p></td></tr><tr><td class="confluenceTd"><p>Get Software Products Statuses</p></td><td class="confluenceTd"><p>V2</p></td><td class="confluenceTd"><p></p></td><td class="confluenceTd"><p>404:<br>Invalid Industry</p></td></tr><tr><td class="confluenceTd"><p>Get Data Recipients Statuses</p></td><td class="confluenceTd"><p>V2</p></td><td class="confluenceTd"><p></p></td><td class="confluenceTd"><p>404:<br>Invalid Industry</p></td></tr><tr><td class="confluenceTd"><p>Get Data Recipients</p></td><td class="confluenceTd"><p>V3</p></td><td class="confluenceTd"><p></p></td><td class="confluenceTd"><p>404:<br>Invalid Industry</p></td></tr></tbody></table>

**Comment by CDR-API-Stream** [comment]
Thanks @ACCC-CDR and @perlboy for your input.

## Proposal
The DSB proposes to specify the appropriate error codes for the CDR Register API to align to the [Standards error codes](https://consumerdatastandardsaustralia.github.io/standards#error-codes). These changes will be incorporatd into future versions of the CDR Register APIs. Current versions of the CDR APIs will not be impacted. 
 
The rationale for not incorporating this change into the current versions of the CDR Register APIs is due to the low priority of this change. The motivation for this change is to align the CDR Register APIs to the API conventions laid out in the Consumer Data Standards. These changes are low priority and will not be incorporated into V1.18.0, to minimise this implementation burden on participants.


API | Updated Error Codes | New Error Codes
--  | -- | --
Get Data Holder Brands | 400: <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry
Get Software Statement Assertion (SSA)  | 400: <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field  <br /><br />403: <br />The ADR or the ADR's Software Product is not active  <br /><br />404: <br />Invalid Industry / Invalid Brand Id / Invalid Software Product Id |  
Get Data Holder Statuses  | 400: <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry
Get Software Products Statuses  | 400: <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry
Get Data Recipients Statuses  | 400: <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry
Get Data Recipients  | 400: <br />Missing Required Header / Invalid Header / Invalid Version / Invalid Field | 404: <br />Invalid Industry

Note that **GetDataHolderBrandSummary** is not specified as this API already aligns to the error code conventions

**Comment by CDR-API-Stream** [comment]
This issue has been staged at: https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/202
