### ISSUE TITLE
Clarity around GET Metrics for AER, DELWP and AEMO

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#515]
# Description
In discussion with Treasury and the ACCC it has been recommended that the standards make it clear that AER and DELWP (for Energy Tariff Data) and AEMO (as secondary data holder for a number of data clusters) will not be required to implement the GET Metrics endpoint.

# Area Affected
This would be a change to the description of the GET Metrics API

# Change Proposed
A statement indicating that the three agencies identified (using language that aligns to their identification in the rules) will be explicitly exempt from implement the GET Metrics API

**Comment by perlboy** [comment]
While it is the governments prerogative as to whether related government entities are required to provide Get Metrics data, as noted in the MI call the absence of this data, particularly for designated secondary holders (ie. AEMO), will make dispute resolution with respect to a Data Holders recorded response metrics difficult. 

Assurances _may_ be given that these departments are tracking metrics via alternate means but I'd note that a correct, like for like, implementation of the current Get Metrics endpoint is a complex undertaking including 95th percentile, microsecond resolution and per minute aggregation recommendations. I'd also note that if instrumenting to achieve these _is_ already delivered attaching an API to it is a somewhat trivial task (ie. the work effort isn't the API it's the data to populate the API).

Under these circumstances it seems reasonable that, in the absence of mathematically similar (and preferably non-opaque) collection of data from an SDH, a Holder can directly dispute assertions provided _by_ that SDH as to their supposed performance and dispute a potential accusation from the Regulator with respect to NFR non-compliance.

Put more bluntly, the Regulator may make a rather vicarious legal assertion related to Holder NFR non-compliance with nothing more than the hear-say of other participants.
