### ISSUE TITLE
Make id_token mandatory for refresh_token grant type

### ISSUE THREAD

**Issue by pcurtisrab** [ConsumerDataStandardsAustralia/standards-maintenance#52]
# Description
The CDS standards allow for refresh token cycling. Data recipients need to know refresh token expiry in order to keep tokens fresh until the end of the agreement. Tweaking the specification in this regard should simplify implementation for Data Recipients, leading to more robust integration between participants.

# Area Affected

- Token endpoint
- Introspection endpoint

# Change Proposed
- The standard should specify that the token endpoint MUST always include an id_token, regardless of grant_type.
- The standard should specify that the introspection endpoint "MUST include both of and only the following fields:" when referring to the the active and exp fields.

## Rationale

When refresh token cycling is performed, data recipients must make a further call to the UserInfo endpoint in order to determine the expiration date of the refresh token, despite the potential alternatives which are discounted as follows:

1. The id_token parameter of the refresh response could be used, except that [OIDC (section 12.2)](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.12.2) states that the response body _might not_ contain an id_token.

2. The introspection endpoint could be used, but the [CDS spec](https://consumerdatastandardsaustralia.github.io/standards/#introspection-end-point) is not clear that the exp claim must be present (it only says that the response SHALL _only_ include active and exp).

Even though the UserInfo is functionally fit, and the introspection may be (pending clarification), both rely on a second HTTP call. This heightens the possibility of a loss of token and expiry synchronisation between parties due to comms issues, and increases the implementation burden on Data Recipients to effectively manage this. In contrast, being able to relying on the ID Token refresh_token_expires_at claim in for all token refreshes minimizes further token management complexity beyond what is needed to cycle refresh tokens at all.

Regional Australia Bank's opinion is that an atomic update of tokens and expiry dates together in one HTTP call is ideal, and that the standards should mandate the presence of the id_token in all responses to the token endpoint support it.

**Comment by CDR-API-Stream** [comment]
The standards state:
>Data Holders MUST implement an Introspection End Point to allow Data Recipients to determine the status and expiry date of Refresh Tokens. The requirements for an Introspection End Point are described in section 2 of **[RFC7662]**

This combined with the statement that the `exp` and `active` claims are the only ones supported and the other statements requiring a refresh expiry to be set and explicit support for the `refresh_expires_at` claim are understood by the DSB to make it clear that the introspection end point must support the ability to obtain the expiry of the Refresh Token.

Overriding the grant_type to require that an id_token is already supplied is a significant variation that does not appear, on initial review, to be justified.  Refresh token cycling is a standard mechanism for OAuth 2 Authorisation Servers so the use of standard mechanisms would be preferred.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.
