### ISSUE TITLE
softwareProductDescription should be marked as mandatory

### ISSUE THREAD

**Issue by CDR-DF** [ConsumerDataStandardsAustralia/standards-maintenance#525]
# Description
In the _SoftwareProductMetaData_ schema, the _softwareProductDescription_ field is marked as "optional".  However, in the **SSA Definition** (https://consumerdatastandardsaustralia.github.io/standards/#client-registration) section, the _client_description_ field (that maps to the _softwareProductDescription_ field) is marked as "Required".

# Area Affected
Register APIs -> Get Data Recipients

# Change Proposed
Mark the _softwareProductDescription_ field of the _SoftwareProductMetaData_ schema as "mandatory".

# DSB Proposed Solution
The current DSB proposal for this issue is in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/525#issuecomment-1217349173).

**Comment by CDR-API-Stream** [comment]
This appears to be a reasonable change request.  If the SSA setting of required is valid then the value will be always available so making the value mandatory in the software products API should have no implementation impact.

As a result, the current proposed solution is to adopt the change as proposed in the **Change Proposed** section of the issue.

Feedback is sought to identify if the assumption that this will have zero implementation impact and would not be a breaking change.  If there is feedback that this assumption is incorrect then the proposed solution will be revisited.

**Comment by CDR-API-Stream** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.19.0...maintenance/525

**Comment by CDR-API-Stream** [comment]
This change has been updated to target v1.20.0: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.20.0...maintenance/525
