### ISSUE TITLE
CX - Energy Data Language Standards - NMI and Scheduled Payments

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#529]
# Description
Consultation and changes relating to [CR495](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/495) during maintenance iteration 11 (MI11) highlighted issues with the existing [energy data language standards](https://consumerdatastandardsaustralia.github.io/standards/#energy-language) where descriptions refer to NMI and the payment schedule scope, specifically: 

- NMI is only shared through the NMI standing data cluster but accounts and billing clusters also (incorrectly) include the term 'NMI' in the permission language
- the discussion and changes relating to [CR495](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/495) have also highlighted that the existing data language standards may not accurately reflect the information that is shareable through the payment schedule scope

# Area Affected
**Energy Accounts**
Data language standards relating to the energy:accounts.basic:read and energy:accounts.detail:read scopes

**Billing**
Data language standards relating to the energy:billing:read scope

**Stored Payment Information**
Data language standards relating to the energy:accounts.paymentschedule:read scope

# Change Proposed
**Energy Accounts** (_energy:accounts.basic:read and energy:accounts.detail:read scopes_)
Remove all references to 'NMI' in permission language

**Billing** (_energy:billing:read scope_)
Remove reference to 'NMI' in permission language

**Stored Payment Information** (_energy:accounts.paymentschedule:read scope_)
Change existing data cluster and permission language to:

> **Payment preferences**
> - Any scheduled payment details
> - Payment and billing frequency

The payment schedule language changes are proposed to cover where consumers may have automated payments setup, and/or may pay bills manually after receiving their bill(s), as well as the associated frequency for payments and/or billing.

DSB welcomes views on these changes and if they need to be proposed as a future dated obligation or can take effect in November for energy DHs.

# DSB Proposed Solution
The current DSB proposal for this issue is in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/529#issuecomment-1210237934)

# Decision Record
The Data Standards Chair approved this decision as an urgent change on 1 September 2022. The decision record is attached: [Decision 529](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/9467987/Decision.529.pdf)

**Comment by biza-io** [comment]
Biza.io is comfortable with the proposed changes although we note that the proposal doesn't explicitly restate the data clusters being altered. A table of before and after would provide the most completeness. 

Since the proposed changes directly relate to the potential alteration of a Consumers perceived consent we believe there may be unintended consequences with altering the language post launch. As such we recommend the changes be made effective from the November delivery date. To facilitate this timeline we request the DSB formalise and finalise this proposal immediately.

**Comment by CDR-CX-Stream** [comment]
Thanks Biza for your input - see the below table to illustrate the proposed language changes for accounts, billing, and paymentschedule scopes.  Items that have struck through will be removed.  
<h3 id="energy-accounts">Energy accounts</h3>

 

Data cluster language | Permission language | Authorisation Scopes
-- | -- | --
Accounts and plans | Account and plan information; ~~National Meter Identifier (NMI);~~ | energy:accounts.basic:read
Account and plan details | Account and plan information; ~~National Meter Identifier (NMI);~~ Account type; Fees, features, rates, and discounts; Additional account users; | energy:accounts.detail:read

<h3 id="billing">Billing</h3>


Data cluster language | Permission language | Authorisation Scopes
-- | -- | --
Billing payments and history | Account balance; ~~National Meter Identifier (NMI);~~ Payment method; Payment status; Charges, discounts, credits; Billing date; Usage for billing period; Payment date; Invoice number; | energy:billing:read

Changes to payment language will be proposed as follows:
<h3 id="payments">Payments</h3>

_(Before)_
Data cluster language | Permission language | Authorisation Scopes
-- | -- | --
Stored payment information | Payment details; Scheduled payment amount; | energy:accounts.paymentschedule:read

_(After proposed change)_
Data cluster language | Permission language | Authorisation Scopes
-- | -- | --
Payment preferences | Payment and billing frequency; Any scheduled payment details; | energy:accounts.paymentschedule:read



We note Biza's support for this change and preference for it to be finalised and made effective from November. We are seeking additional input from energy retailers with November obligations to understand if there is consensus in this regard. If so, we will propose that the change be treated as urgent and dealt with separate to MI12.

**Comment by jsaxon-red** [comment]
Red Energy are comfortable with this proposed change

**Comment by JohnMillsEnergyAustralia** [comment]
EA supports the change proposed to remove NMI from the above two data clusters (Billing payments and history; Account and plan details)

**Comment by CDR-CX-Stream** [comment]
Thanks @jsaxon-red and @JohnMillsEnergyAustralia.

@JohnMillsEnergyAustralia we also invite EA's views on the **Payments** cluster change being effective from November.

**Comment by JohnMillsEnergyAustralia** [comment]
EA supports the subsequent changes proposed to the above payment data cluster (Payment preferences)

**Comment by agl-cdrprogram** [comment]
AGL supports this change and recommends this change to be effective from November 22

**Comment by CDR-CX-Stream** [comment]
Thanks @agl-cdrprogram. The DSB would like to clarify that the proposed changes, if supported, would be made effective for energy retailers with November obligations from 15 November 2022 as outlined in the tranche 1 date in Schedule 4, Part 8, Rules 8.1 and 8.6.

**Comment by PratibhaOrigin** [comment]
Origin Energy supports the recommended changes for the NMI field. We understand this will come into effect from Nov 22.

**Comment by CDR-CX-Stream** [comment]
The Data Standards Chair has now approved this decision as an urgent change. The decision record can be found in the original post.

**Comment by CDR-API-Stream** [comment]
This approved change has been staged: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.19.0..maintenance/529

**Comment by CDR-CX-Stream** [comment]
CR529 has been incorporated into v1.19.0 of the published standards (see: https://consumerdatastandardsaustralia.github.io/standards/#change-log). 

This issue can now be closed.
