### ISSUE TITLE
aud claim for Data Recipients calling Data Holders

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#53]
# Request For Clarification
Currently, the [Data Recipients calling Data Holders section](https://consumerdatastandardsaustralia.github.io/standards/#data-recipients-calling-data-holders) of the security profile states that the JWT must bear an aud claim which must be ‘The URL of the end point being invoked’. 

This is inconsistent with the [CDR Register calling Data Holders and Data Recipients](https://consumerdatastandardsaustralia.github.io/standards/#cdr-register-calling-data-holders-and-data-recipients) and the [Data Holders calling Data Recipients sections](https://consumerdatastandardsaustralia.github.io/standards/#data-holders-calling-data-recipients). These both state ‘The aud (audience) Claim. Value that identifies the intended audience. The Data Holder or Data Recipient MUST verify that it is an intended audience for the token. Contents MUST be the base URI for the end point being accessed.’ in relation to the aud claim.

We suspect that this discrepancy was unintended. Please confirm if this is the case.

**Comment by CDR-API-Stream** [comment]
This discrepancy is a feature of the evolution of the standards.  The section for the Register calling DHs and DRs and the section for DHs calling DRs are both new as of v1.0.0 whereas the section for DRs calling DHs has been in place since prior to Christmas 2018 (see the [v0.1.0 archive](https://consumerdatastandardsaustralia.github.io/standards/archive/infosec-0.1/docs/index.html#5-client-authentication) of the InfoSec profile).

As this section had been stable for nearly a year and had been included in two external security reviews it was not modified for v1.0.0.

If a change is warranted please raise a change request with a proposed change and if it is urgent for February please indicate the reason for this.

**Comment by pcurtisrab** [comment]
It may be helpful to clarify the difference, if any.

> ### Data Holders calling Data Recipients:
> 
> aud - REQUIRED. Audience. The aud (audience) Claim. Value that identifies the Data Recipient as the intended audience. The Data Recipient MUST verify that it is an intended audience for the token. Contents MUST be the **base URI for the end point being accessed**.
> 
> ### Data Recipients calling Data Holders
> 
> aud: **The URL of the end point being invoked.**

Base URI and URL, in relation to an endpoint, can be interpreted to be exactly the same thing.

**Comment by CDR-API-Stream** [comment]
To be clear, where the the term base URI is used it refers to the value in the appropriate field in the registry metadata.

Where the term "URL of the end point" is used it means the full URL path without query parameters but including path arguments.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.

**Comment by pcurtisrab** [comment]
There is still a need to clarify this. Previous comments are concerning the details of the Client Authentication section, but they assume that the Client Authentication section applies to the Authorisation endpoint.

There is no explicit statement of applicability. The [Authorisation End Point](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-end-point) description reads "Client Authentication Required: No", but this does not state that the Client Authentication section of the document does not apply. On the other hand, the Client Authentication section does not seem to exclude the Authorise End Points, but only mentions "end points" in general.

Note that [OIDC Core 6.1](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.6.1) states that aud SHOULD be the issuer, which does not seem to prohibit overruling this in the Consumer Data Standards.

![image](https://user-images.githubusercontent.com/50900464/72489943-d38a5000-3869-11ea-88ce-5d26e3ee4bf3.png)

All things considered, it seems reasonable to conclude that Client Authentication does apply, and further that the consequent overruling of the OIDC guidance is unintended.

We suggest a clarification with a statement to the effect that either (a) the Client Authentication section only applies to endpoints listed as "Client Authentication Required", or alternatively (b), that it does indeed apply to the Authorise endpoint.

**Comment by CDR-API-Stream** [comment]
Apologies for not clarifying effectively earlier as the specific point of misunderstanding was not clearly understood.  Hopefully this clarification will resolve the issue.

The standards define the use of multiple JWTs for various purposes.  The *Data Recipients calling Data Holders* section under [Client Authentication](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) defines the use of a JWT for the purposes of a recipient client authenticating with a data holder authorisation server.

The [Request Object](https://consumerdatastandardsaustralia.github.io/standards/#request-object) section describes the behaviour of a JWT called a request object that is submitted via the authorize end point.  These two JWTs are different and have different behaviour.  This is why the authorize end point is marked as "Client Authentication Required" as no.

WIth regard to the content of the `aud` field the comment stated above is applicable...

> Note that [OIDC Core 6.1](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.6.1) states that aud SHOULD be the issuer, which does not seem to prohibit overruling this in the Consumer Data Standards.
> 
> ![image](https://user-images.githubusercontent.com/50900464/72489943-d38a5000-3869-11ea-88ce-5d26e3ee4bf3.png)

The request object is explicitly stated as being governed by section 6.1 of OIDC so this statement applies.  `aud` should be the issuer identifier URL.

**Comment by CDR-API-Stream** [comment]
If there is no further discussion on this query it will be closed on Friday.
