### ISSUE TITLE
Update x-fapi-auth-date description for Customer APIs

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#532]
# Description
[CR #489](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/489) addressed consistency issues regarding the description of the `x-fapi-auth-date` header in the Banking API resource requests. 

Customer API resource requests are also inconsistent and require updating to align with the description in the [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/index.html#http-headers) section.

# Area Affected
Customer APIs

# Change Proposed
Align to the description in the [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/index.html#http-headers) section.

**Comment by cuctrangsb** [comment]
@nils-work our understanding of this change is to fix the documentation only. It does not require any action from the Data Holder with our current implementation. Please correct me if this is misinterpreted.

**Comment by nils-work** [comment]
Hi @cuctrangsb 

The intention of the change was only to make the description of that header consistent throughout the Standards. It contained slightly different wording in the `Get Customer` and `Get Customer Detail` endpoints only.

A diff of the change in staging is available here:  https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/273/commits/8f4570e73d950315681dc1628f59bdaf44107d39.
