### ISSUE TITLE
Intended meaning of BankingAccount.productName

### ISSUE THREAD

**Issue by boardbloke** [ConsumerDataStandardsAustralia/standards-maintenance#54]
I'd like some clarification of the intended use of the schema attribute BankingAccount.productName.

I note these comments:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/31#issuecomment-432862307

https://github.com/ConsumerDataStandardsAustralia/standards/issues/30#issuecomment-434964095

Am I correct that the value is intended to represent an identifier (i.e not a display name) for the product that in some way relates to its definition when the account as opened, noting further that there is no intention for the value to link meaningfully to any product ids returned by the /banking/products endpoints.

My confusion arises over the description of the field as "The unique identifier of the account as defined by the account holder (akin to model number for the account)".   Which implies it is determined by the account holder (not the bank), and may vary by account (i.e. instance-of-product), rather than per product

If this field is not to be used an unambiguous indication of a product from which an account was created, then which field, if any serves that purpose?

**Comment by CDR-API-Stream** [comment]
This confusion is possibly arising from the evolution of terminology in the CDR regime over time.  The description should more correctly read as:
*The unique identifier of the account as defined by the **data** holder (akin to model number for the account)*

This will be fixed as a documentation defect in the upcoming release

**Comment by boardbloke** [comment]
Thanks for the clarification :-)
