### ISSUE TITLE
Recover from lost client registration

### ISSUE THREAD

**Issue by Smoovsky** [ConsumerDataStandardsAustralia/standards-maintenance#545]
I'm not sure if this is the right place to ask, as this could be either a Consumer Data Standard question or a Data Holder Implementation question.

That standard states that "Duplicate registrations are not permitted so attempts to create a registration which already exists MUST return an HTTP 400 error."
Whilst it's not impossible that the data recipient failed to receive and save the registration result due to some transient network/database error or lost the detail of existing registration in some edge cases. In that case, I don't see any plan B other than contacting the data holder's support and asking them to either give the existing registration detail or simply delete the old registration.

**Comment by perlboy** [comment]
> In that case, I don't see any plan B other than contacting the data holder's support and asking them to either give the existing registration detail or simply delete the old registration.

That is _exactly_ what the expected behaviour is.

Client Registrations are so rare (_once_) I'm unclear what the cost/benefit win is of having some backup method for, arguably, the most complex technical action in the CDR.

**Comment by Smoovsky** [comment]
> That is _exactly_ what the expected behaviour is.

Thanks for your prompt reply.
If that's the intended then the data recipient just needs to be careful with keeping existing registrations.

**Comment by perlboy** [comment]
Yes, Recipients _must_ be careful with their registrations because there are legal requirements on the organisation if they are lost (data deletion, arrangement revocations etc).
