### ISSUE TITLE
Allow for Personal/Private use of APIs

### ISSUE THREAD

**Issue by hovrawl** [ConsumerDataStandardsAustralia/standards-maintenance#548]
# Description
Currently in order to access the CDR you need to register as a business as it is expected applications requesting data will be a commercial product, in my use case I want to create a personal use application that would read data to provide insights.

# Area Affected
Register/Authorisation APIs

# Change Proposed
Open the API's or add new APIs for consumers to be able to get their own data without needing to be a business.

**Comment by perlboy** [comment]
@hovrawl this is the Direct to Consumer component of the CDR which was [deferred by Treasury](https://treasury.gov.au/media-release/developments-australias-consumer-data-right-response-community-feedback) pending consultation in 2021. I don't believe this has kicked off yet.

**Comment by hovrawl** [comment]
That is a shame. After looking around it is hard to find any clarification around this topic. There were no articles to indicate whether it would be implemented at any point since it is past the community feedback stage. Is there any way to bump this topic back up and try get this implemented at some point?

**Comment by nils-work** [comment]
Hi @hovrawl 

Thanks for raising this issue.

As mentioned in the [previous comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/548#issuecomment-1272221660), this capability is not currently provided by the CDR.

Further information is available in this guidance article - [Response to queries: Deferral of joint account and direct to consumer obligations](https://cdr-support.zendesk.com/hc/en-us/articles/360004343516-Response-to-queries-Deferral-of-joint-account-and-direct-to-consumer-obligations) under the heading **What are ‘direct to consumer’ obligations that are being deferred?**

Further questions such as this can be directed to the [CDR Support Portal](https://cdr-support.zendesk.com/hc/en-us).
