### ISSUE TITLE
GreenPower pricing is being rounded to the nearest cent in plan documents

### ISSUE THREAD

**Issue by garychapman** [ConsumerDataStandardsAustralia/standards-maintenance#549]
[Apologies if this isn't the correct forum for these kinds of reports, but I'm not sure where else it might belong]

GreenPower pricing is being rounded to the nearest cent in Get Generic Plan Detail documents. For example, https://www.energymadeeasy.gov.au/plan?id=ACT118891SRE5&postcode=2321 has GreenPower tariffs of 0.0055, 0.01375 and 0.055, but the corresponding Get Generic Plan Detail document (https://cdr.energymadeeasy.gov.au/actewagl/cds-au/v1/energy/plans/ACT118891SRE5@EME) rounds these values to 0.01, 0.01 and 0.06, which is effectively useless for calculating GreenPower charges. This rounding occurs in numerous plan documents: ActewAGL, Amber, Aurora, Diamond and Red Energy seem to be the main offenders.

**Comment by naslanian** [comment]
@garychapman Thanks for bringing this to our attention. This issue has been fixed – energy plans with GreenPower charges on the [Energy Made Easy](https://www.energymadeeasy.gov.au/) website, now round to the same values via Get Generic Plan Detail.

**Comment by nils-work** [comment]
Hi @garychapman 

Although the [current version of the plan](https://cdr.energymadeeasy.gov.au/actewagl/cds-au/v1/energy/plans/ACT118891SRE7@EME) you mentioned appears to mix the scale of **AmountString** values between Dollars (for fees) and Cents (for usage charge, load unit price and solar tariff), it appears that the rounding issue for GreenPower pricing (in Cents) is resolved as noted in the [comment above](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/549#issuecomment-1349977302).

[**Plan data**](https://cdr.energymadeeasy.gov.au/actewagl/cds-au/v1/energy/plans/ACT118891SRE7@EME):
```
"greenPowerCharges": [
  {
    "type": "FIXED_PER_UNIT",
    "tiers": [
      {
        "amount": "0.0066",
        "percentGreen": "0.1"
      },
```
[**Plan page**](https://www.energymadeeasy.gov.au/plan?id=ACT118891SRE7&postcode=2321):
![image](https://github.com/user-attachments/assets/cb266195-f273-40cc-80ab-b6f1cd35d509)


Can you confirm that this issue can now be closed?

**Comment by garychapman** [comment]
Can confirm that this has been fixed.
