### ISSUE TITLE
Specify the type of sharing_duration claim as a number in the normative standards

### ISSUE THREAD

**Issue by pcurtisrab** [ConsumerDataStandardsAustralia/standards-maintenance#55]
# Description
The `sharing_duration` claim is specified as a duration in seconds. This makes sense to be encoded as a number, and this is allowed for by the OIDC. However, the normative standards don't specify the type, and the non-normative example is a string. Since the number type is the most natural fit, this appears to be unintended as a possible typographical error.

# Area Affected
[Request Object](https://consumerdatastandardsaustralia.github.io/standards/#request-object)

# Change Proposed
Specify the type of `sharing_duration` claim as of type `number` in the normative standards and update the Non-Normative accordingly:

```
{
  "alg": "PS256",
  "typ": "JWT",
  "kid": "123"
}
{
  "aud": "https://www.recipient.com.au",
  "response_type": "code id_token",
  "client_id": "12345",
  "redirect_uri": "https://www.recipient.com.au/coolstuff",
  "scope": "openid",
  "state": "af0ifjsldkj",
  "nonce": "n-0S6_WzA2Mj",
  "claims": {
    "sharing_duration": 7776000,
    "id_token": {
      "acr": {
        "essential": true,
        "values": ["urn:cds.au:cdr:3"]
      }
    },
    "userinfo": {
      "given_name": null,
      "family_name": null
    }
  }
}

```

**Comment by CDR-API-Stream** [comment]
The DSB concurs with this assessment and would accommodate this change as a defect as it does not impact the standards materially (non-normative examples are illustrative only).

If this change is considered urgent please indicate that otherwise it will be addressed in the next iteration or scheduled update.

**Comment by WestpacOpenBanking** [comment]
Westpac considers specifying the type of sharing_duration and correcting the example to be urgent.

**Comment by CDR-API-Stream** [comment]
This change has been incorporated into [v1.3.0 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.3.0.html#v1-3-0-release-notes).
