### ISSUE TITLE
Iteration 13 Holistic Feedback 

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#551]
This CR has been created to simplify the raising of minor changes, such as text corrections or description clarifications, that are not really material to the standards but do have real impact of readability and clarity.

Please raise any such suggestions that you would like included in Maintenance Iteration 13 and the DSB will review them. If we believe the suggestion are material we will raise a dedicated CR for them.

**Comment by perlboy** [comment]
`readQualities` for usage is being described as an Object when it isn't:
![image](https://user-images.githubusercontent.com/4291448/197374757-276a77b9-e1f5-4d26-ba24-9ac372d9cf90.png)

This should be an array of objects because it is possible for there to be multiple sets of read qualities over a sampling period.

**Comment by nils-work** [comment]
A missing font reference appears to have some impact on the Standards page rendering time.
Detail is in https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/235

**Comment by nils-work** [comment]
Two broken links in Register APIs documentation
https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/234

**Comment by nils-work** [comment]
The first sentence in the **[Register APIs](https://consumerdatastandardsaustralia.github.io/standards/#register-apis)** section of the Standards states -
> This following provides an overview of the Register APIs for Data Holders and Data Recipients to collect participant metadata **exclusively for the banking sector**. These endpoints are exposed by the Register and consumed by Data Holders and Data Recipients.

It should be updated to -
> The following section provides an overview of the Register APIs for Data Holders and Data Recipients to collect participant metadata. These endpoints are exposed by the Register and consumed by Data Holders and Data Recipients.

**Comment by nils-work** [comment]
Links referencing **TDIF** should be updated to the new site - https://www.digitalidentity.gov.au/tdif

**Comment by nils-work** [comment]
Apart from the FDO table where some historical dates are maintained for reference, the [Amending Authorisation Standards](https://consumerdatastandardsaustralia.github.io/standards/#amending-authorisation-standards) section repeats that the amending standards are **Effective from November 2021**.
As this is now almost 12 months past, it may be appropriate to remove this specific mention.

**Comment by nils-work** [comment]
Consider extending the list of applicable endpoints in the [CORS section](https://consumerdatastandardsaustralia.github.io/standards/?examples#cors) to include the unauthenticated endpoints for Energy (and Telco?) or move the endpoint designation into the respective endpoint definitions so it doesn't need to be maintained separately.
Another alternative may be to clarify that all unauthenticated endpoints require CORS, but this may not always be the case.

**Comment by nils-work** [comment]
The endpoints in the [Energy Secondary DH APIs](https://consumerdatastandardsaustralia.github.io/standards/?examples#energy-secondary-dh-apis) section all incorrectly state **This operation does not require authentication**.
These should be updated to something like **This operation may only be called by Energy Primary Data Holders**.

**Comment by CDR-API-Stream** [comment]
> `readQualities` for usage is being described as an Object when it isn't: ![image](https://user-images.githubusercontent.com/4291448/197374757-276a77b9-e1f5-4d26-ba24-9ac372d9cf90.png)
> 
> This should be an array of objects because it is possible for there to be multiple sets of read qualities over a sampling period.

This defect was fixed in version 1.20.0 release of the standards.

**Comment by nils-work** [comment]
One additional documentation fix that may warrant late inclusion for MI13 is a typo in this statement in the Version Delta alongside [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/?diff#http-headers) - 
`Clarified that the x-fapi-interaction-id is not required for authenticated resource APIs`
It should state **unauthenticated** -
`Clarified that the x-fapi-interaction-id is not required for unauthenticated resource APIs`

**Comment by nils-work** [comment]
These items were delivered through https://github.com/ConsumerDataStandardsAustralia/standards/issues/272#issuecomment-1362187373
