### ISSUE TITLE
ABN should not have spaces

### ISSUE THREAD

**Issue by c799878** [ConsumerDataStandardsAustralia/standards-maintenance#555]
# Description
An ABN is often displayed with spaces between groups of digits, but in API responses the spaces should be absent.

# Area Affected
The "abn" field in response to the registry API "Get Data Holder Brands Summary".

# Change Proposed
The list returned on 2022-11-18 includes 116 entries with an "abn". 101 are 11-character strings with no spaces (eg "93111195389"). 15 are 14-character strings with spaces (eg "48 006 434 162").
The OpenAPI files specify a maxLength of 11 for the "abn" field.

Fix the metadata for the 15 data holders brands that have spaces in the ABN: HSBC; NAB; AMP; Heritage Bank; IMB Bank; Queensland Country Bank; UBank; Card Services; Coles; Kogan; Qantas; Citi; Hume Bank.

**Comment by nils-work** [comment]
Hi @c799878 
This appears to be resolved now, would you like to confirm and close this issue?
