### ISSUE TITLE
PAF vs Simple Address in the Customer Data Payloads[Descriptive Issue Title]

### ISSUE THREAD

**Issue by TlsRish** [ConsumerDataStandardsAustralia/standards-maintenance#556]
# Common APIs (Customer Detail)  Simple vs PAF address Format
Seeking clarity on the format of Address in the Customer Data Payloads provided by the Data Holders. 

Question: 
It is fair to assume that Data holder can choose to provide either of the Simple or The PAF format and **not obligated to  support both formats.** 
https://consumerdatastandardsaustralia.github.io/standards/#tocScommonphysicaladdresswithpurpose

**Comment by nils-work** [comment]
Hi @TlsRish 

That is correct, you would expect a Data Holder to provide either the `paf` or `simple` address object, not both.

This is perhaps described more clearly in the first schema within `CommonPhysicalAddressWithPurpose`, `CommonPhysicalAddress`.
As highlighted below:

![image](https://user-images.githubusercontent.com/60594671/203486585-cbe95fc2-3914-43d9-b5cc-baf8375345cc.png)

Just for your awareness, this repo is intended to capture change requests for the Data Standards. 
If you have further questions about their operation, you may [post them](https://cdr-support.zendesk.com/hc/en-us/requests/new), or find existing answers on the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).

**Comment by nils-work** [comment]
Closing as an answered question.
