### ISSUE TITLE
 FAPI 1.0 Final Phase 3 Obligation example for authorisation request using the Authorisation Code Flow does not have "response_mode" attribute

### ISSUE THREAD

**Issue by AG-IAM** [ConsumerDataStandardsAustralia/standards-maintenance#559]
# Description
For FAPI 1.0 Final Phase 3 Obligations, the Non-Normative Example Utilising FAPI 1.0 Final, PAR RFC9126, PKCE, JARM and Authorization Code Flow does not have "response_mode" attribute in the decoded request. The "response_mode" attribute will be identified by Authorisation server to provide the corresponding authorisation response. Without this attribute, the code will be sent directly as a query parameter and not in a signed/encrypted JWT. Is this the expected behaviour? if yes, the documentation needs to be updated with the attribute "response_mode" as Optional and expected response for authorisation code Flow and authorisation code Flow with JARM.

# Area Affected
https://consumerdatastandardsaustralia.github.io/standards/?examples#security-endpoints > Pushed Authorisation End Point > Decoded Request - FAPI 1.0 Final Phase 3 Obligation
![image](https://user-images.githubusercontent.com/119274961/204197502-44c86879-99d8-4209-b370-dbd1aef170f5.png)

# Change Proposed
Update non-normative example for FAPI 1.0 Final Phase 3 Obligations to include "response_mode" in the Decoded Request or update the documentation with the expected response for authorisation code Flow and authorisation code Flow with JARM.

# DSB Proposed Solution

The current DSB proposal for this issue is in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/559#issuecomment-1491214909

**Comment by markverstege** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.24.0...maintenance/559

Note it is compared against the previous release. At present no draft 1.25.0 release has been staged but it is expected this change will target 1.25.0 for release at the end of maintenance iteration 15.

**Comment by markverstege** [comment]
Hi @biza-io, the staged non-normative example should address your feedback when JARM is used in combination with Authorization Code Flow. [FAPI 1.0 Advanced](https://openid.net/specs/openid-financial-api-part-2-1_0.html#jarm-1) states that `response_mode` of `jwt` be used which is reflected in the staged non-normative example.

**Comment by nils-work** [comment]
Staging link for 1.25.0 - https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.25.0...maintenance/559

**Comment by nils-work** [comment]
[Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html) version 1.25.0 has now been published, incorporating this change.
