### ISSUE TITLE
Intention of the lastUpdated property within BankingProductV4

### ISSUE THREAD

**Issue by af-stayorgo** [ConsumerDataStandardsAustralia/standards-maintenance#564]
I would like to request clarification on the intention of the `lastUpdated` property within BankingProductV4 responses. The current description is:

“The last date and time that the information for this product was changed (or the creation date for the product if it has never been altered)“.

It seems clear that if the product changes, for example an increase to a fee or rate, then the `lastUpdated` property should be set to the time of change.  What is not clear is, if the product doesn't change, however the formatting of information within the payload does, should the `lastUpdated` property be updated?  Examples of this include:

- Removing trailing zeros from RateStrings, e.g. "0.03500" to "0.035"
- Changing numeric data types, e.g. 5.0 (float) to 5 (int)
- Modifying currency representations, e.g. "$600" to "600 AUD"
- Modifying frequency strings, e.g. "per year" to "P1Y"
- Modifying DateTimeString precision, e.g. "2022-12-01T18:21:00.0000Z" to "2022-12-01T18:21:00Z"
- Modifying case within additionalInfo strings, e.g. "... lvr ..." to "... LVR ..."
- Omitting an optional property that previously had a null value
- etc.

Furthermore, are data holders permitted to arbitrarily set the `lastUpdated` property (e.g. each day), when there have been no changes to the data?

Thanks

**Comment by nils-work** [comment]
Hi @af-stayorgo 

While it may be recommended for Data Holders to update the `lastUpdated` value when changes such as you have described are made, it is ultimately at their discretion to determine what constitutes an 'update' that could warrant a potentially more timely refresh by consumers of that data.

It would not be recommended for data holders to change the `lastUpdated` value if no changes have been made, as this could cause consumers (of the API) to make unnecessary requests.

Further questions such as this can be directed to the [CDR Support Portal](https://cdr-support.zendesk.com/hc/en-us) where it could become the basis for additional guidance.
