### ISSUE TITLE
Security Evaluation of existing_refresh_token

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#57]
# Request For Clarification
With reference to the recently published [Concurrent Consent](https://github.com/ConsumerDataStandardsAustralia/standards/issues/85) ConsumerDataStandardsAustralia/standards#85 proposal it appears the decision, which appears to have limited community feedback, is to introduce an environment where an existing refresh token is to be provided as part of the Request Object for a new additional consent?

This addition appears to introduce a scenario where an end-users browser will become aware of a token which was not previously disclosed by a Recipient (RP) to the end user but now is disclosed during Request Object communication sent to the Holder's (OP) authorisation server? Within typical OIDC this is not disclosed to the user and is mitigated via the use of a one-time `authorization_code`. 

Since this is end user browser interaction it is also not protected by CDR CA MTLS. At a glance, the immediate and easiest attack vector is XSS injected at a Recipient level that silently intercepts functional refresh tokens during additional consent requests.

Has a security evaluation been conducted regarding additional attack vectors the consent sequence is now exposed to?

**Comment by CDR-API-Stream** [comment]
The decision also notes that additional consultation on the target state will be conducted.  The issue described above was raised in the Advisory Committee meeting and will be analysed.

It is worth noting that the vector described above is ameliorated by the fact that the refresh token described is only included so that it can be immediately revoked which reduces the usefulness of the token.  Also, the refresh token (if not revoked) can only be used via the token end point which is protected by MTLS, and private_key_jet to verify the source of the request.

**Comment by jogu** [comment]
> It is worth noting that the vector described above is ameliorated by the fact that the refresh token described is only included so that it can be immediately revoked which reduces the usefulness of the token.

This token is presumably only revoked *after* being passed through the front channel and a successful user authentication/authorization, so is quite far from 'immediate', with the timescales ranging from "seconds" up-to and including "never revoked".

Passing items in the front channel that all security analysis of the underlying protocol assume are not exposed outside the client invalidates a significant amount of the research into attacks that has been done. It's not something I'd suggest doing without running past some standards experts first, i.e. at a minimum, raising it the working groups for the relevant standard(s).

> Also, the refresh token (if not revoked) can only be used via the token end point which is protected by MTLS, and private_key_jet to verify the source of the request.

This is reasonable, however it's not entirely true. As per this change, the refresh token can also now be used in the front channel which is not MTLS protected. Admittedly if I've understood correctly this can [currently] only potentially cancel the token and hence can only give rise to the DoS style attack if there is a weakness, but there's an inherent danger that this might behaviour might be tweaked further.

**Comment by perlboy** [comment]
Putting aside the actual change specified here because I feel @jogu has provided a sufficient response it does raise a fundamental question as to how a change has been approved by the Chair without any formal analysis conducted of the security impact.

Could the DSB provide guidelines or a documented workflow with respect to the assessment of security impact and risk analysis conducted of changes? I am not aware of any formalised document the DSB has adopted that provides clear guidance on how risks are assessed although maybe I missed it?

 Within an ISO27001 certified organisation this would typically be contained within a Risk Register coupled with Risk Management and Risk Classification documentation.

**Comment by WestpacOpenBanking** [comment]
Westpac shares the concerns raised and agrees that there is a need for further security analysis to understand the extent to which risk is increased by distributing long lived security credentials widely to CDR consumers.
 
We also note that this approach conflicts with the normative security standards. For example, [section 10.4 of the OAuth 2.0 standard](https://tools.ietf.org/html/rfc6749#section-10.4) says that refresh tokens must be kept confidential between authorization server and client to which token was issued.

**Comment by commbankoss** [comment]
Commonwealth Bank shares @WestpacOpenBanking concerns about front channel exposure of long lived refresh tokens. 

Commonwealth Bank also believe that a comprehensive round of security assessment is required prior to go-live to account for the impacts of ACCC registry interactions and the latest changes to security standards.

**Comment by tlodderstedt** [comment]
I would like to share my thoughts on this issue.

Your design recommendation uses refresh tokens under circumstances they were never designed for, which changes the security properties of the protocol. Experience shows that such changes will almost always result in security flaws, this issue obviously not being an exception. 

Designing security protocols is not an easy task, it takes time and the right mixture of expertise. To give you an examples: the OAuth 2.0 security threat model (RFC 6819) took about a year, a 70 pages document and the attention of the OAuth WG and the IETF's security experts. 

I therefore recommend you to change your design to utilize existing protocol capabilities to achieve your objectives. 

What I mean is I don't think you need to use refresh tokens as pointer to different consents. As far as I understand your design, the data recipient is supposed to maintain a refresh token and associated access token for every consent related to a distinct use case. This is rather complex to manage given OAuth libraries most likely will not support this new behaviour out of the box. 

I think using different client_ids (bound to the same legal entity) to represent different use cases would work as well but has the advantage of being fully compatible with the way OAuth was designed and is used today. This would also solve the security issue since the client_id (which is designed to be public) would select the consent not the refresh token (a credential).

best regards,
Torsten Lodderstedt (editor OAuth 2.0 Security Best Current Practice & OpenID FAPI WG member)

**Comment by spikejump** [comment]
Other than the mentioned security concerns can there be a clarification on the specific use-cases that require the introduction of a `existing_refresh_token` claim?

When an existing consent it due to expire the end-users (customers) can simply initiate a new consent and letting the existing expire.

If this route is taken, then it seems `existing_refresh_token` will not be required?  And then the only real change to the spec is the removal of the single consent?

**Comment by jogu** [comment]
> Other than the mentioned security concerns can there be a clarification on the specific use-cases that require the introduction of an `existing_refresh_token` claim?
> 
> When an existing consent is due to expire the end-users (customers) can simply initiate a new consent and letting the existing expire.

As I understand it, the goal is to make extending a consent simpler and less error-prone for end users than granting a new consent.

e.g. extending a consent will not require the user to select the accounts to be shared

Personally I think it's a flaw in the law (in both Australia and the UK) that the consumer does not have the authority to grant permanent (non-expiring) access if they so desire. In the UK the user has to extend the consent every 90 days and it causes real problems with continuity of service.

**Comment by qcastel** [comment]
Best mentioning that the refresh token can be stateless, so a JWT and has a consequence, putting it as a claim will increase significantly the size of the request parameter.
This may become a technical challenge if the size of the request parameter get closed to 2000 characters : https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by spikejump** [comment]
> As I understand it, the goal is to make extending a consent simpler and less error-prone for end users than granting a new consent.

Conceptually it seems easier to offer customers an UI that says to continue your current authorisation just click this button and thereby leverage `existing_refresh_token`.  However, CDR Rules is very explicit on what is presented to the customer for consent.  It requires customer to explicitly select each cluster for consent.  You can't even present a pre-selected data cluster to customer.  It's questionable how a re-authorisation experience may be simpler from first time consent (or full consent process) for customers.

CDR Rules does not cater for re-authorisation.  There is also no CX Guidelines that supports re-authorisation.  Use-cases should be developed to understand how `existing_refresh_token` helps to make the customer experience better.  This path although viable would raise question about the July 2020 timeline.

**Comment by tlodderstedt** [comment]
I think re-authorization does not require a refresh token to be present in the request.

In my opinion, the most robust way is to treat a re-authorization request like any authorization request (including scopes and so on) and the AS (data holder) determines the pre-existing authorization of the user for this particular data recipient based on user id and client id. And then it is indeed just a question of UX at the AS side how this request is processed (ask again for selection and approval, just re-confirm, process automatically if law/regulation permits). 

That's at least the way it is implemented in various places outside of CDR.

If one uses the refresh token as a pointer to an existing authorization, it also needs to treat the error condition that the refresh token has been revoked, in which case the AS wouldn’t have enough information to re-gather authorization from the user. Instead the AS would need to deny re-authorization (redirect back with error code) and the data recipient would need to re-start an authorization process. I don't think this is the desired UX.

**Comment by CDR-API-Stream** [comment]
The scenario you describe @tlodderstedt is essentially the previous position of the standards where each client_id was limited to a single consent and the establishment of a new consent would replace the previous one.

In response to CX research, the design of the Register and community feedback it was determined that this approach would not be viable as the regime scales and data recipients start to explore different use cases with the same customer within a single service.  This was exacerbated by the regulatory rules of the regime that specify a data minimisation principle that is not believed to be compatible with a single extant consent covering all of the scopes needed for a variety of use cases at the same time.

Some of the suggestions being put forward in this thread are good and have been suggested previously.  The CDR standards are, however, constrained by the CDR regulatory rules to which they must align.  Currently, among other things, the rules:
- do not allow for a separate, simpler, CX flow for re-authorisation
- require that when a consent is revoked or expired that all data collected under the consent is deleted or de- identified
- mandate that consent is limited to a maximum of 12 months

This makes the use of straight OAuth difficult which has been the main driver for variation.

**Comment by tlodderstedt** [comment]
Would you please describe why the rules you listed precludes use of "straight OAuth"? As I stated in my previous comment, demarcation of different use cases for a particular data recipient (legal entity) is possible by using different client_ids. Everything else can be built on top of this foundation (including data deletion on revocation and limits on consent duration).

**Comment by CDR-API-Stream** [comment]
> Would you please describe why the rules you listed precludes use of "straight OAuth"?

The answer to that question can't be simply summarised.  The current position of the standards is the result of eighteen months of consultation in the threads available in this repository and the main standards repository.

> As I stated in my previous comment, demarcation of different use cases for a particular data recipient (legal entity) is possible by using different client_ids. Everything else can be built on top of this foundation (including data deletion on revocation and limits on consent duration).

That specific option of using different client_ids being difficult to adopt is related to the design of the register and practical logistics of managing the accredited entities and their brands rather than the rules.

**Comment by tlodderstedt** [comment]
> That specific option of using different client_ids being difficult to adopt is related to the design of the register and practical logistics of managing the accredited entities and their brands rather than the rules.

So you are saying the register and the processes were designed to maintain a single client_id per data recipient. 

I think the effort required to adopt this implementation and processes needs to be weight against extending a mature security protocol by CDR proprietary features. This is possible but will require an in-depth security analysis and implementation support by vendors and open source libraries.

**Comment by CDR-API-Stream** [comment]
The register allows for a client_id per "service" or "application" offered as opposed to a client_id per purpose.  A single service may still request data for many purposes, especially noting that the concept of purpose in the CDR is driven by the legal framework and is quite granular.

**Comment by tlodderstedt** [comment]
Do I get it right that the register supports multiple services per legal entity?

**Comment by CDR-API-Stream** [comment]
> Do I get it right that the register supports multiple services per legal entity?

Yes

**Comment by CDR-API-Stream** [comment]
If there are no more questions related to this query it will be closed on Friday.

**Comment by cdradr** [comment]
What is the outcome here?

Has security evaluation been performed?

PS this is a great non-answer by the way: 
> The answer to that question can't be simply summarised. The current position of the standards is the result of eighteen months of consultation in the threads available in this repository and the main standards repository.

**Comment by tlodderstedt** [comment]
I repeat my concerns regarding use of refresh tokens in the front channel to identify consents. 

I think this proposal is much better suited: https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-592320557

**Comment by jogu** [comment]
I'm similarly confused as to the outcome here and the desire to close the ticket without any clear conclusion?

If refresh tokens are to continue to be used in the front channel (which I think would be a very bad decision) then CDR should be funding security analysis by experts, and would have to accept that there is at least a medium level risk that serious concerns are raised by such an analysis.

If that analysis doesn't happen (or the security analysis finds serious concerns) then alternative protocol level approaches must be sought, and this would seem to be best approach given the feedback to date. The most sensible option on the table looks to be aligning with international efforts that solve the same goal, as per the OpenID Foundation's suggestion here:

https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-592320557

CDR could feed into that effort to make sure any particular requirements Australia has are addressed, and OpenID Foundation protocols are generally adopted by the vendors so this would make later roll out of CDR beyond the banking use cases significantly quicker and less error prone, as well as allowing CDR participants to leverage what they build in Australia to expand into other markets that follow international standards.

**Comment by perlboy** [comment]
In addition to the concerns highlighted again by more enlightened members of the security community I re-ask the same fundamental question I posted in my first response:

> Could the DSB provide guidelines or a documented workflow with respect to the assessment of security impact and risk analysis conducted of changes? I am not aware of any formalised document the DSB has adopted that provides clear guidance on how risks are assessed although maybe I missed it?

The timeline on `existing_refresh_token` proposal appears to be as follows:

- 22 September 2019: [Decision 85](https://github.com/ConsumerDataStandardsAustralia/standards/issues/85) is posted, receives 2 feedback, one preferring "Option 2", one preferring a formalised Consent API.
- 29 October 2019: [Decision 85](https://github.com/ConsumerDataStandardsAustralia/standards/issues/85) Final Decisions document is published proposing Option 3 (`existing_refresh_token`)
- 10 December 2019: The Chair, Andrew Stevens, approves this document effectively with no public feedback supporting it
- 11 December 2019: This thread is opened. 8 participants, multiple responses, few answers to my original question. Participants include ADR's, FAPI WG and authors of [OAuth 2.0 Security Best Current Practice](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-14)
- 16 December 2019: @CDR-API-Stream clarifies stating _"The decision also notes that additional consultation on the target state will be conducted."_
- 29 January 2020: [Changes to the Slate specification](https://github.com/ConsumerDataStandardsAustralia/standards/commit/2c2216eca9aa3c9d7f40caf563f7cd077fcbf633) are made by @JamesMBligh
- 31 January 2020: [V1.2.0](https://github.com/ConsumerDataStandardsAustralia/standards/commit/4fc751ed7b44e522077803a4edb49b2d589d78db) of the Standards are merged by @JamesMBligh including enforceable dates
- 4 February 2020: [Decision Proposal 99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issue-559369359) is opened requesting feedback. 7 feedback items are received, zero support `existing_refresh_token`, 2 support the introduction of a `sharing_id` without more structured identification of consent and 5 request more collaborative workshops to ensure a reasonable target state
- 28 February 2020: [CBA raises inconsistencies](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/144) between published Standard and the Decision Proposal
- 2 March 2020: @CDR-API-Stream asks if this query can be closed.
- 3 March 2020: [Decision Proposal 99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issue-559369359) thread is closed and locked.

So I come back to my first response after my original query of _"Has a security evaluation been conducted regarding additional attack vectors the consent sequence is now exposed to?"_ and follow it up with my first comment response _"Could the DSB provide guidelines or a documented workflow with respect to the assessment of security impact and risk analysis conducted of changes?"_

I'm confused as to what process is being followed and in the meantime approximately 6 months have been burned that could have been utilised to have a fruitful discussion on a solution which is future proofed (one of the "asks" if I remember correctly), is considered by leading security experts and clearly specified in a way implementer's can adopt.

**Comment by cdradr** [comment]
Plus 1 for progressing this proposal https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-592320557

It’s a pity the issue was closed for feedback  - more feedback from the local community to support or challenge this proposal would be great. @CDR-API-Stream may be you could enable comments?

It’s great to see active contributions from OpenId Foundation.

**Comment by CDR-API-Stream** [comment]
Hi everyone thanks for the additional feedback and responses. This was an initial request for consultation. Feedback such as handling of refresh tokens is noted and as @perlboy mentions will be covered under a specific issue for consultation: [Decision Proposal 99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issue-559369359). 

We will leave this issue open until completion of [Decision Proposal 99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issue-559369359)

**Comment by CDR-API-Stream** [comment]
Hi @cdradr feedback on the current consultation for [Decision Proposal 99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issue-559369359) is closed. This feedback is now being reviewed and incorporated into an updated decision proposal which will be circulated.

**Comment by perlboy** [comment]
@CDR-API-Stream You still haven't answered the question asked and this is unrelated to DP99.

**Comment by commbankoss** [comment]
Commonwealth Bank would like to strongly reiterate its desire that a comprehensive independent security assessment is done prior to go-live. We need to review all the changes since the last assessment as well as the final state of the ecosystem.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

`existing_refresh_token` was removed from 1.3.0.
