### ISSUE TITLE
Additional functionality to support account selection

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#574]
# Description
Data holders (DH) have queried how to present, sort, and select multiple accounts in the account selection step where the consumer has an extensive list of eligible accounts for sharing. This may, for example, occur where a non-individual consumer has hundreds of eligible accounts. 

Sharing the correct account(s) may be cumbersome and non-intuitive if a DH did not provide additional functionality to support account selection such as pagination, sorting, and filtering. However, the rules and standards do not explicitly refer to this type of functionality as permitted:

- Rule 4.24 prohibits data holders adding additional information, interactions, or services to the authorisation process beyond what is outlined in the CDR rules and standards.
- The current [Authorisation Standards](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-standards) outline optional functionality that may be included in the authorisation flow, but does not specify additional functionality to aid account selection (such as sorting and searching).

A current example of account selection can be found in the [Authorise](https://d61cds.notion.site/Authorise-a51263ba331b4ca8b3defac444c2327f) section of the CX Guidelines.

This change request proposes a new standard to unambiguously allow additional functionalities in the authorisation flow where it is appropriate to do so.

# Area Affected
This issue may affect consumers that have a large number of accounts such as large businesses (i.e. commerical and industrial customers).

The proposed standard would be added to the [Authorisation Standards](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-standards).

The related area is CDR rule 4.24, Restrictions when asking CDR consumer to authorise disclosure of CDR data:

> When asking a CDR consumer to authorise the disclosure of CDR data or to amend a current authorisation, the data holder must not do any of the following: 
     (a) add any requirements to the authorisation process beyond those specified in the data standards and these rules; 
     (b) provide or request additional information during the authorisation process beyond that specified in the data standards and these rules; 
     (c) offer additional or alternative services as part of the authorisation process; 
     (d) include or refer to other documents.

# Change Proposed
A new [Authorisation CX Standard](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-standards) is proposed to allow additional account selection functionality in the authorisation flow, as follows:

> Data holders **MAY** include additional functionality to support account discovery and selection where scrolling is required to view all accounts. This **MAY**, for example, include search, sort, filter, scroll, and pagination. Any such functionality **MUST NOT** introduce unwarranted friction.

The DSB would like feedback on the following: 

1. Does the proposed approach appropriately address the described issue?
2. What additional functionality is desirable to support account discoverability and selection in this scenario?
3. Are there technical limitations that need to be considered when displaying an extensive list of accounts (e.g. loading and timeout issues)?
4. What use cases would this additional functionality support, for example:
   - Are customers with extensive accounts seeking to share all accounts, a subset of accounts, or a specific account(s)?
   - How are these customers seeking to sort, filter, or specify their accounts, e.g. based on the account type, property, alphabetically etc.?

# DSB Proposed Solution

The current DSB proposal for this issue is in this [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/574#issuecomment-1504632103)

**Comment by anzbankau** [comment]
Thank you for the opportunity to provide feedback on this matter. Our comments below
 
1. _Does the proposed approach appropriately address the described issue?_
ANZ: Yes, we believe it does.
2. _What additional functionality is desirable to support account discoverability and selection in this scenario?_
ANZ: Yes, we believe the DSB has provided a good level of coverage in terms of the possible UI sorting and filtering capabilities. However, it should be noted that the standards should not be so prescriptive that Data Holders need to differentiate the sorting / filtering capabilities in OB flows to existing online banking experience. Data holders should be supported in providing their customers with sorting / filtering capabilities that are consistent with their existing online banking experience in other digital channels.
3. _Are there technical limitations that need to be considered when displaying an extensive list of accounts (e.g. loading and timeout issues)?_
ANZ: The following factors should to be considered:
 
    - Accessibility: The standards/guidelines should consider accessibility needs and additional sorting/filtering capabilities must not adversely impact the journey for those users with accessibility requirements.
    - Device type & size: Full elimination of scrolling may not be achievable due to different device types (i.e. mobile, tables, etc.) though we would try minimise as much as possible.
 
4. _What use cases would this additional functionality support, for example:_
 
    - _Are customers with extensive accounts seeking to share all accounts, a subset of accounts, or a specific account(s)?_
ANZ: We have not observed the need for a 'select all' function, and would note that such a function may violate the principle of data minimisation.
    - _How are these customers seeking to sort, filter, or specify their accounts, e.g. based on the account type, property, alphabetically etc.?_
ANZ:  We could also consider sorting / filtering accounts based on :
      - Ownership type (for example, joint or solely owned)
      - Account status

**Comment by JohnMillsEnergyAustralia** [comment]
As a data holder here our submission is that: 
•	No additional functionality is desirable to support account discoverability / selection as we have found the existing standards provide the adequate flexibility for implementation. 
•	No technical limitations were found in displaying an “accounts selection” lists
•	Existing business customers have alternate existing means to secure appropriate data from retailers.

**Comment by PratibhaOrigin** [comment]
Origin Energy would like to thank DSB for the opportunity to provide feedback on this topic. 
We welcome the proposed change - 

> Data holders MAY include additional functionality to support account discovery and selection where scrolling is required to view all accounts. This MAY, for example, include search, sort, filter, scroll, and pagination. Any such functionality MUST NOT introduce unwarranted friction.

This will give us the flexibility to provide better CX experience for our large customers with multiple accounts during their CDR journey. Once this CR is approved , we will look to support these customers via the suggested options like search , pagination capability. We may look at providing search by parameters which the customer is aware of via their online experience on our portal like accounts , address etc.

**Comment by joshuanicholson** [comment]
As an ADR we support this change. We are definitely coming across "business consumers" who have many 50+ accounts. Any form of improvement to allow consumers to find and select bank accounts quickly would be of great assistance. Common user cases would include
* filtering based on account type - for example, filter all credit cards
* filter on account details like a BSB - the logical assumption being sort, filter or search on a BSB allows consumers to determine accounts & select based on their location since BSB's often relate to specific locations/towns/suburbs
* Search or order by account number; for larger businesses & some DHs many of the account names could be the same; for example, 100 accounts are "Everyday Business Accounts" so the only reliable way to distinguish one account from another is via the unique account number. This also leads to DH's displaying account nicknames if that feature is available.   
* Searching account names, nicknames, and legal owner of an account.

**Comment by CDR-CX-Stream** [comment]
Thank you to everyone for their feedback so far. 

Based on the input received here and on the MI call from 29 March, this proposal is supported. A minor revision has been made to the proposal as per below to provide further flexibility. 

> Data holders **MAY** include additional functionality to support account discovery and selection where further navigation or interaction is required to view all accounts. This may, for example, include search, sort, filter, scroll, grouping, and pagination, or other controls in line with existing consumer experiences. Any such functionality **MUST NOT** introduce unwarranted friction. 
> 
> **Note:** Unwarranted friction should have regard to CDR Rule 4.24 and is considered to include the addition of any requirements beyond normal data holder practices for an equivalent account selection process. 

This updated proposal will be included in the decision proposal for MI14.

**Comment by CDR-API-Stream** [comment]
> Thank you to everyone for their feedback so far.
> 
> Based on the input received here and on the MI call from 29 March, this proposal is supported. A minor revision has been made to the proposal as per below to provide further flexibility.
> 
> > Data holders **MAY** include additional functionality to support account discovery and selection where further navigation or interaction is required to view all accounts. This may, for example, include search, sort, filter, scroll, grouping, and pagination, or other controls in line with existing consumer experiences. Any such functionality **MUST NOT** introduce unwarranted friction.
> > **Note:** Unwarranted friction should have regard to CDR Rule 4.24 and is considered to include the addition of any requirements beyond normal data holder practices for an equivalent account selection process.
> 
> This updated proposal will be included in the decision proposal for MI14.

This change has been staged and can be reviewed here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/615e59faa2ece707038a3b6bb05bf77da3fa4121
