### ISSUE TITLE
Inconsistency of data types in various schema

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#575]
# Description
There are minor differences in how some header types are defined in the [Register API Specification](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_register.json), compared to [Banking](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_banking.json) and others.

# Area Affected
For example: 

**Register**: [Get Data Holder Brands](https://consumerdatastandardsaustralia.github.io/standards/#get-data-holder-brands)

`x-v`, `x-min-v`, `page` and `page-size` appear as `integer`: 

![image](https://user-images.githubusercontent.com/60594671/214242530-72ce185d-2490-42c2-96cc-765512f8dafe.png)

The corresponding sample reflects the integer type: 

![image](https://user-images.githubusercontent.com/60594671/214244980-44e3bbda-6e26-45d3-933a-4f800a7b57e3.png)

**Banking**: [Get Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-accounts)

`x-v` and `x-min-v` appear as `string`, while `page` and `page-size` appear as `PositiveInteger`.

![image](https://user-images.githubusercontent.com/60594671/214242757-810a7018-45da-4eab-8103-d184ff3c8b12.png)

The corresponding sample reflects the string type: 

![image](https://user-images.githubusercontent.com/60594671/214242778-567ed0aa-b1cf-4a5b-91c4-3b0de83a8f8b.png)

# Change Proposed
Agree on the most appropriate convention and apply it consistently.

**Comment by biza-io** [comment]
Biza supports the alignment of specifications between the CDR Data APIs and the Register. Specifically we recommend aligning as follows:

1. Adopt `page` and `page-size` as PositiveInteger which we believe to be most appropriate and for which error handling behaviour is nuanced based on this (Invalid Field vs. Invalid Page)
2. The headers should be aligned to a string as this is aligned to the upstream standard governing headers (ie. HTTP 1.0/1.1).

**Comment by nils-work** [comment]
[Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html) version 1.25.0 has now been published, incorporating this change.
