### ISSUE TITLE
Energy Plan Contract coolingOffDays specified as int but many providers return string

### ISSUE THREAD

**Issue by georgesolomos** [ConsumerDataStandardsAustralia/standards-maintenance#582]
# Description
Let me acknowledge this is not a spec/schema issue, it's an implementation issue, but it's affecting many providers. Not sure where else I can report this issue.

The `EnergyPlanContractFull` schema lists the `coolingOffDays` field as an integer, but many providers are returning it from the Get Generic Plan Detail endpoint as a string. A non-exhaustive list is:

- AGL
- Diamond
- Energy Locals
- Origin
- Powershop
- Red Energy

To reproduce:

1. `GET https://cdr.energymadeeasy.gov.au/origin/cds-au/v1/energy/plans/ORI539562MRE1@EME`
2. The JSON returned includes `"coolingOffDays": "10"` when it should be `"coolingOffDays": 10`

# Area Affected
`EnergyPlanContractFull` type, `coolingOffDays` property.

# Change Proposed
Inform providers to ensure they adhere to the schema and send it as an integer.

**Comment by CDR-API-Stream** [comment]
@georgesolomos, the data holder for Energy Generic Tariff data (i.e. Production Reference Data), which the Get Generic Plan Detail endpoint returns, is AER. They host the endpoint and provide data for all the retailers.

AER are already aware of various data quality issues and are working on resolving them. You can report this issue (and similar ones related to PRD data quality) directly with them via the contact address on this page - https://www.aer.gov.au/consumers/energy-product-reference-data.

If there are other questions you can raise these via the Consumer Data Right Support Portal: https://cdr-support.zendesk.com/hc/en-us

**Comment by perlboy** [comment]
I love how this was opened in **April** and _nothing_ was done. These issues have persisted since launch and only under pressure has AER _actually_ acknowledged the problem but not committed to _any_ date to fix. It's pretty hypocritical that government departments, _especially_ entities which are subordinate organisations of the Regulator, are giving themselves a free pass .

**Comment by nils-work** [comment]
Hi @georgesolomos 

[This issue](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/582#issue-1650780911) appears to be resolved now, would you like to confirm?
If there are no further comments, this issue will be closed on 26 July 2024.

Thanks
