### ISSUE TITLE
Common Field Types enumerations versus customerUType and addressUType Schemas

### ISSUE THREAD

**Issue by cuctrangsb** [ConsumerDataStandardsAustralia/standards-maintenance#583]
# Description
The Common Field Types enum in the standard specifies that:
String representing an option from a defined list of values
- All possible values MUST be provided
- **Values MUST be in all caps**
- Spaces MUST be replaced with under bars '_'
- Values MUST be limited to the ASCII character set

However, the enumerated Values for customerUType and addressUType in the Banking APIs Schemas are all in lower case. 

![image](https://user-images.githubusercontent.com/118866266/229425503-68438b8f-4da6-4411-8b90-3878580ef9cd.png)

![image](https://user-images.githubusercontent.com/118866266/229425923-3e9e8d5e-27ab-45ff-becb-e7901b562b5b.png)

The requirements in these areas therefore appear to be conflicting. 

# Area Affected
Banking APIs Schemas

# Change Proposed
customerUType and addressUType enumerated values to be changed to Uppercase to be consistent with the Common Field Types enum.

**Please note**: this change will result in some technical changes for GSB to implement. Our current solution is compliant with the Schemas.

**Comment by nils-work** [comment]
Hi @cuctrangsb 

You are correct that enums are upper case, but as these values specify a reference to a union object by field name, they follow a different style according to the [Payload Conventions](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions) > **Field Naming Style**, and **Object conventions** -
`A specific convention will apply to union objects.`

That convention is applied across the Standards, not just the Banking schemas.

**Comment by nils-work** [comment]
This issue will be considered as a query with an answer provided and scheduled to be closed on 19 May 2023 if there are no further comments or changes to the Standards expected as an outcome.
