### ISSUE TITLE
Clarify Base and Adjustment Rate Types

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#585]
# Description
The **Product Deposit Rate Types** and **Product Lending Rate Types** tables under [**Product & Account Components**](https://consumerdatastandardsaustralia.github.io/standards/#product-amp-account-components) include all 'Base' and 'Adjustment' rate types in each respective table, and it may not be clear how these are expected to be used; individually or combined.

# Area Affected
The **Product Deposit Rate Types** and **Product Lending Rate Types** tables under [**Product & Account Components**](https://consumerdatastandardsaustralia.github.io/standards/#product-amp-account-components).

# Change Proposed
1. Split each table into 'Base' and 'Adjustment' types to more clearly convey the way they were expected to be used.
2. Provide guidance on rate usage for each section.
3. Add clarification in the _Description_ field for Base rate types that are expected to apply to `CRED_AND_CHRG_CARDS` products only.

No other changes to the _Value_, _Description_ or _Use of additionalValue Field_ content is being proposed in this change.

**Additional change considered but not proposed in this issue**
The DSB have also considered including a clarification that adjustment `rate` values should be provided as either positive or negative `RateString` values corresponding to the product and rate type. For example - 
- BONUS rates for a _Deposit_ product should be _positive_ values to sum with the Base, creating a _higher_ effective rate.
- DISCOUNT rates for a _Lending_ product should be _negative_ values to sum with the Base, creating a _lower_ effective rate.
- PENALTY rates for a _Lending_ product should be _positive_ values to sum with the Base, creating a _higher_ effective rate.

As this could lead to a different interpretation of current implementations, this change may be covered in a subsequent Decision Proposal.

The proposed changes would alter the table formatting as demonstrated below.

---

## Product Deposit Rate Types
Description of the usage of the depositRateType field as it applies to products.

### Deposit Base rate types
A deposit product is expected to present a single Base rate corresponding to relevant selection criteria including the rate `tiers` and `additionalValue`, where applicable.
Value | Description | Use of additionalValue Field
-- | -- | --
FIXED | Fixed rate for a period of time | The period of time fixed. Formatted according to ISO 8601 Durations
FLOATING | A floating rate is relatively fixed but still adjusts under specific circumstances | Details of the float parameters
MARKET_LINKED | A rate that is linked to a specific market, commodity or asset class | Details of the market linkage
VARIABLE | A variable base rate for the product | NA

### Deposit Adjustment rate types
A product may have zero, one, or multiple adjustment rates that are taken to apply to a Base rate.
Value | Description | Use of additionalValue Field
-- | -- | --
BONUS | A bonus rate available by meeting a specific criteria | A description of the criteria to obtain the bonus
BUNDLE_BONUS | A bonus rate obtained by originating a bundle instead of a standalone product | The name of the bundle
INTRODUCTORY | An introductory bonus that will expire after a set period | The period of time for the introductory rate. Formatted according to ISO 8601 Durations

## Product Lending Rate Types
Description of the usage of the lendingRateType field as it applies to products.

### Lending Base rate types
A lending product is expected to present a single Base rate corresponding to relevant selection criteria including the rate `tiers` and `additionalValue`, where applicable.

Card products may have two or more base rates, including `CASH_ADVANCE` and `PURCHASE` as they may apply to different transaction types within an account. The `PURCHASE` lendingRateType is considered the rate commonly applicable to a card.

Value | Description | Use of additionalValue Field
-- | -- | --
CASH_ADVANCE | Specific rate applied to cash advances from the account. This is expected to apply to products in the `CRED_AND_CHRG_CARDS` category only | NA
FIXED | Fixed rate for a period of time | The period of time fixed. Formatted according to ISO 8601 Durations
FLOATING | A floating rate is relatively fixed but still adjusts under specific circumstances | Details of the float parameters
MARKET_LINKED | A rate that is linked to a specific market, commodity or asset class | Details of the market linkage
PURCHASE | Specific rate applied to purchases from the account. This is expected to apply to products in the `CRED_AND_CHRG_CARDS` category only | NA
VARIABLE | A variable base rate for the product | NA

### Lending Adjustment rate types
A product may have zero, one, or multiple adjustment rates that are taken to apply to a Base rate.
Value | Description | Use of additionalValue Field
-- | -- | --
BUNDLE_DISCOUNT_FIXED | A discount rate off the fixed rate obtained by originating a bundle instead of a standalone product | The name of the bundle
BUNDLE_DISCOUNT_VARIABLE | A discount rate off the variable rate obtained by originating a bundle instead of a standalone product | The name of the bundle
DISCOUNT | A specific discount rate that may be applied. A discount rate reduces the interest payable | Description of the discount rate that is applicable
INTRODUCTORY | An introductory discount that will expire after a set period | The period of time for the introductory rate. Formatted according to ISO 8601 Durations
PENALTY | A specific penalty rate that may be applied. A penalty rate increases the interest payable | Description of the penalty rate that is applicable

**Comment by biza-io** [comment]
Biza supports the documentation update but requests that the guidance be proposed in this issue so that the data holders can provide feedback that it does not conflict with their existing interpretations and inadvertently raise compliance concerns.

**Comment by nils-work** [comment]
Hi @biza-io 
The guidance has been included in the proposed change above, under each sub-heading.

**Comment by perlboy** [comment]
Can a link be provided to the proposed changes please?

**Comment by nils-work** [comment]
Hi @perlboy 
Changes are here - https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.24.0...maintenance/585

**Comment by nils-work** [comment]
The changes to the tables described in this issue have been staged as part of the proposal resulting from [Maintenance Iteration 15](https://github.com/ConsumerDataStandardsAustralia/standards/issues/303).

The DSB is proposing the additional change relating to a lending discount rate (being negative) be addressed as part of [Decision Proposal 306](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306). Any feedback would be welcome.

**Comment by nils-work** [comment]
[Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html) version 1.25.0 has now been published, incorporating this change.
