### ISSUE TITLE
EnergyBillingDemandTransactionV2 - Measure Unit

### ISSUE THREAD

**Issue by rhys-ergon** [ConsumerDataStandardsAustralia/standards-maintenance#587]
# Description
In Energy, demand transactions are assumed to be measured in kVA. Ergon Energy has some customers, particularly with older meters (Type 6 or Basic), that are charged in kW for demand tariffs. To convert from kW to kVA requires an equipment power factor from behind the meter for every 30 minutes, which is not recorded and therefore we cannot convert kVA.

# Area Affected
Schema - `EnergyBillingDemandTransactionV2`
APIs - `GET /energy/accounts/{accountId}/billing` and `GET /energy/accounts/billing`

# Change Proposed
Add a new property to `EnergyBillingDemandTransactionV2`

Name = MeasureUnit
Type = string
Required = optional (Assumed KVA if absent)
enum = KVA, KW

# DSB Proposed Solution

The current DSB proposal for this issue is in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/587#issuecomment-1784304014.

**Comment by rhys-ergon** [comment]
**Supporting information**

Demand tariffs 44, 45 & 46 can be charged in kVA or kW

![image](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/assets/132527914/793356d1-80e6-479a-99e9-7a9d16c340ac)

**Comment by HemangCDR** [comment]
Below is the proposed `EnergyBillingTransactionV2.demand` object with the option `measureUnit` field:

```json
{
  "servicePointId": "string",
  "invoiceNumber": "string",
  "timeOfUseType": "PEAK",
  "description": "string",
  "isEstimate": true,
  "startDate": "string",
  "endDate": "string",
  "measureUnit": [ "KWH", "KVA", "KVAR", "KVARH", "KW", "DAYS", "METER", "MONTH" ], // optional - The measurement unit of rate. Assumed to be KVA if absent
  "rate": 0, //The rate for the demand charge . Assumed to be KVA if measureUnit not provided. A negative value indicates power generated
  "amount": "string",
  "calculationFactors": [
    {
      "value": 0,
      "type": "DLF"
    }
  ],
  "adjustments": [
    {
      "amount": "string",
      "description": "string"
    }
  ]
}
```

As discussed during the MI call on 18th October, this would be considered a breaking change. However, given the change involves adding an option field (which not every retailer may need), no future dated obligation is being proposed for the new version. Retailers may choose to implement the new version as required. It is also proposed The current version MAY be retired on September 9th 2024 if the new version is implemented.

Feedback on the above is welcome.

**Comment by rhys-ergon** [comment]
Thanks Hemang, this fulfils our requirements.

**Comment by CDR-API-Stream** [comment]
This [change](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/587#issuecomment-1784304014) has been staged and can be reviewed here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/d315a337ec374581b448746f226dbd7816c64532

**Comment by CDR-API-Stream** [comment]
**Note**: The following Billing APIs impacted by this change have incorrect endpoint version number of 2 (instead of 3) noted in v1.29.0 of the standards:

- Get Bulk Billing
- Get Billing For Specific Accounts

This issue has been raised in [staging ](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/359) and noted in the [Known Issues](https://consumerdatastandardsaustralia.github.io/standards/#known-issues) section of v1.29.0 of the standards.  It will be fixed in the next version release.
