### ISSUE TITLE
Remove FAPI 1.0 draft references

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#590]
# Description
Clean up of FAPI 1.0 references to remove the legacy FAPI 1.0 draft references.

# Area Affected
Information Security profile

# Change Proposed

* Remove legacy references to draft FAPI specifications. Now that the standards are fully migrated to FAPI 1.0 Final, references to previous draft versions of FAPI 1.0 (Implementer's Draft 2) and corresponding draft specifications will be removed and instead reference the final normative specs.
* Remove FAPI 1.0 phasing dates and include only the target state requirements.

**Comment by markverstege** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.24.0...maintenance/590

Note it is compared against the previous release. At present no draft 1.25.0 release has been staged but it is expected this change will target 1.25.0 for release at the end of maintenance iteration 15.

**Comment by nils-work** [comment]
Staging link for 1.25.0 - https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.25.0...maintenance/590

**Comment by perlboy** [comment]
LGTM

**Comment by nils-work** [comment]
[Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html) version 1.25.0 has now been published, incorporating this change.
