### ISSUE TITLE
EnergyBillingDemandTransaction - timeOfUseType - New Value

### ISSUE THREAD

**Issue by rhys-ergon** [ConsumerDataStandardsAustralia/standards-maintenance#592]
# Description
QLD has demand tariffs, e.g. Tariff 44, that are charged at a flat rate, meaning there is no peak or offpeak rate. The `timeOfUseType` enum in the `EnergyBillingDemandTransaction` schema doesn't have a value to map to in this situation.

# Area Affected
Schema - `EnergyBillingDemandTransaction`
Enum - `timeOfUseType`
APIs - `GET /energy/accounts/{accountId}/billing` and `GET /energy/accounts/billing`

# Change Proposed
Add `ALLDAY` to `timeOfUseType` in the `EnergyBillingDemandTransaction` schema

**Comment by biza-io** [comment]
Biza supports this change but would like to suggest altering the proposed enum to `ALL_DAY` instead.

**Comment by rhys-ergon** [comment]
QLD has a demand tariff, 50A, which has an excess component. 

**Tariff 50A**
![image](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/assets/132527914/dc807c8f-66d9-4144-a1d2-67d5e3e11e45)

So updating the changes required to:

### Change Proposed
1. Add `ALL_DAY` to `timeOfUseType` in the `EnergyBillingDemandTransaction` and `EnergyBillingUsageTransaction` schemas
2. Add `EXCESS` to `timeOfUseType` in the `EnergyBillingDemandTransaction` schema

**Comment by CDR-API-Stream** [comment]
The change noted in comment https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/592#issuecomment-1575800858 have been staged and can be viewed here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/f37be24fba8b0d31a5373e94ba281e97900b65a8

**Comment by CDR-API-Stream** [comment]
The DSB would like to note that, despite being minor in nature, this will be considered a breaking change and should result in version increment of the following affected endpoints:
- Get Billing For Account
- Get Bulk Billing
- Get Billing For Specific Accounts

A Future Dated Obligation for version 2 of the above end points will be proposed as **01/11/2023** in alignment with tranche 3 release of the energy sector, with the retirement date for version 1 as **09/09/2024**. 

If there are concerns with these dates they can be discussed in a future Maintenance Iteration.

The updated changes (along with API version increments) have been staged and can be viewed here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/282/commits/990eb5900e1e66a78060e35ba447f269bcad6cd4

**Comment by nils-work** [comment]
[Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html) version 1.25.0 has now been published, incorporating this change.
