### ISSUE TITLE
V1.1.0: Get Account Balance operationId Renamed

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#60]
# Request For Clarification
Following release to the Slate site of V1.1.0 yesterday we have now initiated analysis of changes using the diff previously provided in #56.

Within the `slate/source/includes/swagger/cds_full.json` line 354 the `operationId` for Get Account Balance was changed from `listBalance` to `getBalance`, was this intentional? If so, it is not noted within the provided Change Log.

Since Get Account Balance can have multiple currency balances, `listBalance` seems more appropriate.

**Comment by CDR-API-Stream** [comment]
It was a deliberate change but not material to the standards.  Model naming in the swagger file is non-normative.  For this reason the change was not included in the release notes.

**Comment by perlboy** [comment]
> It was a deliberate change but not material to the standards. Model naming in the swagger file is non-normative. For this reason the change was not included in the release notes.

Further to my comments regarding developer experience https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/61#issuecomment-566029223 the Swagger v2 specification states the following with regards to `operationId`:

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

This change causes existing code generation tools for both server stubs and client consumers to generate a duplicate function with the altered name. Merely noting this change would have been sufficient and helpful to the developer experience, normative or not.

**Comment by CDR-API-Stream** [comment]
The operationId was changed from listBalance to getBalance but it is still unique in the file so, as far as we can tell, the operationId aligns with the section of the Swagger v2 specification you have quoted.  I checked and the operationId does not appear to be duplicated in the swagger file.

**Comment by perlboy** [comment]
> The operationId was changed from listBalance to getBalance but it is still unique in the file so, as far as we can tell, the operationId aligns with the section of the Swagger v2 specification you have quoted. I checked and the operationId does not appear to be duplicated in the swagger file.

This was not the statement. Repeating what was stated: 
>This change causes existing code generation tools for both server stubs and client consumers to generate a duplicate function with the altered name. Merely noting this change would have been sufficient and helpful to the developer experience, normative or not.

That is to say, this change of operationId results in a regeneration on a previously generated interface (which is the intended operation mode of `swagger-codegen`) results in a new function of `getBalance` and a dangling (and now invalid) function of `listBalance`.

The issue here isn't that it was changed, the issue is was that it wasn't noted as a change. What is interpreted as a change worth publishing is variable depending on perspective. The opposition for noting these changes doesn't seem to be driven by a pragmatic approach to disclosing to participants all the changes made, normative or not.

**Comment by CDR-API-Stream** [comment]
The issue you have articulated would appear to be a feature of your code generation process. 
 The DSB does not commit to servicing any specific implementation model or mechanism.  The standard seeks to be implementation independent.  The swagger files are provided to assist but not specifically support any single implementation model.

The purpose of the release notes is to provide clarity, not to be an exhaustive description of all technical changes.  The diffs available by comparing GitHub commits are sufficient for that purpose.

**Comment by perlboy** [comment]
> The issue you have articulated would appear to be a feature of your code generation process.

The issue articulated is part of the code generation process from the industry tooling provided specifically by the creators of Swagger/OpenAPI (SmartBear) specifically for this purpose. It isn't "my" code generation process it is the industry standard but it would appear this is not understood.

> The DSB does not commit to servicing any specific implementation model or mechanism. The standard seeks to be implementation independent. The swagger files are provided to assist but not specifically support any single implementation model. The purpose of the release notes is to provide clarity, not to be an exhaustive description of all technical changes. The diffs available by comparing GitHub commits are sufficient for that purpose.

The answer given seems to be arguing to not provide a minor comment on changes for the sake of being deliberately ambiguous and arguing against feedback provided. I see no further value in providing comment in an environment where the developer experience is not understood.

**Comment by cdradr** [comment]
> The purpose of the release notes is to provide clarity, not to be an exhaustive description of all technical changes. The diffs available by comparing GitHub commits are sufficient for that purpose.

Every participant is expected to do their own impact analysis based on a diff that produces thousands of lines of differences with no comments? There must be a better way if we want CDR to succeed.

**Comment by perlboy** [comment]
@cdradr This thread is closed now so don't expect any further answer. A "better" way was presented in #56 but I don't expect it will be prioritised nor do I expect the DSB understands (nor particularly cares about) the implication of it's statement beyond how hard it is for them to change their own documentation.
