### ISSUE TITLE
Metrics: Performance threshold including SDH

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#605]
# Description

The Get Metrics model `PerformanceMetrics` specifies a description of "Percentage of calls within the performance thresholds" which effectively captures _all_ calls _regardless_ of Primary or Secondary Data Holder behaviours. The indication in the MI call today was that this wasn't intentional _however_ current implementations _are_ reporting to the Regulator these metrics _inclusive_ of all calls.

*Note:* I've created this pretty quickly for consideration in this MI and therefore have not had a chance to pass this through Biza.io's Data Standards Committee.

# Area Affected

- Get Metrics V3 > `data.performance.currentDay/previousDays`
- Get Metrics V4 > `data.performance.currentDay/previousDays`
- Get Metrics V5 > `data.performance.aggregate.currentDay/previousDays`

# Change Proposed

Alter description of these attributes to be explicitly "calls for which Primary Data Holder is responsible".

**Comment by nils-work** [comment]
A fix for this issue has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/a7de13e8e775506144e80a30d3bbc205ffa77b5c

**Comment by nils-work** [comment]
This change has been incorporated into version 1.27.0
