### ISSUE TITLE
Update Get Metrics Endpoint Schedule

### ISSUE THREAD

**Issue by ACCC-CDR** [ConsumerDataStandardsAustralia/standards-maintenance#606]
In [Decision 288](https://github.com/ConsumerDataStandardsAustralia/standards/issues/288), the Data Standards Body (DSB) highlighted that deprecation dates for v3 would be published once the ACCC had developed its transition plan. The ACCC has completed this planning, and can now suggest applicable retirement dates. The ACCC has [published the transition plan](https://consumerdataright.atlassian.net/wiki/spaces/DP/pages/32899076/Transition+Plan+-+V4+and+V5) on its developer portal for transparency. The ACCC has raised this change request to suggest relevant Standards changes, allowing the DSB to gather and consider community feedback. 

As part of this analysis, we have identified that compliance costs can be reduced for Tier 2 Energy Retailers without substantial impact on the ACCC’s functions. The ACCC expects to be able to fully retire usage of Get Metrics v3 by 13 May 2024. As such, our view is implementation of this endpoint version by Tier 2 Energy Data Holders is not in the best interests of the ecosystem. We therefore suggest that the v3 Standard be amended to clarify that it does not apply to data holders whose Consumer Data Sharing obligations commence on or after 1 November 2023. 

Given the need for these data holders to conduct design and build activities, we suggest that this could be considered a candidate for an **urgent change** to the Standards. 

### Area Affected

- [Endpoint version schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#admin-apis) for the Get Metrics
- Description of the [Get Metrics API](https://consumerdatastandardsaustralia.github.io/standards/#get-metrics) 

### Change Proposed

- Get Metrics v3: Change the description to state that this endpoint version is not required for data holders for whom Consumer Data Sharing obligations are scheduled to commence on or after 1 November 2023. 
- Get Metrics v3: Insert retirement date of 13 May 2024. 
- Get Metrics v3: Insert deprecated date that aligns with the v1.25.0 published date
- Get Metrics v4: Change the deprecated date to 1 November 2023.
- Get Metrics v5: Change the binding date from 13 June 2024 to 13 May 2024 to align with Y24#2 obligation milestone date.

**Comment by CDR-API-Stream** [comment]
As this change has been requested as being urgent we will include it in the backlog for MI16 and the DSB will seek approval from the Data Standards Chair for the change to be considered urgent.

**Comment by CDR-API-Stream** [comment]
The Data Standards Chair has approved for this change request to be handled urgently.

To ensure that the consultation on this request can be expedited but also ensure visibility to all participants we propose to make this require a standalone decision proposal.

**Comment by CDR-API-Stream** [comment]
This request will be closed and will be address under a decision proposal at:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/322
