### ISSUE TITLE
Plan Obligation Milestones for 2025

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#615]
# Description
The **Milestone Dates** in the [Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule) currently extend to **11/11/2024**.

# Area Affected
[Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule)

# Change Proposed
Plan **Milestone Dates** for 2025 to include on the [Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule).

# DSB Proposed Solution
The proposed solution can be found in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/615#issuecomment-2179891230).

**Comment by nils-work** [comment]
Following the Y24 convention (typically the second Monday of every second month, from March-November) in the [Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule), **Y25** dates could be specified as follows (in **bold**) -

Obligation Milestone | Milestone Date
-------------------- | --------------
Y24 #&#x2060;1       | 11/03/2024
Y24 #&#x2060;2       | 13/05/2024
Y24 #&#x2060;3       | 15/07/2024
Y24 #&#x2060;4       | 09/09/2024
Y24 #&#x2060;5       | 11/11/2024
**Y25 #&#x2060;1**   | **10/03/2025**
**Y25 #&#x2060;2**   | **12/05/2025**
**Y25 #&#x2060;3**   | **14/07/2025**
**Y25 #&#x2060;4**   | **08/09/2025**
**Y25 #&#x2060;5**   | **10/11/2025**

Please note the detail in the [schedule section](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule), including: 

> The calendar of obligation milestones are published to provide predictability. This calendar does not mean that any obligations exist at these dates however when addressing the future dating of obligations for any breaking changes, this calendar will be used to pin those obligations to pre-determined obligation milestones.
> 
> These dates may be subject to change depending upon new or changed legislative and policy dates as well as optimisation and streamlining based on community feedback.

**Comment by markverstege** [comment]
We discussed this issue in the first meeting for Maintenance Iteration 19. Instead of looking across the next three years, we are consulting on feedback specifically for 2025 in this iteration.

**Comment by nils-work** [comment]
The focus for MI19 consultation is the schedule of 2025 dates to be added to the [Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule) table in the next Standards version. 
Please provide any feedback on this proposal:

Obligation Milestone | Milestone Date
-------------------- | --------------
**Y25 #&#x2060;1**   | **10 March 2025** (2025-03-10)
**Y25 #&#x2060;2**   | **12 May 2025** (2025-05-12)
**Y25 #&#x2060;3**   | **14 July 2025** (2025-07-14)
**Y25 #&#x2060;4**   | **08 September 2025** (2025-09-08)
**Y25 #&#x2060;5**   | **10 November 2025** (2025-11-10)

**Comment by nils-work** [comment]
The proposed change has been [staged](https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/404/files) for review.

**Comment by nils-work** [comment]
In today's Implementation Call it was noted that Y25 Obligation 1 (10th March 2025) is a public holiday in Victoria (Labour Day). It also coincides with Adelaide Cup Day (South Australia), Canberra Day (ACT) and Eight Hours Day (Tasmania).
 
See https://www.fairwork.gov.au/employment-conditions/public-holidays/2025-public-holidays
 
The original purpose of selecting obligation milestone dates on the second Monday was the feedback received from Data Holders to avoid key shutdown periods and avoid mid-week releases. The feedback at the time was that a Monday obligation gave Data Holders choice to have teams deploy over the weekend (potentially reducing customer impact) and monitor on the Monday in case of rollback or hotfix. Importantly, the obligation date represents the last day to deploy compliant implementations, and the expectation is that Data Holders plan their deployments appropriately so they do not deploy at the 11th hour (which in turn increases their risk).
 
Given that the first milestone falls on a long-weekend for many Data Holders, it is proposed the first milestone be shifted one week later to 17th March 2025. The alternative is shifting the date one week earlier to the 3rd of March 2025 however this clashes with a public holiday in Western Australia.

The revised schedule below is proposed:

Obligation Milestone | Original Proposed Milestone Date | Revised Milestone Date
-- | --| --
Y25 #&#x2060;1 | 10 March 2025 (2025-03-10) | 17 March 2025 (2025-03-17)
Y25 #&#x2060;2 | 12 May 2025 (2025-05-12) | No change |
Y25 #&#x2060;3 | 14 July 2025 (2025-07-14) |  No change |
Y25 #&#x2060;4 | 08 September 2025 (2025-09-08) |  No change |
Y25 #&#x2060;5 | 10 November 2025 (2025-11-10) |  No change |
