### ISSUE TITLE
Get Metrics v4 & v5 authorisations property changed from optional to mandatory as part of Maintenance Issue 599 & v1.27.0

### ISSUE THREAD

**Issue by MrWoo16** [ConsumerDataStandardsAustralia/standards-maintenance#617]
# Description
The CDS v1.27.0 published on 10 October 2023 includes a change that updates the Get Metrics v4 & v5 authorisations property from optional to mandatory. This change has been classed as a minor non-breaking change within Maintenance Issue 599.

However we have, and I'm sure other data holders will have done the same, based our new Get Metrics v4 response on the direction in CDS v1.25.0 that confirmed the new authorisations property was optional, with the assumption that the individual metrics under this property would be mandatory if the authorisations property was returned.

As the ACCC / CDS deadline to implement Get Metrics v4 is the 1 November 2023 we have taken the approach at this time to emit the authorisations property from the v4 response, as the collection of all the required authorisations, revocations and expiry metrics for population within the GET Metrics API response requires significant re-development and enhancements.

Again I'm sure we are not alone with this approach and development requirement with the assumption that a number of data holders will be facing the same non compliance issue as a result of this 'simple' wording change.

The section within Maintenance Issue 599 confirms:

"_The authorisations property in Get Metrics v4 and v5 is marked as optional. This may have been intended to be mandatory as per most other top-level properties_".

# Area Affected
Get Metrics v4 and v5 authorisations property within v1.27.0 changed from optional to mandatory.

# Change Proposed
Can you please advise whether the authorisations property was intended to be optional or mandatory as the original Decision 288 –Non-Functional Requirements Revision does not provide any clear direction on this.

Given this change to make the authorisations property mandatory is a breaking change requiring a longer development timeline can this property be changed back to optional?

Apologies if this has been covered elsewhere rather than CDS v1.25.0 and Decision 288 – Non-Functional Requirements Revision

**Comment by perlboy** [comment]
Some vendors have already shipped Get Metrics endpoints following the unreasonable timelines prescribed by the DSB and the ACCC. Any change to the Standards regarding these endpoints will not be applied by November 1 and any expectation is unreasonable.

**Comment by MrWoo16** [comment]
Can you please provide an update whether this issue has been reviewed or is being considered for review to determine whether the change of the Get Metrics v4 and v5 `authorisations` property from optional to mandatory as part of v1.27.0 was done in error?

It appears that this issue is NOT currently included for consideration as part Maintenance Iteration 17, and given the timeline for the implementation and support of the Get Metrics v4 endpoint is from 1st November 2023, confirmation if this change was planned and required is welcome.

**Comment by CDR-API-Stream** [comment]
Hi @MrWoo16
 
The [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/599#issuecomment-1691010927) you referred to on issue 599 was added during Maintenance Iteration 16 on 24 Aug., in recognition of an error identified after the [release](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.25.0.html) of Standards version 1.25.0, in which the updates to the Get Metrics endpoint were introduced.
 
That error was corrected in the [release](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.27.0.html) of version 1.27.0 on 10 Oct., as part of the [outcome](https://github.com/ConsumerDataStandardsAustralia/standards/issues/313#issuecomment-1747852316) from the Maintenance Iteration. The change to make that field mandatory was not made in error.
 
Regarding the optionality of fields, the Standards also provide this statement: 

> Note that optional fields are not considered optionally implementable by a Data Holder.

**Comment by CDR-API-Stream** [comment]
The DSB acknowledges feedback that the requirement of the authorisations property wasn't accurate at the time of publishing version 1.25.0. After the issue was identified, guidance was provided through the CDR Support Portal and the CDR Implementation Call, and a correction was made to the standards as soon as practicable.
 
For related issues on compliance, the ACCC and OAIC [Compliance and Enforcement policy](https://www.cdr.gov.au/resources/guides/compliance-and-enforcement-policy) sets out the general approach to CDR compliance and enforcement and their strategic and risk based approach and may be consulted.

**Comment by DougFromPayPal** [comment]
The amount of work required to support this authorization object is significant. At the time this was prioritized, it was optional and  how our V5 was coded and launched into production. This is not remotely a minor non-breaking change and will require a fairly large analysis to determine current capability and data availability, as well as the development effort to support.
