### ISSUE TITLE
Authorization Response Algs should be conditional in RegistrationProperties

### ISSUE THREAD

**Issue by ShaneDoolanAdatree** [ConsumerDataStandardsAustralia/standards-maintenance#620]
# Description
The properties `authorization_signed_response_alg` and `authorization_encrypted_response_alg` are designated as `optional` properties in the client registration response schema `RegistrationProperties` section of the DCR API definitions. According to their descriptions they are `conditional`.

1. `authorization_signed_response_alg`
The JWS alg algorithm required for signing authorization responses. If this is specified, the response will be signed using JWS and the configured algorithm. The algorithm “none” is not allowed. **Required if response_type of “code” is registered by the client.**
2. `authorization_encrypted_response_alg`
The JWE alg algorithm required for encrypting authorization responses. If unspecified, the default is that no encryption is performed. **Required if “authorization_encrypted_response_enc” is included.**

# Area Affected
[DCR APIs > Schema > RegistrationProperties](https://consumerdatastandardsaustralia.github.io/standards/#tocSregistrationproperties)

# Change Proposed
Make `authorization_signed_response_alg` and `authorization_encrypted_response_alg` conditional.

**Comment by kirkycdr** [comment]
This issue has been staged for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/d14e093b8aed746bb289f77d6e95a53248cd0ba7
