### ISSUE TITLE
V1.1.0: CX Guidelines Renamed File

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#63]
# Description
Following release to the Slate site of V1.1.0 yesterday we have now initiated analysis of changes using the diff previously provided in #56.

With reference to the file `CX-Standards-v1.1.0.pdf` this appears to be a simple rename of the previous CX Standards v1.0.1. This rename is not noted in the existing changelog.

We recommend binaries which are not changed are not renamed but rather release notes specifically designate existing guidance is appropriate.

# Area Affected
`pdfs/`

# Change Proposed

Revert rename of file to original filename and only update binary attachment versions when they are actually changed.

**Comment by CDR-API-Stream** [comment]
This change was deliberate to avoid confusion as to whether the CX Guidelines are applicable for the latest versions fo the standards.  We are currently discussing with the CX team how to handle this going forward.

The change proposed will not be made.

**Comment by perlboy** [comment]
> This change was deliberate to avoid confusion as to whether the CX Guidelines are applicable for the latest versions fo the standards. We are currently discussing with the CX team how to handle this going forward.

If this is the case then the confusing outcome now is that the filename now references `v1.1.0` but the document itself on it's first page states `Version 1.0.1`.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No response has been received on this and the DSB does not appear to have shown interest in resolving it.
