### ISSUE TITLE
Potential error in Telco specification

### ISSUE THREAD

**Issue by samWighton** [ConsumerDataStandardsAustralia/standards-maintenance#634]
In the Telco specification.

The 'TelcoAccountDetailResponseData' Schema is a combination of the three schemas

"#/components/schemas/TelcoAccountBase"
"#/components/schemas/TelcoAccount"
"#/components/schemas/TelcoAccountDetail"

This leads to multiple 'properties' called 'plans'.

Nils Berge mentioned that this may be an error.

In the case this is intentional, should a particular property take precedence ?

Thanks

# DSB Proposed Solution
The proposed solution can be found through the staging link provided in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/634#issuecomment-2019433685).

**Comment by nils-work** [comment]
A change to address this issue has been staged for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.30.0...maintenance/634

![image](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/assets/60594671/9df9dc77-3470-49f5-bac6-2b81c2291ba0)

**Comment by nils-work** [comment]
A decision on this change was made with other items in [Maintenance Iteration 18](https://github.com/ConsumerDataStandardsAustralia/standards/issues/340#issuecomment-2071829593), but this issue was not included in version 1.30.0. 
This issue will be included in the next release.
