### ISSUE TITLE
Support URI Encoded Images in Payloads

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#64]
# Description
Following release to the Slate site of V1.1.0 yesterday we have now initiated analysis of changes using the diff previously provided in #56.

`BankingProductV2_cardArt` has been introduced to support card art as per #3. We are not aware of the specific proposal for structure on this but find a number of deficiencies with implementation notably:
1) Based on the description, URL Encoded card art does not appear to be supported. This introduces a requirement for all holders to host a card art location and also limits the opportunities available to provide "live customisation" based on consumer environment (ie. detect a Sydney Swans fan and present a dynamic card art for that)
2) Data Structure within the swagger file does not meet existing data structure norms

# Area Affected
`BankingProductV2_cardArt`

# Change Proposed

1) Support url encoded card art within the existing structure not just a "Link"
2) Fix naming of the Data Structure, `BankingProductCardArt` seems like a similar fit

**Comment by CDR-API-Stream** [comment]
Hi @perlboy, cart art is currently represented as a URIString which supports valid URI conventions. URI encoded images are based on the data URI scheme (https://en.wikipedia.org/wiki/Data_URI_scheme) which is currently allowed with the existing standards so the proposal for non-URL referenced images is supported.

No change is required.

**Comment by perlboy** [comment]
As stated in the original request:
> Based **on the description**, URL Encoded card art does not appear to be supported.

Specifically the description is:
_"**Link to** a PNG, JPG or GIF image with proportions defined by ISO 7810 ID-1 and width no greater than 512 pixels"_

URL Encoded values are not "links" and with the interpretation of "link" allowing `data` responses as per your response Holders are now permitted to provide binary content for `applicationUri`, `overviewUri`, `termsUri` `eligibilityUri` `feesAndPricingUri` `bundleUri` among many others.

**Comment by CDR-API-Stream** [comment]
Hi @perlboy with respect to the description of a "link" for card art, this can be changed to 
> **URI reference** to a PNG, JPG or GIF image with proportions defined by ISO 7810 ID-1 and width no greater than 512 pixels. **The URI reference may be a link or url-encoded data URI [[RFC 2397]](https://tools.ietf.org/html/rfc2397).**

As for changing ``BankingProductV3_cardArt`` to ``BankingProductCardArt`` there are already other precedents of the former. This change won't be adopted.

**Comment by perlboy** [comment]
> As for changing `BankingProductV3_cardArt` to `BankingProductCardArt` there are already other precedents of the former. This change won't be adopted.

There are also precedents of the latter used throughout. What is requested is consistency but since the DSB continues to inconsistently apply it's own conventions I see no value in continuing to prosecute this. Closing ticket.
