### ISSUE TITLE
Get Metrics V5 error metrics documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#655]
# Description
To ensure the requirements are clear, the field descriptions in the [ErrorMetricsV2](https://consumerdatastandardsaustralia.github.io/standards/index.html?examples#cdr-admin-api_schemas_tocSerrormetricsv2) schema could indicate that errors are to be reported against each respective error code in the 4xx and 5xx series where the example **additionalProperties** and _property1_ and _property2_ fields currently appear.

# Intention and Value of Change
Ensure compliant **Get Metrics** responses are provided to allow detailed analysis of ecosystem performance.

# Area Affected
[Get Metrics](https://consumerdatastandardsaustralia.github.io/standards/index.html?examples#cdr-admin-api_get-metrics) endpoint > [ErrorMetricsV2](https://consumerdatastandardsaustralia.github.io/standards/index.html?examples#cdr-admin-api_schemas_tocSerrormetricsv2) schema

# Change Proposed
Make the following changes to the documentation only, to provide clarity of the existing requirement. 
No changes to the endpoint version or structure are proposed.

Name | Description
 --  | --
»» additionalProperties | ~~Number of errors for a specific HTTP error code. Note that the property name must be 3 digits represent the HTTP error code the error is for~~<br>This is a placeholder field to be substituted with each respective HTTP error code in the 4xx and 5xx range recorded by the Data Holder. It is represented by _property1_ and _property2_ in the _Non-normative Examples_ section. Note that the property name **MUST** be the three-digit HTTP error code as per the adjacent _500_ example. All possible property names have not been defined as the range is expected to vary across participants. Examples would include, but are not limited to: _400, 401, 403, 404, 405, 406, 415, 422, 429, 500, 503, 504_.
»» 500 | ~~Number of errors for HTTP error code 500. Note that this field is an example of a single entry due to the lack of OAS support [for the] JSON Schema patternProperties syntax. See the additionalProperties field in this schema for the generic property structure for error code counts~~<br>Reflecting the description provided in the adjacent _additionalProperties_ field, this is an example demonstrating the structure for reporting the number of calls resulting in HTTP error code `500`. Each error code recorded by the Data Holder in the 4xx and 5xx range **MUST** be provided in this format against the respective property name. 

# DSB Proposed Solution
The current DSB proposal for this issue is in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/655#issuecomment-2484837011

**Comment by perlboy** [comment]
The published openapi specification does not specify these additional error codes. On this basis this is not a non-breaking change, will require an update to the API specification and an associated FDO.

**Comment by cuctran-greatsouthernbank** [comment]
Hi @nils-work,
When we read the Data Standards for ErrorMetricsV2, our interpretation is that we only report the server-side errors only. This was written in the Description for Aggregate error metric and by that, should also be applicable to the Unauthenticated and Authenticated error metrics. 

If 4xx errors are required to be reported, then I suggest we also change the description of the Aggregate error metric. That would become a breaking change for GSB.

![image](https://github.com/user-attachments/assets/7f985f74-fb2e-4b4b-884e-5f1de66ca287)

**Comment by nils-work** [comment]
Hi @cuctran-greatsouthernbank 

The _aggregate_ property is a continuation of the error reporting that was available prior to Get Metrics v4, which was expected to capture server-side (5xx) codes only. The earlier structure was retained as _aggregate_ in v4 to facilitate the reporting transition for the ACCC. It is unrelated to the changed proposed in this issue and will remain unaffected.

The breakdown by unauthenticated and authenticated, and per code (in the 4xx and 5xx range) in v4 was to provide greater insight.

The detail from the [Decision](https://github.com/ConsumerDataStandardsAustralia/standards/issues/288#issuecomment-1599976783) that introduced these fields in v4 stated:
> - The ErrorMetrics model will be changed from a number to an object with the following: 
>   - Two fields containing objects named authenticated and unauthenticated to separate the errors for authenticated vs unauthenticated APIs 
>   - Each of these objects will contain objects per period containing a series of fields with the label of each field being a HTTP Status Code (e.g. 422, 500, etc) and the value being a number indicating the number of errors for the period 

Guidance on error reporting, including some of this detail is available in this article - [Errors](https://cdr-support.zendesk.com/hc/en-us/articles/6461435303823-CDR-metrics-and-reporting-by-Data-Holders#Errors).

**Comment by nils-work** [comment]
To accommodate the response [above](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/655#issuecomment-2257236122), feedback on the following options is being sought:

1. No change to Get Metrics v5
   1. (Assumes the requirement to provide all error codes is clear.)
3. Non-breaking change to Get Metrics v5. Options:
   1. Update the field descriptions to provide clarity on the requirement, with no FDO provided.
   2. Update the field descriptions to provide clarity on the requirement, with an FDO of **Y25 <span>#</span>2: 2025-05-12**
4. Breaking change necessitating Get Metrics v6
   1. Update the schema to include the error codes defined in the Standards (excluding upstream specs) as mandatory fields. The _additionalProperties_ capability will be retained to accommodate error codes associated with upstream specs or extensibility. Get Metrics v6 could have an FDO of **Y25 <span>#</span>2: 2025-05-12**

**Comment by benkolera** [comment]
Thanks for this. 

Biza supports position 2.2 or 3.1. Option 2.2 is the best quick win for the ecosystem without any undue immediate disruption to implementations. We encourage the changes mentioned in V6 when we have reason to add new metrics to the ecosystem and have a better reason to release a V6.

**Comment by nils-work** [comment]
The proposal is to change the field descriptions as per below. The authenticated section has two additional example error codes that are assumed to only be applicable to authenticated endpoints (_401_, _403_), but all other detail is common.

This clarification will be applicable from the FDO **Y25 <span>#</span>2: 2025-05-12**. The Get Metrics version remains unchanged.

**Unauthenticated** section

Name | Type | Required | Description
-- | -- | -- | --
»» **additionalProperties** | NaturalNumber | optional | This is a placeholder field to be substituted with each respective HTTP error code in the 4xx and 5xx range recorded by the Data Holder. It is represented by _property1_ and _property2_ in the _Non-normative Examples_ section. Note that the property name **MUST** be the three-digit HTTP error code as per the adjacent _500_ example. All possible property names have not been defined as the range is expected to vary across participants. Examples would include, but are not limited to: _400, 404, 405, 406, 415, 422, 429, 500, 503, 504_.
»» 500 | NaturalNumber | optional | Reflecting the description provided in the adjacent _additionalProperties_ field, this is an example demonstrating the structure for reporting the number of calls resulting in HTTP error code `500`. Each error code recorded by the Data Holder in the 4xx and 5xx range **MUST** be provided in this format against the respective property name.

**Authenticated** section

Name | Type | Required | Description
-- | -- | -- | --
»» **additionalProperties** | NaturalNumber | optional | This is a placeholder field to be substituted with each respective HTTP error code in the 4xx and 5xx range recorded by the Data Holder. It is represented by _property1_ and _property2_ in the _Non-normative Examples_ section. Note that the property name **MUST** be the three-digit HTTP error code as per the adjacent _500_ example. All possible property names have not been defined as the range is expected to vary across participants. Examples would include, but are not limited to: _400, 401, 403, 404, 405, 406, 415, 422, 429, 500, 503, 504_.
»» 500 | NaturalNumber | optional | Reflecting the description provided in the adjacent _additionalProperties_ field, this is an example demonstrating the structure for reporting the number of calls resulting in HTTP error code `500`. Each error code recorded by the Data Holder in the 4xx and 5xx range **MUST** be provided in this format against the respective property name.

**Comment by perlboy** [comment]
Can the ACCC gives some guidance here? Historical experience has been a highly prescriptive metrics processing approach. This means that the optionality of additional error codes may not _actually_ be true _including_ if an metric is completely absent as it's count is 0 (`429` would be a common one). 

Clarifying that the Regulator will not seek to change schema compliant responses outside the specification, as has happened in the past, would be appreciated.

**Comment by nils-work** [comment]
Hi @perlboy 
The ACCC have not communicated any concerns with participants providing a varying array of error codes, including any codes being absent where the respective value is 0 from time to time.
