### ISSUE TITLE
V1.1.0: lastWeekDay change is a new version

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#66]
# Description
Following release to the Slate site of V1.1.0 yesterday we have now initiated analysis of changes using the diff previously provided in #56.

With reference to `slate/source/includes/cds_full.md ` line 6673 the `lastWeekDay` was altered from an integer representing a week day to a string bound by an enumeration. This is a conversion from integer (which defaulted to 1) to an enumeration which is either a string or positional (depends on implementation). Since the default value was 1 existing payloads will default to Tuesday (ie. the second index position in an enum).

While the payload this belongs to is not widely available (short of DataRight.io's test holder) this still represents a material change to the Standards which is not backward compatible.

# Area Affected
`BankingScheduledPaymentRecurrenceLastWeekday` 

# Change Proposed
Increment payload versions that use `BankingScheduledPaymentRecurrenceLastWeekday` to version 2.

**Comment by CDR-API-Stream** [comment]
As the impacted end points are not yet in production by any data holders (and therefore no clients are yet in place utilising them) the DSB has not versioned the end point.  This has been the practice with the standards since inception.  A new version of this end point will not be included in the standards to accommodate this change.

**Comment by perlboy** [comment]
> As the impacted end points are not yet in production by any data holders (and therefore no clients are yet in place utilising them) the DSB has not versioned the end point. 

If these are not in production yet there is reason to assume changing an `x-v` value and perhaps discarding the older version would be trivial. Conversely for those who have **already** built clients in anticipation of data holders the version change is an ideal way of clearly targeting backlog. At the very least it seems likely that new versions of endpoints will be a regular occurrence so practicing such change frequently will validate a currently unvalidated and untested versioning architecture.

>This has been the practice with the standards since inception. 

Except this is now `standards-maintenance`. In the absence of a clearly articulated decision proposal with respect to cadence, `maintenance` definitionally implies _"the process of preserving a condition or situation or the state of being preserved"_. If memory serves the last known position on this topic was minimum 3 month release cycles (some longer depending on complexity) from the version declared as `1.0.0`.

**Comment by WestpacOpenBanking** [comment]
Whilst this is a breaking change from earlier drafts of this endpoint specification, Westpac does not see the benefit of supporting two versions of this endpoint from go live and we are happy for the endpoint version number not to be incremented.

**Comment by perlboy** [comment]
> Whilst this is a breaking change from earlier drafts of this endpoint specification, Westpac does not see the benefit of supporting two versions of this endpoint from go live and we are happy for the endpoint version number not to be incremented.

For clarity, Biza.io is comfortable with version 1 being prematurely retired and replaced by version 2. Our issue here is that a precedent has now been set that versions can be "overridden" in an environment where the specification has been declared "stable".

**Comment by CDR-API-Stream** [comment]
Given the fact that there are no live implementations and mindful of where the first wave of ADIs are with implementation, the view is this is not a breaking change and data holders will implement against the current representation of ``BankingScheduledPaymentRecurrenceLastWeekday``.

**Comment by perlboy** [comment]
This hasn't clarified the release strategy the DSB is adopting as the approach to versioning appears to be case by case.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

This remains an example of inconsistent release strategies applied to payload versions. The 1.3.0 release demonstrated V3 of ProductDetail. It seems asking the DSB to provide consistent guidelines on versioning is _"too hard"_.
