### ISSUE TITLE
Example of ID token value for sharing_expires_at and refresh_token_expires_at is a string instead of NumericDate

### ISSUE THREAD

**Issue by johnson-cdr** [ConsumerDataStandardsAustralia/standards-maintenance#67]
# Request For Clarification
In the example provided in the Tokens section https://consumerdatastandardsaustralia.github.io/standards/#tokens sharing_expires_at and refresh_token_expires_at is expressed as string values i.e.
"refresh_token_expires_at": "1311281970",
"sharing_expires_at": "1311281970"
in the actual definition of these two values in the Scopes and Claims section above, it clearly states that refresh_token_expires_at and sharing_expires_at their values MUST be a number containing a NumericDate value, as specified in section 2 of [JWT].
Please update the example so that it is consistent with the definitions.

**Comment by CDR-API-Stream** [comment]
This is an error and will be fixed in a future version.

It is noted that the example is stated as non-normative.  The content of `sharing_expires_at` and `refresh_token_expires_at` should be the same as for `exp`.

**Comment by WestpacOpenBanking** [comment]
See [our response](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/55#issuecomment-566368384) to  the _[Specify the type of sharing_duration claim as a number in the normative standards](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/57)_ issue.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.

(noting that the change alluded to is captured in #55)
