### ISSUE TITLE
Incorrect example in RateString common type

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataStandardsAustralia/standards-maintenance#670]
# Description
The `RateString` common type currently has its final example listed as:
“-99.123456789123”`(=9912.3456789123%)`
I believe this example is missing a negative sign on the equivalent percentage.

# Intention and Value of Change
Rectifying this example will decrease ambiguity in the application of the standards. 

# Area Affected
The `RateString` type is used throughout the standards, but this specific example occurs in the "Common Field Types" subheading under "High Level Standards".
[Common Field Types](https://consumerdatastandardsaustralia.github.io/standards/#common-field-types)

# Change Proposed
Update the example to include the negative sign in the `RateString` percentage equivalent.
“-99.123456789123”`(=-9912.3456789123%)`

**Comment by nils-work** [comment]
Hi @Aiden-Ziegelaar 

Thanks for raising this, it will be resolved in the next version of the Standards through an existing documentation change providing clearer examples - [#410 - Clarify RateString description and examples](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/410).

**Comment by nils-work** [comment]
Hi @Aiden-Ziegelaar 
This was resolved in Standards v1.32.0, see updated [Common Field Types](https://consumerdatastandardsaustralia.github.io/standards/#common-field-types).
