### ISSUE TITLE
PAR/RFC9126 in Normative references appears twice.

### ISSUE THREAD

**Issue by windsleigh** [ConsumerDataStandardsAustralia/standards-maintenance#675]
# Description
In the Normative References there are two references to Pushed Authorization Requests [RFC9126]

| RFC           | Title                                              | Link                                           | Date       |
|---------------|----------------------------------------------------|------------------------------------------------|------------|
| [PAR]     | OAuth 2.0 Pushed Authorization Requests  RFC9126: | [https://tools.ietf.org/html/rfc9126](https://tools.ietf.org/html/rfc9126) | September 2021  |
| [RFC9126]     | OAuth 2.0 Pushed Authorization Requests: | [https://tools.ietf.org/html/rfc9126](https://tools.ietf.org/html/rfc9126) | September 2021 |

# Intention and Value of Change
Avoid redundancy 

# Area Affected
Normative References

# Change Proposed
I propose taking the same stance as PKCE reference.

| RFC           | Title                                              | Link                                           | Date       |
|---------------|----------------------------------------------------|------------------------------------------------|------------|
| [PKCE] / [RFC7636]| Proof Key for Code Exchange by OAuth Public Clients:| [https://datatracker.ietf.org/doc/html/rfc7636](https://datatracker.ietf.org/doc/html/rfc7636) | September 2015  |

| RFC           | Title                                              | Link                                           | Date       |
|---------------|----------------------------------------------------|------------------------------------------------|------------|
| [[PAR] / [RFC9126]| OAuth 2.0 Pushed Authorization Requests: | [https://tools.ietf.org/html/rfc9126](https://tools.ietf.org/html/rfc9126) | September 2021 |

# DSB Proposed Solution
The current DSB proposal for this issue is in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/675#issuecomment-2484498149

**Comment by windsleigh** [comment]
![par-redundancy](https://github.com/user-attachments/assets/bf5cfe5a-eb8a-432e-ab9f-2e0bddbe82e1)

**Comment by nils-work** [comment]
This has been staged - https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/461/files

**Comment by nils-work** [comment]
DSB proposal has been [added](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/675#issuecomment-2484498149).
