### ISSUE TITLE
V1.1.0: Normative Reference Change Fixes

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#68]
# Description
Following release to the Slate site of V1.1.0 yesterday we have now initiated analysis of changes using the diff previously provided in #56.

There are a number of links in the normative references which are expired or superseded.

# Area Affected
Normative References
# Change Proposed

JWA is an RFC not a Draft since 2015: https://tools.ietf.org/html/rfc7518
JWT is an RFC not a Draft since 2015: https://tools.ietf.org/html/rfc7519
JWS is an RFC not a Draft since 2016: https://tools.ietf.org/html/rfc7797
OAUTH MTLS is now at Draft 17: https://tools.ietf.org/html/draft-ietf-oauth-mtls-17
JWE is an RFC not a Draft since 2015: https://tools.ietf.org/html/rfc7516

**Comment by WestpacOpenBanking** [comment]
Westpac agrees that there is a need to update the normative references.

**Comment by CDR-API-Stream** [comment]
Thanks for picking this up.  These will be fixed as a documentation defect.

**Comment by CDR-API-Stream** [comment]
This was addressed in v1.1.1
