### ISSUE TITLE
Adoption of JARM

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#7]
# Description
The Fortian security review recommended the adoption of JARM.  The DSB agreed that this should be investigated.  

# Area Affected
The information security profile.

# Change Proposed
Adopt the [JARM](https://openid.net/specs/openid-financial-api-part-1-ID2.html) standard into the information security profile.

The description of this standards is as follows:

> This document defines a new JWT-based mode to encode authorization responses parameters. All response parameters defined for a given response type are conveyed in a JWT along with additional fields used to further protect the transmission. Since there are different techniques to encode the JWT itself in the response to the client, namely query URI parameter, fragment component and form post, this draft defines a set of response mode values in accordance with [OIDM] corresponding to this techniques.

**Comment by commbankoss** [comment]
Commonwealth Bank is supportive of adopting the JARM standard into the InfoSec Profile for authorisation responses in a later iteration of the Standards

**Comment by nils-work** [comment]
**JARM** was introduced in v1.15.0 of the Standards (on 23/12/2021) as part of FAPI 1.0 Migration Phase 1.
