### ISSUE TITLE
Support for RBA Outage Publishing Requirements

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#70]
# Request For Clarification

Could some guidance be provided as to whether Consumer Data Standards Australia intend to propose, support or otherwise integrate the apparent emergence of standardised outage reporting information being mandated by the RBA [as  reported yesterday](https://www.itnews.com.au/news/bank-outage-name-and-shame-regime-just-six-months-away-535266)? 

It would be most helpful, and a significant reduction in implementation costs and requirements, for all involved, if Australian government participants could align with each other on similar payload structures, somewhat similar to the related ACCC CDR Register.

I note this is a follow on from previous, currently unanswered, questions I've raised with respect to RBA work occurring within the ISO20022 payments space (#49 )

**Comment by CDR-API-Stream** [comment]
The DSB is regularly in discussions with other agencies and standards bodies with a view to greater alignment where possible.

In the specific example mentioned the CDR proposed outage and status end points are designed for an entirely different use case and are also planned for use beyond the Banking sector so alignment should not be assumed to be possible.  If, as details of the RBA regime become clear, alignment is of value then it will be considered.

**Comment by perlboy** [comment]
This doesn't appear to answer the original question.

> Could some guidance be provided as to whether Consumer Data Standards Australia intend to propose, support or otherwise integrate the apparent emergence of standardised outage reporting information being mandated by the RBA as reported yesterday?

Whether the existing payloads are suitable seems to be irrelevant to the question being asked.

**Comment by CDR-API-Stream** [comment]
> This doesn't appear to answer the original question.
> 
> > Could some guidance be provided as to whether Consumer Data Standards Australia intend to propose, support or otherwise integrate the apparent emergence of standardised outage reporting information being mandated by the RBA as reported yesterday?
> 
> Whether the existing payloads are suitable seems to be irrelevant to the question being asked.

No.  The Data Standards Body does not currently intend to propose, support or otherwise integrate the apparent emergence of standardised outage reporting information being mandated by the RBA as reported

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week
