### ISSUE TITLE
V1.1.0: Updated Payload Samples

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#71]
# Description
The existing sample payloads haven't been updated in 6 months.

# Area Affected

https://github.com/ConsumerDataStandardsAustralia/standards/tree/master/samples/banking/products

# Change Proposed
Provide updated samples of each payload versios.

**Comment by CDR-API-Stream** [comment]
The example payloads were provided for a specific purpose a few months ago are not linked to and have not been maintained.  These will be removed in the next defect update.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

The solution was to remove all payload samples. Confusion during implementation is likely to occur.
