### ISSUE TITLE
V1.1.0: Remove x-cds-subject header from OpenAPI specification

### ISSUE THREAD

**Issue by deboraelkin2** [ConsumerDataStandardsAustralia/standards-maintenance#72]
# Description
The OpenAPI specification still includes x-cds-subject header in all operations even though it has been removed from the standards

# Area Affected
Both JSON and YAML versions of OpenAPI spec

# Change Proposed
Remove the header as parameter for operations

**Comment by CDR-API-Stream** [comment]
The retention of the x-cds-subject was an error and has been included in the errata section of the release notes for v1.1.0.  This will be resolved in the next version of the standards.

**Comment by perlboy** [comment]
Based on the response in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/61#issuecomment-566029223 whereby the OpenAPI specification is "non normative" it does not appear errata should have contained a note about an error in the OpenAPI specification.

Could guidelines how a decision was reached to document one omission in errata but not document changes with additional direct developer impacts?

**Comment by deboraelkin2** [comment]
> The retention of the x-cds-subject was an error and has been included in the errata section of the release notes for v1.1.0. This will be resolved in the next version of the standards.

Thanks for the clarification

**Comment by CDR-API-Stream** [comment]
> Based on the response in [#61 (comment)](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/61#issuecomment-566029223) whereby the OpenAPI specification is "non normative" it does not appear errata should have contained a note about an error in the OpenAPI specification.
> 
> Could guidelines be provided as to how a decision was reached to document one omission in errata but not document changes with additional direct developer impacts?

The incorrect specification of headers in end point documentation is obviously material to the standards whereas model names (the focus of the discussion in #61) are not material.

**Comment by CDR-API-Stream** [comment]
This change has been incorporated into [v1.1.1 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.1.1.html#v1-1-1-release-notes).
