### ISSUE TITLE
Publishing of OpenID Feedback & Response

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#73]
# Request For Clarification
Biza.io wishes to clarify whether the DSB intends to provide transparency on the correspondence that occurred in the last two weeks of August 2019 regarding divergences identified by the FAPI WG within correspondence between the FAPI WG and the DSB Chair. The presence of this documentation was noted (and content broadly refuted) in the [August minutes](https://consumerdatastandards.org.au/wp-content/uploads/2019/09/DSB-Committee-Minutes_August-19_Final.pdf) (page 10) and mentioned [again in September](https://consumerdatastandards.org.au/wp-content/uploads/2019/10/DSB-Committee-Minutes_Sept-2019.pdf) (page 3).

As a contributor to the analysis provided to the DSB, a member of the FAPI Working Group and an implementer of the emerging Standards, Biza.io notes that many of the responses provided by the DSB for these divergences have either been reversed since or are currently being raised as potential changes in both `standards-maintenance` and `cdr-register` repositories.

With this consideration in mind Biza.io shall provide a revised copy of the analysis by early January and believes that transparency on prior correspondence is inline with the [stated transparency principle](https://consumerdatastandards.org.au/workinggroups/):

> Principle Two: transparency
> The proposals put forward, the feedback provided and the resulting decisions will be transparent to the wider community. This is to ensure that all participants and segments of a designated sector have an equal opportunity to participate whilst simultaneously ensuring there is no perception of bias toward any specific stakeholder group.

Biza.io is also of the understanding that the invitation from the OpenID Foundation and the FAPI Working Group to the CDS Working Group (ie. Data61 team) remains active but as yet unactioned.

**Comment by CDR-API-Stream** [comment]
The DSB have reviewed this request and publish below the response to the Open ID Foundation sent by the Data Standards Chair.  The DSB will not be publishing the response from the foundation.

Note that this letter was tabled and discussed at the September meeting of the Data Standards Advisory Committee.

[OpenID Foundation Letter.pdf](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/4087755/OpenID.Foundation.Letter.pdf)
