### ISSUE TITLE
Change of x-cds-user-agent to x-cds-client-headers not always reflected

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#75]
# Description
The rename of the `x-cds-user-agent` to `x-cds-client-headers` in the HTTP headers section has not been reflected in the endpoint documentation or the swagger. We assume that this was not intended.

# Area Affected
HTML documentation and swagger for all non-public banking and common resource endpoints.

# Change Proposed
Update the resource endpoint HTML documentation and swagger to reflect the decision to change to use of `x-cds-client-headers`.

**Comment by CDR-API-Stream** [comment]
This will be addressed as a documentation defect.

**Comment by CDR-API-Stream** [comment]
This change has been incorporated into [v1.1.1 of the standards](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.1.1.html#v1-1-1-release-notes).
