### ISSUE TITLE
Clarification on CORS headers

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#76]
# Request For Clarification
Version 1.1.0 of the standards added a new section to the security profile stating that [CORS headers](https://consumerdatastandardsaustralia.github.io/standards/#cors) must be added to a number of endpoints. This change has not been reflected in the [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) section, [the swagger](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.yaml), nor the documentation for each endpoint. For example the header is not included in the documentation for [v2 of the product endpoint](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-product-detail-v1.html#get-product-detail-v1) nor for the [documentation of v1](https://consumerdatastandardsaustralia.github.io/standards/#get-product-detail). We think that the intent is for the requirement to retrospectively apply to both versions of the endpoint, but would appreciate if this was made clear.

**Comment by CDR-API-Stream** [comment]
As they are standard HTTP the DSB opted not to include and restate the use and behaviour of CORS headers.  The specific end points were specified, however.

It is a correct interpretation to assume that all versions of these end points come under this part of the standard.  The DSB were aware that v1 of PRD end points are already implemented by the majors.  A future date was not specified as a number of the majors have already enabled CORS, there are currently no reports of client use of public client and the enablement of CORS is a relatively trivial change for most implementations.  The existing implementations should be modified as appropriate within the holder's delivery plans.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.
