### ISSUE TITLE
Performance Tier not specified for Get Scheduled Payments endpoints

### ISSUE THREAD

**Issue by deboraelkin2** [ConsumerDataStandardsAustralia/standards-maintenance#77]
# Request For Clarification
The [Performance Requirements](https://consumerdatastandardsaustralia.github.io/standards/#performance-requirements) section of the standards establishes different performance tiers and specifies which endpoints belong to which tiers.
There is no classification for any of the 3 Get Scheduled Payments endpoints.
Is it safe to assumed they would all be considered as _Large Payload_?
Also, _Get Bulk Transactions_ and _Get Transactions For Specific Accounts_  are listed as _Large Payload_, but they are no longer part of the standard

**Comment by CDR-API-Stream** [comment]
Thanks for this.  It will be treated as a documentation defect.  These end points were added to the standard after the NFR section was added.

The interpretation of their categorisation, however, is incorrect.  These end points are paged but, as they only specific potential future payments the record sets are not expected to be large.  They would be classified as Low Priority according to the tiering in the NFR section.

**Comment by CDR-API-Stream** [comment]
This has been addressed in v1.1.1
