### ISSUE TITLE
New constraint type for product detailed and account detailed endpoints

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#79]
# Description
Currently there is only a limited amount of constraint types available to map products. When mapping the next tranche of product information for personal loans and home loans it has become apparent that there is a need to include new enumeration values. Currently constraint types are more applicable to Credit Cards.

# Area Affected
Product detailed and account detailed constraint enumerated types  

# Change Proposed
Add an additional values of  “MAX_LOAN_AMOUNT” and “MIN_LOAN_AMOUNT” to the constraintType enumeration

**Comment by anzbankau** [comment]
While this proposal seems eminently sensible, the existing "MAX_LIMIT" and "MIN_LIMIT" enumerations have descriptions "A [maximum|minimum] credit limit exists" that we've applied to home loans and personal loans in the generic sense of a 'credit facility' or 'line of credit'. If we add enumerations with the additional "LOAN" qualifier like "MAX_LOAN_AMOUNT" should we then change "MAX_LIMIT" to "MAX_CREDIT_CARD_LIMIT" or is the key distinction "LIMIT" (i.e. where balances move around under a limit) vs. "AMOUNT" i.e. an original/contracted loan amount? Would a flexible line of credit (non-credit card) have a "MAX_LIMIT" or a "MAX_LOAN_AMOUNT" (or even a separate qualifier like "MAX_LINE_OF_CREDIT_AMOUNT" - taking it too far)? Being more specific can get murky.

**Comment by perlboy** [comment]
@anzbankau Tend to agree introduction of additional value leads to ambiguity of the original enum especially. Would suggest that specific enum's are preferable leaving it to the recipient to choose to perhaps decrease fidelity on their side if they wish. With that said, it will be interesting to see how enum's are intended to be versioned.

There seems to be a greater question here regarding whether there should be an evaluation that wraps up "all home loan" requirements which may wrap this small tweak up in a larger set? 

A reasonably large set of sample payloads would be very useful....

**Comment by CDR-API-Stream** [comment]
This will be considered for the backlog of the next maintenance iteration

**Comment by commbankoss** [comment]
The key distinction is the word ‘LIMIT’. This is important because when we say ‘LIMIT’ it means we can reach that limit at any point in time.

This would work perfectly fine with a ‘revolving’ facility such as credit card. For example if I have a credit card with limit of $10,000; it means I can use my card and spend until my card balance reaches $10,000. Then I can pay part (or whole) of it and again able to spend and reach the limit of $10,000.

Personal Loans on the other hand can’t have a ‘LIMIT’ because every month the loan balance keeps decreasing as I keep paying off. Instead ‘MAX_LOAN_AMOUNT’ / ‘MIN_LOAN_AMOUNT’ are much better representation. 

Commonwealth Bank agree's with @perlboy we should look at what is required to enhance the product(s) API for a later version of the Standards.

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss, the intention of ``MAX_LIMIT`` and ``MIN_LIMIT`` was always to support min and max loan balances denoting the borrowable amount. 

If there is confusion arising because of the word "credit" in the constraint value's description, rather than include new enumerations, this could be treated as a documentation defect. Would amendment of the description to make clear that the limit constraints also apply to balances satisfy this issue?

**Comment by commbankoss** [comment]
Hi @CDR-API-Stream , Commonwealth Bank is satisfied with your proposed amendment to make clear that the limit constraints also apply to balances.

**Comment by CDR-API-Stream** [comment]
Thanks @commbankoss. Based on consultation this CR was deferred until the following maintenance iteration. It is proposed that the documentation be updated for [Product Constraint Types](https://consumerdatastandardsaustralia.github.io/standards/#product-amp-account-components) as follows:

> **MAX_LIMIT:** A maximum limit exists (such as a maximum loan balance denoting the borrowable amount or maximum allowable credit limit)
> **MIN_LIMIT:** A minimum limit exists (such as a minimum borrowable amount or minimum credit limit)

**Comment by CDR-API-Stream** [comment]
Feedback has been received by @commbankoss to align wording of MIN_LIMIT with MAX_LIMIT. This will be incorporated as a documentation fix. 

> MAX_LIMIT: A maximum limit exists (such as a maximum loan balance denoting the borrowable amount or maximum allowable credit limit)
> MIN_LIMIT: A minimum limit exists (such as a minimum borrowable amount or minimum credit limit)

**Proposed**
> MAX_LIMIT: A maximum limit exists (such as a maximum loan balance denoting the borrowable amount or maximum allowable credit limit)
> MIN_LIMIT: A minimum limit exists (such as a minimum **loan balance denoting the** borrowable amount or minimum credit limit)

**Comment by CDR-API-Stream** [comment]
This change request was included in release 1.3.1.
