### ISSUE TITLE
Invalid Reference in HoK Explanation

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#80]
# Description
The HoK section of the Transaction Security section states the following:

> This is an equivalent position to section 6.2.1 of the UK Open Banking Information Security Profile.

There is no linked reference the "UK Open Banking Information Security Profile" (this term is only ever used in this sentence) and the [Open Banking Security Profile Implementers Draft](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/83919096/Open+Banking+Security+Profile+-+Implementer+s+Draft+v1.1.2) has no section 6.2.1, although the embedded profile does contain the reference being searched for.
 
# Area Affected
_Transaction Security_ section: https://consumerdatastandardsaustralia.github.io/standards/#transaction-security

# Change Proposed
Reference material that exists, I believe this should be a reference to this document: https://bitbucket.org/openid/obuk/src/4630771db004da59992fb201641f5c4ff2c881f1/uk-openbanking-security-profile.md?at=master&fileviewer=file-view-default

**Comment by CDR-API-Stream** [comment]
This statement was included from the original decision proposal which included both rationale for change as well as the specifics of the change.  Stylistically, the inclusion of rationale in the formal standards documentation is not preferred and, if this statement is creating ambiguity, it is best removed.  The statement does not amend the standards in any way.

The statement will therefore be removed as a documentation defect.
