### ISSUE TITLE
NonBusinessDayTreatment Value Descriptions

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#81]
# Request For Clarification
Could clarification be provided regarding the four values of NonBusinessDayTreatment? The documentation does not appear to explain these beyond specifying that "ON" is the default value and there are 4 values available.

**Comment by CDR-API-Stream** [comment]
This documentation was lost in transit from the decision proposal as Swagger does not provide for descriptions of enum values.  The documentation from the decision is as follows:

- **AFTER** If a scheduled payment date is a non-business day the payment will be made on the first business day after the scheduled payment date
- **BEFORE** If a scheduled payment date is a non-business day the payment will be made on the first business day before the scheduled payment date
- **ON** If a scheduled payment date is a non-business day the payment will be made on that day regardless
- **ONLY** Payments only occur on business days.  If a scheduled payment date is a non-business day the payment will be ignored

This will be addressed as a documentation defect.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.

**Comment by perlboy** [comment]
Can the published documentation please be updated prior to closing issues. There are a number of occurrences now where content changes have been committed to, tickets closed and then changes not made and issues reoccurring.

**Comment by CDR-API-Stream** [comment]
The intent is that they won't be closed until the defects have been resolved either in a patch release or errata.  For queries we would like to confirm if the original question has been answered, however.

If you could articulate the specific cases where things have been missed we will endeavour to ensure they are corrected.

**Comment by perlboy** [comment]
I think the response here is, Yes, the above description seems sufficient provided it goes into the published spec somewhere for when people are hunting for it. 

Related note, Babelfish solves for mentioned swagger description limitation using an implementation of  [`LabelValueInterface`](https://github.com/bizaio/babelfish-cdr/blob/develop/src/main/java/io/biza/babelfish/cdr/v1/enumerations/BankingPaymentNonBusinessDayTreatment.java) allowing reflection for presentation.

**Comment by CDR-API-Stream** [comment]
This has been addressed in v1.1.1
