### ISSUE TITLE
UnitOfMeasure Enum Value Descriptions

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#82]
# Request For Clarification
UnitOfMeasure is described as `DOLLAR`, `PERCENT`, `MONTH`, `DAY` but there is no supporting documentation explaining what these specifically mean. While `DOLLAR` and `PERCENT` can be implied is `MONTH` a Month Number in a Year or an explicit name of the month? Is `DAY` a day in a month or a day in a year?

**Comment by anzbankau** [comment]
The `BankingProductRateTier` extends the basic model for applicable interest rates based upon time intervals in the `additionalValue` properties of `BankingProductDepositRate` and `BankingProductLendingRate` (requiring ISO 8601 durations for FIXED and INTRODUCTORY rate types). Time-related `BankingProductRateTier.UnitOfMeasure` values (e.g. DAY, MONTH, YEAR) associated with the numeric-valued `tierValueMinimum` and `tierValueMaximum` properties allow time intervals to be supported in the same generic way as for ranges of continuous values - in any combination of discrete/ranged values and single/multiple dimensions. The typical use of time intervals for determining applicable interest rate tiers for a product offering is time periods (e.g. fixed rate for 12 months) and time intervals (e.g. term deposit with a term of between 4 and 6 months).

While we support enhancement of the description for this property, time intervals from fixed calendar-related points (e.g. 28th day of the month, 6th month of the year) are unlikely to be useful for determining an interest rate for a product offering or an account. Since `UnitOfMeasure` only qualifies the numeric-valued `tierValueMinimum` and `tierValueMaximum` properties, a month name could not be incorporated. We'd welcome examples of any product offerings that would require these types of cases to qualify for an interest rate tier.

**Comment by perlboy** [comment]
@anzbankau I hadn't really considered whether these were useful yet because I hadn't found a description for them. :)

Nonetheless, @anzbankau does seem to make a valid point as to whether there is any real requirement for unit of measures which may never be used. 

Anecdotally, at this stage across 4 holders comprising 113 products and 400+ rate tiers we have only observed a unit of measure of `DOLLAR` in use. I guess this will change to include `PERCENT` once home loan data is added.

**Comment by anzbankau** [comment]
@perlboy , since ranges are not supported in `BankingProductDepositRate` you will see that ANZ and Westpac have `unitOfMeasure` of 'MONTH' for several term deposits as the products have ranges for investment terms (e.g. 1-2 months). ANZ has a phase 3 product similar to Westpac's term deposits with multiple tier dimensions: 'MONTH' and 'DOLLAR' (represented as a 2-element array of tiers rather than the subTier structure that should have been deprecated in the standards).

**Comment by perlboy** [comment]
> @perlboy , since ranges are not supported in `BankingProductDepositRate` you will see that ANZ and Westpac have `unitOfMeasure` of 'MONTH' for several term deposits as the products have ranges for investment terms (e.g. 1-2 months). ANZ has a phase 3 product similar to Westpac's term deposits with multiple tier dimensions: 'MONTH' and 'DOLLAR' (represented as a 2-element array of tiers rather than the subTier structure that should have been deprecated in the standards).

@anzbankau, apologies it appears my hacky sql query blew up in my face. Looking at the payload I see what you mean for Westpac's product (`TDTermDeposit`):
```
            {
                "depositRateType": "FIXED",
                "rate": "0.011",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "10000 to 20000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 10000,
                        "maximumValue": 20000,
                        "rateApplicationMethod": "WHOLE_BALANCE",
                        "subTier": {
                            "name": "10 Month",
                            "unitOfMeasure": "MONTH",
                            "minimumValue": 10,
                            "maximumValue": 11,
                            "rateApplicationMethod": "WHOLE_BALANCE"
                        }
                    }
                ],
                "additionalValue": "P11M"
            },
```

For ANZ's Term Deposit (`2d41a5d3-0c8d-d5e9-cadc-195410627e08`) our parser is b0rking due to `Minimum and Maximum values must be equal when Unit Of Measure is a discrete value` which is a reference to this statement in the standards: _"For a tier with a discrete value (as opposed to a range of values e.g. 1 month) this must be the same as tierValueMinimum. "_

Wary of taking this off topic, Biza would like to render ANZ's payloads consistently like we are rendering CBA and Westpac's (NAB's seems to have a variety of other issues). Any chance a rep from ANZ could jump on the DataRight.io Slack? The invite link is in the _Join the Community_ section just below the fold on [dataright.io](https://dataright.io))?

**Comment by anzbankau** [comment]
@perlboy , tiers were designed to be generic extensions to `additionalValue` in `ProductDepositRate` and `ProductLendingRate` - supporting discrete/ranged values and multi-dimensional tiers in combination or separately. As the description you've quoted indicates, the discrete vs. ranged value is a matter of choice, so I wouldn't expect a parser to enforce the discrete value option over the ranged value option (in the absence of a typing mechanism in the standards to inform that decision).

**Comment by perlboy** [comment]
> @perlboy , tiers were designed to be generic extensions to `additionalValue` in `ProductDepositRate` and `ProductLendingRate` - supporting discrete/ranged values and multi-dimensional tiers in combination or separately. 

@anzbankau To be honest "Rate Tier" is never described within the Standards so what it is meant to be seems to be undefined for someone interpreting purely based on the specifications. I did however find @bazzat's [comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/41#issuecomment-447249138) which appears to include contributions from ANZ. Is this what is being referred to here by "were designed to be"? While @bazzat's documented Option 1 appears to have been adopted (based on near exact match of descriptions in the Standards now) there doesn't appear to have been a documented decision formally integrating these. It also doesn't appear to have been adopted without modification which leads to continued ambiguity.

> As the description you've quoted indicates, the discrete vs. ranged value is a matter of choice, so I wouldn't expect a parser to enforce the discrete value option over the ranged value option (in the absence of a typing mechanism in the standards to inform that decision).

We interpreted this statement as "if it is a specific month or day it must be equal". Having reviewed @bazzat's document and helpful entity relationship content we now understand the intent of this statement was "If it is for a single month it should be restated in `maximumValue` with the same value". Does this seem like an accurate interpretation?

**Comment by anzbankau** [comment]
@perlboy , after the first release of the standards the ABA arranged a workshop with the major banks to provide feedback to Data61. To manage major proposals for change, each bank was assigned an area of the standards most in need of improvement/extension as a basis for further refinement through consensus. While the narratives and examples in the Tiering section of the document in the ABA's document in the comment you referenced did not make it into the standards, it's not inconsistent with other aspects of the standards where you could argue extended descriptions and examples would be warranted. James' [comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/41#issuecomment-456010767) has "Accept the recommendation regarding tiering" (i.e. Option 1 as recommended in the ABA proposal document) and the proposal was marked with 'Decision Made' on 21/2/19. Several decision proposals thereafter refined this, with [this comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/48#issuecomment-467702449) showing more examples including a product with 3 tier sets/dimensions (term, amount, LVR).

Your statement using 'month' as an example for a discrete (singular) value versus a ranged value (e.g. 4 to 6 `UnitOfMeasure`s) is correct. Reversing the contents of the bracketed text in the description for `maximumValue` from "For a tier with a discrete value (as opposed to a range of values e.g. 1 month)" to "... (eg. 1 month vs. a range of 4-6 months)" would perhaps avoid some confusion.

**Comment by CDR-API-Stream** [comment]
It would appear that this query has been clarified by the community.  If there is a proposed change arising from the thread it would be welcome if it was raised as a specific change request.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.

**Comment by perlboy** [comment]
> UnitOfMeasure is described as DOLLAR, PERCENT, MONTH, DAY but there is no supporting documentation explaining what these specifically mean.

The original request was to provide add documentation for these definitions. The discussion above only highlights that the Standards do not adequately explain these.

**Comment by CDR-API-Stream** [comment]
We will look to improve the documentation in the next defect release.
