### ISSUE TITLE
Data Recipient Calling Data Holders

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#83]
In the latest V1.1.0 spec, under [Client Authentication ](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication )section there is a sub-section of Data Recipients calling Data Holders.  There is a statement saying

> Client public keys MUST only be obtained from the CDR Register.

Is this correct?  Isn't it true that Clients are hosting their own public keys via their own JWKS endpoints?  The JWKS endpoint is registered at the Register but not the public keys.

**Comment by CDR-API-Stream** [comment]
That is correct and thanks for picking this up @spikejump.  This statement remains from a previous understanding of the register design.  It will be fixed as a documentation defect.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.

**Comment by CDR-API-Stream** [comment]
Confirmed fixed in v1.1.1 branch
