### ISSUE TITLE
JWKS Endpoint

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#84]
In V1.1.0 of the spec, under section [Endpoints](https://consumerdatastandardsaustralia.github.io/standards/#end-points), sub-section JSON Web Key Set End Point should include Data Recipients as a possible value for "Hosted By" (similar to that done for Revocation End Point).

**Comment by CDR-API-Stream** [comment]
That is correct.  This will be addressed as a documentation defect.
