### ISSUE TITLE
BankingProductDetail specifies BankingProduct as Optional

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#85]
# Description
The description for `BankingProductDetail` specifies that `BankingProduct` elements are optional when it should be mandatory:
![image](https://user-images.githubusercontent.com/4291448/71775391-6d354000-2fd4-11ea-9f77-67bc453334be.png)
 
# Area Affected
`BankingProductDetail`

# Change Proposed
Alter documentation to specify _Mandatory_.

**Comment by CDR-API-Stream** [comment]
The observation is correct and will be treated as a documentation defect.

**Comment by perlboy** [comment]
This appears to apply to all *Detail objects.

**Comment by CDR-API-Stream** [comment]
This has been addressed in v1.1.1
