### ISSUE TITLE
BankingTermDepositAccount maturityInstructions described as String when Enum

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#86]
# Description
`BankingTermDepositAccount.maturityInstructions` is described as a string or anonymous enumeration:
![image](https://user-images.githubusercontent.com/4291448/71796211-cae18f00-309d-11ea-904f-fe8201736efc.png)

# Area Affected
`BankingTermDepositAccount`

# Change Proposed
Describe this value as an enumeration object of `BankingMaturityInstructions` or similar which is consistent with other enumerations in use.

**Comment by CDR-API-Stream** [comment]
All of the enums (unless contained in a separate model) are documented in this way.  The enumeration restriction is documented in the Enumerated Values section.

**Comment by perlboy** [comment]
You're right. Closing.
