### ISSUE TITLE
BankingAuthorisedEntity specifies no mandatory fields

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#87]
# Description
`BankingAuthorisedEntity` does not specify any mandatory fields. It is included in `BankingDirectDebit` as mandatory which could result in a `BankingDirectDebit` authorisation with nothing but an account identifier in it.

# Area Affected
`BankingAuthorisedEntity`

# Change Proposed
Conditional Mandatory fields introduction into `BankingAuthorisedEntity` possibly with an associated uType to designate what fields are mandatory. Additional conditional fields may be the requirement for `description` to be present when `lastDebitDateTime` is specified in the `BankingDirectDebit` payload.

**Comment by CDR-API-Stream** [comment]
As direct debits are expected to be derived using analytics there is no current understanding of whether any of the fields are able to be present in all situations.  This is, in effect, a true representation of our current understanding of the data domain.

If any fields are able to be derived then they must be included under the definition of optionality in the standards.  If no fields are able to be derived then it is an open question as to how the direct debit was identified and why it is included in the recordset at all.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

The DSB doesn't appear to be willing or able to determine through consultation with holders whether the fields are or aren't available. What is clear is that many of these fields are **required** to be available as part of the participation in BECS as part of APCA's defined [regulations](https://www.auspaynet.com.au/sites/default/files/2018-04/BECS_Regulations%20Version%20022%20-%20Effective%201%20January%202018.pdf),  [guidelines](https://www.auspaynet.com.au/sites/default/files/2019-06/Guidelines_for_Establishing_DDRs_Electronically_or_by_Telephone_0.pdf) and [procedures](https://www.auspaynet.com.au/sites/default/files/2019-09/BECS%20Procedures%20Version%20E062%20-%20Effective%2016%20September%202019%20-%20public.pdf).
