### ISSUE TITLE
CommonSimpleAddress Mandatory State Field

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#88]
# Request For Clarification
`CommonSimpleAddress` contains a `State` field which, for international addresses, is specified as a Mandatory free text field.

What is the expected behaviour for:

1. Countries for which states/provinces are not used in mailing addresses?
2. Countries for which states/provinces use non-UTF8 names?

**Comment by CDR-API-Stream** [comment]
For case 1, an empty string would be expected.
For case 2, it would be helpful if clarity could be provided on cases where a state or province cannot be represented in unicode before a clarification is provided.

**Comment by perlboy** [comment]
> For case 2, it would be helpful if clarity could be provided on cases where a state or province cannot be represented in unicode before a clarification is provided.

Admittedly, everything _should_ be able to be encoded to UTF-8 primarily because it has 95%+ international adoption however the conversion becomes messy. A Chinese address of `内蒙古敕勒歌火锅` for instance converts to `\xe5\x86\x85\xe8\x92\x99\xe5\x8f\xa4\xe6\x95\x95\xe5\x8b\x92\xe6\xad\x8c\xe7\x81\xab\xe9\x94\x85`, is this the intended presentation? We suspect there are some foreign entity banking deployments which are deployed using `Shift JIS` or `GB 2312` and while we see this primarily as a Holder side issue (ie. "Convert it yourself") we thought we would ask.

In addition, could it be clarified that non ASCII characters are intended to be allowed in addresses? Notable example is Japan which would use non ASCII UTF-8 quite a lot, still valid UTF-8 but casting this to pure ASCII will barf: `1-chōme-20-13 Jingūmae, Shibuya City, Tōkyō-to 150-0001, Japan`.

If non ASCII characters are intended does this include non-printable characters (which would be an indication of data quality issues)?

**Comment by CDR-API-Stream** [comment]
The standards define a normal string to be:
`Standard UTF-8 string but unrestricted in content. Any valid Unicode character can be used.`

There is a separate, specific, type called `ASCIIString` that is specifically limited to ASCII characters.  The `ASCIIString` type has been used wherever it is known that the content will be limited to ASCII characters.  All other string fields should assume UTF-8.

That said, as you have suggested, this is a holder issue.  If a holder converts a unicode string into ASCII in their internal database then they will only be able to supply an ASCII response.  Data recipients should not assume this, however.

**Comment by perlboy** [comment]
Thanks for the response we understand and support the use of unicode encoding for presentation. Specifically with regards to non-printable characters could I suggest that the specification for `String` have it's description changed from _Any valid Unicode character can be used_ to _Any valid **printable** Unicode character can be used_ . This would notably exclude [Control characters](https://en.wikipedia.org/wiki/Control_character) which don't seem like they should ever be present and would result in improved data quality.

**Comment by CDR-API-Stream** [comment]
This has been raised previously and the decision was to leave this to the underlying JSON specification.  It was decided that the standards should not seek to constrain strings beyond the standard behaviour of JSON.

Note that the NFR requiring that CDR data transferred should be commensurate with other digital channels is applicable here.  This would mitigate the issues raised as the string provided by the data holder will need to be aligned to what they currently provide via other digital experiences.  By implication this means they have already had to deal with non-printable characters.

**Comment by perlboy** [comment]
"Other digital experience" would most likely be a presentation layer comparison. If it's non-printable it would not be visible. Where was this decision documented? We are interested to know what justification there was for including non-printable's at all?

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No decision was provided and currently the standards allow for non-printable but valid unicode characters to be used. [Biza's Babelfish](https://github.com/bizaio/babelfish) will **not** be adopting this allowance and will therefore require printable string's for any information intended for visual display.
