### ISSUE TITLE
Inconsistency between register specifications and standards on authentication of register

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#89]
# Request For Clarification
The register standard for [CDR Register Calling Participant Admin API using Client Authentication](https://cdr-register.github.io/register/#cdr-register-calling-participant-admin-api-using-client-authentication) specifies that the CDR register will authenticate to participants using a client assertion presented to the resource server, i.e. by using the client_id, client_assertion_type, client_assertion and potentially grant_type request parameters.
 
The data standard for [CDR Register calling Data Holders and Data Recipients](https://consumerdatastandardsaustralia.github.io/standards/#cdr-register-calling-data-holders-and-data-recipients) specifies that the CDR register will authenticate to participants using a client assertion presented in the authorization request header.
                                                                                                                    
Which approach is intended? We have [also posted an issue](https://github.com/cdr-register/register/issues/45) on the ACCC registry GitHub repository.

**Comment by CDR-API-Stream** [comment]
This inconsistency is noted, thank you.  The DSB understands that the standards represents the expected behaviour but this will be clarified with the ACCC.

**Comment by CDR-API-Stream** [comment]
It is the understanding of the DSB that the standards reflect the intended behaviour.  This issue should be discussed on the Register GitHub.  As always, if the Register design decisions result in changes to this standards then the standards will be modified to accommodate the Register design once the Chair has approved the changes.

**Comment by CDR-API-Stream** [comment]
If there is no further discussion on this query it will be closed on Friday.

**Comment by CDR-Register-Stream** [comment]
The standards reflect the intended behaviour. The CDR Register documentation will be updated to reference the CDS rather than duplicate this content.
