### ISSUE TITLE
Allowance for multiple term deposit values in a single account

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#9]
# Description
Arising from feedback in the main standards repository it was requested that a single account be able to support an array of Term Deposit balances, maturity dates, etc.

# Area Affected
Account and Balance end points

# Change Proposed
The change requested is specific at this comment:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/79#issuecomment-527270890

The request is quoted below:

**Term Deposits in the Get Account Detail Api.**
As a non-technical resource, not sure if this is the appropriate section to raise this query relating to Get Account details on behalf of our API developers.

With the way the Consumer Data Standard is representing Term Deposits in the Get Account Detail Api.

We have the situation where there can be a many-to-one relationship between deposits and deposit accounts. Ie multiple deposits can be represented in a single account, each of these deposits could have different lodgement dates, maturity dates, maturity instructions and maturity amount.

The CDS structure for BankingAccountDetail only allows for 1 term deposit (https://consumerdatastandardsaustralia.github.io/standards/?javascript#tocSresponsebankingaccountbyid). 

For us to fully describe a deposit account as requested, we would need the termDepost property of BankingAccount to be an array of BankingTermDepositAccount.  Is this planned or possible?

**Comment by WestpacOpenBanking** [comment]
See also #21.

**Comment by CDR-API-Stream** [comment]
After investigation it is apparent that this complexity must be accommodated but it does not only affect the term deposit maturity instructions.  By implication it will also impact the balance structures as each subsidiary deposit will have its own balance.

To address this the following recommendation will be made:
- The term deposit structure in account details will be made an array
- It is assumed that the balance for the subsidiary deposits are aggregated into a single value when the balance is being requested (ie. the balance will not be broken down into the subsidiary deposits when requested for the account)

**Comment by NationalAustraliaBank** [comment]
NAB supports the recommendation that term deposit data in account details be made into an array. NAB would prefer that balances within the account should not be aggregated unless this is requested by the customer; the default position should be to present balances for each part of such an account.
