### ISSUE TITLE
x-fapi-interaction-id description clarification							

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#90]
Version 1.0.0 | Version 1.1.0
-- | --
An optional RFC4122 UID used as a correlation id. If provided, the data holder   must "play back" this value in the x-fapi-interaction-id   response header. **If not provided a [RFC4122] UUID value is required to   be provided in the response header to track the interaction** | An optional [RFC4122] UUID used as a correlation id. If provided, the data holder   must "play back" this value in the x-fapi-interaction-id response header.

The change log indicates that the CDR engineering team recommended the removal of this statement. Commonwealth Bank would like to understand the reason for this recommendation as it differs from [FAPI Read profile.](https://openid.net/specs/openid-financial-api-part-1-ID2.html): "..or to a [RFC4122] UUID value if the request header was not provided to track the interaction, e.g., x-fapi-interaction-id: c770aef3-6784-41f7-8e0e-ff5f97bddb3a;…”

**Comment by perlboy** [comment]
@commbankoss I tripped on this too in #59. 

If you look at the request header description for `/accounts` it says:

> An RFC4122 UID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a [RFC4122] UUID value is required to be provided in the response header to track the interaction.

I doubt any engineer would have recommended removing this requirement deliberately and the errata says _"A clarification of the description recommended by the CDR Engineering team"_. It would appear this "clarification" backfired.

**Comment by CDR-API-Stream** [comment]
Previously the description for `x-fapi-interaction-id` was the same in the request and response sections of the [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) section of the standards.  The request made was to change these descriptions to make them specific to the request and response modality.

As the inline descriptions of headers supplied for each end point only represent the request modality the description was left unchanged to contain a description that addresses both request and response usage of this header.

This change does not represent a material change in the standards.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.
