### ISSUE TITLE
BankingDomesticPayeePayId identifier formats

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#91]
# Request For Clarification
We are having difficulties locating public documentation regarding what is considered valid formats for the NPP PayID identifiers of `TELEPHONE` and `ORG_IDENTIFIER`. Could you please provide a format specification for these PayID types?

**Comment by CDR-API-Stream** [comment]
Unfortunately these are external standards that the DSB also does not have access to as they are not publicly published (as far as we are aware).  The specifications for these fields may also change independently of the CDR so being more specific would introduce change control issues.

The preferred approach would be to define these fields with the external ref type and link to a publicly published standard.  In the absence of such a reference the standards cannot be more specific than the use of a generic string type.

**Comment by perlboy** [comment]
@CDR-API-Stream Data Recipients are also unable to access NPP directly, short of screen scraping an exposed interface from an NPP member which has previously caused enumeration attack vulnerabilities, they therefore have no avenue for validation. Performing blind validation as a string there is potential for financial loss if the presented value is invalid. Perhaps the DSB could request more information from Holders?

**Comment by CDR-API-Stream** [comment]
The intent of the NPP PayId is to act as an address that can be used as the target of an NPP payment.  For this purpose the internal structure of the field is not relevant, only that it is transferred faithfully by the holder in the form that the PayId is registered in the NPP network.

**Comment by perlboy** [comment]
> The intent of the NPP PayId is to act as an address that can be used as the target of an NPP payment. For this purpose the internal structure of the field is not relevant, only that it is transferred faithfully by the holder in the form that the PayId is registered in the NPP network.

The issue raised is how to perform reasonable payload validation without NPP access. This is important for validating conformance of Holder's payloads. We are of the understanding that Holders have developed an internal set of general rules around what is valid NPP PayID's. Collating these and placing them in the Standards even as a recommendation would assist in a unified perspective of what is valid. Currently [babelfish-cdr](https://github.com/bizaio/babelfish-cdr/) is only able to validate Telephone Number, Email Address and ABN's as outlined in it's [BankingDomesticPayeePayId](https://github.com/bizaio/babelfish-cdr/blob/develop/src/main/java/io/biza/babelfish/cdr/v1/model/banking/BankingDomesticPayeePayId.java) payload definition.

**Comment by CDR-API-Stream** [comment]
The DSB has reviewed this and will decline to include this information in the standards.  The DSB has no authority or visibility over the NPP standards and are therefore unable to specify the contents of these fields.  The contents of the fields are therefore unconstrained and any content is valid (assuming it aligns with what is delivered to other digital channels) according to the CDR standards.

**Comment by CDR-API-Stream** [comment]
If there is no further discussion on this query it will be closed on Friday.
