### ISSUE TITLE
Cross Industry Product Bundles

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#92]
# Request For Clarification
Currently `BankingProductBundle` appears to imply that bundles can only contain items from a single industry. Could clarity be given what is the intent of the DSB regarding bundles which cross industry boundaries? Perhaps `BankingProductBundle` can be renamed to `CommonProductBundle` and an API defined for `/common/bundles` specifically for this payload?

**Comment by CDR-API-Stream** [comment]
There is currently no intent to combine banking product reference data with other sectors.  As new sectors come into the regime there may be an opportunity to take advantage of cross-industry bundles if they exist. 

The existing capability for specifying bundles is rudimentary.  During consultation on the PRD it was determined that, in the future, a more elaborate bundle specific end point would be a worthy addition to the standards but this was deferred.  No plan for when this will be addressed has yet been sets.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.
