### ISSUE TITLE
Is the acr claim essential?

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#93]
# Is the acr claim essential?
The non-normative example in the [request object](https://consumerdatastandardsaustralia.github.io/standards/#request-object) section includes **acr** as an Essential claim.  Can data recipients provide **acr** as a voluntary claim, or is it intended that the **acr** claim is always essential? This will affect behaviour in the case where a LoA of “urn:cds.au:cdr:3” is requested but not achieved – [the request should be rejected in the essential claim case whereas the achieved acr would be returned in the voluntary claim case. ](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.5.1.1)

**Comment by CDR-API-Stream** [comment]
The usage of `acr` is as per the normative standards.  Recipients can therefore request that the `acr` be essential or non-essential.  The standards do not constrain or modify the use of the `acr` claim beyond providing a consistent list of LoA values.

**Comment by CDR-API-Stream** [comment]
If there is no further clarification required for this query it will be closed on Friday of this week.
