### ISSUE TITLE
Clarification of rate presentation and use of subTier

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#94]
# Request For Clarification

Following on from the discussion in #82 could the DSB please provide clarity regarding the use of `subTier` and the correct application of combinatory rate rules and delivery of rate objects? If our understanding of ANZ's response is correct `subTier` is intended for deprecation and instead overlapping rules should leverage the `additionalValue` component? By way of example here is parts of the live payloads from all major holders right now. The most demonstrable example of this area for clarification is each Holder's term deposit product.

Consistency of interpretation and presentation between Holders is paramount to retain the usefulness of this data. Could the DSB make a series of sample payloads available to enable cross-holder consistency to be achieved?

Westpac appears to use the `subTier` object primarily to qualify the amount under deposit within their `TDTermDeposit` product and declares an individual `BankingProductDepositRate` per period+dollar combination with variable `calculationFrequency` and `applicationFrequency` entries. In the context of the parent rate this seems like an overlap in the scenario where multiple `BankingProductDepositRate` entries are presented (versus multiple `tiers` entries). The sample below appears to imply that an interest rate of 0.5% will be calculated on a daily basis and applied on a yearly basis (presumably this is "end of term") for fixed terms of 2 months. While the interest rate doesn't change they appear to specify separate tiers based on money under deposit, extract below is for $10,000-$20,000 and $100,000-$250,000:

```
"depositRates": [
            {
                "depositRateType": "FIXED",
                "rate": "0.005",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "10000 to 20000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 10000,
                        "maximumValue": 20000,
                        "rateApplicationMethod": "WHOLE_BALANCE",
                        "subTier": {
                            "name": "1 Month",
                            "unitOfMeasure": "MONTH",
                            "minimumValue": 1,
                            "maximumValue": 2,
                            "rateApplicationMethod": "WHOLE_BALANCE"
                        }
                    }
                ],
                "additionalValue": "P2M"
            },
            {
                "depositRateType": "FIXED",
                "rate": "0.005",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "100000 to 250000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 100000,
                        "maximumValue": 250000,
                        "rateApplicationMethod": "WHOLE_BALANCE",
                        "subTier": {
                            "name": "1 Month",
                            "unitOfMeasure": "MONTH",
                            "minimumValue": 1,
                            "maximumValue": 2,
                            "rateApplicationMethod": "WHOLE_BALANCE"
                        }
                    }
                ],
                "additionalValue": "P2M"
            },
```

Commbank's appears to not use subTier's in it's term deposit product `523f5c6a7e5b46e78a533e3272faeb97` instead relying on `additionalValue` for term length but, like other holders, uses many overlapping `BankingProductDepositRate` objects with variable `calculationFrequency` and `applicationFrequency` entries. The payloads below appear to indicate a 0.35% interest rate for 1 Month term deposits of both $1-$4999.99 and $5000-$9999.99 ranges and an interest rate of 0.45% for 2 month term deposits for multiple dollar ranges, we have only included one $5,000-$9999.99 example here:
```
"depositRates": [
            {
                "depositRateType": "FIXED",
                "rate": "0.0035",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "Amount",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 1.0,
                        "maximumValue": 4999.99,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    }
                ],
                "additionalValue": "P1M",
                "additionalInfo": "Holding facility rate. When your funds are in the holding facility, they’re renewed at a fixed interest rate every seven days until we receive your instructions for withdrawal or reinvestment for an agreed fixed term of one month or longer. You can give us instructions at any time, once you decide what you want to do."
            },
            {
                "depositRateType": "FIXED",
                "rate": "0.0035",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "Amount",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 5000.0,
                        "maximumValue": 9999.99,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    }
                ],
                "additionalValue": "P1M",
                "additionalInfo": "Holding facility rate. When your funds are in the holding facility, they’re renewed at a fixed interest rate every seven days until we receive your instructions for withdrawal or reinvestment for an agreed fixed term of one month or longer. You can give us instructions at any time, once you decide what you want to do."
            },
            {
                "depositRateType": "FIXED",
                "rate": "0.0045",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P4W",
                "tiers": [
                    {
                        "name": "Amount",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 5000.0,
                        "maximumValue": 9999.99,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    },
                    {
                        "name": "Term",
                        "unitOfMeasure": "MONTH",
                        "minimumValue": 1,
                        "maximumValue": 2
                    }
                ],
                "additionalValue": "P2M"
            },

```

ANZ (`4438b7ed-e889-1ff0-4599-4524d5f55ae3`) appears to also use many `BankingProductDepositRate` entries but omits the `calculationFrequency` and `applicationFrequency` some of the time. The payloads below appear to present a 2 month fixed term deposit with 0.7% interest rate with an "undefined" applicationFrequency and a Monthly application frequency. The other thing of note is that ANZ is not currently presenting interest rates with dollar tiers despite their advertised rates being applicable for $5,000 - $100,000 under deposit only (with "Contact Us" for $100,000+).

```
"depositRates": [
            {
                "tiers": [
                    {
                        "minimumValue": 2,
                        "unitOfMeasure": "MONTH",
                        "applicabilityConditions": {
                            "additionalInfo": "2-3 Months, Monthly Interest"
                        },
                        "name": "Term",
                        "maximumValue": 3,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    }
                ],
                "rate": "0.007",
                "applicationFrequency": "P1M",
                "additionalInfo": "2-3 Months, Monthly Interest",
                "additionalValue": "P2M",
                "depositRateType": "FIXED"
            },
            {
                "tiers": [
                    {
                        "minimumValue": 2,
                        "unitOfMeasure": "MONTH",
                        "applicabilityConditions": {
                            "additionalInfo": "2-3 Months, Maturity Interest"
                        },
                        "name": "Term",
                        "maximumValue": 3,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    }
                ],
                "rate": "0.007",
                "additionalInfo": "2-3 Months, Maturity Interest",
                "additionalValue": "P2M",
                "depositRateType": "FIXED"
            },
```

NAB (`76a6fbec-0d25-4a57-b1e0-b30338a5d2f3`) appears to use many `BankingProductDepositRate` entries with variability of `calculationFrequency`, `applicationFrequency` and `additionalValue` combined with a dollar range for tiering while supplying a valid but empty `applicabilityConditions` entry. This example appears to indicate a 1.2% interest rate on a 12 month term, calculated daily and applied at the end of the term for dollar ranges $5,000 to $499,999.

```
            {
                "depositRateType": "FIXED",
                "rate": "0.012",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P12M",
                "additionalValue": "P12M",
                "additionalInfoUri": "https://www.nab.com.au/personal/interest-rates-fees-and-charges/indicator-rates-selected-term-deposit-products",
                "tiers": [
                    {
                        "name": "Amount",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 5000,
                        "maximumValue": 499999,
                        "rateApplicationMethod": "WHOLE_BALANCE",
                        "applicabilityConditions": {}
                    }
                ]
            },
```

**Comment by anzbankau** [comment]
## applicationFrequency
For term deposits where credit interest is only 'applied' (i.e. credited) to the account (or nominated account) at maturity, we do not believe `applicationFrequency` is applicable - as 'frequency' implies that the rate is applied more than once.

## calculationFrequency
Given term deposit balances remain unchanged throughout the term, we did not believe that `calculationFrequency` is applicable. However, we can see an argument for aligning it with the `applicationFrequency` as the calculation is effectively done immediately prior to the application of the credit interest to the account. `calculationFrequency` is more applicable to transaction and non-term deposit savings accounts where the balance can change daily and it is in the customer's interest to have credit interest calculated daily (yet the sum of the daily calculations may only be applied/credited once per month).

**Comment by perlboy** [comment]
Hi @anzbankau,

Thanks for the quick response, it's greatly appreciated.

> ## applicationFrequency
> For term deposits where credit interest is only 'applied' (i.e. credited) to the account (or nominated account) at maturity, we do not believe `applicationFrequency` is applicable - as 'frequency' implies that the rate is applied more than once.

This isn't strictly true for all products. CBA for instance on terms longer than 12 months pays the interest annually. That is to say they have a 36 month (`additionalValue`) term with an annual (among others) payment of interest:
```
            {
                "depositRateType": "FIXED",
                "rate": "0.0115",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "Amount",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 5000.0,
                        "maximumValue": 9999.99,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    },
                    {
                        "name": "Term",
                        "unitOfMeasure": "MONTH",
                        "minimumValue": 34,
                        "maximumValue": 36
                    }
                ],
                "additionalValue": "P36M"
            },
```

This correlates with their product page too:
![image](https://user-images.githubusercontent.com/4291448/72583148-4c0c1200-3939-11ea-82ae-e4940fec77ec.png)

These `*frequency` attributes ARE optional though (ie. what ANZ is presenting is still a valid payload) but there is no assumption specified in the Standards about what to do. Perhaps a statement added to the Standards of _Assumed to be equal to the `additionalValue` if not present_ would be a solution?

> ## calculationFrequency
> Given term deposit balances remain unchanged throughout the term, we did not believe that `calculationFrequency` is applicable. However, we can see an argument for aligning it with the `applicationFrequency` as the calculation is effectively done immediately prior to the application of the credit interest to the account. `calculationFrequency` is more applicable to transaction and non-term deposit savings accounts where the balance can change daily and it is in the customer's interest to have credit interest calculated daily (yet the sum of the daily calculations may only be applied/credited once per month).

Once again, other Holder products are offering different rates based on when the value is calculated (Daily, Weekly, Monthly seems most popular), then applying them at non aligned intervals to a total "lock up" period. Whether this lock up is called "maturity" I guess is up for interpretation. Westpac goes so far as to say "Maturity and Yearly" as well as "Monthly":
![image](https://user-images.githubusercontent.com/4291448/72583347-161b5d80-393a-11ea-93bd-a9abd05aea59.png)

As an arbitrary example a common approach is to indicate the interest is calculated Daily, applied Monthly and the term is 2 years. This translates to `calculationFrequency`=1D, `applicationFrequency`=1M and `additionalValue`=24M. Once again, as above, since this is optional there is grounds to suggest the description could be amended with an assumption sentence to use the mandatory `additionalValue`.

**Comment by anzbankau** [comment]
@perlboy ,

> This isn't strictly true for all products. CBA for instance on terms longer than 12 months pays the interest annually. That is to say they have a 36 month (additionalValue) term with an annual (among others) payment of interest:

This is not a term deposit with interest credited 'at maturity'. 'Maturity' is at the end of the term - in your example 36 months. There is nothing special about 12 months.

> These *frequency attributes ARE optional though (ie. what ANZ is presenting is still a valid payload) but there is no assumption specified in the Standards about what to do. Perhaps a statement added to the Standards of Assumed to be equal to the additionalValue if not present would be a solution?

We elected to exclude `applicationFrequency` from 'at maturity' term deposits to help data consumers to identify these special cases. We can provide the value (aligned to `additionalValue`) but that removes the business information that missing `applicationFrequency` provides.

The meaning of `additionalValue` is specific to the `depositRateType`. The term deposit term is only relevant for 'FIXED' and 'INTRODUCTORY' types so  'Assumed to be equal to the additionalValue if not present' could only be applied to those types and only in the context of term deposits. This would be a very limited business rule.

> Once again, other Holder products are offering different rates based on when the value is calculated (Daily, Weekly, Monthly seems most popular), then applying them at non aligned intervals to a total "lock up" period. Whether this lock up is called "maturity" I guess is up for interpretation. Westpac goes so far as to say "Maturity and Yearly" as well as "Monthly":

I presume you mean 'when the value is applied' rather than '... calculated' - as evidenced by only 'P1D' values for `calculationFrequency` in your examples. As a customer, would expect a lesser rate for a TD with a monthly `applicationFrequency` than your would for a yearly application of credit interest because you are getting the advantage of compounding.

I'd suggest that the concepts of 'term' (your 'lock-up') and how often interest is credited (`applicationFrequency`) are well established in the market. For example, ANZ has a table with rows headed with 'Term' and column headings of 'Interest at Maturity', 'Monthly Interest', 'Quarterly Interest', 'Half Yearly Interest', 'Annual Interest'.

I wouldn't like to speak on behalf of Westpac, but 'yearly and at maturity' makes sense for a term not aligned to years. For a 30 month TD you would expect interest to be paid at the end of the 12 and 24 months and at the end of 30 months i.e. at maturity. 'Maturity' should not be a matter of interpretation for data holders and data recipients, but you could argue that 'end of the term' (as per the your image from CBA) is more appropriate for consumers.

**Comment by anzbankau** [comment]
@perlboy ,

> Commbank's appears to not use subTier's in it's term deposit product 523f5c6a7e5b46e78a533e3272faeb97 instead relying on additionalValue for term length ...

CBA's term deposit does not need to use a tier (or the deprecated subTier) as `additionalValue` for `depositRateType` is the period of time for the 'FIXED' or 'INTRODUCTORY' periods (as per the enumerations table. As mentioned in  #82, a tier is only required for ranged term/period tiers or for other (non-term/period) dimensions like DOLLAR and PERCENT.

> ... like other holders, uses many overlapping BankingProductDepositRate objects with variable calculationFrequency and applicationFrequency entries.

Refer to last quoted text response in [previous post](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/94#issuecomment-575466866).

**Comment by perlboy** [comment]
@anzbankau I'm going to leave Commbank and Westpac to provide a response on interpretation here. What I'd flag is that ANZ's listed term deposit rates do appear to [differentiate](https://www.anz.com.au/personal/bank-accounts/your-account/rates-fees-terms/#td) between the term deposit length ("maturity") and when interest appears in the account:
![image](https://user-images.githubusercontent.com/4291448/72586791-09e9cd00-3947-11ea-99a8-8cd6239a74fb.png)

This is combined with your [Ts &Cs page 62](https://www.anz.com.au/content/dam/anzcomau/documents/pdf/saving-transaction-products-tcs.pdf) which state:
![image](https://user-images.githubusercontent.com/4291448/72586914-79f85300-3947-11ea-8eb1-b4bb2ea60585.png)

On this basis our current interpretation of the cross sectioned item would be an `additionalValue` of P6M, an `applicationFrequency` of P3M and a `calculationFrequency` of P1D. Is this correct?

**Comment by anzbankau** [comment]
Thanks @perlboy. 

`applicationFrequency` is correct.

Given the other banks are using `calculationFrequency` of 'P1D' we should follow suit. It aligns with our Ts & Cs and has the same effect.

`additionalValue` is not correct though as the term is a range (6-7 months), not a discrete value (6 months). I'd refer you to my earlier posts here and #82 for the full explanation.

**Comment by perlboy** [comment]
> `additionalValue` is not correct though as the term is a range (6-7 months), not a discrete value (6 months). I'd refer you to my earlier posts here and #82 for the full explanation.

@anzbankau as always thanks for your prompt reply. This is an interesting use case,  particularly where there might be variability between 6 months and 6.5 months, from what I can tell there aren't any holders offering term deposits like this though, rather "6 months" or "7 months".

The behaviour we have seen from other holders is to list each month (`P6M`, `P7M` etc) as individual interest rates and then rate tiers based on ranges of dollars (`DOLLAR`) and, sometimes, also adding an overlapping rate tier value with `MONTH`. We've found this approach the easiest to render as it allows a sorted iteration during rendering.

I admit this can lead to some ambiguity though so guidance from the DSB would be appreciated. Technically this is solvable by allowing ISO8601 time intervals and while I asked this question in November 2019 it [wasn't specifically answered](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/5#issuecomment-555769600) (only recurring intervals was declared as not supported).

All of this is highlighting that it would be appreciated if the DSB could provide "model" sample payloads to enable Holders to align.

**Comment by CDR-API-Stream** [comment]
If a specific change arising from this discussion is desired please raise it as a change request.

**Comment by perlboy** [comment]
> All of this is highlighting that it would be appreciated if the DSB could provide "model" sample payloads to enable Holders to align.

**Comment by RodDal** [comment]
As suggested, we'll raise the removal of subTier as a change request. It will use the Westpac example from @perlboy 's issue statement here for continuity (and repeated below for completeness), so it may not represent current Westpac product data. The ANZ example in @perlboy 's later [post](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/94#issuecomment-575454596) also demonstrates the use of the `tiers` array for multi-dimensional tiering.

It will also propose adding `additionalInformation` to `ProductRateTier` as, without it, we were forced to use `applicabilityConditions` to use its `additionalInfo`. The real purpose of `applicabilityConditions` was to provide conditions additional to those codified in the generic `ProductRateTier` structure - not to restate them. Given the ubiquitous use of `additionalInfo` in the standards (for good reason), it was really just an oversight in our initial proposal.

### Using Subtier
```
"depositRates": [
            {
                "depositRateType": "FIXED",
                "rate": "0.005",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "10000 to 20000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 10000,
                        "maximumValue": 20000,
                        "rateApplicationMethod": "WHOLE_BALANCE",
                        "subTier": {
                            "name": "1 Month",
                            "unitOfMeasure": "MONTH",
                            "minimumValue": 1,
                            "maximumValue": 2,
                            "rateApplicationMethod": "WHOLE_BALANCE"
                        }
                    }
                ],
                "additionalValue": "P2M"
            }
```

### Using Tier Array (i.e. multi-dimensional)
```
"depositRates": [
            {
                "depositRateType": "FIXED",
                "rate": "0.005",
                "calculationFrequency": "P1D",
                "applicationFrequency": "P1Y",
                "tiers": [
                    {
                        "name": "10000 to 20000",
                        "unitOfMeasure": "DOLLAR",
                        "minimumValue": 10000,
                        "maximumValue": 20000,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    },
                    {
                        "name": "1 Month",
                        "unitOfMeasure": "MONTH",
                        "minimumValue": 1,
                        "maximumValue": 2,
                        "rateApplicationMethod": "WHOLE_BALANCE"
                    }
                ],
                "additionalValue": "P2M"
            }
```

**Comment by perlboy** [comment]
Hi @RodDal, Sounds good. One question I would have is that the proposed change doesn't appear to have the ability to offer `AND` versus `OR` (ie. Compound versus Exclusive). Is the intent here that an `OR` presentation (ie. 10,000->20,000 OR for 1 Month instead of 10,000->20,000 AND for 1 Month) would simply be a new `depositRate` entry and therefore any combination is AND'd together?

**Comment by anzbankau** [comment]
@perlboy, with the objectives for the first major release of the standards being simplicity and expediency, only conjunction (AND) is supported in `ProductRateTiers`.  Disjunction (OR - both inclusive and exclusive) is not supported. This is in line with the multi-dimensional nature of tiers where intersections are logical ANDs. Combining ANDs and ORs requires grouping (effectively nested parentheses in logic text) in order to prevent ambiguity, requiring complicated data structures to represent, maintain and process.

I know it's only an example, but "10,000->20,000 OR for 1 Month" demonstrates the value of ANDs over ORs when both values (from different domains/dimensions) are required to determine an interest rate i.e. from the intersection.

**Comment by CDR-API-Stream** [comment]
If there are no more questions related to this query it will be closed on Friday.
