### ISSUE TITLE
Explicitly define Registration endpoint definition in the OpenID Provider Configuration Endpoint

### ISSUE THREAD

**Issue by CDR-Register-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#96]
# Request For Clarification
The OpenID Provider Configuration End Point does not explicitly outline that the Registration  endpoint needs to be defined in this structure: https://consumerdatastandardsaustralia.github.io/standards/#end-points

It is included in the non-normative example.

The documentation would benefit from being explicit

**Comment by CDR-API-Stream** [comment]
This will be addressed as a documentation defect

**Comment by CDR-API-Stream** [comment]
This has been resolved in v1.2.0 so this issue will be closed.
