### ISSUE TITLE
Representing Fee Waiver Discounts

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#97]
# Request For Clarification
Many home loan products have a "waiver" applied provided a certain package of products of products is purchased. For instance Suncorp has a [Home Package Plus](https://www.suncorp.com.au/banking/loans/home-loans/package-plus.html) which waives the $375/year package fee for life provided the customer is a first home buyer and does not alter their finance agreement (for instance, doesn't cancel their associated credit card or change to a credit line facility).

Currently we have identified that the only way of representing this discount is to create an `ELIGIBILITY_ONLY` discount with a `OTHER` eligibility type but this means that the interpretation of "net benefit" should a customer be looking to switch is impacted (by $375/year) and there is nearly zero programmatic solution to differentiating `OTHER` entries.

Can the DSB provide comment on whether there is an alternate way of representing this condition?

**Comment by CDR-API-Stream** [comment]
While this type of fee is characterised as being waived while certain conditions are met, this is really a fee incurred if an event occurs (such as a change to their finance agreement).  It would be expected that this fee would therefore be represented as a fee with a `feeType` of `EVENT`.

Another valid scenario is that the fee is included in the product information with a `feeType` of `UPFRONT` but the `additionalInformation` or `additionalInformationUri` contain the detail of the waiver in human readable form.

**Comment by perlboy** [comment]
> While this type of fee is characterised as being waived while certain conditions are met, this is really a fee incurred if an event occurs (such as a change to their finance agreement). It would be expected that this fee would therefore be represented as a fee with a `feeType` of `EVENT`.

`EVENT` doesn't appear to consider the annual nature of the example fee once the agreement has changed?

> Another valid scenario is that the fee is included in the product information with a `feeType` of `UPFRONT` but the `additionalInformation` or `additionalInformationUri` contain the detail of the waiver in human readable form.

Once again `UPFRONT` doesn't appear to consider the annual nature of the example provided?

In evaluating this consideration we've used a `PERIODIC` fee type with a `P1Y` `additionalValue` then waived it with an eligibility discount. What would be ideal is some way of describing an `EVENT` (or non-event as the case may be) for discount eligibility.

**Comment by CDR-API-Stream** [comment]
If this is an addition that would be of value then please raise a change request describing the desired change.

**Comment by perlboy** [comment]
> If this is an addition that would be of value then please raise a change request describing the desired change.

This is a clarification request, it would be up to the DSB to decide whether this is a desired change. Nonetheless, repeating the questions:

> EVENT doesn't appear to consider the annual nature of the example fee once the agreement has changed?
> Once again UPFRONT doesn't appear to consider the annual nature of the example provided?

And further, is there any other options beyond the first presented and the two questions above?

**Comment by CDR-API-Stream** [comment]
If it is annual then periodic would appear to be appropriate.  The two options to indicate the waiver, under the current standards, would be to use a 100% feeRate discount with type ELIGIBILITY_ONLY (as you indicate) or to have no discount and indicate the waiver in free text in additionalInformation or additionalInformationUri on the fee.

**Comment by CDR-API-Stream** [comment]
If there are no more questions related to this query it will be closed on Friday.
