### ISSUE TITLE
TimeString vs. DateTimeString Offsets

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#98]
# Request For Clarification
The Standards specify:
![image](https://user-images.githubusercontent.com/4291448/72698334-e8335480-3b97-11ea-9c0c-82be8119269a.png)

This seems to imply that `DateTimeString`'s can be non-UTC RFC-3339 formatted time strings? Conversely `TimeString` explicitly states UTC time should always be used. Additionally the ABNF definition for `full-time` in RFC-3339 is specified as `partial-time time-offset` which explicitly allows for offsets to be presented.

Are `DateTimeString`'s intended to also always be UTC formatted? If not, could the DSB give reasons why, despite RFC-3339 supporting otherwise, `TimeString` is explicitly requested to be UTC? Also, date's don't have any timezone so the specification they are in UTC format means nothing. Perhaps this statement was intended for `DateTimeString`?

At face value it seems logical to suggest that time's should always be given in UTC OR be given in a local timezone (personal preference to UTC). Specifying both based on presentation layer is confusing to implementors saved only by the fact `TimeString` is never actually used.

**Comment by CDR-API-Stream** [comment]
There is no intent to create any implied or explicit restriction of RFC-3339 in these types.  The comment applied to `TimeString` referencing UTC is only intended to highlight that RFC-3339 aligns all times to UTC.  Even if an offset is provided it is still an offset with reference to UTC.

In the case of the `TimeString` type the default format can easily be misunderstood to be able to represent current time and a number of participants have asked what timezone times should be reported in.  The description of this type is therefore to ensure that it is clear that the implication of using RFC-3339 means that the time should be aligned to UTC.

**Comment by perlboy** [comment]
Would suggest this sentence be reworded to something like "As specified in RFC-3339 an offset relative to UTC should be applied" along with introducing this statement into `DateTimeString`.

**Comment by CDR-API-Stream** [comment]
This may be considered as a text clarification in a future update of the standards.

**Comment by CDR-API-Stream** [comment]
This has been incorporated into the latest v1.2.0 release. This issue will now be closed.
